Search.appendIndex(
    [
                {
            "fqsen": "\\Horde\\Platform\\ExecutionResult",
            "name": "ExecutionResult",
            "summary": "The\u0020results\u0020of\u0020an\u0020executed\u0020command",
            "url": "classes/Horde-Platform-ExecutionResult.html"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Platform-ExecutionResult.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResult\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "The\u0020execution\u0027s\u0020output\u0020as\u0020a\u0020string",
            "url": "classes/Horde-Platform-ExecutionResult.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResult\u003A\u003AgetOutputString\u0028\u0029",
            "name": "getOutputString",
            "summary": "The\u0020execution\u0027s\u0020output\u0020as\u0020a\u0020string",
            "url": "classes/Horde-Platform-ExecutionResult.html#method_getOutputString"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResult\u003A\u003AgetOutputArray\u0028\u0029",
            "name": "getOutputArray",
            "summary": "The\u0020execution\u0027s\u0020output\u0020as\u0020potentially\u0020empty\u0020array\u0020of\u0020strings",
            "url": "classes/Horde-Platform-ExecutionResult.html#method_getOutputArray"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResult\u003A\u003AgetReturnCode\u0028\u0029",
            "name": "getReturnCode",
            "summary": "The\u0020return\u0020code\u0020of\u0020an\u0020execution\u0020or\u0020null",
            "url": "classes/Horde-Platform-ExecutionResult.html#method_getReturnCode"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResult\u003A\u003A\u0024output",
            "name": "output",
            "summary": "",
            "url": "classes/Horde-Platform-ExecutionResult.html#property_output"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResult\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/Horde-Platform-ExecutionResult.html#property_code"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResultInterface",
            "name": "ExecutionResultInterface",
            "summary": "The\u0020results\u0020of\u0020an\u0020executed\u0020command",
            "url": "classes/Horde-Platform-ExecutionResultInterface.html"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResultInterface\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "The\u0020execution\u0027s\u0020output\u0020as\u0020a\u0020string\u0020\u002D\u0020Stringable\u0020interface",
            "url": "classes/Horde-Platform-ExecutionResultInterface.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResultInterface\u003A\u003AgetOutputString\u0028\u0029",
            "name": "getOutputString",
            "summary": "The\u0020execution\u0027s\u0020output\u0020as\u0020a\u0020string",
            "url": "classes/Horde-Platform-ExecutionResultInterface.html#method_getOutputString"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResultInterface\u003A\u003AgetOutputArray\u0028\u0029",
            "name": "getOutputArray",
            "summary": "The\u0020execution\u0027s\u0020output\u0020as\u0020potentially\u0020empty\u0020array\u0020of\u0020strings",
            "url": "classes/Horde-Platform-ExecutionResultInterface.html#method_getOutputArray"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutionResultInterface\u003A\u003AgetReturnCode\u0028\u0029",
            "name": "getReturnCode",
            "summary": "The\u0020return\u0020code\u0020of\u0020an\u0020execution\u0020or\u0020null",
            "url": "classes/Horde-Platform-ExecutionResultInterface.html#method_getReturnCode"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutorInterface",
            "name": "ExecutorInterface",
            "summary": "Run\u0020a\u0020command\u0020in\u0020shell\u0020context",
            "url": "classes/Horde-Platform-ExecutorInterface.html"
        },                {
            "fqsen": "\\Horde\\Platform\\ExecutorInterface\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Run\u0020the\u0020command",
            "url": "classes/Horde-Platform-ExecutorInterface.html#method___invoke"
        },                {
            "fqsen": "\\Horde\\Platform\\PlatformDetector",
            "name": "PlatformDetector",
            "summary": "",
            "url": "classes/Horde-Platform-PlatformDetector.html"
        },                {
            "fqsen": "\\Horde\\Platform\\PlatformDetectorInterface",
            "name": "PlatformDetectorInterface",
            "summary": "",
            "url": "classes/Horde-Platform-PlatformDetectorInterface.html"
        },                {
            "fqsen": "\\Horde\\Platform\\SimpleExecutor",
            "name": "SimpleExecutor",
            "summary": "Run\u0020a\u0020one\u002Doff\u0020command\u0020and\u0020capture\u0020STDOUT\u0020and\u0020return\u0020code.",
            "url": "classes/Horde-Platform-SimpleExecutor.html"
        },                {
            "fqsen": "\\Horde\\Platform\\SimpleExecutor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Platform-SimpleExecutor.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Platform\\SimpleExecutor\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Run\u0020the\u0020command",
            "url": "classes/Horde-Platform-SimpleExecutor.html#method___invoke"
        },                {
            "fqsen": "\\Horde\\Platform\\SimpleExecutor\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/Horde-Platform-SimpleExecutor.html#property_logger"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Platform",
            "name": "Platform",
            "summary": "",
            "url": "namespaces/horde-platform.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
