Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Stream_Exception",
            "name": "Horde_Stream_Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020Horde_Stream\u0020package.",
            "url": "classes/Horde-Stream-Exception.html"
        },                {
            "fqsen": "\\Horde_Stream_Existing",
            "name": "Horde_Stream_Existing",
            "summary": "Implementation\u0020of\u0020Horde_Stream\u0020for\u0020an\u0020existing\u0020stream\u0020resource.\u0020This\nresource\u0020will\u0020be\u0020directly\u0020modified\u0020when\u0020manipulating\u0020using\u0020this\u0020class.",
            "url": "classes/Horde-Stream-Existing.html"
        },                {
            "fqsen": "\\Horde_Stream_Existing\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Stream-Existing.html#method___construct"
        },                {
            "fqsen": "\\Horde_Stream_String",
            "name": "Horde_Stream_String",
            "summary": "Implementation\u0020of\u0020Horde_Stream\u0020that\u0020uses\u0020a\u0020PHP\u0020native\u0020string\u0020variable\nfor\u0020the\u0020internal\u0020storage.",
            "url": "classes/Horde-Stream-String.html"
        },                {
            "fqsen": "\\Horde_Stream_String\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Stream-String.html#method___construct"
        },                {
            "fqsen": "\\Horde_Stream_Temp",
            "name": "Horde_Stream_Temp",
            "summary": "Implementation\u0020of\u0020Horde_Stream\u0020for\u0020a\u0020PHP\u0020temporary\u0020stream.",
            "url": "classes/Horde-Stream-Temp.html"
        },                {
            "fqsen": "\\Horde_Stream_Temp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Stream-Temp.html#method___construct"
        },                {
            "fqsen": "\\Horde_Stream_Temp\u003A\u003A_init\u0028\u0029",
            "name": "_init",
            "summary": "Initialization\u0020method.",
            "url": "classes/Horde-Stream-Temp.html#method__init"
        },                {
            "fqsen": "\\Horde_Stream_TempString",
            "name": "Horde_Stream_TempString",
            "summary": "Implementation\u0020of\u0020Horde_Stream\u0020that\u0020uses\u0020a\u0020PHP\u0020native\u0020string\u0020variable\nuntil\u0020a\u0020certain\u0020size\u0020is\u0020reached,\u0020at\u0020which\u0020point\u0020it\u0020converts\u0020storage\u0020to\u0020a\nPHP\u0020temporary\u0020stream.",
            "url": "classes/Horde-Stream-TempString.html"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Stream-TempString.html#method___construct"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003A_init\u0028\u0029",
            "name": "_init",
            "summary": "Initialization\u0020method.",
            "url": "classes/Horde-Stream-TempString.html#method__init"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method___get"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method___set"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method___clone"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method___toString"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_add"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_length"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003AgetToChar\u0028\u0029",
            "name": "getToChar",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_getToChar"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_peek"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_search"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003AgetString\u0028\u0029",
            "name": "getString",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_getString"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Asubstring\u0028\u0029",
            "name": "substring",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_substring"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003AgetChar\u0028\u0029",
            "name": "getChar",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_getChar"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Apos\u0028\u0029",
            "name": "pos",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_pos"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_rewind"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Aseek\u0028\u0029",
            "name": "seek",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_seek"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Aend\u0028\u0029",
            "name": "end",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_end"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Aeof\u0028\u0029",
            "name": "eof",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_eof"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_serialize"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method_unserialize"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003A__serialize\u0028\u0029",
            "name": "__serialize",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method___serialize"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003A__unserialize\u0028\u0029",
            "name": "__unserialize",
            "summary": "",
            "url": "classes/Horde-Stream-TempString.html#method___unserialize"
        },                {
            "fqsen": "\\Horde_Stream_TempString\u003A\u003A\u0024_string",
            "name": "_string",
            "summary": "String\u0020stream\u0020object.",
            "url": "classes/Horde-Stream-TempString.html#property__string"
        },                {
            "fqsen": "\\Horde_Stream",
            "name": "Horde_Stream",
            "summary": "Object\u0020that\u0020adds\u0020convenience\/utility\u0020methods\u0020to\u0020interacting\u0020with\u0020PHP\nstreams.",
            "url": "classes/Horde-Stream.html"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Stream.html#method___construct"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A_init\u0028\u0029",
            "name": "_init",
            "summary": "Initialization\u0020method.",
            "url": "classes/Horde-Stream.html#method__init"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-Stream.html#method___get"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "",
            "url": "classes/Horde-Stream.html#method___set"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "",
            "url": "classes/Horde-Stream.html#method___clone"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "String\u0020representation\u0020of\u0020object.",
            "url": "classes/Horde-Stream.html#method___toString"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020data\u0020to\u0020the\u0020stream.",
            "url": "classes/Horde-Stream.html#method_add"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "Returns\u0020the\u0020length\u0020of\u0020the\u0020data.\u0020Does\u0020not\u0020change\u0020the\u0020stream\u0020position.",
            "url": "classes/Horde-Stream.html#method_length"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003AgetToChar\u0028\u0029",
            "name": "getToChar",
            "summary": "Get\u0020a\u0020string\u0020up\u0020to\u0020a\u0020certain\u0020character\u0020\u0028or\u0020EOF\u0029.",
            "url": "classes/Horde-Stream.html#method_getToChar"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "Return\u0020the\u0020current\u0020character\u0028s\u0029\u0020without\u0020moving\u0020the\u0020pointer.",
            "url": "classes/Horde-Stream.html#method_peek"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020for\u0020character\u0028s\u0029\u0020and\u0020return\u0020its\u0020position.",
            "url": "classes/Horde-Stream.html#method_search"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003AgetString\u0028\u0029",
            "name": "getString",
            "summary": "Returns\u0020the\u0020stream\u0020\u0028or\u0020a\u0020portion\u0020of\u0020it\u0029\u0020as\u0020a\u0020string.\u0020Position\u0020values\nare\u0020the\u0020byte\u0020position\u0020in\u0020the\u0020stream.",
            "url": "classes/Horde-Stream.html#method_getString"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Asubstring\u0028\u0029",
            "name": "substring",
            "summary": "Return\u0020part\u0020of\u0020the\u0020stream\u0020as\u0020a\u0020string.",
            "url": "classes/Horde-Stream.html#method_substring"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003AgetEOL\u0028\u0029",
            "name": "getEOL",
            "summary": "Auto\u002Ddetermine\u0020the\u0020EOL\u0020string.",
            "url": "classes/Horde-Stream.html#method_getEOL"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003AgetChar\u0028\u0029",
            "name": "getChar",
            "summary": "Return\u0020a\u0020character\u0020from\u0020the\u0020string.",
            "url": "classes/Horde-Stream.html#method_getChar"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Apos\u0028\u0029",
            "name": "pos",
            "summary": "Return\u0020the\u0020current\u0020stream\u0020pointer\u0020position.",
            "url": "classes/Horde-Stream.html#method_pos"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "Rewind\u0020the\u0020internal\u0020stream\u0020to\u0020the\u0020beginning.",
            "url": "classes/Horde-Stream.html#method_rewind"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Aseek\u0028\u0029",
            "name": "seek",
            "summary": "Move\u0020internal\u0020pointer.",
            "url": "classes/Horde-Stream.html#method_seek"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Aend\u0028\u0029",
            "name": "end",
            "summary": "Move\u0020internal\u0020pointer\u0020to\u0020the\u0020end\u0020of\u0020the\u0020stream.",
            "url": "classes/Horde-Stream.html#method_end"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Aeof\u0028\u0029",
            "name": "eof",
            "summary": "Has\u0020the\u0020end\u0020of\u0020the\u0020stream\u0020been\u0020reached\u003F",
            "url": "classes/Horde-Stream.html#method_eof"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020stream.",
            "url": "classes/Horde-Stream.html#method_close"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/Horde-Stream.html#method_serialize"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "",
            "url": "classes/Horde-Stream.html#method_unserialize"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A__serialize\u0028\u0029",
            "name": "__serialize",
            "summary": "",
            "url": "classes/Horde-Stream.html#method___serialize"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A__unserialize\u0028\u0029",
            "name": "__unserialize",
            "summary": "",
            "url": "classes/Horde-Stream.html#method___unserialize"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A\u0024stream",
            "name": "stream",
            "summary": "Stream\u0020resource.",
            "url": "classes/Horde-Stream.html#property_stream"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "Configuration\u0020parameters.",
            "url": "classes/Horde-Stream.html#property__params"
        },                {
            "fqsen": "\\Horde_Stream\u003A\u003A\u0024_utf8_char",
            "name": "_utf8_char",
            "summary": "Parse\u0020character\u0020as\u0020UTF\u002D8\u0020data\u0020instead\u0020of\u0020single\u0020byte.",
            "url": "classes/Horde-Stream.html#property__utf8_char"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
