Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_SessionHandler_Exception",
            "name": "Horde_SessionHandler_Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020SessionHandler\u0020package.",
            "url": "classes/Horde-SessionHandler-Exception.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin",
            "name": "Horde_SessionHandler_Storage_Builtin",
            "summary": "SessionHandler\u0020storage\u0020implementation\u0020for\u0020PHP\u0027s\u0020built\u002Din\u0020session\u0020handler.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Builtin\u003A\u003A\u0024_path",
            "name": "_path",
            "summary": "Directory\u0020with\u0020session\u0020files.",
            "url": "classes/Horde-SessionHandler-Storage-Builtin.html#property__path"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_External",
            "name": "Horde_SessionHandler_Storage_External",
            "summary": "SessionHandler\u0020storage\u0020implementation\u0020for\u0020an\u0020external\u0020save\u0020handler\u0020defined\nvia\u0020configuration\u0020parameters.",
            "url": "classes/Horde-SessionHandler-Storage-External.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_External\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler-Storage-External.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_External\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-External.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_External\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-External.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_External\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-External.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_External\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-External.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_External\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-External.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_External\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-External.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_External\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler-Storage-External.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File",
            "name": "Horde_SessionHandler_Storage_File",
            "summary": "SessionHandler\u0020implementation\u0020for\u0020storage\u0020in\u0020text\u0020files.",
            "url": "classes/Horde-SessionHandler-Storage-File.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003A_open\u0028\u0029",
            "name": "_open",
            "summary": "Open\u0020the\u0020file\u0020stream\u0020connection.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#method__open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003APREFIX",
            "name": "PREFIX",
            "summary": "",
            "url": "classes/Horde-SessionHandler-Storage-File.html#constant_PREFIX"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_File\u003A\u003A\u0024_fp",
            "name": "_fp",
            "summary": "File\u0020stream.",
            "url": "classes/Horde-SessionHandler-Storage-File.html#property__fp"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable",
            "name": "Horde_SessionHandler_Storage_Hashtable",
            "summary": "Horde_HashTable\u0020SessionHandler\u0020driver.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003AtrackGC\u0028\u0029",
            "name": "trackGC",
            "summary": "Do\u0020garbage\u0020collection\u0020for\u0020session\u0020tracking\u0020information.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method_trackGC"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003A_getTrackIds\u0028\u0029",
            "name": "_getTrackIds",
            "summary": "Get\u0020the\u0020tracking\u0020IDs.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#method__getTrackIds"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003A\u0024_hash",
            "name": "_hash",
            "summary": "HashTable\u0020object.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#property__hash"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Current\u0020session\u0020ID.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#property__id"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Hashtable\u003A\u003A\u0024_trackID",
            "name": "_trackID",
            "summary": "The\u0020ID\u0020used\u0020for\u0020session\u0020tracking.",
            "url": "classes/Horde-SessionHandler-Storage-Hashtable.html#property__trackID"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache",
            "name": "Horde_SessionHandler_Storage_Memcache",
            "summary": "Memcache\u0020sessionhandler\u0020driver.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003AtrackGC\u0028\u0029",
            "name": "trackGC",
            "summary": "Do\u0020garbage\u0020collection\u0020for\u0020session\u0020tracking\u0020information.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#method_trackGC"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003A\u0024_memcache",
            "name": "_memcache",
            "summary": "Memcache\u0020object.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#property__memcache"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Current\u0020session\u0020ID.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#property__id"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Memcache\u003A\u003A\u0024_trackID",
            "name": "_trackID",
            "summary": "The\u0020ID\u0020used\u0020for\u0020session\u0020tracking.",
            "url": "classes/Horde-SessionHandler-Storage-Memcache.html#property__trackID"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo",
            "name": "Horde_SessionHandler_Storage_Mongo",
            "summary": "MongoDB\u0020storage\u0020driver.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003AcheckMongoIndices\u0028\u0029",
            "name": "checkMongoIndices",
            "summary": "",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method_checkMongoIndices"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003AcreateMongoIndices\u0028\u0029",
            "name": "createMongoIndices",
            "summary": "",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#method_createMongoIndices"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003ADATA",
            "name": "DATA",
            "summary": "",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#constant_DATA"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003ALOCK",
            "name": "LOCK",
            "summary": "",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#constant_LOCK"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003AMODIFIED",
            "name": "MODIFIED",
            "summary": "",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#constant_MODIFIED"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003ASID",
            "name": "SID",
            "summary": "",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#constant_SID"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003A\u0024_db",
            "name": "_db",
            "summary": "MongoCollection\u0020object\u0020for\u0020the\u0020storage\u0020table.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#property__db"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003A\u0024_locked",
            "name": "_locked",
            "summary": "Is\u0020the\u0020session\u0020locked.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#property__locked"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Mongo\u003A\u003A\u0024_indices",
            "name": "_indices",
            "summary": "Indices\u0020list.",
            "url": "classes/Horde-SessionHandler-Storage-Mongo.html#property__indices"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql",
            "name": "Horde_SessionHandler_Storage_Sql",
            "summary": "SessionHandler\u0020storage\u0020implementation\u0020for\u0020SQL\u0020databases.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Sql\u003A\u003A\u0024_db",
            "name": "_db",
            "summary": "Handle\u0020for\u0020the\u0020current\u0020database\u0020connection.",
            "url": "classes/Horde-SessionHandler-Storage-Sql.html#property__db"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack",
            "name": "Horde_SessionHandler_Storage_Stack",
            "summary": "SessionHandler\u0020storage\u0020implementation\u0020that\u0020will\u0020loop\u0020through\u0020a\u0020list\u0020of\nstorage\u0020drivers\u0020to\u0020handle\u0020the\u0020session\u0020information.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage_Stack\u003A\u003A\u0024_stack",
            "name": "_stack",
            "summary": "Stack\u0020of\u0020storage\u0020objects.",
            "url": "classes/Horde-SessionHandler-Storage-Stack.html#property__stack"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage",
            "name": "Horde_SessionHandler_Storage",
            "summary": "This\u0020is\u0020the\u0020abstract\u0020class\u0020that\u0020all\u0020SessionHandler\u0020storage\u0020drivers\u0020inherit\nfrom.",
            "url": "classes/Horde-SessionHandler-Storage.html"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler-Storage.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003A__sleep\u0028\u0029",
            "name": "__sleep",
            "summary": "Storage\u0020objects\u0020do\u0020not\u0020support\u0020serialization.",
            "url": "classes/Horde-SessionHandler-Storage.html#method___sleep"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003AsetLogger\u0028\u0029",
            "name": "setLogger",
            "summary": "Set\u0020the\u0020logger\u0020object.",
            "url": "classes/Horde-SessionHandler-Storage.html#method_setLogger"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler-Storage.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler-Storage.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003AisValidSessionID\u0028\u0029",
            "name": "isValidSessionID",
            "summary": "Validate\u0020a\u0020session\u0020id\u0020against\u0020the\u0020schema\u0020mentioned\u0020in\u0020the\u0020PHP\u0020manual\u0020page\u0020for\u0020session_id\u0028\u0029",
            "url": "classes/Horde-SessionHandler-Storage.html#method_isValidSessionID"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003A\u0024readonly",
            "name": "readonly",
            "summary": "Access\u0020session\u0020read\u002Donly\u003F",
            "url": "classes/Horde-SessionHandler-Storage.html#property_readonly"
        },                {
            "fqsen": "\\Horde_SessionHandler_Storage\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "Hash\u0020containing\u0020connection\u0020parameters.",
            "url": "classes/Horde-SessionHandler-Storage.html#property__params"
        },                {
            "fqsen": "\\Horde_SessionHandler",
            "name": "Horde_SessionHandler",
            "summary": "This\u0020class\u0020provides\u0020the\u0020interface\u0020to\u0020the\u0020session\u0020storage\u0020backend.",
            "url": "classes/Horde-SessionHandler.html"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SessionHandler.html#method___construct"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "Destructor.",
            "url": "classes/Horde-SessionHandler.html#method___destruct"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler.html#method_open"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler.html#method_close"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler.html#method_read"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020session\u0020data\u0020to\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler.html#method_write"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003Adestroy\u0028\u0029",
            "name": "destroy",
            "summary": "Destroy\u0020the\u0020data\u0020for\u0020a\u0020particular\u0020session\u0020identifier\u0020in\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler.html#method_destroy"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003Agc\u0028\u0029",
            "name": "gc",
            "summary": "Garbage\u0020collect\u0020stale\u0020sessions\u0020from\u0020the\u0020backend.",
            "url": "classes/Horde-SessionHandler.html#method_gc"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003AgetSessionIDs\u0028\u0029",
            "name": "getSessionIDs",
            "summary": "Get\u0020a\u0020list\u0020of\u0020the\u0020valid\u0020session\u0020identifiers.",
            "url": "classes/Horde-SessionHandler.html#method_getSessionIDs"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003AgetSessionsInfo\u0028\u0029",
            "name": "getSessionsInfo",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020authenticated\u0020users\u0020and\u0020data\u0020about\u0020their\u0020session.",
            "url": "classes/Horde-SessionHandler.html#method_getSessionsInfo"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003A\u0024changed",
            "name": "changed",
            "summary": "If\u0020true,\u0020indicates\u0020the\u0020session\u0020data\u0020has\u0020changed.",
            "url": "classes/Horde-SessionHandler.html#property_changed"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003A\u0024_connected",
            "name": "_connected",
            "summary": "Has\u0020a\u0020connection\u0020been\u0020made\u0020to\u0020the\u0020backend\u003F",
            "url": "classes/Horde-SessionHandler.html#property__connected"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003A\u0024_logger",
            "name": "_logger",
            "summary": "A\u0020logger\u0020instance.",
            "url": "classes/Horde-SessionHandler.html#property__logger"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "Configuration\u0020parameters.",
            "url": "classes/Horde-SessionHandler.html#property__params"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003A\u0024_sig",
            "name": "_sig",
            "summary": "Initial\u0020session\u0020data\u0020signature.",
            "url": "classes/Horde-SessionHandler.html#property__sig"
        },                {
            "fqsen": "\\Horde_SessionHandler\u003A\u003A\u0024_storage",
            "name": "_storage",
            "summary": "The\u0020storage\u0020object.",
            "url": "classes/Horde-SessionHandler.html#property__storage"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
