Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_JavascriptMinify_Closure",
            "name": "Horde_JavascriptMinify_Closure",
            "summary": "Google\u0020Closure\u0020Compiler\u0020minification\u0020driver.",
            "url": "classes/Horde-JavascriptMinify-Closure.html"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Closure\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Closure.html#method_setOptions"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Closure\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "Return\u0020the\u0020minified\u0020javascript.",
            "url": "classes/Horde-JavascriptMinify-Closure.html#method_minify"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Exception",
            "name": "Horde_JavascriptMinify_Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020Horde_JavascriptMinify\u0020package.",
            "url": "classes/Horde-JavascriptMinify-Exception.html"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Null",
            "name": "Horde_JavascriptMinify_Null",
            "summary": "Javascript\u0020minification\u0020driver\u0020that\u0020does\u0020nothing\u0020\u0028returns\u0020the\u0020unaltered\njavascript\u0029.",
            "url": "classes/Horde-JavascriptMinify-Null.html"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Null\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "Return\u0020the\u0020minified\u0020javascript.",
            "url": "classes/Horde-JavascriptMinify-Null.html#method_minify"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Uglifyjs",
            "name": "Horde_JavascriptMinify_Uglifyjs",
            "summary": "UglifyJS\u0020minification\u0020driver.\u0020\u0020Supports\u0020UglifyJS\u0020versions\u00201\u0020\u0028with\u0020limited\nfeatures\u0029\u0020and\u00202.",
            "url": "classes/Horde-JavascriptMinify-Uglifyjs.html"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Uglifyjs\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Uglifyjs.html#method_setOptions"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Uglifyjs\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "Return\u0020the\u0020minified\u0020javascript.",
            "url": "classes/Horde-JavascriptMinify-Uglifyjs.html#method_minify"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Util_Cmdline",
            "name": "Horde_JavascriptMinify_Util_Cmdline",
            "summary": "Class\u0020that\u0020provides\u0020common\u0020function\u0020for\u0020running\u0020a\u0020command\u0020line\u0020program.",
            "url": "classes/Horde-JavascriptMinify-Util-Cmdline.html"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Util_Cmdline\u003A\u003ArunCmd\u0028\u0029",
            "name": "runCmd",
            "summary": "Runs\u0020the\u0020compression\u0020command\u0020and\u0020returns\u0020the\u0020output.",
            "url": "classes/Horde-JavascriptMinify-Util-Cmdline.html#method_runCmd"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Yui",
            "name": "Horde_JavascriptMinify_Yui",
            "summary": "YUI\u0020Compressor\u0020minification\u0020driver.",
            "url": "classes/Horde-JavascriptMinify-Yui.html"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Yui\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Yui.html#method_setOptions"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Yui\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "Return\u0020the\u0020minified\u0020javascript.",
            "url": "classes/Horde-JavascriptMinify-Yui.html#method_minify"
        },                {
            "fqsen": "\\Horde_JavascriptMinify",
            "name": "Horde_JavascriptMinify",
            "summary": "Abstract\u0020base\u0020class\u0020for\u0020implementing\u0020a\u0020javascript\u0020minification\u0020driver.",
            "url": "classes/Horde-JavascriptMinify.html"
        },                {
            "fqsen": "\\Horde_JavascriptMinify\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-JavascriptMinify.html#method___construct"
        },                {
            "fqsen": "\\Horde_JavascriptMinify\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify.html#method___toString"
        },                {
            "fqsen": "\\Horde_JavascriptMinify\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "Set\u0020minification\u0020options.",
            "url": "classes/Horde-JavascriptMinify.html#method_setOptions"
        },                {
            "fqsen": "\\Horde_JavascriptMinify\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "Return\u0020the\u0020minified\u0020javascript.",
            "url": "classes/Horde-JavascriptMinify.html#method_minify"
        },                {
            "fqsen": "\\Horde_JavascriptMinify\u003A\u003Asourcemap\u0028\u0029",
            "name": "sourcemap",
            "summary": "Returns\u0020the\u0020sourcemap\u0020data.",
            "url": "classes/Horde-JavascriptMinify.html#method_sourcemap"
        },                {
            "fqsen": "\\Horde_JavascriptMinify\u003A\u003A_sourceUrls\u0028\u0029",
            "name": "_sourceUrls",
            "summary": "Creates\u0020a\u0020list\u0020of\u0020source\u0020comments\u0020linking\u0020to\u0020the\u0020original\u0020URLs\u0020of\u0020the\nsource\u0020files.",
            "url": "classes/Horde-JavascriptMinify.html#method__sourceUrls"
        },                {
            "fqsen": "\\Horde_JavascriptMinify\u003A\u003A\u0024_data",
            "name": "_data",
            "summary": "Original\u0020javascript\u0020data.",
            "url": "classes/Horde-JavascriptMinify.html#property__data"
        },                {
            "fqsen": "\\Horde_JavascriptMinify\u003A\u003A\u0024_opts",
            "name": "_opts",
            "summary": "Minification\u0020options.",
            "url": "classes/Horde-JavascriptMinify.html#property__opts"
        },                {
            "fqsen": "\\Horde_JavascriptMinify\u003A\u003A\u0024_sourcemap",
            "name": "_sourcemap",
            "summary": "Temporary\u0020file\u0020containing\u0020sourcemap\u0020data.",
            "url": "classes/Horde-JavascriptMinify.html#property__sourcemap"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
