Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine",
            "name": "Horde_Stream_Wrapper_Combine",
            "summary": "A\u0020stream\u0020wrapper\u0020that\u0020will\u0020combine\u0020multiple\u0020strings\/streams\u0020into\u0020a\u0020single\nstream.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Create\u0020a\u0020stream\u0020from\u0020multiple\u0020data\u0020sources.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_getStream"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_open\u0028\u0029",
            "name": "stream_open",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_open"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_read\u0028\u0029",
            "name": "stream_read",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_read"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_write\u0028\u0029",
            "name": "stream_write",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_write"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_tell\u0028\u0029",
            "name": "stream_tell",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_tell"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_eof\u0028\u0029",
            "name": "stream_eof",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_eof"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_stat\u0028\u0029",
            "name": "stream_stat",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_stat"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_seek\u0028\u0029",
            "name": "stream_seek",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_seek"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003AWRAPPER_NAME",
            "name": "WRAPPER_NAME",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#constant_WRAPPER_NAME"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024context",
            "name": "context",
            "summary": "Context.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property_context"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_data",
            "name": "_data",
            "summary": "Array\u0020that\u0020holds\u0020the\u0020various\u0020streams.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__data"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_length",
            "name": "_length",
            "summary": "The\u0020combined\u0020length\u0020of\u0020the\u0020stream.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__length"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_position",
            "name": "_position",
            "summary": "The\u0020current\u0020position\u0020in\u0020the\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__position"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_datapos",
            "name": "_datapos",
            "summary": "The\u0020current\u0020position\u0020in\u0020the\u0020data\u0020array.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__datapos"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_ateof",
            "name": "_ateof",
            "summary": "Have\u0020we\u0020reached\u0020EOF\u003F",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__ateof"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Unique\u0020ID\u0020tracker\u0020for\u0020the\u0020streams.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__id"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_CombineStream",
            "name": "Horde_Stream_Wrapper_CombineStream",
            "summary": "Provides\u0020access\u0020to\u0020the\u0020CombineStream\u0020stream\u0020wrapper.",
            "url": "classes/Horde-Stream-Wrapper-CombineStream.html"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_CombineStream\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Return\u0020a\u0020reference\u0020to\u0020the\u0020data.",
            "url": "classes/Horde-Stream-Wrapper-CombineStream.html#method_getData"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String",
            "name": "Horde_Stream_Wrapper_String",
            "summary": "A\u0020stream\u0020wrapper\u0020that\u0020will\u0020treat\u0020a\u0020native\u0020PHP\u0020string\u0020as\u0020a\u0020stream.",
            "url": "classes/Horde-Stream-Wrapper-String.html"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Create\u0020a\u0020stream\u0020from\u0020a\u0020PHP\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_getStream"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_open\u0028\u0029",
            "name": "stream_open",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_open"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_close\u0028\u0029",
            "name": "stream_close",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_close"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_read\u0028\u0029",
            "name": "stream_read",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_read"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_write\u0028\u0029",
            "name": "stream_write",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_write"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_tell\u0028\u0029",
            "name": "stream_tell",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_tell"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_eof\u0028\u0029",
            "name": "stream_eof",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_eof"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_stat\u0028\u0029",
            "name": "stream_stat",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_stat"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_seek\u0028\u0029",
            "name": "stream_seek",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_seek"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003AWRAPPER_NAME",
            "name": "WRAPPER_NAME",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#constant_WRAPPER_NAME"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003A\u0024context",
            "name": "context",
            "summary": "The\u0020current\u0020context.",
            "url": "classes/Horde-Stream-Wrapper-String.html#property_context"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003A\u0024_pos",
            "name": "_pos",
            "summary": "String\u0020position.",
            "url": "classes/Horde-Stream-Wrapper-String.html#property__pos"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003A\u0024_string",
            "name": "_string",
            "summary": "The\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-String.html#property__string"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Unique\u0020ID\u0020tracker\u0020for\u0020the\u0020streams.",
            "url": "classes/Horde-Stream-Wrapper-String.html#property__id"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_StringStream",
            "name": "Horde_Stream_Wrapper_StringStream",
            "summary": "Provides\u0020access\u0020to\u0020the\u0020StringStream\u0020stream\u0020wrapper.",
            "url": "classes/Horde-Stream-Wrapper-StringStream.html"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_StringStream\u003A\u003AgetString\u0028\u0029",
            "name": "getString",
            "summary": "Return\u0020a\u0020reference\u0020to\u0020the\u0020wrapped\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-StringStream.html#method_getString"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
