Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine",
            "name": "Horde_Stream_Wrapper_Combine",
            "summary": "A\u0020stream\u0020wrapper\u0020that\u0020will\u0020combine\u0020multiple\u0020strings\/streams\u0020into\u0020a\u0020single\nstream.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Create\u0020a\u0020stream\u0020from\u0020multiple\u0020data\u0020sources.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_getStream"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_open\u0028\u0029",
            "name": "stream_open",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_open"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_read\u0028\u0029",
            "name": "stream_read",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_read"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_write\u0028\u0029",
            "name": "stream_write",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_write"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_tell\u0028\u0029",
            "name": "stream_tell",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_tell"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_eof\u0028\u0029",
            "name": "stream_eof",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_eof"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_stat\u0028\u0029",
            "name": "stream_stat",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_stat"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003Astream_seek\u0028\u0029",
            "name": "stream_seek",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#method_stream_seek"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003AWRAPPER_NAME",
            "name": "WRAPPER_NAME",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#constant_WRAPPER_NAME"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024context",
            "name": "context",
            "summary": "Context.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property_context"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_data",
            "name": "_data",
            "summary": "Array\u0020that\u0020holds\u0020the\u0020various\u0020streams.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__data"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_length",
            "name": "_length",
            "summary": "The\u0020combined\u0020length\u0020of\u0020the\u0020stream.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__length"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_position",
            "name": "_position",
            "summary": "The\u0020current\u0020position\u0020in\u0020the\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__position"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_datapos",
            "name": "_datapos",
            "summary": "The\u0020current\u0020position\u0020in\u0020the\u0020data\u0020array.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__datapos"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_ateof",
            "name": "_ateof",
            "summary": "Have\u0020we\u0020reached\u0020EOF\u003F",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__ateof"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_Combine\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Unique\u0020ID\u0020tracker\u0020for\u0020the\u0020streams.",
            "url": "classes/Horde-Stream-Wrapper-Combine.html#property__id"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_CombineStream",
            "name": "Horde_Stream_Wrapper_CombineStream",
            "summary": "Provides\u0020access\u0020to\u0020the\u0020CombineStream\u0020stream\u0020wrapper.",
            "url": "classes/Horde-Stream-Wrapper-CombineStream.html"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_CombineStream\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Return\u0020a\u0020reference\u0020to\u0020the\u0020data.",
            "url": "classes/Horde-Stream-Wrapper-CombineStream.html#method_getData"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String",
            "name": "Horde_Stream_Wrapper_String",
            "summary": "A\u0020stream\u0020wrapper\u0020that\u0020will\u0020treat\u0020a\u0020native\u0020PHP\u0020string\u0020as\u0020a\u0020stream.",
            "url": "classes/Horde-Stream-Wrapper-String.html"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Create\u0020a\u0020stream\u0020from\u0020a\u0020PHP\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_getStream"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_open\u0028\u0029",
            "name": "stream_open",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_open"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_close\u0028\u0029",
            "name": "stream_close",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_close"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_read\u0028\u0029",
            "name": "stream_read",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_read"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_write\u0028\u0029",
            "name": "stream_write",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_write"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_tell\u0028\u0029",
            "name": "stream_tell",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_tell"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_eof\u0028\u0029",
            "name": "stream_eof",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_eof"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_stat\u0028\u0029",
            "name": "stream_stat",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_stat"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003Astream_seek\u0028\u0029",
            "name": "stream_seek",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#method_stream_seek"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003AWRAPPER_NAME",
            "name": "WRAPPER_NAME",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-String.html#constant_WRAPPER_NAME"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003A\u0024context",
            "name": "context",
            "summary": "The\u0020current\u0020context.",
            "url": "classes/Horde-Stream-Wrapper-String.html#property_context"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003A\u0024_pos",
            "name": "_pos",
            "summary": "String\u0020position.",
            "url": "classes/Horde-Stream-Wrapper-String.html#property__pos"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003A\u0024_string",
            "name": "_string",
            "summary": "The\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-String.html#property__string"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_String\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Unique\u0020ID\u0020tracker\u0020for\u0020the\u0020streams.",
            "url": "classes/Horde-Stream-Wrapper-String.html#property__id"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_StringStream",
            "name": "Horde_Stream_Wrapper_StringStream",
            "summary": "Provides\u0020access\u0020to\u0020the\u0020StringStream\u0020stream\u0020wrapper.",
            "url": "classes/Horde-Stream-Wrapper-StringStream.html"
        },                {
            "fqsen": "\\Horde_Stream_Wrapper_StringStream\u003A\u003AgetString\u0028\u0029",
            "name": "getString",
            "summary": "Return\u0020a\u0020reference\u0020to\u0020the\u0020wrapped\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-StringStream.html#method_getString"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineStreamWrapper",
            "name": "CombineStreamWrapper",
            "summary": "Provides\u0020access\u0020to\u0020the\u0020CombineStream\u0020stream\u0020wrapper.",
            "url": "classes/Horde-Stream-Wrapper-CombineStreamWrapper.html"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineStreamWrapper\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Return\u0020a\u0020reference\u0020to\u0020the\u0020data.",
            "url": "classes/Horde-Stream-Wrapper-CombineStreamWrapper.html#method_getData"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper",
            "name": "CombineWrapper",
            "summary": "A\u0020stream\u0020wrapper\u0020that\u0020will\u0020combine\u0020multiple\u0020strings\/streams\u0020into\u0020a\u0020single\nstream.\u0020Stream\u0020Wrappers\u0020implement\u0020method\u0020signatures\u0020defined\u0020in\u0020the\u0020builtin\nclass\u0020streamWrapper\u0020but\u0020they\u0020do\u0020not\u0020need\u0020to\u0020inherit\u0020from\u0020it.\u0020Not\u0020all\u0020methods\nof\u0020streamWrapper\u0020need\u0020to\u0020be\u0020implemented.\u0020We\u0020follow\u0020the\u0020signatures\u0020as\u0020defined\nin\u0020the\u0020php\u0020manual",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Create\u0020a\u0020stream\u0020from\u0020multiple\u0020data\u0020sources.",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#method_getStream"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003Astream_open\u0028\u0029",
            "name": "stream_open",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#method_stream_open"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003Astream_read\u0028\u0029",
            "name": "stream_read",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#method_stream_read"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003Astream_write\u0028\u0029",
            "name": "stream_write",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#method_stream_write"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003Astream_tell\u0028\u0029",
            "name": "stream_tell",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#method_stream_tell"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003Astream_eof\u0028\u0029",
            "name": "stream_eof",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#method_stream_eof"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003Astream_stat\u0028\u0029",
            "name": "stream_stat",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#method_stream_stat"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003Astream_seek\u0028\u0029",
            "name": "stream_seek",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#method_stream_seek"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003AWRAPPER_NAME",
            "name": "WRAPPER_NAME",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#constant_WRAPPER_NAME"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003A\u0024context",
            "name": "context",
            "summary": "Context.",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#property_context"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003A\u0024data",
            "name": "data",
            "summary": "Array\u0020that\u0020holds\u0020the\u0020various\u0020streams.",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#property_data"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003A\u0024length",
            "name": "length",
            "summary": "The\u0020combined\u0020length\u0020of\u0020the\u0020stream.",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#property_length"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003A\u0024position",
            "name": "position",
            "summary": "The\u0020current\u0020position\u0020in\u0020the\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#property_position"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003A\u0024datapos",
            "name": "datapos",
            "summary": "The\u0020current\u0020position\u0020in\u0020the\u0020data\u0020array.",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#property_datapos"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003A\u0024ateof",
            "name": "ateof",
            "summary": "Have\u0020we\u0020reached\u0020EOF\u003F",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#property_ateof"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\CombineWrapper\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Unique\u0020ID\u0020tracker\u0020for\u0020the\u0020streams.",
            "url": "classes/Horde-Stream-Wrapper-CombineWrapper.html#property_id"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringStreamWrapper",
            "name": "StringStreamWrapper",
            "summary": "Provides\u0020access\u0020to\u0020the\u0020StringStream\u0020stream\u0020wrapper.",
            "url": "classes/Horde-Stream-Wrapper-StringStreamWrapper.html"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringStreamWrapper\u003A\u003AgetString\u0028\u0029",
            "name": "getString",
            "summary": "Return\u0020a\u0020reference\u0020to\u0020the\u0020wrapped\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-StringStreamWrapper.html#method_getString"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper",
            "name": "StringWrapper",
            "summary": "A\u0020stream\u0020wrapper\u0020that\u0020will\u0020treat\u0020a\u0020native\u0020PHP\u0020string\u0020as\u0020a\u0020stream.",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Create\u0020a\u0020stream\u0020from\u0020a\u0020PHP\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#method_getStream"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003Astream_open\u0028\u0029",
            "name": "stream_open",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#method_stream_open"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003Astream_close\u0028\u0029",
            "name": "stream_close",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#method_stream_close"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003Astream_read\u0028\u0029",
            "name": "stream_read",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#method_stream_read"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003Astream_write\u0028\u0029",
            "name": "stream_write",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#method_stream_write"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003Astream_tell\u0028\u0029",
            "name": "stream_tell",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#method_stream_tell"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003Astream_eof\u0028\u0029",
            "name": "stream_eof",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#method_stream_eof"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003Astream_stat\u0028\u0029",
            "name": "stream_stat",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#method_stream_stat"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003Astream_seek\u0028\u0029",
            "name": "stream_seek",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#method_stream_seek"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003AWRAPPER_NAME",
            "name": "WRAPPER_NAME",
            "summary": "",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#constant_WRAPPER_NAME"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003A\u0024context",
            "name": "context",
            "summary": "The\u0020current\u0020context.",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#property_context"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003A\u0024pos",
            "name": "pos",
            "summary": "String\u0020position.",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#property_pos"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003A\u0024string",
            "name": "string",
            "summary": "The\u0020string.",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#property_string"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper\\StringWrapper\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Unique\u0020ID\u0020tracker\u0020for\u0020the\u0020streams.",
            "url": "classes/Horde-Stream-Wrapper-StringWrapper.html#property_id"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Stream\\Wrapper",
            "name": "Wrapper",
            "summary": "",
            "url": "namespaces/horde-stream-wrapper.html"
        },                {
            "fqsen": "\\Horde\\Stream",
            "name": "Stream",
            "summary": "",
            "url": "namespaces/horde-stream.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
