Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Http_Client",
            "name": "Horde_Http_Client",
            "summary": "An\u0020HTTP\u0020client.",
            "url": "classes/Horde-Http-Client.html"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Horde_Http_Client\u0020constructor.",
            "url": "classes/Horde-Http-Client.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Sends\u0020a\u0020GET\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_get"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Sends\u0020a\u0020POST\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_post"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Sends\u0020a\u0020PUT\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_put"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Sends\u0020a\u0020DELETE\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_delete"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Ahead\u0028\u0029",
            "name": "head",
            "summary": "Sends\u0020a\u0020HEAD\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_head"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Sends\u0020an\u0020HTTP\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_request"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Returns\u0020a\u0020client\u0020parameter.",
            "url": "classes/Horde-Http-Client.html#method___get"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Sets\u0020a\u0020client\u0020parameter.",
            "url": "classes/Horde-Http-Client.html#method___set"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A\u0024_request",
            "name": "_request",
            "summary": "The\u0020current\u0020HTTP\u0020request.",
            "url": "classes/Horde-Http-Client.html#property__request"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A\u0024_lastRequest",
            "name": "_lastRequest",
            "summary": "The\u0020previous\u0020HTTP\u0020request.",
            "url": "classes/Horde-Http-Client.html#property__lastRequest"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A\u0024_lastResponse",
            "name": "_lastResponse",
            "summary": "The\u0020most\u0020recent\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Client.html#property__lastResponse"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A\u0024_httpMethodOverride",
            "name": "_httpMethodOverride",
            "summary": "Use\u0020POST\u0020instead\u0020of\u0020PUT\u0020and\u0020DELETE,\u0020sending\u0020X\u002DHTTP\u002DMethod\u002DOverride\u0020with\nthe\u0020intended\u0020method\u0020name\u0020instead.",
            "url": "classes/Horde-Http-Client.html#property__httpMethodOverride"
        },                {
            "fqsen": "\\Horde_Http_Exception",
            "name": "Horde_Http_Exception",
            "summary": "Base\u0020exception\u0020for\u0020the\u0020Horde_Http\u0020library.",
            "url": "classes/Horde-Http-Exception.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Base",
            "name": "Horde_Http_Request_Base",
            "summary": "Base\u0020class\u0020for\u0020HTTP\u0020request\u0020objects.",
            "url": "classes/Horde-Http-Request-Base.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Base.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "",
            "url": "classes/Horde-Http-Request-Base.html#method_setOptions"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003AgetDefaultOptions\u0028\u0029",
            "name": "getDefaultOptions",
            "summary": "",
            "url": "classes/Horde-Http-Request-Base.html#method_getDefaultOptions"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Base.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Get\u0020an\u0020adapter\u0020parameter",
            "url": "classes/Horde-Http-Request-Base.html#method___get"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Set\u0020a\u0020request\u0020parameter",
            "url": "classes/Horde-Http-Request-Base.html#method___set"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003AsetHeaders\u0028\u0029",
            "name": "setHeaders",
            "summary": "Set\u0020one\u0020or\u0020more\u0020headers",
            "url": "classes/Horde-Http-Request-Base.html#method_setHeaders"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "Get\u0020the\u0020current\u0020value\u0020of\u0020\u0024header",
            "url": "classes/Horde-Http-Request-Base.html#method_getHeader"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A\u0024_headers",
            "name": "_headers",
            "summary": "Request\u0020headers",
            "url": "classes/Horde-Http-Request-Base.html#property__headers"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A\u0024_options",
            "name": "_options",
            "summary": "",
            "url": "classes/Horde-Http-Request-Base.html#property__options"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl",
            "name": "Horde_Http_Request_Curl",
            "summary": "HTTP\u0020request\u0020object\u0020for\u0020the\u0020curl\u0020backend.",
            "url": "classes/Horde-Http-Request-Curl.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Curl.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Curl.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl\u003A\u003A_httpAuthScheme\u0028\u0029",
            "name": "_httpAuthScheme",
            "summary": "Translate\u0020a\u0020Horde_Http\u003A\u003AAUTH_\u002A\u0020constant\u0020to\u0020CURLAUTH_\u002A",
            "url": "classes/Horde-Http-Request-Curl.html#method__httpAuthScheme"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl\u003A\u003A\u0024_httpAuthSchemes",
            "name": "_httpAuthSchemes",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nHTTP_AUTH\u0020constants.",
            "url": "classes/Horde-Http-Request-Curl.html#property__httpAuthSchemes"
        },                {
            "fqsen": "\\Horde_Http_Request_Factory",
            "name": "Horde_Http_Request_Factory",
            "summary": "HTTP\u0020request\u0020object\u0020factory.",
            "url": "classes/Horde-Http-Request-Factory.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Factory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Find\u0020the\u0020best\u0020available\u0020request\u0020backend",
            "url": "classes/Horde-Http-Request-Factory.html#method_create"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen",
            "name": "Horde_Http_Request_Fopen",
            "summary": "HTTP\u0020request\u0020object\u0020for\u0020the\u0020fopen\u0020backend.",
            "url": "classes/Horde-Http-Request-Fopen.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Fopen.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Fopen.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen\u003A\u003A_errorHandler\u0028\u0029",
            "name": "_errorHandler",
            "summary": "PHP\u0020error\u0020handler.",
            "url": "classes/Horde-Http-Request-Fopen.html#method__errorHandler"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen\u003A\u003A\u0024_errors",
            "name": "_errors",
            "summary": "Catched\u0020errors\u0020from\u0020the\u0020error\u0020handler.",
            "url": "classes/Horde-Http-Request-Fopen.html#property__errors"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock",
            "name": "Horde_Http_Request_Mock",
            "summary": "Mock\u0020HTTP\u0020request\u0020object.",
            "url": "classes/Horde-Http-Request-Mock.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Mock.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003AsetResponse\u0028\u0029",
            "name": "setResponse",
            "summary": "Set\u0020the\u0020HTTP\u0020response\u0028s\u0029\u0020to\u0020be\u0020returned\u0020by\u0020this\u0020adapter.\u0020This\u0020overwrites\nany\u0020responses\u0020set\u0020before.",
            "url": "classes/Horde-Http-Request-Mock.html#method_setResponse"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003AaddResponses\u0028\u0029",
            "name": "addResponses",
            "summary": "Set\u0020the\u0020HTTP\u0020response\u0028s\u0029\u0020to\u0020be\u0020returned\u0020by\u0020this\u0020adapter\u0020as\u0020an\u0020array\u0020of\u0020strings.",
            "url": "classes/Horde-Http-Request-Mock.html#method_addResponses"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003AaddResponse\u0028\u0029",
            "name": "addResponse",
            "summary": "Adds\u0020a\u0020response\u0020to\u0020the\u0020stack\u0020of\u0020responses.",
            "url": "classes/Horde-Http-Request-Mock.html#method_addResponse"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003A\u0024_responses",
            "name": "_responses",
            "summary": "Mock\u0020responses\u0020to\u0020return.",
            "url": "classes/Horde-Http-Request-Mock.html#property__responses"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp",
            "name": "Horde_Http_Request_Peclhttp",
            "summary": "HTTP\u0020request\u0020object\u0020for\u0020the\u0020pecl_http\u00201.0\u0020backend.",
            "url": "classes/Horde-Http-Request-Peclhttp.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Peclhttp.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Peclhttp.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp\u003A\u003A\u0024_httpAuthSchemes",
            "name": "_httpAuthSchemes",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nHTTP_AUTH\u0020constants.",
            "url": "classes/Horde-Http-Request-Peclhttp.html#property__httpAuthSchemes"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2",
            "name": "Horde_Http_Request_Peclhttp2",
            "summary": "HTTP\u0020request\u0020object\u0020for\u0020the\u0020pecl_http\u00202.0\u0020backend.",
            "url": "classes/Horde-Http-Request-Peclhttp2.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Peclhttp2.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Peclhttp2.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2\u003A\u003A\u0024_httpAuthSchemes",
            "name": "_httpAuthSchemes",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nHTTP_AUTH\u0020constants.",
            "url": "classes/Horde-Http-Request-Peclhttp2.html#property__httpAuthSchemes"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2\u003A\u003A\u0024_proxyTypes",
            "name": "_proxyTypes",
            "summary": "Map\u0020of\u0020proxy\u0020types\u0020from\u0020Horde_Http\u0020to\u0020implementation\u0020specific\u0020constants.",
            "url": "classes/Horde-Http-Request-Peclhttp2.html#property__proxyTypes"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase",
            "name": "Horde_Http_Request_PeclhttpBase",
            "summary": "Base\u0020HTTP\u0020request\u0020object\u0020for\u0020the\u0020pecl_http\u0020backends.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A_httpAuthScheme\u0028\u0029",
            "name": "_httpAuthScheme",
            "summary": "Translates\u0020a\u0020Horde_Http\u003A\u003AAUTH_\u002A\u0020constant\u0020to\u0020implementation\u0020specific\nconstants.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#method__httpAuthScheme"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A_proxyType\u0028\u0029",
            "name": "_proxyType",
            "summary": "Translates\u0020a\u0020Horde_Http\u003A\u003APROXY_\u002A\u0020constant\u0020to\u0020implementation\u0020specific\nconstants.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#method__proxyType"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A_httpOptions\u0028\u0029",
            "name": "_httpOptions",
            "summary": "Generates\u0020the\u0020HTTP\u0020options\u0020for\u0020the\u0020request.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#method__httpOptions"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A\u0024_httpAuthSchemes",
            "name": "_httpAuthSchemes",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nimplementation\u0020specific\u0020constants.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#property__httpAuthSchemes"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A\u0024_proxyTypes",
            "name": "_proxyTypes",
            "summary": "Map\u0020of\u0020proxy\u0020types\u0020from\u0020Horde_Http\u0020to\u0020implementation\u0020specific\u0020constants.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#property__proxyTypes"
        },                {
            "fqsen": "\\Horde_Http_Response_Base",
            "name": "Horde_Http_Response_Base",
            "summary": "Base\u0020class\u0020for\u0020HTTP\u0020response\u0020objects.",
            "url": "classes/Horde-Http-Response-Base.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A_parseHeaders\u0028\u0029",
            "name": "_parseHeaders",
            "summary": "Parses\u0020an\u0020array\u0020of\u0020response\u0020headers,\u0020mindful\u0020of\u0020line\u0020continuations,\u0020etc.",
            "url": "classes/Horde-Http-Response-Base.html#method__parseHeaders"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Base.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Returns\u0020a\u0020stream\u0020pointing\u0020to\u0020the\u0020response\u0020body\u0020that\u0020can\u0020be\u0020used\u0020with\u0020all\nstandard\u0020PHP\u0020stream\u0020functions.",
            "url": "classes/Horde-Http-Response-Base.html#method_getStream"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "Returns\u0020the\u0020value\u0020of\u0020a\u0020single\u0020response\u0020header.",
            "url": "classes/Horde-Http-Response-Base.html#method_getHeader"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "Fetched\u0020URI.",
            "url": "classes/Horde-Http-Response-Base.html#property_uri"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024httpVersion",
            "name": "httpVersion",
            "summary": "HTTP\u0020protocol\u0020version\u0020that\u0020was\u0020used.",
            "url": "classes/Horde-Http-Response-Base.html#property_httpVersion"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024code",
            "name": "code",
            "summary": "HTTP\u0020response\u0020code.",
            "url": "classes/Horde-Http-Response-Base.html#property_code"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "Response\u0020headers.",
            "url": "classes/Horde-Http-Response-Base.html#property_headers"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024_headers",
            "name": "_headers",
            "summary": "Case\u002Dinsensitive\u0020list\u0020of\u0020headers.",
            "url": "classes/Horde-Http-Response-Base.html#property__headers"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl",
            "name": "Horde_Http_Response_Curl",
            "summary": "HTTP\u0020response\u0020object\u0020for\u0020the\u0020curl\u0020backend.",
            "url": "classes/Horde-Http-Response-Curl.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Http-Response-Curl.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Curl.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A_parseResult\u0028\u0029",
            "name": "_parseResult",
            "summary": "Parses\u0020the\u0020combined\u0020header\/body\u0020result\u0020from\u0020cURL.",
            "url": "classes/Horde-Http-Response-Curl.html#method__parseResult"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A_parseInfo\u0028\u0029",
            "name": "_parseInfo",
            "summary": "Processes\u0020the\u0020results\u0020of\u0020curl_getinfo.",
            "url": "classes/Horde-Http-Response-Curl.html#method__parseInfo"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A\u0024_info",
            "name": "_info",
            "summary": "Info\u0020on\u0020the\u0020request\u0020obtained\u0020from\u0020curl_getinfo\u0028\u0029.",
            "url": "classes/Horde-Http-Response-Curl.html#property__info"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A\u0024_body",
            "name": "_body",
            "summary": "Response\u0020body.",
            "url": "classes/Horde-Http-Response-Curl.html#property__body"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen",
            "name": "Horde_Http_Response_Fopen",
            "summary": "HTTP\u0020response\u0020object\u0020for\u0020the\u0020fopen\u0020backend.",
            "url": "classes/Horde-Http-Response-Fopen.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Http-Response-Fopen.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Fopen.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Returns\u0020a\u0020stream\u0020pointing\u0020to\u0020the\u0020response\u0020body\u0020that\u0020can\u0020be\u0020used\u0020with\nall\u0020standard\u0020PHP\u0020stream\u0020functions.",
            "url": "classes/Horde-Http-Response-Fopen.html#method_getStream"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003A\u0024_stream",
            "name": "_stream",
            "summary": "Response\u0020body.",
            "url": "classes/Horde-Http-Response-Fopen.html#property__stream"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003A\u0024_content",
            "name": "_content",
            "summary": "Response\u0020content",
            "url": "classes/Horde-Http-Response-Fopen.html#property__content"
        },                {
            "fqsen": "\\Horde_Http_Response_Mock",
            "name": "Horde_Http_Response_Mock",
            "summary": "Mock\u0020HTTP\u0020response\u0020object.",
            "url": "classes/Horde-Http-Response-Mock.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Mock\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Response-Mock.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Mock\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Mock.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp",
            "name": "Horde_Http_Response_Peclhttp",
            "summary": "HTTP\u0020response\u0020object\u0020for\u0020the\u0020pecl_http\u0020backend.",
            "url": "classes/Horde-Http-Response-Peclhttp.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Http-Response-Peclhttp.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Peclhttp.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp\u003A\u003A\u0024_message",
            "name": "_message",
            "summary": "HttpMessage\u0020object.",
            "url": "classes/Horde-Http-Response-Peclhttp.html#property__message"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp2",
            "name": "Horde_Http_Response_Peclhttp2",
            "summary": "HTTP\u0020response\u0020object\u0020for\u0020the\u0020pecl_http\u00202.0\u0020backend.",
            "url": "classes/Horde-Http-Response-Peclhttp2.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp2\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Http-Response-Peclhttp2.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp2\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Peclhttp2.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp2\u003A\u003A\u0024_response",
            "name": "_response",
            "summary": "HttpMessage\u0020object.",
            "url": "classes/Horde-Http-Response-Peclhttp2.html#property__response"
        },                {
            "fqsen": "\\Horde_Http",
            "name": "Horde_Http",
            "summary": "Constants\u0020for\u0020Horde_Http.",
            "url": "classes/Horde-Http.html"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_ANY",
            "name": "AUTH_ANY",
            "summary": "Authentication\u0020schemes",
            "url": "classes/Horde-Http.html#constant_AUTH_ANY"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_BASIC",
            "name": "AUTH_BASIC",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_AUTH_BASIC"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_DIGEST",
            "name": "AUTH_DIGEST",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_AUTH_DIGEST"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_NTLM",
            "name": "AUTH_NTLM",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_AUTH_NTLM"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_GSSNEGOTIATE",
            "name": "AUTH_GSSNEGOTIATE",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_AUTH_GSSNEGOTIATE"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003APROXY_HTTP",
            "name": "PROXY_HTTP",
            "summary": "Proxy\u0020types",
            "url": "classes/Horde-Http.html#constant_PROXY_HTTP"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003APROXY_SOCKS4",
            "name": "PROXY_SOCKS4",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_PROXY_SOCKS4"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003APROXY_SOCKS5",
            "name": "PROXY_SOCKS5",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_PROXY_SOCKS5"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Curl",
            "name": "Curl",
            "summary": "HTTP\u0020client\u0020for\u0020the\u0020curl\u0020backend.",
            "url": "classes/Horde-Http-Client-Curl.html"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Curl\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Client-Curl.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Curl\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "",
            "url": "classes/Horde-Http-Client-Curl.html#method_sendRequest"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Curl\u003A\u003AhttpAuthScheme\u0028\u0029",
            "name": "httpAuthScheme",
            "summary": "Translate\u0020Constants\u003A\u003AAUTH_\u002A\u0020constant\u0020to\u0020CURLAUTH_\u002A",
            "url": "classes/Horde-Http-Client-Curl.html#method_httpAuthScheme"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Curl\u003A\u003AHTTP_AUTH_SCHEMES",
            "name": "HTTP_AUTH_SCHEMES",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nHTTP_AUTH\u0020constants.",
            "url": "classes/Horde-Http-Client-Curl.html#constant_HTTP_AUTH_SCHEMES"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Curl\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/Horde-Http-Client-Curl.html#property_responseFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Curl\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-Client-Curl.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Curl\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/Horde-Http-Client-Curl.html#property_options"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Fopen",
            "name": "Fopen",
            "summary": "Fopen\u0020implementation\u0020of\u0020the\u0020Horde\u0020HTTP\u0020Client",
            "url": "classes/Horde-Http-Client-Fopen.html"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Fopen\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Client-Fopen.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Fopen\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "",
            "url": "classes/Horde-Http-Client-Fopen.html#method_sendRequest"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Fopen\u003A\u003AerrorHandler\u0028\u0029",
            "name": "errorHandler",
            "summary": "Helper\u0020for\u0020catching\u0020fopen\u0020errors,\u0020hopefully\u0020getting\u0020a\u0020HTTP\u0020error\u0020code",
            "url": "classes/Horde-Http-Client-Fopen.html#method_errorHandler"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Fopen\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/Horde-Http-Client-Fopen.html#property_responseFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Fopen\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-Client-Fopen.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Fopen\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/Horde-Http-Client-Fopen.html#property_options"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Fopen\u003A\u003A\u0024errors",
            "name": "errors",
            "summary": "",
            "url": "classes/Horde-Http-Client-Fopen.html#property_errors"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Mock",
            "name": "Mock",
            "summary": "Mock\u0020HTTP\u0020client\u0020object.\u0020Derived\u0020from\u0020the\u0020original\u0020Mock\u0020Http\u0020Request.",
            "url": "classes/Horde-Http-Client-Mock.html"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Mock\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Client-Mock.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Mock\u003A\u003AsetResponse\u0028\u0029",
            "name": "setResponse",
            "summary": "Set\u0020the\u0020HTTP\u0020response\u0028s\u0029\u0020to\u0020be\u0020returned\u0020by\u0020this\u0020adapter.\u0020This\u0020overwrites\nany\u0020responses\u0020set\u0020before.",
            "url": "classes/Horde-Http-Client-Mock.html#method_setResponse"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Mock\u003A\u003AaddResponses\u0028\u0029",
            "name": "addResponses",
            "summary": "Set\u0020the\u0020HTTP\u0020response\u0028s\u0029\u0020to\u0020be\u0020returned\u0020by\u0020this\u0020adapter\u0020as\u0020an\u0020array\u0020Response\u0020objects.",
            "url": "classes/Horde-Http-Client-Mock.html#method_addResponses"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Mock\u003A\u003AaddResponse\u0028\u0029",
            "name": "addResponse",
            "summary": "Adds\u0020a\u0020response\u0020to\u0020the\u0020stack\u0020of\u0020responses.",
            "url": "classes/Horde-Http-Client-Mock.html#method_addResponse"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Mock\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "Actually\u0020send\u0020a\u0020request",
            "url": "classes/Horde-Http-Client-Mock.html#method_sendRequest"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Mock\u003A\u003A\u0024responses",
            "name": "responses",
            "summary": "Mock\u0020responses\u0020to\u0020return.",
            "url": "classes/Horde-Http-Client-Mock.html#property_responses"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Mock\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/Horde-Http-Client-Mock.html#property_responseFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Mock\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-Client-Mock.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Options",
            "name": "Options",
            "summary": "An\u0020Options\u0020container\u0020for\u0020HTTP\u0020clients",
            "url": "classes/Horde-Http-Client-Options.html"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Options\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Client-Options.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Options\u003A\u003AsetOption\u0028\u0029",
            "name": "setOption",
            "summary": "",
            "url": "classes/Horde-Http-Client-Options.html#method_setOption"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Options\u003A\u003AgetOption\u0028\u0029",
            "name": "getOption",
            "summary": "",
            "url": "classes/Horde-Http-Client-Options.html#method_getOption"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\Options\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/Horde-Http-Client-Options.html#property_options"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\ParseHeadersTrait",
            "name": "ParseHeadersTrait",
            "summary": "",
            "url": "classes/Horde-Http-Client-ParseHeadersTrait.html"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\ParseHeadersTrait\u003A\u003AparseHeaders\u0028\u0029",
            "name": "parseHeaders",
            "summary": "Parse\u0020a\u0020string\u0020or\u0020array\u0020of\u0020strings\u0020into\u0020a\u0020set\u0020of\u0020headers",
            "url": "classes/Horde-Http-Client-ParseHeadersTrait.html#method_parseHeaders"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\ParseHeadersTrait\u003A\u003A\u0024parsedCode",
            "name": "parsedCode",
            "summary": "Catch\u0020a\u0020parsed\u0020http\u0020return\u0020code",
            "url": "classes/Horde-Http-Client-ParseHeadersTrait.html#property_parsedCode"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\ParseHeadersTrait\u003A\u003A\u0024parsedHttpVersion",
            "name": "parsedHttpVersion",
            "summary": "",
            "url": "classes/Horde-Http-Client-ParseHeadersTrait.html#property_parsedHttpVersion"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp",
            "name": "PeclHttp",
            "summary": "HTTP\u0020client\u0020for\u0020the\u0020pecl_http\u0020extension",
            "url": "classes/Horde-Http-Client-PeclHttp.html"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003AhttpAuthScheme\u0028\u0029",
            "name": "httpAuthScheme",
            "summary": "Translates\u0020a\u0020Horde_Http\u003A\u003AAUTH_\u002A\u0020constant\u0020to\u0020implementation\u0020specific\nconstants.",
            "url": "classes/Horde-Http-Client-PeclHttp.html#method_httpAuthScheme"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003AproxyType\u0028\u0029",
            "name": "proxyType",
            "summary": "Translates\u0020a\u0020Horde_Http\u003A\u003APROXY_\u002A\u0020constant\u0020to\u0020implementation\u0020specific\nconstants.",
            "url": "classes/Horde-Http-Client-PeclHttp.html#method_proxyType"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003AhttpOptions\u0028\u0029",
            "name": "httpOptions",
            "summary": "Generates\u0020the\u0020HTTP\u0020options\u0020for\u0020the\u0020request.",
            "url": "classes/Horde-Http-Client-PeclHttp.html#method_httpOptions"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Client-PeclHttp.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Client-PeclHttp.html#method_sendRequest"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003A\u0024httpAuthSchemes",
            "name": "httpAuthSchemes",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nimplementation\u0020specific\u0020constants.",
            "url": "classes/Horde-Http-Client-PeclHttp.html#property_httpAuthSchemes"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003A\u0024proxyTypes",
            "name": "proxyTypes",
            "summary": "Map\u0020of\u0020proxy\u0020types\u0020from\u0020Horde_Http\u0020to\u0020implementation\u0020specific\u0020constants.",
            "url": "classes/Horde-Http-Client-PeclHttp.html#property_proxyTypes"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-Client-PeclHttp.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/Horde-Http-Client-PeclHttp.html#property_responseFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Client\\PeclHttp\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/Horde-Http-Client-PeclHttp.html#property_options"
        },                {
            "fqsen": "\\Horde\\Http\\ClientException",
            "name": "ClientException",
            "summary": "Every\u0020HTTP\u0020client\u0020related\u0020exception\u0020MUST\u0020implement\u0020this\u0020interface.",
            "url": "classes/Horde-Http-ClientException.html"
        },                {
            "fqsen": "\\Horde\\Http\\Constants",
            "name": "Constants",
            "summary": "Constants\u0020for\u0020Horde_Http.",
            "url": "classes/Horde-Http-Constants.html"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003AAUTH_ANY",
            "name": "AUTH_ANY",
            "summary": "Authentication\u0020schemes",
            "url": "classes/Horde-Http-Constants.html#constant_AUTH_ANY"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003AAUTH_BASIC",
            "name": "AUTH_BASIC",
            "summary": "",
            "url": "classes/Horde-Http-Constants.html#constant_AUTH_BASIC"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003AAUTH_DIGEST",
            "name": "AUTH_DIGEST",
            "summary": "",
            "url": "classes/Horde-Http-Constants.html#constant_AUTH_DIGEST"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003AAUTH_NTLM",
            "name": "AUTH_NTLM",
            "summary": "",
            "url": "classes/Horde-Http-Constants.html#constant_AUTH_NTLM"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003AAUTH_GSSNEGOTIATE",
            "name": "AUTH_GSSNEGOTIATE",
            "summary": "",
            "url": "classes/Horde-Http-Constants.html#constant_AUTH_GSSNEGOTIATE"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003APROXY_HTTP",
            "name": "PROXY_HTTP",
            "summary": "Proxy\u0020types",
            "url": "classes/Horde-Http-Constants.html#constant_PROXY_HTTP"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003APROXY_SOCKS4",
            "name": "PROXY_SOCKS4",
            "summary": "",
            "url": "classes/Horde-Http-Constants.html#constant_PROXY_SOCKS4"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003APROXY_SOCKS5",
            "name": "PROXY_SOCKS5",
            "summary": "",
            "url": "classes/Horde-Http-Constants.html#constant_PROXY_SOCKS5"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003AURI_SCHEMATA",
            "name": "URI_SCHEMATA",
            "summary": "Uri\u0020SCHEMATA\u0020and\u0020their\u0020ports",
            "url": "classes/Horde-Http-Constants.html#constant_URI_SCHEMATA"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003AREADABLE_STREAM_MODES",
            "name": "READABLE_STREAM_MODES",
            "summary": "Stream\u0020modes\u0020we\u0020can\u0020read\u0020from",
            "url": "classes/Horde-Http-Constants.html#constant_READABLE_STREAM_MODES"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003AWRITABLE_STREAM_MODES",
            "name": "WRITABLE_STREAM_MODES",
            "summary": "Stream\u0020modes\u0020that\u0020can\u0020be\u0020written\u0020to",
            "url": "classes/Horde-Http-Constants.html#constant_WRITABLE_STREAM_MODES"
        },                {
            "fqsen": "\\Horde\\Http\\Constants\u003A\u003AREASON_PHRASES",
            "name": "REASON_PHRASES",
            "summary": "Collection\u0020of\u0020reason\u0020phrases\u0020for\u0020HTTP\u0020status\u0020codes\nas\u0020suggested\u0020by\u0020RFC\u00207231\u0020or\u0020IANA,\u0020keyed\u0020by\u0020status\u0020code",
            "url": "classes/Horde-Http-Constants.html#constant_REASON_PHRASES"
        },                {
            "fqsen": "\\Horde\\Http\\Exception",
            "name": "Exception",
            "summary": "Base\u0020exception\u0020for\u0020the\u0020Horde_Http\u0020library.",
            "url": "classes/Horde-Http-Exception.html"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper",
            "name": "HordeClientWrapper",
            "summary": "Wrap\u0020a\u0020PSR\u002D18\u0020HTTP\u0020client\u0020into\u0020a\u0020frontend\u0020similar\u0020to\u0020the\u0020Horde_Http_Client.",
            "url": "classes/Horde-Http-HordeClientWrapper.html"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HordeClientWrapper\u0020constructor.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Sends\u0020a\u0020GET\u0020request.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#method_get"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Sends\u0020a\u0020POST\u0020request.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#method_post"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Sends\u0020a\u0020PUT\u0020request.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#method_put"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Sends\u0020a\u0020DELETE\u0020request.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#method_delete"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003Ahead\u0028\u0029",
            "name": "head",
            "summary": "Sends\u0020a\u0020HEAD\u0020request.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#method_head"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Builds\u0020and\u0020sends\u0020a\u0020HTTP\u0020request\u0020\u0028H5\u0020style\u0029",
            "url": "classes/Horde-Http-HordeClientWrapper.html#method_request"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "Sends\u0020a\u0020PSR\u002D7\u0020request\u0020and\u0020returns\u0020a\u0020PSR\u002D7\u0020response.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#method_sendRequest"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003A\u0024requestFactory",
            "name": "requestFactory",
            "summary": "",
            "url": "classes/Horde-Http-HordeClientWrapper.html#property_requestFactory"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-HordeClientWrapper.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003A\u0024lastRequest",
            "name": "lastRequest",
            "summary": "The\u0020previous\u0020HTTP\u0020request.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#property_lastRequest"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003A\u0024lastResponse",
            "name": "lastResponse",
            "summary": "The\u0020most\u0020recent\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#property_lastResponse"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003A\u0024httpMethodOverride",
            "name": "httpMethodOverride",
            "summary": "Use\u0020POST\u0020instead\u0020of\u0020PUT\u0020and\u0020DELETE,\u0020sending\u0020X\u002DHTTP\u002DMethod\u002DOverride\u0020with\nthe\u0020intended\u0020method\u0020name\u0020instead.",
            "url": "classes/Horde-Http-HordeClientWrapper.html#property_httpMethodOverride"
        },                {
            "fqsen": "\\Horde\\Http\\HordeClientWrapper\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "A\u0020predefined\u0020uri\u0020for\u0020generated\u0020requests",
            "url": "classes/Horde-Http-HordeClientWrapper.html#property_uri"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation",
            "name": "MessageImplementation",
            "summary": "Reusable\u0020implementation\u0020of\u0020Message.",
            "url": "classes/Horde-Http-MessageImplementation.html"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AgetProtocolVersion\u0028\u0029",
            "name": "getProtocolVersion",
            "summary": "Retrieves\u0020the\u0020HTTP\u0020protocol\u0020version\u0020as\u0020a\u0020string.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_getProtocolVersion"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AwithProtocolVersion\u0028\u0029",
            "name": "withProtocolVersion",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020HTTP\u0020protocol\u0020version.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_withProtocolVersion"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "Retrieves\u0020all\u0020message\u0020header\u0020values.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_getHeaders"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AhasHeader\u0028\u0029",
            "name": "hasHeader",
            "summary": "Checks\u0020if\u0020a\u0020header\u0020exists\u0020by\u0020the\u0020given\u0020case\u002Dinsensitive\u0020name.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_hasHeader"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "Retrieves\u0020a\u0020message\u0020header\u0020value\u0020by\u0020the\u0020given\u0020case\u002Dinsensitive\u0020name.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_getHeader"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AgetHeaderName\u0028\u0029",
            "name": "getHeaderName",
            "summary": "Retrieves\u0020the\u0020header\u0020name\u0020in\u0020the\u0020originally\u0020set\u0020case\u0020by\u0020the\u0020given\u0020case\u002Dinsensitive\u0020name.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_getHeaderName"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AsetHeaderName\u0028\u0029",
            "name": "setHeaderName",
            "summary": "Sets\u0020the\u0020header\u0020name\u0020in\u0020its\u0020given\u0020case,\nso\u0020it\u0020can\u0020be\u0020retrieved\u0020later\u0020by\u0020a\u0020case\u002Dinsensitive\u0020version\u0020of\u0020it.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_setHeaderName"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AunsetHeaderName\u0028\u0029",
            "name": "unsetHeaderName",
            "summary": "Unsets\u0020the\u0020header\u0020name\u0020in\u0020by\u0020the\u0020given\u0020case\u002Dinsensitive\u0020name.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_unsetHeaderName"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AgetHeaderLine\u0028\u0029",
            "name": "getHeaderLine",
            "summary": "Retrieves\u0020a\u0020comma\u002Dseparated\u0020string\u0020of\u0020the\u0020values\u0020for\u0020a\u0020single\u0020header.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_getHeaderLine"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AwithHeader\u0028\u0029",
            "name": "withHeader",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020provided\u0020value\u0020replacing\u0020the\u0020specified\u0020header.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_withHeader"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AstoreHeader\u0028\u0029",
            "name": "storeHeader",
            "summary": "Store\u0020or\u0020replace\u0020a\u0020header",
            "url": "classes/Horde-Http-MessageImplementation.html#method_storeHeader"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AwithAddedHeader\u0028\u0029",
            "name": "withAddedHeader",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020header\u0020appended\u0020with\u0020the\u0020given\u0020value.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_withAddedHeader"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AwithoutHeader\u0028\u0029",
            "name": "withoutHeader",
            "summary": "Return\u0020an\u0020instance\u0020without\u0020the\u0020specified\u0020header.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_withoutHeader"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Gets\u0020the\u0020body\u0020of\u0020the\u0020message.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_getBody"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003AwithBody\u0028\u0029",
            "name": "withBody",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020message\u0020body.",
            "url": "classes/Horde-Http-MessageImplementation.html#method_withBody"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "Original\u0020header\u0020names\u0020and\u0020content",
            "url": "classes/Horde-Http-MessageImplementation.html#property_headers"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003A\u0024headerNames",
            "name": "headerNames",
            "summary": "Lookup\u0020original\u0020names\u0020from\u0020normalized\u0020names",
            "url": "classes/Horde-Http-MessageImplementation.html#property_headerNames"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003A\u0024protocolVersion",
            "name": "protocolVersion",
            "summary": "",
            "url": "classes/Horde-Http-MessageImplementation.html#property_protocolVersion"
        },                {
            "fqsen": "\\Horde\\Http\\MessageImplementation\u003A\u003A\u0024stream",
            "name": "stream",
            "summary": "Stream\u0020content\u0020of\u0020the\u0020message",
            "url": "classes/Horde-Http-MessageImplementation.html#property_stream"
        },                {
            "fqsen": "\\Horde\\Http\\NetworkException",
            "name": "NetworkException",
            "summary": "Thrown\u0020when\u0020the\u0020request\u0020cannot\u0020be\u0020completed\u0020because\u0020of\u0020network\u0020issues.",
            "url": "classes/Horde-Http-NetworkException.html"
        },                {
            "fqsen": "\\Horde\\Http\\NetworkException\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "Returns\u0020the\u0020request.",
            "url": "classes/Horde-Http-NetworkException.html#method_getRequest"
        },                {
            "fqsen": "\\Horde\\Http\\NetworkException\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/Horde-Http-NetworkException.html#property_request"
        },                {
            "fqsen": "\\Horde\\Http\\Request\\Psr7ToPeclHttp",
            "name": "Psr7ToPeclHttp",
            "summary": "Convert\u0020a\u0020PSR\u002D7\u0020request\u0020message\u0020to\u0020a\u0020pecl\/Http\u0020native\u0020message\nSplit\u0020off\u0020from\u0020the\u0020PeclHttp\u0020Client\u0020implementation",
            "url": "classes/Horde-Http-Request-Psr7ToPeclHttp.html"
        },                {
            "fqsen": "\\Horde\\Http\\Request\\Psr7ToPeclHttp\u003A\u003AconvertPsr7RequestToPeclHttp\u0028\u0029",
            "name": "convertPsr7RequestToPeclHttp",
            "summary": "Convert\u0020to\u0020native\u0020format",
            "url": "classes/Horde-Http-Request-Psr7ToPeclHttp.html#method_convertPsr7RequestToPeclHttp"
        },                {
            "fqsen": "\\Horde\\Http\\Request",
            "name": "Request",
            "summary": "A\u0020PSR\u002D7\u0020HTTP\u0020request\u0020message\u0020for\u0020Horde",
            "url": "classes/Horde-Http-Request.html"
        },                {
            "fqsen": "\\Horde\\Http\\Request\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Request\u0020Constructor",
            "url": "classes/Horde-Http-Request.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\RequestException",
            "name": "RequestException",
            "summary": "Exception\u0020for\u0020when\u0020a\u0020request\u0020failed.",
            "url": "classes/Horde-Http-RequestException.html"
        },                {
            "fqsen": "\\Horde\\Http\\RequestException\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "Returns\u0020the\u0020request.",
            "url": "classes/Horde-Http-RequestException.html#method_getRequest"
        },                {
            "fqsen": "\\Horde\\Http\\RequestException\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/Horde-Http-RequestException.html#property_request"
        },                {
            "fqsen": "\\Horde\\Http\\RequestFactory",
            "name": "RequestFactory",
            "summary": "Factory\u0020for\u0020Client\u0020and\u0020Server\u0020representations\u0020of\u0020a\u0020HTTP\u0020request\u0020object",
            "url": "classes/Horde-Http-RequestFactory.html"
        },                {
            "fqsen": "\\Horde\\Http\\RequestFactory\u003A\u003AcreateRequest\u0028\u0029",
            "name": "createRequest",
            "summary": "Create\u0020a\u0020new\u0020request.",
            "url": "classes/Horde-Http-RequestFactory.html#method_createRequest"
        },                {
            "fqsen": "\\Horde\\Http\\RequestFactory\u003A\u003AcreateServerRequest\u0028\u0029",
            "name": "createServerRequest",
            "summary": "Create\u0020a\u0020new\u0020server\u0020request.",
            "url": "classes/Horde-Http-RequestFactory.html#method_createServerRequest"
        },                {
            "fqsen": "\\Horde\\Http\\RequestImplementation",
            "name": "RequestImplementation",
            "summary": "Implementation\u0020of\u0020Request\u0020methods\u0020not\u0020covered\u0020by\u0020MessageImplementation.",
            "url": "classes/Horde-Http-RequestImplementation.html"
        },                {
            "fqsen": "\\Horde\\Http\\RequestImplementation\u003A\u003AgetRequestTarget\u0028\u0029",
            "name": "getRequestTarget",
            "summary": "Retrieves\u0020the\u0020message\u0027s\u0020request\u0020target.",
            "url": "classes/Horde-Http-RequestImplementation.html#method_getRequestTarget"
        },                {
            "fqsen": "\\Horde\\Http\\RequestImplementation\u003A\u003AwithRequestTarget\u0028\u0029",
            "name": "withRequestTarget",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specific\u0020request\u002Dtarget.",
            "url": "classes/Horde-Http-RequestImplementation.html#method_withRequestTarget"
        },                {
            "fqsen": "\\Horde\\Http\\RequestImplementation\u003A\u003AgetMethod\u0028\u0029",
            "name": "getMethod",
            "summary": "Retrieves\u0020the\u0020HTTP\u0020method\u0020of\u0020the\u0020request.",
            "url": "classes/Horde-Http-RequestImplementation.html#method_getMethod"
        },                {
            "fqsen": "\\Horde\\Http\\RequestImplementation\u003A\u003AwithMethod\u0028\u0029",
            "name": "withMethod",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020provided\u0020HTTP\u0020method.",
            "url": "classes/Horde-Http-RequestImplementation.html#method_withMethod"
        },                {
            "fqsen": "\\Horde\\Http\\RequestImplementation\u003A\u003AgetUri\u0028\u0029",
            "name": "getUri",
            "summary": "Retrieves\u0020the\u0020URI\u0020instance.",
            "url": "classes/Horde-Http-RequestImplementation.html#method_getUri"
        },                {
            "fqsen": "\\Horde\\Http\\RequestImplementation\u003A\u003AwithUri\u0028\u0029",
            "name": "withUri",
            "summary": "Returns\u0020an\u0020instance\u0020with\u0020the\u0020provided\u0020URI.",
            "url": "classes/Horde-Http-RequestImplementation.html#method_withUri"
        },                {
            "fqsen": "\\Horde\\Http\\RequestImplementation\u003A\u003A\u0024method",
            "name": "method",
            "summary": "HTTP\u0020Verb",
            "url": "classes/Horde-Http-RequestImplementation.html#property_method"
        },                {
            "fqsen": "\\Horde\\Http\\RequestImplementation\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "URI",
            "url": "classes/Horde-Http-RequestImplementation.html#property_uri"
        },                {
            "fqsen": "\\Horde\\Http\\Response\\PeclHttpToPsr7",
            "name": "PeclHttpToPsr7",
            "summary": "Convert\u0020a\u0020pecl\/Http\u0020native\u0020message\u0020to\u0020a\u0020PSR7\u0020response\nSplit\u0020off\u0020from\u0020the\u0020PeclHttp\u0020Client\u0020implementation",
            "url": "classes/Horde-Http-Response-PeclHttpToPsr7.html"
        },                {
            "fqsen": "\\Horde\\Http\\Response\\PeclHttpToPsr7\u003A\u003AconvertPeclHttpResponseToPsr7\u0028\u0029",
            "name": "convertPeclHttpResponseToPsr7",
            "summary": "Convert\u0020to\u0020PSR\u002D7\u0020format",
            "url": "classes/Horde-Http-Response-PeclHttpToPsr7.html#method_convertPeclHttpResponseToPsr7"
        },                {
            "fqsen": "\\Horde\\Http\\Response",
            "name": "Response",
            "summary": "A\u0020PSR\u002D7\u0020HTTP\u0020request\u0020message\u0020for\u0020Horde",
            "url": "classes/Horde-Http-Response.html"
        },                {
            "fqsen": "\\Horde\\Http\\Response\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Response.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Response\u003A\u003AgetStatusCode\u0028\u0029",
            "name": "getStatusCode",
            "summary": "Gets\u0020the\u0020response\u0020status\u0020code.",
            "url": "classes/Horde-Http-Response.html#method_getStatusCode"
        },                {
            "fqsen": "\\Horde\\Http\\Response\u003A\u003AwithStatus\u0028\u0029",
            "name": "withStatus",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020status\u0020code\u0020and,\u0020optionally,\u0020reason\u0020phrase.",
            "url": "classes/Horde-Http-Response.html#method_withStatus"
        },                {
            "fqsen": "\\Horde\\Http\\Response\u003A\u003AgetReasonPhrase\u0028\u0029",
            "name": "getReasonPhrase",
            "summary": "Gets\u0020the\u0020response\u0020reason\u0020phrase\u0020associated\u0020with\u0020the\u0020status\u0020code.",
            "url": "classes/Horde-Http-Response.html#method_getReasonPhrase"
        },                {
            "fqsen": "\\Horde\\Http\\Response\u003A\u003A\u0024httpReasonPhrase",
            "name": "httpReasonPhrase",
            "summary": "The\u0020HTTP\u0020Reason\u0020Phrase.\u0020May\u0020be\u0020a\u0020standard\u0020from\u0020lookup\u0020table\u0020or\u0020freeform.",
            "url": "classes/Horde-Http-Response.html#property_httpReasonPhrase"
        },                {
            "fqsen": "\\Horde\\Http\\Response\u003A\u003A\u0024httpStatusCode",
            "name": "httpStatusCode",
            "summary": "The\u0020HTTP\u0020Status\u0020Code.",
            "url": "classes/Horde-Http-Response.html#property_httpStatusCode"
        },                {
            "fqsen": "\\Horde\\Http\\ResponseFactory",
            "name": "ResponseFactory",
            "summary": "Factory\u0020for\u0020Response\u0020objects",
            "url": "classes/Horde-Http-ResponseFactory.html"
        },                {
            "fqsen": "\\Horde\\Http\\ResponseFactory\u003A\u003AcreateResponse\u0028\u0029",
            "name": "createResponse",
            "summary": "Create\u0020a\u0020new\u0020response.",
            "url": "classes/Horde-Http-ResponseFactory.html#method_createResponse"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest",
            "name": "ServerRequest",
            "summary": "A\u0020PSR\u002D7\u0020HTTP\u0020server\u0020request\u0020message\u0020for\u0020Horde",
            "url": "classes/Horde-Http-ServerRequest.html"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-ServerRequest.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AgetServerParams\u0028\u0029",
            "name": "getServerParams",
            "summary": "Retrieve\u0020server\u0020parameters.",
            "url": "classes/Horde-Http-ServerRequest.html#method_getServerParams"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AgetCookieParams\u0028\u0029",
            "name": "getCookieParams",
            "summary": "Retrieve\u0020cookies.",
            "url": "classes/Horde-Http-ServerRequest.html#method_getCookieParams"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AwithCookieParams\u0028\u0029",
            "name": "withCookieParams",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020cookies.",
            "url": "classes/Horde-Http-ServerRequest.html#method_withCookieParams"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AgetQueryParams\u0028\u0029",
            "name": "getQueryParams",
            "summary": "Retrieve\u0020query\u0020string\u0020arguments.",
            "url": "classes/Horde-Http-ServerRequest.html#method_getQueryParams"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AwithQueryParams\u0028\u0029",
            "name": "withQueryParams",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020query\u0020string\u0020arguments.",
            "url": "classes/Horde-Http-ServerRequest.html#method_withQueryParams"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AgetUploadedFiles\u0028\u0029",
            "name": "getUploadedFiles",
            "summary": "Retrieve\u0020normalized\u0020file\u0020upload\u0020data.",
            "url": "classes/Horde-Http-ServerRequest.html#method_getUploadedFiles"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AwithUploadedFiles\u0028\u0029",
            "name": "withUploadedFiles",
            "summary": "Create\u0020a\u0020new\u0020instance\u0020with\u0020the\u0020specified\u0020uploaded\u0020files.",
            "url": "classes/Horde-Http-ServerRequest.html#method_withUploadedFiles"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AgetParsedBody\u0028\u0029",
            "name": "getParsedBody",
            "summary": "Retrieve\u0020any\u0020parameters\u0020provided\u0020in\u0020the\u0020request\u0020body.",
            "url": "classes/Horde-Http-ServerRequest.html#method_getParsedBody"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AwithParsedBody\u0028\u0029",
            "name": "withParsedBody",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020body\u0020parameters.",
            "url": "classes/Horde-Http-ServerRequest.html#method_withParsedBody"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AgetAttributes\u0028\u0029",
            "name": "getAttributes",
            "summary": "Retrieve\u0020attributes\u0020derived\u0020from\u0020the\u0020request.",
            "url": "classes/Horde-Http-ServerRequest.html#method_getAttributes"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AgetAttribute\u0028\u0029",
            "name": "getAttribute",
            "summary": "Retrieve\u0020a\u0020single\u0020derived\u0020request\u0020attribute.",
            "url": "classes/Horde-Http-ServerRequest.html#method_getAttribute"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AwithAttribute\u0028\u0029",
            "name": "withAttribute",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020derived\u0020request\u0020attribute.",
            "url": "classes/Horde-Http-ServerRequest.html#method_withAttribute"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003AwithoutAttribute\u0028\u0029",
            "name": "withoutAttribute",
            "summary": "Return\u0020an\u0020instance\u0020that\u0020removes\u0020the\u0020specified\u0020derived\u0020request\u0020attribute.",
            "url": "classes/Horde-Http-ServerRequest.html#method_withoutAttribute"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003A\u0024cookieParams",
            "name": "cookieParams",
            "summary": "",
            "url": "classes/Horde-Http-ServerRequest.html#property_cookieParams"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003A\u0024attributes",
            "name": "attributes",
            "summary": "",
            "url": "classes/Horde-Http-ServerRequest.html#property_attributes"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003A\u0024queryParams",
            "name": "queryParams",
            "summary": "",
            "url": "classes/Horde-Http-ServerRequest.html#property_queryParams"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003A\u0024serverParams",
            "name": "serverParams",
            "summary": "",
            "url": "classes/Horde-Http-ServerRequest.html#property_serverParams"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003A\u0024uploadedFiles",
            "name": "uploadedFiles",
            "summary": "",
            "url": "classes/Horde-Http-ServerRequest.html#property_uploadedFiles"
        },                {
            "fqsen": "\\Horde\\Http\\ServerRequest\u003A\u003A\u0024parsedBody",
            "name": "parsedBody",
            "summary": "",
            "url": "classes/Horde-Http-ServerRequest.html#property_parsedBody"
        },                {
            "fqsen": "\\Horde\\Http\\Stream",
            "name": "Stream",
            "summary": "A\u0020PSR\u002D7\u0020compliant\u0020Stream\u0020implementation.",
            "url": "classes/Horde-Http-Stream.html"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Stream\u0020constructor",
            "url": "classes/Horde-Http-Stream.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Reads\u0020all\u0020data\u0020from\u0020the\u0020stream\u0020into\u0020a\u0020string,\u0020from\u0020the\u0020beginning\u0020to\u0020end.",
            "url": "classes/Horde-Http-Stream.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Closes\u0020the\u0020stream\u0020and\u0020any\u0020underlying\u0020resources.",
            "url": "classes/Horde-Http-Stream.html#method_close"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003Adetach\u0028\u0029",
            "name": "detach",
            "summary": "Separates\u0020any\u0020underlying\u0020resources\u0020from\u0020the\u0020stream.",
            "url": "classes/Horde-Http-Stream.html#method_detach"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003AgetSize\u0028\u0029",
            "name": "getSize",
            "summary": "Get\u0020the\u0020size\u0020of\u0020the\u0020stream\u0020if\u0020known.",
            "url": "classes/Horde-Http-Stream.html#method_getSize"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003Atell\u0028\u0029",
            "name": "tell",
            "summary": "Returns\u0020the\u0020current\u0020position\u0020of\u0020the\u0020file\u0020read\/write\u0020pointer",
            "url": "classes/Horde-Http-Stream.html#method_tell"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003Aeof\u0028\u0029",
            "name": "eof",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020stream\u0020is\u0020at\u0020the\u0020end\u0020of\u0020the\u0020stream.",
            "url": "classes/Horde-Http-Stream.html#method_eof"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003AisSeekable\u0028\u0029",
            "name": "isSeekable",
            "summary": "Returns\u0020whether\u0020or\u0020not\u0020the\u0020stream\u0020is\u0020seekable.",
            "url": "classes/Horde-Http-Stream.html#method_isSeekable"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003Aseek\u0028\u0029",
            "name": "seek",
            "summary": "Seek\u0020to\u0020a\u0020position\u0020in\u0020the\u0020stream.",
            "url": "classes/Horde-Http-Stream.html#method_seek"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "Seek\u0020to\u0020the\u0020beginning\u0020of\u0020the\u0020stream.",
            "url": "classes/Horde-Http-Stream.html#method_rewind"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003AisWritable\u0028\u0029",
            "name": "isWritable",
            "summary": "Returns\u0020whether\u0020or\u0020not\u0020the\u0020stream\u0020is\u0020writable.",
            "url": "classes/Horde-Http-Stream.html#method_isWritable"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020data\u0020to\u0020the\u0020stream.",
            "url": "classes/Horde-Http-Stream.html#method_write"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003AisReadable\u0028\u0029",
            "name": "isReadable",
            "summary": "Returns\u0020whether\u0020or\u0020not\u0020the\u0020stream\u0020is\u0020readable.",
            "url": "classes/Horde-Http-Stream.html#method_isReadable"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020data\u0020from\u0020the\u0020stream.",
            "url": "classes/Horde-Http-Stream.html#method_read"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003AgetContents\u0028\u0029",
            "name": "getContents",
            "summary": "Returns\u0020the\u0020remaining\u0020contents\u0020in\u0020a\u0020string",
            "url": "classes/Horde-Http-Stream.html#method_getContents"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003AgetMetadata\u0028\u0029",
            "name": "getMetadata",
            "summary": "Get\u0020stream\u0020metadata\u0020as\u0020an\u0020associative\u0020array\u0020or\u0020retrieve\u0020a\u0020specific\u0020key.",
            "url": "classes/Horde-Http-Stream.html#method_getMetadata"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003A\u0024stream",
            "name": "stream",
            "summary": "Cannot\u0020type\u0020for\u0020resource\u0020in\u0020php\u00207.x\u0020so\u0020keep\u0020this\u0020annotation",
            "url": "classes/Horde-Http-Stream.html#property_stream"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003A\u0024seekable",
            "name": "seekable",
            "summary": "",
            "url": "classes/Horde-Http-Stream.html#property_seekable"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003A\u0024readable",
            "name": "readable",
            "summary": "",
            "url": "classes/Horde-Http-Stream.html#property_readable"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003A\u0024writable",
            "name": "writable",
            "summary": "",
            "url": "classes/Horde-Http-Stream.html#property_writable"
        },                {
            "fqsen": "\\Horde\\Http\\Stream\u003A\u003A\u0024size",
            "name": "size",
            "summary": "",
            "url": "classes/Horde-Http-Stream.html#property_size"
        },                {
            "fqsen": "\\Horde\\Http\\StreamFactory",
            "name": "StreamFactory",
            "summary": "PSR\u002D17\u0020StreamFactory\u0020implementation\u0020to\u0020create\u0020PSR\u002D7\u0020Stream\u0020objects",
            "url": "classes/Horde-Http-StreamFactory.html"
        },                {
            "fqsen": "\\Horde\\Http\\StreamFactory\u003A\u003AcreateStream\u0028\u0029",
            "name": "createStream",
            "summary": "Create\u0020a\u0020new\u0020stream\u0020from\u0020a\u0020string.",
            "url": "classes/Horde-Http-StreamFactory.html#method_createStream"
        },                {
            "fqsen": "\\Horde\\Http\\StreamFactory\u003A\u003AcreateStreamFromFile\u0028\u0029",
            "name": "createStreamFromFile",
            "summary": "Create\u0020a\u0020stream\u0020from\u0020an\u0020existing\u0020file.",
            "url": "classes/Horde-Http-StreamFactory.html#method_createStreamFromFile"
        },                {
            "fqsen": "\\Horde\\Http\\StreamFactory\u003A\u003AcreateStreamFromResource\u0028\u0029",
            "name": "createStreamFromResource",
            "summary": "Create\u0020a\u0020new\u0020stream\u0020from\u0020an\u0020existing\u0020resource.",
            "url": "classes/Horde-Http-StreamFactory.html#method_createStreamFromResource"
        },                {
            "fqsen": "\\Horde\\Http\\StreamUtils",
            "name": "StreamUtils",
            "summary": "Static\u0020utilities\u0020for\u0020PSR\u002D7\u0020Stream\u0020objects",
            "url": "classes/Horde-Http-StreamUtils.html"
        },                {
            "fqsen": "\\Horde\\Http\\StreamUtils\u003A\u003AcopyStreamToResource\u0028\u0029",
            "name": "copyStreamToResource",
            "summary": "",
            "url": "classes/Horde-Http-StreamUtils.html#method_copyStreamToResource"
        },                {
            "fqsen": "\\Horde\\Http\\StreamUtils\u003A\u003AMB16",
            "name": "MB16",
            "summary": "",
            "url": "classes/Horde-Http-StreamUtils.html#constant_MB16"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile",
            "name": "UploadedFile",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Retrieve\u0020a\u0020stream\u0020representing\u0020the\u0020uploaded\u0020file.",
            "url": "classes/Horde-Http-UploadedFile.html#method_getStream"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003AmoveTo\u0028\u0029",
            "name": "moveTo",
            "summary": "Move\u0020the\u0020uploaded\u0020file\u0020to\u0020a\u0020new\u0020location.",
            "url": "classes/Horde-Http-UploadedFile.html#method_moveTo"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003AgetSize\u0028\u0029",
            "name": "getSize",
            "summary": "Retrieve\u0020the\u0020file\u0020size.",
            "url": "classes/Horde-Http-UploadedFile.html#method_getSize"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "Retrieve\u0020the\u0020error\u0020associated\u0020with\u0020the\u0020uploaded\u0020file.",
            "url": "classes/Horde-Http-UploadedFile.html#method_getError"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003AgetClientFilename\u0028\u0029",
            "name": "getClientFilename",
            "summary": "Retrieve\u0020the\u0020filename\u0020sent\u0020by\u0020the\u0020client.",
            "url": "classes/Horde-Http-UploadedFile.html#method_getClientFilename"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003AgetClientMediaType\u0028\u0029",
            "name": "getClientMediaType",
            "summary": "Retrieve\u0020the\u0020media\u0020type\u0020sent\u0020by\u0020the\u0020client.",
            "url": "classes/Horde-Http-UploadedFile.html#method_getClientMediaType"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024originalName",
            "name": "originalName",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#property_originalName"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024mimeType",
            "name": "mimeType",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#property_mimeType"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#property_error"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024size",
            "name": "size",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#property_size"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024clientFileName",
            "name": "clientFileName",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#property_clientFileName"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024clientMediaType",
            "name": "clientMediaType",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#property_clientMediaType"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024stream",
            "name": "stream",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#property_stream"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024hasCalledMoveTo",
            "name": "hasCalledMoveTo",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#property_hasCalledMoveTo"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFile.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFile\u003A\u003A\u0024copyChunkSize",
            "name": "copyChunkSize",
            "summary": "\u0024copyChunkSize",
            "url": "classes/Horde-Http-UploadedFile.html#property_copyChunkSize"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFileFactory",
            "name": "UploadedFileFactory",
            "summary": "",
            "url": "classes/Horde-Http-UploadedFileFactory.html"
        },                {
            "fqsen": "\\Horde\\Http\\UploadedFileFactory\u003A\u003AcreateUploadedFile\u0028\u0029",
            "name": "createUploadedFile",
            "summary": "Create\u0020a\u0020new\u0020uploaded\u0020file.",
            "url": "classes/Horde-Http-UploadedFileFactory.html#method_createUploadedFile"
        },                {
            "fqsen": "\\Horde\\Http\\Uri",
            "name": "Uri",
            "summary": "Uri\u0020implementation\u0020from\u0020PSR\u002D7.",
            "url": "classes/Horde-Http-Uri.html"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct\u0020an\u0020URI\u0020from\u0020a\u0020string",
            "url": "classes/Horde-Http-Uri.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AgetScheme\u0028\u0029",
            "name": "getScheme",
            "summary": "Retrieve\u0020the\u0020scheme\u0020component\u0020of\u0020the\u0020URI.",
            "url": "classes/Horde-Http-Uri.html#method_getScheme"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AgetAuthority\u0028\u0029",
            "name": "getAuthority",
            "summary": "Retrieve\u0020the\u0020authority\u0020component\u0020of\u0020the\u0020URI.",
            "url": "classes/Horde-Http-Uri.html#method_getAuthority"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AgetUserInfo\u0028\u0029",
            "name": "getUserInfo",
            "summary": "Retrieve\u0020the\u0020user\u0020information\u0020component\u0020of\u0020the\u0020URI.",
            "url": "classes/Horde-Http-Uri.html#method_getUserInfo"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AgetHost\u0028\u0029",
            "name": "getHost",
            "summary": "Retrieve\u0020the\u0020host\u0020component\u0020of\u0020the\u0020URI.",
            "url": "classes/Horde-Http-Uri.html#method_getHost"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AgetPort\u0028\u0029",
            "name": "getPort",
            "summary": "Retrieve\u0020the\u0020port\u0020component\u0020of\u0020the\u0020URI.",
            "url": "classes/Horde-Http-Uri.html#method_getPort"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "Retrieve\u0020the\u0020path\u0020component\u0020of\u0020the\u0020URI.",
            "url": "classes/Horde-Http-Uri.html#method_getPath"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AgetQuery\u0028\u0029",
            "name": "getQuery",
            "summary": "Retrieve\u0020the\u0020query\u0020string\u0020of\u0020the\u0020URI.",
            "url": "classes/Horde-Http-Uri.html#method_getQuery"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AgetFragment\u0028\u0029",
            "name": "getFragment",
            "summary": "Retrieve\u0020the\u0020fragment\u0020component\u0020of\u0020the\u0020URI.",
            "url": "classes/Horde-Http-Uri.html#method_getFragment"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AwithScheme\u0028\u0029",
            "name": "withScheme",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020scheme.",
            "url": "classes/Horde-Http-Uri.html#method_withScheme"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AwithUserInfo\u0028\u0029",
            "name": "withUserInfo",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020user\u0020information.",
            "url": "classes/Horde-Http-Uri.html#method_withUserInfo"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AwithHost\u0028\u0029",
            "name": "withHost",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020host.",
            "url": "classes/Horde-Http-Uri.html#method_withHost"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AwithPort\u0028\u0029",
            "name": "withPort",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020port.",
            "url": "classes/Horde-Http-Uri.html#method_withPort"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AwithPath\u0028\u0029",
            "name": "withPath",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020path.",
            "url": "classes/Horde-Http-Uri.html#method_withPath"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AwithQuery\u0028\u0029",
            "name": "withQuery",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020query\u0020string.",
            "url": "classes/Horde-Http-Uri.html#method_withQuery"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AwithFragment\u0028\u0029",
            "name": "withFragment",
            "summary": "Return\u0020an\u0020instance\u0020with\u0020the\u0020specified\u0020URI\u0020fragment.",
            "url": "classes/Horde-Http-Uri.html#method_withFragment"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Return\u0020the\u0020string\u0020representation\u0020as\u0020a\u0020URI\u0020reference.",
            "url": "classes/Horde-Http-Uri.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003AnullStandardPorts\u0028\u0029",
            "name": "nullStandardPorts",
            "summary": "Helper\u003A\u0020If\u0020protocol\u0020and\u0020port\u0020match,\u0020make\u0020port\u0020empty",
            "url": "classes/Horde-Http-Uri.html#method_nullStandardPorts"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003A\u0024scheme",
            "name": "scheme",
            "summary": "",
            "url": "classes/Horde-Http-Uri.html#property_scheme"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003A\u0024userInfo",
            "name": "userInfo",
            "summary": "",
            "url": "classes/Horde-Http-Uri.html#property_userInfo"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003A\u0024host",
            "name": "host",
            "summary": "",
            "url": "classes/Horde-Http-Uri.html#property_host"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003A\u0024port",
            "name": "port",
            "summary": "",
            "url": "classes/Horde-Http-Uri.html#property_port"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Horde-Http-Uri.html#property_path"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/Horde-Http-Uri.html#property_query"
        },                {
            "fqsen": "\\Horde\\Http\\Uri\u003A\u003A\u0024fragment",
            "name": "fragment",
            "summary": "",
            "url": "classes/Horde-Http-Uri.html#property_fragment"
        },                {
            "fqsen": "\\Horde\\Http\\UriFactory",
            "name": "UriFactory",
            "summary": "Uri\u0020Factory",
            "url": "classes/Horde-Http-UriFactory.html"
        },                {
            "fqsen": "\\Horde\\Http\\UriFactory\u003A\u003AcreateUri\u0028\u0029",
            "name": "createUri",
            "summary": "",
            "url": "classes/Horde-Http-UriFactory.html#method_createUri"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Http\\Client",
            "name": "Client",
            "summary": "",
            "url": "namespaces/horde-http-client.html"
        },                {
            "fqsen": "\\Horde\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/horde-http.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        },                {
            "fqsen": "\\Horde\\Http\\Request",
            "name": "Request",
            "summary": "",
            "url": "namespaces/horde-http-request.html"
        },                {
            "fqsen": "\\Horde\\Http\\Response",
            "name": "Response",
            "summary": "",
            "url": "namespaces/horde-http-response.html"
        }            ]
);
