Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Exception_LastError",
            "name": "Horde_Exception_LastError",
            "summary": "Horde\u0020exception\u0020class\u0020that\u0020accepts\u0020output\u0020of\u0020error_get_last\u0028\u0029\u0020as\u0020\u0024code\u0020and\nmask\u0020itself\u0020as\u0020that\u0020error.",
            "url": "classes/Horde-Exception-LastError.html"
        },                {
            "fqsen": "\\Horde_Exception_LastError\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Exception\u0020constructor",
            "url": "classes/Horde-Exception-LastError.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception_NotFound",
            "name": "Horde_Exception_NotFound",
            "summary": "Exception\u0020thrown\u0020if\u0020an\u0020object\u0020wasn\u0027t\u0020found.",
            "url": "classes/Horde-Exception-NotFound.html"
        },                {
            "fqsen": "\\Horde_Exception_NotFound\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Exception-NotFound.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception_Pear",
            "name": "Horde_Exception_Pear",
            "summary": "Horde\u0020exception\u0020class\u0020that\u0020converts\u0020PEAR\u0020errors\u0020to\u0020exceptions.",
            "url": "classes/Horde-Exception-Pear.html"
        },                {
            "fqsen": "\\Horde_Exception_Pear\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Exception\u0020constructor.",
            "url": "classes/Horde-Exception-Pear.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception_Pear\u003A\u003A_getPearTrace\u0028\u0029",
            "name": "_getPearTrace",
            "summary": "Return\u0020a\u0020trace\u0020for\u0020the\u0020PEAR\u0020error.",
            "url": "classes/Horde-Exception-Pear.html#method__getPearTrace"
        },                {
            "fqsen": "\\Horde_Exception_Pear\u003A\u003AcatchError\u0028\u0029",
            "name": "catchError",
            "summary": "Exception\u0020handling.",
            "url": "classes/Horde-Exception-Pear.html#method_catchError"
        },                {
            "fqsen": "\\Horde_Exception_Pear\u003A\u003A\u0024_class",
            "name": "_class",
            "summary": "The\u0020class\u0020name\u0020for\u0020generated\u0020exceptions.",
            "url": "classes/Horde-Exception-Pear.html#property__class"
        },                {
            "fqsen": "\\Horde_Exception_PermissionDenied",
            "name": "Horde_Exception_PermissionDenied",
            "summary": "Exception\u0020thrown\u0020if\u0020any\u0020access\u0020without\u0020sufficient\u0020permissions\u0020occured.",
            "url": "classes/Horde-Exception-PermissionDenied.html"
        },                {
            "fqsen": "\\Horde_Exception_PermissionDenied\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Exception-PermissionDenied.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception_Translation",
            "name": "Horde_Exception_Translation",
            "summary": "Horde_Exception_Translation\u0020is\u0020the\u0020translation\u0020wrapper\u0020class\u0020for\u0020Horde_Exception.",
            "url": "classes/Horde-Exception-Translation.html"
        },                {
            "fqsen": "\\Horde_Exception_Translation\u003A\u003A\u0024_domain",
            "name": "_domain",
            "summary": "The\u0020translation\u0020domain",
            "url": "classes/Horde-Exception-Translation.html#property__domain"
        },                {
            "fqsen": "\\Horde_Exception_Translation\u003A\u003A\u0024_pearDirectory",
            "name": "_pearDirectory",
            "summary": "The\u0020absolute\u0020PEAR\u0020path\u0020to\u0020the\u0020translations\u0020for\u0020the\u0020default\u0020gettext\u0020handler.",
            "url": "classes/Horde-Exception-Translation.html#property__pearDirectory"
        },                {
            "fqsen": "\\Horde_Exception_Wrapped",
            "name": "Horde_Exception_Wrapped",
            "summary": "Horde\u0020exception\u0020class\u0020that\u0020can\u0020wrap\u0020and\u0020set\u0020its\u0020details\u0020from\u0020PEAR_Error,\nException,\u0020and\u0020other\u0020objects\u0020with\u0020similar\u0020interfaces.",
            "url": "classes/Horde-Exception-Wrapped.html"
        },                {
            "fqsen": "\\Horde_Exception_Wrapped\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Exception\u0020constructor.",
            "url": "classes/Horde-Exception-Wrapped.html#method___construct"
        },                {
            "fqsen": "\\Horde_Exception",
            "name": "Horde_Exception",
            "summary": "Horde\u0020base\u0020exception\u0020class.",
            "url": "classes/Horde-Exception.html"
        },                {
            "fqsen": "\\Horde_Exception\u003A\u003AgetLogLevel\u0028\u0029",
            "name": "getLogLevel",
            "summary": "Get\u0020the\u0020log\u0020level.",
            "url": "classes/Horde-Exception.html#method_getLogLevel"
        },                {
            "fqsen": "\\Horde_Exception\u003A\u003AsetLogLevel\u0028\u0029",
            "name": "setLogLevel",
            "summary": "Sets\u0020the\u0020log\u0020level.",
            "url": "classes/Horde-Exception.html#method_setLogLevel"
        },                {
            "fqsen": "\\Horde_Exception\u003A\u003A\u0024details",
            "name": "details",
            "summary": "Error\u0020details\u0020that\u0020should\u0020not\u0020be\u0020part\u0020of\u0020the\u0020main\u0020exception\u0020message,\ne.g.\u0020any\u0020additional\u0020debugging\u0020information.",
            "url": "classes/Horde-Exception.html#property_details"
        },                {
            "fqsen": "\\Horde_Exception\u003A\u003A\u0024logged",
            "name": "logged",
            "summary": "Has\u0020this\u0020exception\u0020been\u0020logged\u003F",
            "url": "classes/Horde-Exception.html#property_logged"
        },                {
            "fqsen": "\\Horde_Exception\u003A\u003A\u0024_logLevel",
            "name": "_logLevel",
            "summary": "The\u0020log\u0020level\u0020to\u0020use.\u0020A\u0020Horde_Log\u0020constant.",
            "url": "classes/Horde-Exception.html#property__logLevel"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
