Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Text_Textile",
            "name": "Horde_Text_Textile",
            "summary": "References\u003A\n\u0020\u0020http\u003A\/\/www.textism.com\/tools\/textile\/\n\u0020\u0020http\u003A\/\/en.wikipedia.org\/wiki\/Textile_\u0028markup_language\u0029\n\u0020\u0020http\u003A\/\/hobix.com\/textile\/\n\u0020\u0020http\u003A\/\/whytheluckystiff.net\/ruby\/redcloth\/\n\u0020\u0020http\u003A\/\/redcloth.rubyforge.org\/rdoc\/\n\u0020\u0020http\u003A\/\/code.whytheluckystiff.net\/redcloth\/browser\/trunk\/test\/textism.yml",
            "url": "classes/Horde-Text-Textile.html"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003Atransform\u0028\u0029",
            "name": "transform",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#method_transform"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003AREGEX_A_HLGN",
            "name": "REGEX_A_HLGN",
            "summary": "A_HLGN",
            "url": "classes/Horde-Text-Textile.html#constant_REGEX_A_HLGN"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003AREGEX_A_VLGN",
            "name": "REGEX_A_VLGN",
            "summary": "A_VLGN",
            "url": "classes/Horde-Text-Textile.html#constant_REGEX_A_VLGN"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003AREGEX_A",
            "name": "REGEX_A",
            "summary": "\u0027\u0028\u003F\u003A\u0027\u0020.\u0020A_HLGN\u0020.\u0020\u0027\u007C\u0027\u0020.\u0020A_VLGN\u0020.\u0020\u0027\u0029\u002A\u0027",
            "url": "classes/Horde-Text-Textile.html#constant_REGEX_A"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003AREGEX_S",
            "name": "REGEX_S",
            "summary": "\u0027\u0028\u003F\u003A\u0027\u0020.\u0020S_CSPN\u0020.\u0020\u0027\u007C\u0027\u0020.\u0020S_RSPN\u0020.\u0020\u0027\u0029\u002A\u0027",
            "url": "classes/Horde-Text-Textile.html#constant_REGEX_S"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003AREGEX_C",
            "name": "REGEX_C",
            "summary": "\u0027\u0028\u003F\u003A\u0027\u0020.\u0020C_CLAS\u0020.\u0020\u0027\u007C\u0027\u0020.\u0020C_STYL\u0020.\u0020\u0027\u007C\u0027\u0020.\u0020C_LNGE\u0020.\u0020\u0027\u007C\u0027\u0020.\u0020A_HLGN\u0020.\u0020\u0027\u0029\u002A\u0027",
            "url": "classes/Horde-Text-Textile.html#constant_REGEX_C"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003AREGEX_PUNCT",
            "name": "REGEX_PUNCT",
            "summary": "PUNCT",
            "url": "classes/Horde-Text-Textile.html#constant_REGEX_PUNCT"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003AREGEX_URL",
            "name": "REGEX_URL",
            "summary": "LINK_RE",
            "url": "classes/Horde-Text-Textile.html#constant_REGEX_URL"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003AREGEX_BLOCK_TAGS",
            "name": "REGEX_BLOCK_TAGS",
            "summary": "Block\u0020tags",
            "url": "classes/Horde-Text-Textile.html#constant_REGEX_BLOCK_TAGS"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_QUOTE_SINGLE_OPEN",
            "name": "GLYPH_QUOTE_SINGLE_OPEN",
            "summary": "Glyphs.\u0020Can\u0020be\u0020overridden\u0020if\u0020you\u0020want\u0020to\u0020substitute\u0020different\nentities.",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_QUOTE_SINGLE_OPEN"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_QUOTE_SINGLE_CLOSE",
            "name": "GLYPH_QUOTE_SINGLE_CLOSE",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_QUOTE_SINGLE_CLOSE"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_QUOTE_DOUBLE_OPEN",
            "name": "GLYPH_QUOTE_DOUBLE_OPEN",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_QUOTE_DOUBLE_OPEN"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_QUOTE_DOUBLE_CLOSE",
            "name": "GLYPH_QUOTE_DOUBLE_CLOSE",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_QUOTE_DOUBLE_CLOSE"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_APOSTROPHE",
            "name": "GLYPH_APOSTROPHE",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_APOSTROPHE"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_PRIME",
            "name": "GLYPH_PRIME",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_PRIME"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_PRIME_DOUBLE",
            "name": "GLYPH_PRIME_DOUBLE",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_PRIME_DOUBLE"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_ELLIPSIS",
            "name": "GLYPH_ELLIPSIS",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_ELLIPSIS"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_EMDASH",
            "name": "GLYPH_EMDASH",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_EMDASH"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_ENDASH",
            "name": "GLYPH_ENDASH",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_ENDASH"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_DIMENSION",
            "name": "GLYPH_DIMENSION",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_DIMENSION"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_TRADEMARK",
            "name": "GLYPH_TRADEMARK",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_TRADEMARK"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_REGISTERED",
            "name": "GLYPH_REGISTERED",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_REGISTERED"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_COPYRIGHT",
            "name": "GLYPH_COPYRIGHT",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_COPYRIGHT"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024GLYPH_RETURN_ARROW",
            "name": "GLYPH_RETURN_ARROW",
            "summary": "",
            "url": "classes/Horde-Text-Textile.html#property_GLYPH_RETURN_ARROW"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024images",
            "name": "images",
            "summary": "Show\u0020images\u003F\u0020On\u0020by\u0020default.",
            "url": "classes/Horde-Text-Textile.html#property_images"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024rel",
            "name": "rel",
            "summary": "Rel\u0020attribute\u0020for\u0020links\u0020\u0028ex\u003A\u0020nofollow\u0029.",
            "url": "classes/Horde-Text-Textile.html#property_rel"
        },                {
            "fqsen": "\\Horde_Text_Textile\u003A\u003A\u0024_shelf",
            "name": "_shelf",
            "summary": "Shelf\u0020of\u0020values\u0020being\u0020processed.",
            "url": "classes/Horde-Text-Textile.html#property__shelf"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
