Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Mongo_Client",
            "name": "Horde_Mongo_Client",
            "summary": "Extend\u0020the\u0020base\u0020PECL\u0020MongoClient\u0020class\u0020by\u0020allowing\u0020it\u0020to\u0020be\u0020serialized.",
            "url": "classes/Horde-Mongo-Client.html"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Mongo-Client.html#method___construct"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003AdropDB\u0028\u0029",
            "name": "dropDB",
            "summary": "",
            "url": "classes/Horde-Mongo-Client.html#method_dropDB"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003AselectCollection\u0028\u0029",
            "name": "selectCollection",
            "summary": "",
            "url": "classes/Horde-Mongo-Client.html#method_selectCollection"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003AselectDB\u0028\u0029",
            "name": "selectDB",
            "summary": "",
            "url": "classes/Horde-Mongo-Client.html#method_selectDB"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003AcheckIndices\u0028\u0029",
            "name": "checkIndices",
            "summary": "Checks\u0020that\u0020indices\u0020are\u0020up\u002Dto\u002Ddate.",
            "url": "classes/Horde-Mongo-Client.html#method_checkIndices"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003AcreateIndices\u0028\u0029",
            "name": "createIndices",
            "summary": "Create\u0020indices\u0020for\u0020the\u0020collection.",
            "url": "classes/Horde-Mongo-Client.html#method_createIndices"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/Horde-Mongo-Client.html#method_serialize"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "",
            "url": "classes/Horde-Mongo-Client.html#method_unserialize"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003A\u0024dbname",
            "name": "dbname",
            "summary": "Database\u0020name\u0020\u0028Horde_Mongo_Client\u0020uses\u0020this\u0020single\u0020database\u0020by\u0020default\nto\u0020ease\u0020configuration\u0029.",
            "url": "classes/Horde-Mongo-Client.html#property_dbname"
        },                {
            "fqsen": "\\Horde_Mongo_Client\u003A\u003A\u0024_cArgs",
            "name": "_cArgs",
            "summary": "Constructor\u0020args.",
            "url": "classes/Horde-Mongo-Client.html#property__cArgs"
        },                {
            "fqsen": "\\Horde_Mongo_Collection_Index",
            "name": "Horde_Mongo_Collection_Index",
            "summary": "Implement\u0020index\u0020creation\u0020on\u0020a\u0020MongoDB\u0020collection.",
            "url": "classes/Horde-Mongo-Collection-Index.html"
        },                {
            "fqsen": "\\Horde_Mongo_Collection_Index\u003A\u003AcheckMongoIndices\u0028\u0029",
            "name": "checkMongoIndices",
            "summary": "Are\u0020the\u0020indices\u0020up\u002Dto\u002Ddate\u003F",
            "url": "classes/Horde-Mongo-Collection-Index.html#method_checkMongoIndices"
        },                {
            "fqsen": "\\Horde_Mongo_Collection_Index\u003A\u003AcreateMongoIndices\u0028\u0029",
            "name": "createMongoIndices",
            "summary": "Ensures\u0020that\u0020collection\u0020indices\u0020are\u0020created.",
            "url": "classes/Horde-Mongo-Collection-Index.html#method_createMongoIndices"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
