Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Idna_Exception",
            "name": "Horde_Idna_Exception",
            "summary": "Exception\u0020class\u0020for\u0020the\u0020Horde_Idna\u0020package.",
            "url": "classes/Horde-Idna-Exception.html"
        },                {
            "fqsen": "\\Horde_Idna_Punycode",
            "name": "Horde_Idna_Punycode",
            "summary": "Punycode\u0020implementation\u0020as\u0020described\u0020in\u0020RFC\u00203492.",
            "url": "classes/Horde-Idna-Punycode.html"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "Encode\u0020a\u0020domain\u0020to\u0020its\u0020Punycode\u0020version.",
            "url": "classes/Horde-Idna-Punycode.html#method_encode"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003A_encodePart\u0028\u0029",
            "name": "_encodePart",
            "summary": "Encode\u0020a\u0020part\u0020of\u0020a\u0020domain\u0020name,\u0020such\u0020as\u0020tld,\u0020to\u0020its\u0020Punycode\u0020version.",
            "url": "classes/Horde-Idna-Punycode.html#method__encodePart"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "Decode\u0020a\u0020Punycode\u0020domain\u0020name\u0020to\u0020its\u0020Unicode\u0020counterpart.",
            "url": "classes/Horde-Idna-Punycode.html#method_decode"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003A_decodePart\u0028\u0029",
            "name": "_decodePart",
            "summary": "Decode\u0020a\u0020part\u0020of\u0020domain\u0020name,\u0020such\u0020as\u0020tld.",
            "url": "classes/Horde-Idna-Punycode.html#method__decodePart"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003A_calculateThreshold\u0028\u0029",
            "name": "_calculateThreshold",
            "summary": "Calculate\u0020the\u0020bias\u0020threshold\u0020to\u0020fall\u0020between\u0020TMIN\u0020and\u0020TMAX.",
            "url": "classes/Horde-Idna-Punycode.html#method__calculateThreshold"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003A_adapt\u0028\u0029",
            "name": "_adapt",
            "summary": "Bias\u0020adaptation.",
            "url": "classes/Horde-Idna-Punycode.html#method__adapt"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003A_codePoints\u0028\u0029",
            "name": "_codePoints",
            "summary": "List\u0020code\u0020points\u0020for\u0020a\u0020given\u0020input.",
            "url": "classes/Horde-Idna-Punycode.html#method__codePoints"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003A_charToCodePoint\u0028\u0029",
            "name": "_charToCodePoint",
            "summary": "Convert\u0020a\u0020single\u0020or\u0020multi\u002Dbyte\u0020character\u0020to\u0020its\u0020code\u0020point.",
            "url": "classes/Horde-Idna-Punycode.html#method__charToCodePoint"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003A_codePointToChar\u0028\u0029",
            "name": "_codePointToChar",
            "summary": "Convert\u0020a\u0020code\u0020point\u0020to\u0020its\u0020single\u0020or\u0020multi\u002Dbyte\u0020character",
            "url": "classes/Horde-Idna-Punycode.html#method__codePointToChar"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003ABASE",
            "name": "BASE",
            "summary": "Bootstring\u0020parameter\u0020values.",
            "url": "classes/Horde-Idna-Punycode.html#constant_BASE"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003ATMIN",
            "name": "TMIN",
            "summary": "",
            "url": "classes/Horde-Idna-Punycode.html#constant_TMIN"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003ATMAX",
            "name": "TMAX",
            "summary": "",
            "url": "classes/Horde-Idna-Punycode.html#constant_TMAX"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003ASKEW",
            "name": "SKEW",
            "summary": "",
            "url": "classes/Horde-Idna-Punycode.html#constant_SKEW"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003ADAMP",
            "name": "DAMP",
            "summary": "",
            "url": "classes/Horde-Idna-Punycode.html#constant_DAMP"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003AINITIAL_BIAS",
            "name": "INITIAL_BIAS",
            "summary": "",
            "url": "classes/Horde-Idna-Punycode.html#constant_INITIAL_BIAS"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003AINITIAL_N",
            "name": "INITIAL_N",
            "summary": "",
            "url": "classes/Horde-Idna-Punycode.html#constant_INITIAL_N"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003APREFIX",
            "name": "PREFIX",
            "summary": "",
            "url": "classes/Horde-Idna-Punycode.html#constant_PREFIX"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003ADELIMITER",
            "name": "DELIMITER",
            "summary": "",
            "url": "classes/Horde-Idna-Punycode.html#constant_DELIMITER"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003A\u0024_encodeTable",
            "name": "_encodeTable",
            "summary": "Encode\u0020table.",
            "url": "classes/Horde-Idna-Punycode.html#property__encodeTable"
        },                {
            "fqsen": "\\Horde_Idna_Punycode\u003A\u003A\u0024_decodeTable",
            "name": "_decodeTable",
            "summary": "Decode\u0020table.",
            "url": "classes/Horde-Idna-Punycode.html#property__decodeTable"
        },                {
            "fqsen": "\\Horde_Idna_Translation",
            "name": "Horde_Idna_Translation",
            "summary": "Horde_Idna_Translation\u0020is\u0020the\u0020translation\u0020wrapper\u0020class\u0020for\nHorde_Idna.",
            "url": "classes/Horde-Idna-Translation.html"
        },                {
            "fqsen": "\\Horde_Idna_Translation\u003A\u003A\u0024_domain",
            "name": "_domain",
            "summary": "The\u0020translation\u0020domain",
            "url": "classes/Horde-Idna-Translation.html#property__domain"
        },                {
            "fqsen": "\\Horde_Idna_Translation\u003A\u003A\u0024_pearDirectory",
            "name": "_pearDirectory",
            "summary": "The\u0020absolute\u0020PEAR\u0020path\u0020to\u0020the\u0020translations\u0020for\u0020the\u0020default\u0020gettext\u0020handler.",
            "url": "classes/Horde-Idna-Translation.html#property__pearDirectory"
        },                {
            "fqsen": "\\Horde_Idna",
            "name": "Horde_Idna",
            "summary": "Provide\u0020normalized\u0020encoding\/decoding\u0020support\u0020for\u0020IDNA\u0020strings.",
            "url": "classes/Horde-Idna.html"
        },                {
            "fqsen": "\\Horde_Idna\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Horde-Idna.html#method_encode"
        },                {
            "fqsen": "\\Horde_Idna\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Horde-Idna.html#method_decode"
        },                {
            "fqsen": "\\Horde_Idna\u003A\u003A_checkForError\u0028\u0029",
            "name": "_checkForError",
            "summary": "Checks\u0020if\u0020the\u0020\u0024idna_info\u0020parameter\u0020of\u0020idn_to_ascii\u0028\u0029\u0020or\u0020idn_to_utf8\u0028\u0029\ncontains\u0020errors.",
            "url": "classes/Horde-Idna.html#method__checkForError"
        },                {
            "fqsen": "\\Horde_Idna\u003A\u003A_getBackend\u0028\u0029",
            "name": "_getBackend",
            "summary": "Return\u0020the\u0020IDNA\u0020backend.",
            "url": "classes/Horde-Idna.html#method__getBackend"
        },                {
            "fqsen": "\\Horde_Idna\u003A\u003A\u0024_backend",
            "name": "_backend",
            "summary": "The\u0020backend\u0020to\u0020use.",
            "url": "classes/Horde-Idna.html#property__backend"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
