Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Http_Client",
            "name": "Horde_Http_Client",
            "summary": "An\u0020HTTP\u0020client.",
            "url": "classes/Horde-Http-Client.html"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Horde_Http_Client\u0020constructor.",
            "url": "classes/Horde-Http-Client.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Sends\u0020a\u0020GET\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_get"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Sends\u0020a\u0020POST\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_post"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Sends\u0020a\u0020PUT\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_put"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Sends\u0020a\u0020DELETE\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_delete"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Ahead\u0028\u0029",
            "name": "head",
            "summary": "Sends\u0020a\u0020HEAD\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_head"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Sends\u0020an\u0020HTTP\u0020request.",
            "url": "classes/Horde-Http-Client.html#method_request"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Returns\u0020a\u0020client\u0020parameter.",
            "url": "classes/Horde-Http-Client.html#method___get"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Sets\u0020a\u0020client\u0020parameter.",
            "url": "classes/Horde-Http-Client.html#method___set"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A\u0024_request",
            "name": "_request",
            "summary": "The\u0020current\u0020HTTP\u0020request.",
            "url": "classes/Horde-Http-Client.html#property__request"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A\u0024_lastRequest",
            "name": "_lastRequest",
            "summary": "The\u0020previous\u0020HTTP\u0020request.",
            "url": "classes/Horde-Http-Client.html#property__lastRequest"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A\u0024_lastResponse",
            "name": "_lastResponse",
            "summary": "The\u0020most\u0020recent\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Client.html#property__lastResponse"
        },                {
            "fqsen": "\\Horde_Http_Client\u003A\u003A\u0024_httpMethodOverride",
            "name": "_httpMethodOverride",
            "summary": "Use\u0020POST\u0020instead\u0020of\u0020PUT\u0020and\u0020DELETE,\u0020sending\u0020X\u002DHTTP\u002DMethod\u002DOverride\u0020with\nthe\u0020intended\u0020method\u0020name\u0020instead.",
            "url": "classes/Horde-Http-Client.html#property__httpMethodOverride"
        },                {
            "fqsen": "\\Horde_Http_Exception",
            "name": "Horde_Http_Exception",
            "summary": "Base\u0020exception\u0020for\u0020the\u0020Horde_Http\u0020library.",
            "url": "classes/Horde-Http-Exception.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Base",
            "name": "Horde_Http_Request_Base",
            "summary": "Base\u0020class\u0020for\u0020HTTP\u0020request\u0020objects.",
            "url": "classes/Horde-Http-Request-Base.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Base.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "",
            "url": "classes/Horde-Http-Request-Base.html#method_setOptions"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003AgetDefaultOptions\u0028\u0029",
            "name": "getDefaultOptions",
            "summary": "",
            "url": "classes/Horde-Http-Request-Base.html#method_getDefaultOptions"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Base.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Get\u0020an\u0020adapter\u0020parameter",
            "url": "classes/Horde-Http-Request-Base.html#method___get"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Set\u0020a\u0020request\u0020parameter",
            "url": "classes/Horde-Http-Request-Base.html#method___set"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003AsetHeaders\u0028\u0029",
            "name": "setHeaders",
            "summary": "Set\u0020one\u0020or\u0020more\u0020headers",
            "url": "classes/Horde-Http-Request-Base.html#method_setHeaders"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "Get\u0020the\u0020current\u0020value\u0020of\u0020\u0024header",
            "url": "classes/Horde-Http-Request-Base.html#method_getHeader"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A\u0024_headers",
            "name": "_headers",
            "summary": "Request\u0020headers",
            "url": "classes/Horde-Http-Request-Base.html#property__headers"
        },                {
            "fqsen": "\\Horde_Http_Request_Base\u003A\u003A\u0024_options",
            "name": "_options",
            "summary": "",
            "url": "classes/Horde-Http-Request-Base.html#property__options"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl",
            "name": "Horde_Http_Request_Curl",
            "summary": "HTTP\u0020request\u0020object\u0020for\u0020the\u0020curl\u0020backend.",
            "url": "classes/Horde-Http-Request-Curl.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Curl.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Curl.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl\u003A\u003A_httpAuthScheme\u0028\u0029",
            "name": "_httpAuthScheme",
            "summary": "Translate\u0020a\u0020Horde_Http\u003A\u003AAUTH_\u002A\u0020constant\u0020to\u0020CURLAUTH_\u002A",
            "url": "classes/Horde-Http-Request-Curl.html#method__httpAuthScheme"
        },                {
            "fqsen": "\\Horde_Http_Request_Curl\u003A\u003A\u0024_httpAuthSchemes",
            "name": "_httpAuthSchemes",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nHTTP_AUTH\u0020constants.",
            "url": "classes/Horde-Http-Request-Curl.html#property__httpAuthSchemes"
        },                {
            "fqsen": "\\Horde_Http_Request_Factory",
            "name": "Horde_Http_Request_Factory",
            "summary": "HTTP\u0020request\u0020object\u0020factory.",
            "url": "classes/Horde-Http-Request-Factory.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Factory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Find\u0020the\u0020best\u0020available\u0020request\u0020backend",
            "url": "classes/Horde-Http-Request-Factory.html#method_create"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen",
            "name": "Horde_Http_Request_Fopen",
            "summary": "HTTP\u0020request\u0020object\u0020for\u0020the\u0020fopen\u0020backend.",
            "url": "classes/Horde-Http-Request-Fopen.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Fopen.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Fopen.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen\u003A\u003A_errorHandler\u0028\u0029",
            "name": "_errorHandler",
            "summary": "PHP\u0020error\u0020handler.",
            "url": "classes/Horde-Http-Request-Fopen.html#method__errorHandler"
        },                {
            "fqsen": "\\Horde_Http_Request_Fopen\u003A\u003A\u0024_errors",
            "name": "_errors",
            "summary": "Catched\u0020errors\u0020from\u0020the\u0020error\u0020handler.",
            "url": "classes/Horde-Http-Request-Fopen.html#property__errors"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock",
            "name": "Horde_Http_Request_Mock",
            "summary": "Mock\u0020HTTP\u0020request\u0020object.",
            "url": "classes/Horde-Http-Request-Mock.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Mock.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003AsetResponse\u0028\u0029",
            "name": "setResponse",
            "summary": "Set\u0020the\u0020HTTP\u0020response\u0028s\u0029\u0020to\u0020be\u0020returned\u0020by\u0020this\u0020adapter.\u0020This\u0020overwrites\nany\u0020responses\u0020set\u0020before.",
            "url": "classes/Horde-Http-Request-Mock.html#method_setResponse"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003AaddResponses\u0028\u0029",
            "name": "addResponses",
            "summary": "Set\u0020the\u0020HTTP\u0020response\u0028s\u0029\u0020to\u0020be\u0020returned\u0020by\u0020this\u0020adapter\u0020as\u0020an\u0020array\u0020of\u0020strings.",
            "url": "classes/Horde-Http-Request-Mock.html#method_addResponses"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003AaddResponse\u0028\u0029",
            "name": "addResponse",
            "summary": "Adds\u0020a\u0020response\u0020to\u0020the\u0020stack\u0020of\u0020responses.",
            "url": "classes/Horde-Http-Request-Mock.html#method_addResponse"
        },                {
            "fqsen": "\\Horde_Http_Request_Mock\u003A\u003A\u0024_responses",
            "name": "_responses",
            "summary": "Mock\u0020responses\u0020to\u0020return.",
            "url": "classes/Horde-Http-Request-Mock.html#property__responses"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp",
            "name": "Horde_Http_Request_Peclhttp",
            "summary": "HTTP\u0020request\u0020object\u0020for\u0020the\u0020pecl_http\u00201.0\u0020backend.",
            "url": "classes/Horde-Http-Request-Peclhttp.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Peclhttp.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Peclhttp.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp\u003A\u003A\u0024_httpAuthSchemes",
            "name": "_httpAuthSchemes",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nHTTP_AUTH\u0020constants.",
            "url": "classes/Horde-Http-Request-Peclhttp.html#property__httpAuthSchemes"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2",
            "name": "Horde_Http_Request_Peclhttp2",
            "summary": "HTTP\u0020request\u0020object\u0020for\u0020the\u0020pecl_http\u00202.0\u0020backend.",
            "url": "classes/Horde-Http-Request-Peclhttp2.html"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Request-Peclhttp2.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020this\u0020HTTP\u0020request",
            "url": "classes/Horde-Http-Request-Peclhttp2.html#method_send"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2\u003A\u003A\u0024_httpAuthSchemes",
            "name": "_httpAuthSchemes",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nHTTP_AUTH\u0020constants.",
            "url": "classes/Horde-Http-Request-Peclhttp2.html#property__httpAuthSchemes"
        },                {
            "fqsen": "\\Horde_Http_Request_Peclhttp2\u003A\u003A\u0024_proxyTypes",
            "name": "_proxyTypes",
            "summary": "Map\u0020of\u0020proxy\u0020types\u0020from\u0020Horde_Http\u0020to\u0020implementation\u0020specific\u0020constants.",
            "url": "classes/Horde-Http-Request-Peclhttp2.html#property__proxyTypes"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase",
            "name": "Horde_Http_Request_PeclhttpBase",
            "summary": "Base\u0020HTTP\u0020request\u0020object\u0020for\u0020the\u0020pecl_http\u0020backends.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A_httpAuthScheme\u0028\u0029",
            "name": "_httpAuthScheme",
            "summary": "Translates\u0020a\u0020Horde_Http\u003A\u003AAUTH_\u002A\u0020constant\u0020to\u0020implementation\u0020specific\nconstants.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#method__httpAuthScheme"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A_proxyType\u0028\u0029",
            "name": "_proxyType",
            "summary": "Translates\u0020a\u0020Horde_Http\u003A\u003APROXY_\u002A\u0020constant\u0020to\u0020implementation\u0020specific\nconstants.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#method__proxyType"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A_httpOptions\u0028\u0029",
            "name": "_httpOptions",
            "summary": "Generates\u0020the\u0020HTTP\u0020options\u0020for\u0020the\u0020request.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#method__httpOptions"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A\u0024_httpAuthSchemes",
            "name": "_httpAuthSchemes",
            "summary": "Map\u0020of\u0020HTTP\u0020authentication\u0020schemes\u0020from\u0020Horde_Http\u0020constants\u0020to\nimplementation\u0020specific\u0020constants.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#property__httpAuthSchemes"
        },                {
            "fqsen": "\\Horde_Http_Request_PeclhttpBase\u003A\u003A\u0024_proxyTypes",
            "name": "_proxyTypes",
            "summary": "Map\u0020of\u0020proxy\u0020types\u0020from\u0020Horde_Http\u0020to\u0020implementation\u0020specific\u0020constants.",
            "url": "classes/Horde-Http-Request-PeclhttpBase.html#property__proxyTypes"
        },                {
            "fqsen": "\\Horde_Http_Response_Base",
            "name": "Horde_Http_Response_Base",
            "summary": "Base\u0020class\u0020for\u0020HTTP\u0020response\u0020objects.",
            "url": "classes/Horde-Http-Response-Base.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A_parseHeaders\u0028\u0029",
            "name": "_parseHeaders",
            "summary": "Parses\u0020an\u0020array\u0020of\u0020response\u0020headers,\u0020mindful\u0020of\u0020line\u0020continuations,\u0020etc.",
            "url": "classes/Horde-Http-Response-Base.html#method__parseHeaders"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Base.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Returns\u0020a\u0020stream\u0020pointing\u0020to\u0020the\u0020response\u0020body\u0020that\u0020can\u0020be\u0020used\u0020with\u0020all\nstandard\u0020PHP\u0020stream\u0020functions.",
            "url": "classes/Horde-Http-Response-Base.html#method_getStream"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "Returns\u0020the\u0020value\u0020of\u0020a\u0020single\u0020response\u0020header.",
            "url": "classes/Horde-Http-Response-Base.html#method_getHeader"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "Fetched\u0020URI.",
            "url": "classes/Horde-Http-Response-Base.html#property_uri"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024httpVersion",
            "name": "httpVersion",
            "summary": "HTTP\u0020protocol\u0020version\u0020that\u0020was\u0020used.",
            "url": "classes/Horde-Http-Response-Base.html#property_httpVersion"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024code",
            "name": "code",
            "summary": "HTTP\u0020response\u0020code.",
            "url": "classes/Horde-Http-Response-Base.html#property_code"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "Response\u0020headers.",
            "url": "classes/Horde-Http-Response-Base.html#property_headers"
        },                {
            "fqsen": "\\Horde_Http_Response_Base\u003A\u003A\u0024_headers",
            "name": "_headers",
            "summary": "Case\u002Dinsensitive\u0020list\u0020of\u0020headers.",
            "url": "classes/Horde-Http-Response-Base.html#property__headers"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl",
            "name": "Horde_Http_Response_Curl",
            "summary": "HTTP\u0020response\u0020object\u0020for\u0020the\u0020curl\u0020backend.",
            "url": "classes/Horde-Http-Response-Curl.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Http-Response-Curl.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Curl.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A_parseResult\u0028\u0029",
            "name": "_parseResult",
            "summary": "Parses\u0020the\u0020combined\u0020header\/body\u0020result\u0020from\u0020cURL.",
            "url": "classes/Horde-Http-Response-Curl.html#method__parseResult"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A_parseInfo\u0028\u0029",
            "name": "_parseInfo",
            "summary": "Processes\u0020the\u0020results\u0020of\u0020curl_getinfo.",
            "url": "classes/Horde-Http-Response-Curl.html#method__parseInfo"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A\u0024_info",
            "name": "_info",
            "summary": "Info\u0020on\u0020the\u0020request\u0020obtained\u0020from\u0020curl_getinfo\u0028\u0029.",
            "url": "classes/Horde-Http-Response-Curl.html#property__info"
        },                {
            "fqsen": "\\Horde_Http_Response_Curl\u003A\u003A\u0024_body",
            "name": "_body",
            "summary": "Response\u0020body.",
            "url": "classes/Horde-Http-Response-Curl.html#property__body"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen",
            "name": "Horde_Http_Response_Fopen",
            "summary": "HTTP\u0020response\u0020object\u0020for\u0020the\u0020fopen\u0020backend.",
            "url": "classes/Horde-Http-Response-Fopen.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Http-Response-Fopen.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Fopen.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003AgetStream\u0028\u0029",
            "name": "getStream",
            "summary": "Returns\u0020a\u0020stream\u0020pointing\u0020to\u0020the\u0020response\u0020body\u0020that\u0020can\u0020be\u0020used\u0020with\nall\u0020standard\u0020PHP\u0020stream\u0020functions.",
            "url": "classes/Horde-Http-Response-Fopen.html#method_getStream"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003A\u0024_stream",
            "name": "_stream",
            "summary": "Response\u0020body.",
            "url": "classes/Horde-Http-Response-Fopen.html#property__stream"
        },                {
            "fqsen": "\\Horde_Http_Response_Fopen\u003A\u003A\u0024_content",
            "name": "_content",
            "summary": "Response\u0020content",
            "url": "classes/Horde-Http-Response-Fopen.html#property__content"
        },                {
            "fqsen": "\\Horde_Http_Response_Mock",
            "name": "Horde_Http_Response_Mock",
            "summary": "Mock\u0020HTTP\u0020response\u0020object.",
            "url": "classes/Horde-Http-Response-Mock.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Mock\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Response-Mock.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Mock\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Mock.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp",
            "name": "Horde_Http_Response_Peclhttp",
            "summary": "HTTP\u0020response\u0020object\u0020for\u0020the\u0020pecl_http\u0020backend.",
            "url": "classes/Horde-Http-Response-Peclhttp.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Http-Response-Peclhttp.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Peclhttp.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp\u003A\u003A\u0024_message",
            "name": "_message",
            "summary": "HttpMessage\u0020object.",
            "url": "classes/Horde-Http-Response-Peclhttp.html#property__message"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp2",
            "name": "Horde_Http_Response_Peclhttp2",
            "summary": "HTTP\u0020response\u0020object\u0020for\u0020the\u0020pecl_http\u00202.0\u0020backend.",
            "url": "classes/Horde-Http-Response-Peclhttp2.html"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp2\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Http-Response-Peclhttp2.html#method___construct"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp2\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020the\u0020body\u0020of\u0020the\u0020HTTP\u0020response.",
            "url": "classes/Horde-Http-Response-Peclhttp2.html#method_getBody"
        },                {
            "fqsen": "\\Horde_Http_Response_Peclhttp2\u003A\u003A\u0024_response",
            "name": "_response",
            "summary": "HttpMessage\u0020object.",
            "url": "classes/Horde-Http-Response-Peclhttp2.html#property__response"
        },                {
            "fqsen": "\\Horde_Http",
            "name": "Horde_Http",
            "summary": "Constants\u0020for\u0020Horde_Http.",
            "url": "classes/Horde-Http.html"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_ANY",
            "name": "AUTH_ANY",
            "summary": "Authentication\u0020schemes",
            "url": "classes/Horde-Http.html#constant_AUTH_ANY"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_BASIC",
            "name": "AUTH_BASIC",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_AUTH_BASIC"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_DIGEST",
            "name": "AUTH_DIGEST",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_AUTH_DIGEST"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_NTLM",
            "name": "AUTH_NTLM",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_AUTH_NTLM"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003AAUTH_GSSNEGOTIATE",
            "name": "AUTH_GSSNEGOTIATE",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_AUTH_GSSNEGOTIATE"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003APROXY_HTTP",
            "name": "PROXY_HTTP",
            "summary": "Proxy\u0020types",
            "url": "classes/Horde-Http.html#constant_PROXY_HTTP"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003APROXY_SOCKS4",
            "name": "PROXY_SOCKS4",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_PROXY_SOCKS4"
        },                {
            "fqsen": "\\Horde_Http\u003A\u003APROXY_SOCKS5",
            "name": "PROXY_SOCKS5",
            "summary": "",
            "url": "classes/Horde-Http.html#constant_PROXY_SOCKS5"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
