Search.appendIndex(
    [
                {
            "fqsen": "\\Horde\\Composer\\CommandProvider",
            "name": "CommandProvider",
            "summary": "",
            "url": "classes/Horde-Composer-CommandProvider.html"
        },                {
            "fqsen": "\\Horde\\Composer\\CommandProvider\u003A\u003AgetCommands\u0028\u0029",
            "name": "getCommands",
            "summary": "",
            "url": "classes/Horde-Composer-CommandProvider.html#method_getCommands"
        },                {
            "fqsen": "\\Horde\\Composer\\ConfigLinker",
            "name": "ConfigLinker",
            "summary": "",
            "url": "classes/Horde-Composer-ConfigLinker.html"
        },                {
            "fqsen": "\\Horde\\Composer\\ConfigLinker\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Composer-ConfigLinker.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Composer\\ConfigLinker\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Symlink\u0020contents\u0020of\u0020var\/config",
            "url": "classes/Horde-Composer-ConfigLinker.html#method_run"
        },                {
            "fqsen": "\\Horde\\Composer\\ConfigLinker\u003A\u003A\u0024baseDir",
            "name": "baseDir",
            "summary": "",
            "url": "classes/Horde-Composer-ConfigLinker.html#property_baseDir"
        },                {
            "fqsen": "\\Horde\\Composer\\ConfigLinker\u003A\u003A\u0024configDir",
            "name": "configDir",
            "summary": "",
            "url": "classes/Horde-Composer-ConfigLinker.html#property_configDir"
        },                {
            "fqsen": "\\Horde\\Composer\\ConfigLinker\u003A\u003A\u0024vendorDir",
            "name": "vendorDir",
            "summary": "",
            "url": "classes/Horde-Composer-ConfigLinker.html#property_vendorDir"
        },                {
            "fqsen": "\\Horde\\Composer\\ConfigLinker\u003A\u003A\u0024webDir",
            "name": "webDir",
            "summary": "",
            "url": "classes/Horde-Composer-ConfigLinker.html#property_webDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller",
            "name": "HordeInstaller",
            "summary": "Installer\u0020implementation\u0020for\u0020horde\u0020apps\u0020and\u0020themes",
            "url": "classes/Horde-Composer-HordeInstaller.html"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003AsetupDirs\u0028\u0029",
            "name": "setupDirs",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#method_setupDirs"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003AgetInstallPath\u0028\u0029",
            "name": "getInstallPath",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Horde-Composer-HordeInstaller.html#method_getInstallPath"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003Apostinstall\u0028\u0029",
            "name": "postinstall",
            "summary": "Handle\u0020horde\u002Dspecific\u0020postinstall\u0020tasks",
            "url": "classes/Horde-Composer-HordeInstaller.html#method_postinstall"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003AlinkVarConfig\u0028\u0029",
            "name": "linkVarConfig",
            "summary": "Symlink\u0020contents\u0020of\u0020var\/config",
            "url": "classes/Horde-Composer-HordeInstaller.html#method_linkVarConfig"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003AlinkJavaScript\u0028\u0029",
            "name": "linkJavaScript",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#method_linkJavaScript"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A_legacyWorkaround\u0028\u0029",
            "name": "_legacyWorkaround",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#method__legacyWorkaround"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Horde-Composer-HordeInstaller.html#method_supports"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024projectRoot",
            "name": "projectRoot",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_projectRoot"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024configDir",
            "name": "configDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_configDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024appConfigDir",
            "name": "appConfigDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_appConfigDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024hordeConfigDir",
            "name": "hordeConfigDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_hordeConfigDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024webDir",
            "name": "webDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_webDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024presetDir",
            "name": "presetDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_presetDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024jsDir",
            "name": "jsDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_jsDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024hordeWebDir",
            "name": "hordeWebDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_hordeWebDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024configRegistryDir",
            "name": "configRegistryDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_configRegistryDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024packageDir",
            "name": "packageDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_packageDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024packageDocRegistryDir",
            "name": "packageDocRegistryDir",
            "summary": "A\u0020location\u0020to\u0020look\u0020for\u0020package\u002Dsupplied\u0020registry\u0020snippets\nThis\u0020is\u0020useful\u0020for\u0020custom\u0020apps",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_packageDocRegistryDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024packageName",
            "name": "packageName",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_packageName"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstaller\u003A\u003A\u0024vendorName",
            "name": "vendorName",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstaller.html#property_vendorName"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstallerPlugin",
            "name": "HordeInstallerPlugin",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstallerPlugin.html"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstallerPlugin\u003A\u003Aactivate\u0028\u0029",
            "name": "activate",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstallerPlugin.html#method_activate"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstallerPlugin\u003A\u003Adeactivate\u0028\u0029",
            "name": "deactivate",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstallerPlugin.html#method_deactivate"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstallerPlugin\u003A\u003Auninstall\u0028\u0029",
            "name": "uninstall",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstallerPlugin.html#method_uninstall"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstallerPlugin\u003A\u003AgetSubscribedEvents\u0028\u0029",
            "name": "getSubscribedEvents",
            "summary": "Exposre\u0020which\u0020events\u0020are\u0020handled\u0020by\u0020which\u0020handler",
            "url": "classes/Horde-Composer-HordeInstallerPlugin.html#method_getSubscribedEvents"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstallerPlugin\u003A\u003ApostInstallHandler\u0028\u0029",
            "name": "postInstallHandler",
            "summary": "Handler\u0020for\u0020post\u002Dpackage\u002Dinstall",
            "url": "classes/Horde-Composer-HordeInstallerPlugin.html#method_postInstallHandler"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstallerPlugin\u003A\u003ApostUpdateHandler\u0028\u0029",
            "name": "postUpdateHandler",
            "summary": "Handler\u0020for\u0020post\u002Dpackage\u002Dupdate",
            "url": "classes/Horde-Composer-HordeInstallerPlugin.html#method_postUpdateHandler"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstallerPlugin\u003A\u003AgetCapabilities\u0028\u0029",
            "name": "getCapabilities",
            "summary": "Expose\u0020capabilities",
            "url": "classes/Horde-Composer-HordeInstallerPlugin.html#method_getCapabilities"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeInstallerPlugin\u003A\u003A\u0024installer",
            "name": "installer",
            "summary": "",
            "url": "classes/Horde-Composer-HordeInstallerPlugin.html#property_installer"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter",
            "name": "HordeLocalFileWriter",
            "summary": "",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Undocumented\u0020function",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#method_run"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003AprocessApp\u0028\u0029",
            "name": "processApp",
            "summary": "",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#method_processApp"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003A_legacyWorkaround\u0028\u0029",
            "name": "_legacyWorkaround",
            "summary": "Legacy\u0020support",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#method__legacyWorkaround"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003A\u0024apps",
            "name": "apps",
            "summary": "List\u0020of\u0020apps",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#property_apps"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003A\u0024baseDir",
            "name": "baseDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#property_baseDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003A\u0024configDir",
            "name": "configDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#property_configDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003A\u0024vendorDir",
            "name": "vendorDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#property_vendorDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003A\u0024webDir",
            "name": "webDir",
            "summary": "",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#property_webDir"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeLocalFileWriter\u003A\u003A\u0024filesystem",
            "name": "filesystem",
            "summary": "",
            "url": "classes/Horde-Composer-HordeLocalFileWriter.html#property_filesystem"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeReconfigureCommand",
            "name": "HordeReconfigureCommand",
            "summary": "",
            "url": "classes/Horde-Composer-HordeReconfigureCommand.html"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeReconfigureCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/Horde-Composer-HordeReconfigureCommand.html#method_configure"
        },                {
            "fqsen": "\\Horde\\Composer\\HordeReconfigureCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/Horde-Composer-HordeReconfigureCommand.html#method_execute"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker",
            "name": "JsTreeLinker",
            "summary": "",
            "url": "classes/Horde-Composer-JsTreeLinker.html"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Composer-JsTreeLinker.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Build\u0020the\u0020web\/js\/\u0020symlink\u0020tree",
            "url": "classes/Horde-Composer-JsTreeLinker.html#method_run"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003AlinkDir\u0028\u0029",
            "name": "linkDir",
            "summary": "",
            "url": "classes/Horde-Composer-JsTreeLinker.html#method_linkDir"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003A\u0024filesystem",
            "name": "filesystem",
            "summary": "",
            "url": "classes/Horde-Composer-JsTreeLinker.html#property_filesystem"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003A\u0024baseDir",
            "name": "baseDir",
            "summary": "",
            "url": "classes/Horde-Composer-JsTreeLinker.html#property_baseDir"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003A\u0024vendorDir",
            "name": "vendorDir",
            "summary": "",
            "url": "classes/Horde-Composer-JsTreeLinker.html#property_vendorDir"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003A\u0024webDir",
            "name": "webDir",
            "summary": "",
            "url": "classes/Horde-Composer-JsTreeLinker.html#property_webDir"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003A\u0024jsDir",
            "name": "jsDir",
            "summary": "",
            "url": "classes/Horde-Composer-JsTreeLinker.html#property_jsDir"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003A\u0024apps",
            "name": "apps",
            "summary": "List\u0020of\u0020apps",
            "url": "classes/Horde-Composer-JsTreeLinker.html#property_apps"
        },                {
            "fqsen": "\\Horde\\Composer\\JsTreeLinker\u003A\u003A\u0024libs",
            "name": "libs",
            "summary": "List\u0020of\u0020libraries",
            "url": "classes/Horde-Composer-JsTreeLinker.html#property_libs"
        },                {
            "fqsen": "\\Horde\\Composer\\PackageDocRegistrySnippetHandler",
            "name": "PackageDocRegistrySnippetHandler",
            "summary": "Look\u0020for\u0020registry\u0020snippets\u0020in\u0020all\u0020app\u0027s\u0020doc\/registry.d\u0020folder",
            "url": "classes/Horde-Composer-PackageDocRegistrySnippetHandler.html"
        },                {
            "fqsen": "\\Horde\\Composer\\PackageDocRegistrySnippetHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Composer-PackageDocRegistrySnippetHandler.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Composer\\PackageDocRegistrySnippetHandler\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Horde-Composer-PackageDocRegistrySnippetHandler.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Composer\\PackageDocRegistrySnippetHandler\u003A\u003A\u0024apps",
            "name": "apps",
            "summary": "List\u0020of\u0020installed\u0020apps",
            "url": "classes/Horde-Composer-PackageDocRegistrySnippetHandler.html#property_apps"
        },                {
            "fqsen": "\\Horde\\Composer\\PackageDocRegistrySnippetHandler\u003A\u003A\u0024configDir",
            "name": "configDir",
            "summary": "",
            "url": "classes/Horde-Composer-PackageDocRegistrySnippetHandler.html#property_configDir"
        },                {
            "fqsen": "\\Horde\\Composer\\PackageDocRegistrySnippetHandler\u003A\u003A\u0024filesystem",
            "name": "filesystem",
            "summary": "",
            "url": "classes/Horde-Composer-PackageDocRegistrySnippetHandler.html#property_filesystem"
        },                {
            "fqsen": "\\Horde\\Composer\\PackageDocRegistrySnippetHandler\u003A\u003A\u0024webDir",
            "name": "webDir",
            "summary": "",
            "url": "classes/Horde-Composer-PackageDocRegistrySnippetHandler.html#property_webDir"
        },                {
            "fqsen": "\\Horde\\Composer\\PresetHandler",
            "name": "PresetHandler",
            "summary": "",
            "url": "classes/Horde-Composer-PresetHandler.html"
        },                {
            "fqsen": "\\Horde\\Composer\\PresetHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Composer-PresetHandler.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Composer\\PresetHandler\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Horde-Composer-PresetHandler.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Composer\\PresetHandler\u003A\u003A\u0024rootDir",
            "name": "rootDir",
            "summary": "",
            "url": "classes/Horde-Composer-PresetHandler.html#property_rootDir"
        },                {
            "fqsen": "\\Horde\\Composer\\PresetHandler\u003A\u003A\u0024presetDir",
            "name": "presetDir",
            "summary": "",
            "url": "classes/Horde-Composer-PresetHandler.html#property_presetDir"
        },                {
            "fqsen": "\\Horde\\Composer\\PresetHandler\u003A\u003A\u0024configDir",
            "name": "configDir",
            "summary": "",
            "url": "classes/Horde-Composer-PresetHandler.html#property_configDir"
        },                {
            "fqsen": "\\Horde\\Composer\\PresetHandler\u003A\u003A\u0024filesystem",
            "name": "filesystem",
            "summary": "",
            "url": "classes/Horde-Composer-PresetHandler.html#property_filesystem"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesCatalog",
            "name": "ThemesCatalog",
            "summary": "Encapsulate\u0020handling\u0020the\u0020themes\u0020catalog",
            "url": "classes/Horde-Composer-ThemesCatalog.html"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesCatalog\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesCatalog.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesCatalog\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesCatalog.html#method_save"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesCatalog\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesCatalog.html#method_register"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesCatalog\u003A\u003Aunregister\u0028\u0029",
            "name": "unregister",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesCatalog.html#method_unregister"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesCatalog\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Return\u0020an\u0020array\u0020representation",
            "url": "classes/Horde-Composer-ThemesCatalog.html#method_toArray"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesCatalog\u003A\u003A\u0024rootDir",
            "name": "rootDir",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesCatalog.html#property_rootDir"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesCatalog\u003A\u003A\u0024catalog",
            "name": "catalog",
            "summary": "Nested\u0020structure",
            "url": "classes/Horde-Composer-ThemesCatalog.html#property_catalog"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesCatalog\u003A\u003A\u0024themesFile",
            "name": "themesFile",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesCatalog.html#property_themesFile"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler",
            "name": "ThemesHandler",
            "summary": "Themes\u0020Handler\u0020class",
            "url": "classes/Horde-Composer-ThemesHandler.html"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesHandler.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler\u003A\u003AensureThemesFolderExists\u0028\u0029",
            "name": "ensureThemesFolderExists",
            "summary": "Create\u0020the\u0020basic\u0020themes\u0020folder\u0020if\u0020missing",
            "url": "classes/Horde-Composer-ThemesHandler.html#method_ensureThemesFolderExists"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler\u003A\u003AsetupDefaultTheme\u0028\u0029",
            "name": "setupDefaultTheme",
            "summary": "Cycle\u0020through\u0020applications\u0020to\u0020setup\u0020the\u0020directories\u0020for\u0020the\u0020default\u0020folder",
            "url": "classes/Horde-Composer-ThemesHandler.html#method_setupDefaultTheme"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler\u003A\u003AsetupPackagedThemes\u0028\u0029",
            "name": "setupPackagedThemes",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesHandler.html#method_setupPackagedThemes"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler\u003A\u003AsetupThemes\u0028\u0029",
            "name": "setupThemes",
            "summary": "Rebuild\u0020the\u0020link\u0020structure\u0020from\u0020index",
            "url": "classes/Horde-Composer-ThemesHandler.html#method_setupThemes"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler\u003A\u003A\u0024filesystem",
            "name": "filesystem",
            "summary": "Filesystem\u0020API",
            "url": "classes/Horde-Composer-ThemesHandler.html#property_filesystem"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler\u003A\u003A\u0024rootDir",
            "name": "rootDir",
            "summary": "The\u0020root\u0020package\u0027s\u0020dir",
            "url": "classes/Horde-Composer-ThemesHandler.html#property_rootDir"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler\u003A\u003A\u0024themesCatalog",
            "name": "themesCatalog",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesHandler.html#property_themesCatalog"
        },                {
            "fqsen": "\\Horde\\Composer\\ThemesHandler\u003A\u003A\u0024themesDir",
            "name": "themesDir",
            "summary": "",
            "url": "classes/Horde-Composer-ThemesHandler.html#property_themesDir"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Composer",
            "name": "Composer",
            "summary": "",
            "url": "namespaces/horde-composer.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
