Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_PubSub_Handle",
            "name": "Horde_PubSub_Handle",
            "summary": "Publish\u002DSubscribe\u0020handler\u003A\u0020unique\u0020handle\u0020subscribed\u0020to\u0020a\u0020given\u0020topic.",
            "url": "classes/Horde-PubSub-Handle.html"
        },                {
            "fqsen": "\\Horde_PubSub_Handle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-PubSub-Handle.html#method___construct"
        },                {
            "fqsen": "\\Horde_PubSub_Handle\u003A\u003AgetTopic\u0028\u0029",
            "name": "getTopic",
            "summary": "Get\u0020topic\u0020to\u0020which\u0020handle\u0020is\u0020subscribed",
            "url": "classes/Horde-PubSub-Handle.html#method_getTopic"
        },                {
            "fqsen": "\\Horde_PubSub_Handle\u003A\u003AgetCallback\u0028\u0029",
            "name": "getCallback",
            "summary": "Retrieve\u0020registered\u0020callback",
            "url": "classes/Horde-PubSub-Handle.html#method_getCallback"
        },                {
            "fqsen": "\\Horde_PubSub_Handle\u003A\u003Acall\u0028\u0029",
            "name": "call",
            "summary": "Invoke\u0020handler",
            "url": "classes/Horde-PubSub-Handle.html#method_call"
        },                {
            "fqsen": "\\Horde_PubSub_Handle\u003A\u003A\u0024_callback",
            "name": "_callback",
            "summary": "PHP\u0020callback\u0020to\u0020invoke",
            "url": "classes/Horde-PubSub-Handle.html#property__callback"
        },                {
            "fqsen": "\\Horde_PubSub_Handle\u003A\u003A\u0024_topic",
            "name": "_topic",
            "summary": "Topic\u0020to\u0020which\u0020this\u0020handle\u0020is\u0020subscribed",
            "url": "classes/Horde-PubSub-Handle.html#property__topic"
        },                {
            "fqsen": "\\Horde_PubSub_Provider",
            "name": "Horde_PubSub_Provider",
            "summary": "Publish\u002DSubscribe\u0020provider",
            "url": "classes/Horde-PubSub-Provider.html"
        },                {
            "fqsen": "\\Horde_PubSub_Provider\u003A\u003Apublish\u0028\u0029",
            "name": "publish",
            "summary": "Publish\u0020to\u0020all\u0020handlers\u0020for\u0020a\u0020given\u0020topic",
            "url": "classes/Horde-PubSub-Provider.html#method_publish"
        },                {
            "fqsen": "\\Horde_PubSub_Provider\u003A\u003Asubscribe\u0028\u0029",
            "name": "subscribe",
            "summary": "Subscribe\u0020to\u0020a\u0020topic",
            "url": "classes/Horde-PubSub-Provider.html#method_subscribe"
        },                {
            "fqsen": "\\Horde_PubSub_Provider\u003A\u003Aunsubscribe\u0028\u0029",
            "name": "unsubscribe",
            "summary": "Unsubscribe\u0020a\u0020handler\u0020from\u0020a\u0020topic",
            "url": "classes/Horde-PubSub-Provider.html#method_unsubscribe"
        },                {
            "fqsen": "\\Horde_PubSub_Provider\u003A\u003AgetTopics\u0028\u0029",
            "name": "getTopics",
            "summary": "Retrieve\u0020all\u0020registered\u0020topics",
            "url": "classes/Horde-PubSub-Provider.html#method_getTopics"
        },                {
            "fqsen": "\\Horde_PubSub_Provider\u003A\u003AgetSubscribedHandles\u0028\u0029",
            "name": "getSubscribedHandles",
            "summary": "Retrieve\u0020all\u0020handlers\u0020for\u0020a\u0020given\u0020topic",
            "url": "classes/Horde-PubSub-Provider.html#method_getSubscribedHandles"
        },                {
            "fqsen": "\\Horde_PubSub_Provider\u003A\u003AclearHandles\u0028\u0029",
            "name": "clearHandles",
            "summary": "Clear\u0020all\u0020handlers\u0020for\u0020a\u0020given\u0020topic",
            "url": "classes/Horde-PubSub-Provider.html#method_clearHandles"
        },                {
            "fqsen": "\\Horde_PubSub_Provider\u003A\u003A\u0024_topics",
            "name": "_topics",
            "summary": "Subscribed\u0020topics\u0020and\u0020their\u0020handles",
            "url": "classes/Horde-PubSub-Provider.html#property__topics"
        },                {
            "fqsen": "\\Horde_PubSub",
            "name": "Horde_PubSub",
            "summary": "Publish\u002DSubscribe\u0020system",
            "url": "classes/Horde-PubSub.html"
        },                {
            "fqsen": "\\Horde_PubSub\u003A\u003Apublish\u0028\u0029",
            "name": "publish",
            "summary": "Publish\u0020to\u0020all\u0020handlers\u0020for\u0020a\u0020given\u0020topic",
            "url": "classes/Horde-PubSub.html#method_publish"
        },                {
            "fqsen": "\\Horde_PubSub\u003A\u003Asubscribe\u0028\u0029",
            "name": "subscribe",
            "summary": "Subscribe\u0020to\u0020a\u0020topic",
            "url": "classes/Horde-PubSub.html#method_subscribe"
        },                {
            "fqsen": "\\Horde_PubSub\u003A\u003Aunsubscribe\u0028\u0029",
            "name": "unsubscribe",
            "summary": "Unsubscribe\u0020a\u0020handler\u0020from\u0020a\u0020topic",
            "url": "classes/Horde-PubSub.html#method_unsubscribe"
        },                {
            "fqsen": "\\Horde_PubSub\u003A\u003AgetTopics\u0028\u0029",
            "name": "getTopics",
            "summary": "Retrieve\u0020all\u0020registered\u0020topics",
            "url": "classes/Horde-PubSub.html#method_getTopics"
        },                {
            "fqsen": "\\Horde_PubSub\u003A\u003AgetSubscribedHandles\u0028\u0029",
            "name": "getSubscribedHandles",
            "summary": "Retrieve\u0020all\u0020handlers\u0020for\u0020a\u0020given\u0020topic",
            "url": "classes/Horde-PubSub.html#method_getSubscribedHandles"
        },                {
            "fqsen": "\\Horde_PubSub\u003A\u003AclearHandles\u0028\u0029",
            "name": "clearHandles",
            "summary": "Clear\u0020all\u0020handlers\u0020for\u0020a\u0020given\u0020topic",
            "url": "classes/Horde-PubSub.html#method_clearHandles"
        },                {
            "fqsen": "\\Horde_PubSub\u003A\u003A\u0024_topics",
            "name": "_topics",
            "summary": "Subscribed\u0020topics\u0020and\u0020their\u0020handles",
            "url": "classes/Horde-PubSub.html#property__topics"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
