Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Cli_Modular_Exception",
            "name": "Horde_Cli_Modular_Exception",
            "summary": "This\u0020provides\u0020the\u0020standard\u0020exception\u0020class\u0020for\u0020this\u0020package.",
            "url": "classes/Horde-Cli-Modular-Exception.html"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Module",
            "name": "Horde_Cli_Modular_Module",
            "summary": "The\u0020Horde_Cli_Modular_Module\u0020interface\u0020characterizes\u0020a\u0020single\u0020CLI\u0020module.",
            "url": "classes/Horde-Cli-Modular-Module.html"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Module\u003A\u003AgetUsage\u0028\u0029",
            "name": "getUsage",
            "summary": "Returns\u0020additional\u0020usage\u0020description\u0020for\u0020this\u0020module.",
            "url": "classes/Horde-Cli-Modular-Module.html#method_getUsage"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Module\u003A\u003AgetBaseOptions\u0028\u0029",
            "name": "getBaseOptions",
            "summary": "Returns\u0020a\u0020set\u0020of\u0020base\u0020options\u0020that\u0020this\u0020module\u0020adds\u0020to\u0020the\u0020CLI\u0020argument\nparser.",
            "url": "classes/Horde-Cli-Modular-Module.html#method_getBaseOptions"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Module\u003A\u003AhasOptionGroup\u0028\u0029",
            "name": "hasOptionGroup",
            "summary": "Returns\u0020whether\u0020the\u0020module\u0020provides\u0020an\u0020option\u0020group.",
            "url": "classes/Horde-Cli-Modular-Module.html#method_hasOptionGroup"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Module\u003A\u003AgetOptionGroupTitle\u0028\u0029",
            "name": "getOptionGroupTitle",
            "summary": "Returns\u0020the\u0020title\u0020for\u0020the\u0020option\u0020group\u0020representing\u0020this\u0020module.",
            "url": "classes/Horde-Cli-Modular-Module.html#method_getOptionGroupTitle"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Module\u003A\u003AgetOptionGroupDescription\u0028\u0029",
            "name": "getOptionGroupDescription",
            "summary": "Returns\u0020the\u0020description\u0020for\u0020the\u0020option\u0020group\u0020representing\u0020this\u0020module.",
            "url": "classes/Horde-Cli-Modular-Module.html#method_getOptionGroupDescription"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Module\u003A\u003AgetOptionGroupOptions\u0028\u0029",
            "name": "getOptionGroupOptions",
            "summary": "Returns\u0020the\u0020options\u0020for\u0020this\u0020module.",
            "url": "classes/Horde-Cli-Modular-Module.html#method_getOptionGroupOptions"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleProvider",
            "name": "Horde_Cli_Modular_ModuleProvider",
            "summary": "The\u0020Horde_Cli_Modular_ModuleProvider\u003A\u003A\u0020class\u0020provides\u0020access\u0020to\u0020a\u0020single\nmodule.",
            "url": "classes/Horde-Cli-Modular-ModuleProvider.html"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleProvider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Cli-Modular-ModuleProvider.html#method___construct"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleProvider\u003A\u003AgetModule\u0028\u0029",
            "name": "getModule",
            "summary": "Return\u0020the\u0020specified\u0020module.",
            "url": "classes/Horde-Cli-Modular-ModuleProvider.html#method_getModule"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleProvider\u003A\u003AcreateModule\u0028\u0029",
            "name": "createModule",
            "summary": "Create\u0020the\u0020specified\u0020module.",
            "url": "classes/Horde-Cli-Modular-ModuleProvider.html#method_createModule"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleProvider\u003A\u003A\u0024_prefix",
            "name": "_prefix",
            "summary": "Class\u0020prefix.",
            "url": "classes/Horde-Cli-Modular-ModuleProvider.html#property__prefix"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleProvider\u003A\u003A\u0024_dependencies",
            "name": "_dependencies",
            "summary": "Constructor\u0020argument\u0020for\u0020CLI\u0020modules.\u0020Likely\u0020to\u0020be\u0020a\u0020Horde_Injector\ninstance.",
            "url": "classes/Horde-Cli-Modular-ModuleProvider.html#property__dependencies"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleProvider\u003A\u003A\u0024_instances",
            "name": "_instances",
            "summary": "A\u0020cache\u0020for\u0020initialized\u0020module\u0020instances.",
            "url": "classes/Horde-Cli-Modular-ModuleProvider.html#property__instances"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Modules",
            "name": "Horde_Cli_Modular_Modules",
            "summary": "The\u0020Horde_Cli_Modular_Modules\u003A\u003A\u0020class\u0020handles\u0020a\u0020set\u0020of\u0020CLI\u0020modules.",
            "url": "classes/Horde-Cli-Modular-Modules.html"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Modules\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Cli-Modular-Modules.html#method___construct"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Modules\u003A\u003A_initModules\u0028\u0029",
            "name": "_initModules",
            "summary": "Initialize\u0020the\u0020list\u0020of\u0020module\u0020class\u0020names.",
            "url": "classes/Horde-Cli-Modular-Modules.html#method__initModules"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Modules\u003A\u003AlistModules\u0028\u0029",
            "name": "listModules",
            "summary": "List\u0020the\u0020available\u0020modules.",
            "url": "classes/Horde-Cli-Modular-Modules.html#method_listModules"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Modules\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/Horde-Cli-Modular-Modules.html#method_getIterator"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Modules\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "Implementation\u0020of\u0020Countable\u0020count\u0028\u0029\u0020method.\u0020Returns\u0020the\u0020number\u0020of\u0020modules.",
            "url": "classes/Horde-Cli-Modular-Modules.html#method_count"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Modules\u003A\u003A\u0024_parameters",
            "name": "_parameters",
            "summary": "Parameters.",
            "url": "classes/Horde-Cli-Modular-Modules.html#property__parameters"
        },                {
            "fqsen": "\\Horde_Cli_Modular_Modules\u003A\u003A\u0024_modules",
            "name": "_modules",
            "summary": "The\u0020available\u0020modules.",
            "url": "classes/Horde-Cli-Modular-Modules.html#property__modules"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleUsage",
            "name": "Horde_Cli_Modular_ModuleUsage",
            "summary": "The\u0020Horde_Cli_Modular_ModuleUsage\u0020interface\u0020extends\u0020the\nHorde_Cli_Modular_Module\u0020interface\u0020with\u0020new\u0020functionality.",
            "url": "classes/Horde-Cli-Modular-ModuleUsage.html"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleUsage\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Returns\u0020additional\u0020usage\u0020title\u0020for\u0020this\u0020module.",
            "url": "classes/Horde-Cli-Modular-ModuleUsage.html#method_getTitle"
        },                {
            "fqsen": "\\Horde_Cli_Modular_ModuleUsage\u003A\u003AgetUsage\u0028\u0029",
            "name": "getUsage",
            "summary": "Returns\u0020additional\u0020usage\u0020description\u0020for\u0020this\u0020module.",
            "url": "classes/Horde-Cli-Modular-ModuleUsage.html#method_getUsage"
        },                {
            "fqsen": "\\Horde_Cli_Modular",
            "name": "Horde_Cli_Modular",
            "summary": "Glue\u0020class\u0020for\u0020a\u0020modular\u0020CLI.",
            "url": "classes/Horde-Cli-Modular.html"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Cli-Modular.html#method___construct"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003AgetParserClass\u0028\u0029",
            "name": "getParserClass",
            "summary": "Return\u0020the\u0020class\u0020name\u0020for\u0020the\u0020parser\u0020that\u0020should\u0020be\u0020used.",
            "url": "classes/Horde-Cli-Modular.html#method_getParserClass"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003AgetUsage\u0028\u0029",
            "name": "getUsage",
            "summary": "Return\u0020the\u0020usage\u0020description\u0020for\u0020the\u0020help\u0020output\u0020of\u0020the\u0020parser.",
            "url": "classes/Horde-Cli-Modular.html#method_getUsage"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003AcreateParser\u0028\u0029",
            "name": "createParser",
            "summary": "Create\u0020the\u0020parser\u0020for\u0020command\u0020line\u0020arguments.",
            "url": "classes/Horde-Cli-Modular.html#method_createParser"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003AgetModules\u0028\u0029",
            "name": "getModules",
            "summary": "Return\u0020the\u0020module\u0020handler.",
            "url": "classes/Horde-Cli-Modular.html#method_getModules"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003A_createModules\u0028\u0029",
            "name": "_createModules",
            "summary": "Create\u0020the\u0020module\u0020handler.",
            "url": "classes/Horde-Cli-Modular.html#method__createModules"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003AgetProvider\u0028\u0029",
            "name": "getProvider",
            "summary": "Return\u0020the\u0020module\u0020provider.",
            "url": "classes/Horde-Cli-Modular.html#method_getProvider"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003A_createProvider\u0028\u0029",
            "name": "_createProvider",
            "summary": "Create\u0020the\u0020module\u0020provider.",
            "url": "classes/Horde-Cli-Modular.html#method__createProvider"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003A\u0024_parameters",
            "name": "_parameters",
            "summary": "Parameters.",
            "url": "classes/Horde-Cli-Modular.html#property__parameters"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003A\u0024_modules",
            "name": "_modules",
            "summary": "Handler\u0020for\u0020the\u0020list\u0020of\u0020modules.",
            "url": "classes/Horde-Cli-Modular.html#property__modules"
        },                {
            "fqsen": "\\Horde_Cli_Modular\u003A\u003A\u0024_provider",
            "name": "_provider",
            "summary": "Module\u0020provider.",
            "url": "classes/Horde-Cli-Modular.html#property__provider"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
