Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_ListHeaders_Base",
            "name": "Horde_ListHeaders_Base",
            "summary": "Object\u0020representation\u0020of\u0020a\u0020basic\u0020list\u0020header\u0020\u0028RFC\u00202369\u0029\u0020element.",
            "url": "classes/Horde-ListHeaders-Base.html"
        },                {
            "fqsen": "\\Horde_ListHeaders_Base\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-ListHeaders-Base.html#method___construct"
        },                {
            "fqsen": "\\Horde_ListHeaders_Base\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-ListHeaders-Base.html#method___get"
        },                {
            "fqsen": "\\Horde_ListHeaders_Base\u003A\u003A\u0024_comments",
            "name": "_comments",
            "summary": "Comments.",
            "url": "classes/Horde-ListHeaders-Base.html#property__comments"
        },                {
            "fqsen": "\\Horde_ListHeaders_Base\u003A\u003A\u0024_url",
            "name": "_url",
            "summary": "URL.",
            "url": "classes/Horde-ListHeaders-Base.html#property__url"
        },                {
            "fqsen": "\\Horde_ListHeaders_Id",
            "name": "Horde_ListHeaders_Id",
            "summary": "Object\u0020representation\u0020of\u0020a\u0020List\u002DID\u0020\u0028RFC\u00202919\u0029\u0020element.",
            "url": "classes/Horde-ListHeaders-Id.html"
        },                {
            "fqsen": "\\Horde_ListHeaders_Id\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-ListHeaders-Id.html#method___construct"
        },                {
            "fqsen": "\\Horde_ListHeaders_Id\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-ListHeaders-Id.html#method___get"
        },                {
            "fqsen": "\\Horde_ListHeaders_Id\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "List\u0020ID.",
            "url": "classes/Horde-ListHeaders-Id.html#property__id"
        },                {
            "fqsen": "\\Horde_ListHeaders_Id\u003A\u003A\u0024_label",
            "name": "_label",
            "summary": "List\u0020label.",
            "url": "classes/Horde-ListHeaders-Id.html#property__label"
        },                {
            "fqsen": "\\Horde_ListHeaders_NoPost",
            "name": "Horde_ListHeaders_NoPost",
            "summary": "Object\u0020representation\u0020of\u0020a\u0020basic\u0020list\u0020header\u0020\u0028RFC\u00202369\u0029\u0020element.",
            "url": "classes/Horde-ListHeaders-NoPost.html"
        },                {
            "fqsen": "\\Horde_ListHeaders_NoPost\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-ListHeaders-NoPost.html#method___construct"
        },                {
            "fqsen": "\\Horde_ListHeaders_NoPost\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-ListHeaders-NoPost.html#method___get"
        },                {
            "fqsen": "\\Horde_ListHeaders_Object",
            "name": "Horde_ListHeaders_Object",
            "summary": "Object\u0020representation\u0020of\u0020a\u0020list\u0020header\u0020element.",
            "url": "classes/Horde-ListHeaders-Object.html"
        },                {
            "fqsen": "\\Horde_ListHeaders_Translation",
            "name": "Horde_ListHeaders_Translation",
            "summary": "Horde_ListHeaders_Translation\u0020is\u0020the\u0020translation\u0020wrapper\u0020class\u0020for\nHorde_ListHeaders.",
            "url": "classes/Horde-ListHeaders-Translation.html"
        },                {
            "fqsen": "\\Horde_ListHeaders_Translation\u003A\u003A\u0024_domain",
            "name": "_domain",
            "summary": "The\u0020translation\u0020domain",
            "url": "classes/Horde-ListHeaders-Translation.html#property__domain"
        },                {
            "fqsen": "\\Horde_ListHeaders_Translation\u003A\u003A\u0024_pearDirectory",
            "name": "_pearDirectory",
            "summary": "The\u0020absolute\u0020PEAR\u0020path\u0020to\u0020the\u0020translations\u0020for\u0020the\u0020default\u0020gettext\u0020handler.",
            "url": "classes/Horde-ListHeaders-Translation.html#property__pearDirectory"
        },                {
            "fqsen": "\\Horde_ListHeaders",
            "name": "Horde_ListHeaders",
            "summary": "Class\u0020to\u0020parse\u0020List\u0020Header\u0020fields\u0020\u0028RFC\u00202369\/2919\u0029.",
            "url": "classes/Horde-ListHeaders.html"
        },                {
            "fqsen": "\\Horde_ListHeaders\u003A\u003Aheaders\u0028\u0029",
            "name": "headers",
            "summary": "Returns\u0020the\u0020list\u0020of\u0020valid\u0020mailing\u0020list\u0020headers.",
            "url": "classes/Horde-ListHeaders.html#method_headers"
        },                {
            "fqsen": "\\Horde_ListHeaders\u003A\u003AlistHeadersExist\u0028\u0029",
            "name": "listHeadersExist",
            "summary": "Do\u0020any\u0020mailing\u0020list\u0020headers\u0020exist\u003F",
            "url": "classes/Horde-ListHeaders.html#method_listHeadersExist"
        },                {
            "fqsen": "\\Horde_ListHeaders\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parse\u0020a\u0020list\u0020header.",
            "url": "classes/Horde-ListHeaders.html#method_parse"
        },                {
            "fqsen": "\\Horde_ListHeaders\u003A\u003A_parseBase\u0028\u0029",
            "name": "_parseBase",
            "summary": "Parse\u0020a\u0020base\u0020list\u0020header\u0020\u0028RFC\u00202369\u0029.",
            "url": "classes/Horde-ListHeaders.html#method__parseBase"
        },                {
            "fqsen": "\\Horde_ListHeaders\u003A\u003A_parseListId\u0028\u0029",
            "name": "_parseListId",
            "summary": "Parse\u0020a\u0020List\u002DID\u0020\u0028RFC\u00202919\u0029.",
            "url": "classes/Horde-ListHeaders.html#method__parseListId"
        },                {
            "fqsen": "\\Horde_ListHeaders\u003A\u003A_parseListPost\u0028\u0029",
            "name": "_parseListPost",
            "summary": "Parse\u0020a\u0020List\u002DPost\u0020header\u0020\u0028RFC\u00202369\u0020\u005B3.4\u005D\u0029.",
            "url": "classes/Horde-ListHeaders.html#method__parseListPost"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
