Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Stream_Filter_Bin2hex",
            "name": "Horde_Stream_Filter_Bin2hex",
            "summary": "Stream\u0020filter\u0020class\u0020to\u0020convert\u0020binary\u0020data\u0020into\u0020hexadecimal.",
            "url": "classes/Horde-Stream-Filter-Bin2hex.html"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Bin2hex\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Bin2hex.html#method_filter"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Crc32",
            "name": "Horde_Stream_Filter_Crc32",
            "summary": "Stream\u0020filter\u0020class\u0020to\u0020compute\u0020the\u0020CRC32\u0020value\u0020of\u0020a\u0020string.",
            "url": "classes/Horde-Stream-Filter-Crc32.html"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Crc32\u003A\u003AonCreate\u0028\u0029",
            "name": "onCreate",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Crc32.html#method_onCreate"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Crc32\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Crc32.html#method_filter"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Crc32\u003A\u003A_crc32Combine\u0028\u0029",
            "name": "_crc32Combine",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Crc32.html#method__crc32Combine"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Crc32\u003A\u003A_gf2MatrixSquare\u0028\u0029",
            "name": "_gf2MatrixSquare",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Crc32.html#method__gf2MatrixSquare"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Crc32\u003A\u003A_gf2MatrixTimes\u0028\u0029",
            "name": "_gf2MatrixTimes",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Crc32.html#method__gf2MatrixTimes"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Eol",
            "name": "Horde_Stream_Filter_Eol",
            "summary": "Stream\u0020filter\u0020class\u0020to\u0020convert\u0020EOL\u0020characters.",
            "url": "classes/Horde-Stream-Filter-Eol.html"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Eol\u003A\u003AonCreate\u0028\u0029",
            "name": "onCreate",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Eol.html#method_onCreate"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Eol\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Eol.html#method_filter"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Eol\u003A\u003A\u0024_replace",
            "name": "_replace",
            "summary": "Replacement\u0020data",
            "url": "classes/Horde-Stream-Filter-Eol.html#property__replace"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Eol\u003A\u003A\u0024_search",
            "name": "_search",
            "summary": "Search\u0020array.",
            "url": "classes/Horde-Stream-Filter-Eol.html#property__search"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Eol\u003A\u003A\u0024_split",
            "name": "_split",
            "summary": "First\u0020character\u0020of\u0020a\u0020multi\u002Dcharacter\u0020EOL.",
            "url": "classes/Horde-Stream-Filter-Eol.html#property__split"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Htmlspecialchars",
            "name": "Horde_Stream_Filter_Htmlspecialchars",
            "summary": "Stream\u0020filter\u0020class\u0020to\u0020pass\u0020data\u0020to\u0020htmlspecialchars\u0028\u0029\u0020in\u0020chunks.",
            "url": "classes/Horde-Stream-Filter-Htmlspecialchars.html"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Htmlspecialchars\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Htmlspecialchars.html#method_filter"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Null",
            "name": "Horde_Stream_Filter_Null",
            "summary": "Stream\u0020filter\u0020class\u0020to\u0020remove\u0020null\u0020\u0028\\0\u0029\u0020values.",
            "url": "classes/Horde-Stream-Filter-Null.html"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Null\u003A\u003AonCreate\u0028\u0029",
            "name": "onCreate",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Null.html#method_onCreate"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Null\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "",
            "url": "classes/Horde-Stream-Filter-Null.html#method_filter"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Null\u003A\u003A\u0024_search",
            "name": "_search",
            "summary": "Search\u0020array.",
            "url": "classes/Horde-Stream-Filter-Null.html#property__search"
        },                {
            "fqsen": "\\Horde_Stream_Filter_Null\u003A\u003A\u0024_replace",
            "name": "_replace",
            "summary": "Replacement\u0020data",
            "url": "classes/Horde-Stream-Filter-Null.html#property__replace"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
