Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Smtp_Exception_Recipients",
            "name": "Horde_Smtp_Exception_Recipients",
            "summary": "Extended\u0020exception\u0020class\u0020that\u0020provides\u0020information\u0020on\u0020recipient\u0020addresess\nthat\u0020failed.",
            "url": "classes/Horde-Smtp-Exception-Recipients.html"
        },                {
            "fqsen": "\\Horde_Smtp_Exception_Recipients\u003A\u003A\u0024recipients",
            "name": "recipients",
            "summary": "Failed\u0020recipient\u0020list.",
            "url": "classes/Horde-Smtp-Exception-Recipients.html#property_recipients"
        },                {
            "fqsen": "\\Horde_Smtp_Exception",
            "name": "Horde_Smtp_Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020Horde_Smtp\u0020package.",
            "url": "classes/Horde-Smtp-Exception.html"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Smtp-Exception.html#method___construct"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#method___get"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003AsetSmtpCode\u0028\u0029",
            "name": "setSmtpCode",
            "summary": "Set\u0020the\u0020SMTP\u0020reply\u0020code.",
            "url": "classes/Horde-Smtp-Exception.html#method_setSmtpCode"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003AgetSmtpCode\u0028\u0029",
            "name": "getSmtpCode",
            "summary": "Get\u0020the\u0020SMTP\u0020reply\u0020code.",
            "url": "classes/Horde-Smtp-Exception.html#method_getSmtpCode"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003AsetEnhancedSmtpCode\u0028\u0029",
            "name": "setEnhancedSmtpCode",
            "summary": "Set\u0020SMTP\u0020Enhanced\u0020Mail\u0020System\u0020Status\u0020Code\u0020\u0028RFC\u00203463\u0029.",
            "url": "classes/Horde-Smtp-Exception.html#method_setEnhancedSmtpCode"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003AgetEnhancedSmtpCode\u0028\u0029",
            "name": "getEnhancedSmtpCode",
            "summary": "Get\u0020SMTP\u0020Enhanced\u0020Mail\u0020System\u0020Status\u0020Code\u0020\u0028RFC\u00203463\u0029.",
            "url": "classes/Horde-Smtp-Exception.html#method_getEnhancedSmtpCode"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003AUNSPECIFIED",
            "name": "UNSPECIFIED",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_UNSPECIFIED"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ASERVER_CONNECT",
            "name": "SERVER_CONNECT",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_SERVER_CONNECT"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ASERVER_READERROR",
            "name": "SERVER_READERROR",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_SERVER_READERROR"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ASERVER_WRITEERROR",
            "name": "SERVER_WRITEERROR",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_SERVER_WRITEERROR"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ADISCONNECT",
            "name": "DISCONNECT",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_DISCONNECT"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003AMAILBOX_UNAVAILABLE",
            "name": "MAILBOX_UNAVAILABLE",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_MAILBOX_UNAVAILABLE"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003AINSUFFICIENT_STORAGE",
            "name": "INSUFFICIENT_STORAGE",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_INSUFFICIENT_STORAGE"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003AUNKNOWN_LOCAL_USER",
            "name": "UNKNOWN_LOCAL_USER",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_UNKNOWN_LOCAL_USER"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003AOVERQUOTA",
            "name": "OVERQUOTA",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_OVERQUOTA"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_SYNTAX",
            "name": "CATEGORY_SYNTAX",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_SYNTAX"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_INFORMATIONAL",
            "name": "CATEGORY_INFORMATIONAL",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_INFORMATIONAL"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_CONNECTIONS",
            "name": "CATEGORY_CONNECTIONS",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_CONNECTIONS"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_MAILSYSTEM",
            "name": "CATEGORY_MAILSYSTEM",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_MAILSYSTEM"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_ADDRESS",
            "name": "CATEGORY_ADDRESS",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_ADDRESS"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_MAILBOX",
            "name": "CATEGORY_MAILBOX",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_MAILBOX"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_NETWORK",
            "name": "CATEGORY_NETWORK",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_NETWORK"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_DELIVERY",
            "name": "CATEGORY_DELIVERY",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_DELIVERY"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_CONTENT",
            "name": "CATEGORY_CONTENT",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_CONTENT"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ACATEGORY_SECURITY",
            "name": "CATEGORY_SECURITY",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_CATEGORY_SECURITY"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ALOGIN_TLSFAILURE",
            "name": "LOGIN_TLSFAILURE",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_LOGIN_TLSFAILURE"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ALOGIN_AUTHENTICATIONFAILED",
            "name": "LOGIN_AUTHENTICATIONFAILED",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_LOGIN_AUTHENTICATIONFAILED"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ALOGIN_REQUIREAUTHENTICATION",
            "name": "LOGIN_REQUIREAUTHENTICATION",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_LOGIN_REQUIREAUTHENTICATION"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003ALOGIN_MISSINGEXTENSION",
            "name": "LOGIN_MISSINGEXTENSION",
            "summary": "",
            "url": "classes/Horde-Smtp-Exception.html#constant_LOGIN_MISSINGEXTENSION"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003A\u0024_enhancedcode",
            "name": "_enhancedcode",
            "summary": "SMTP\u0020Enhanced\u0020Mail\u0020System\u0020Status\u0020Code\u0020\u0028see\u0020RFC\u00203463\u0029.",
            "url": "classes/Horde-Smtp-Exception.html#property__enhancedcode"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003A\u0024_rawmsg",
            "name": "_rawmsg",
            "summary": "Raw\u0020error\u0020message\u0020\u0028in\u0020English\u0029.",
            "url": "classes/Horde-Smtp-Exception.html#property__rawmsg"
        },                {
            "fqsen": "\\Horde_Smtp_Exception\u003A\u003A\u0024_smtpcode",
            "name": "_smtpcode",
            "summary": "SMTP\u0020reply\u0020code.",
            "url": "classes/Horde-Smtp-Exception.html#property__smtpcode"
        },                {
            "fqsen": "\\Horde_Smtp_Filter_Body",
            "name": "Horde_Smtp_Filter_Body",
            "summary": "Stream\u0020filter\u0020to\u0020determine\u0020whether\u0020body\u0020needs\u0020to\u0020be\u0020sent\u0020as\u00208\u002Dbit\n\u0028STD\u002071\/RFC\u00206152\u0029\u0020or\u0020binary\u0020\u0028RFC\u00203030\u0029.",
            "url": "classes/Horde-Smtp-Filter-Body.html"
        },                {
            "fqsen": "\\Horde_Smtp_Filter_Body\u003A\u003AonCreate\u0028\u0029",
            "name": "onCreate",
            "summary": "",
            "url": "classes/Horde-Smtp-Filter-Body.html#method_onCreate"
        },                {
            "fqsen": "\\Horde_Smtp_Filter_Body\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "",
            "url": "classes/Horde-Smtp-Filter-Body.html#method_filter"
        },                {
            "fqsen": "\\Horde_Smtp_Filter_Body\u003A\u003A\u0024_crlf",
            "name": "_crlf",
            "summary": "Non\u0020CR\/LF\u0020characters.",
            "url": "classes/Horde-Smtp-Filter-Body.html#property__crlf"
        },                {
            "fqsen": "\\Horde_Smtp_Filter_Data",
            "name": "Horde_Smtp_Filter_Data",
            "summary": "Stream\u0020filter\u0020to\u0020escape\u0020output\u0020to\u0020the\u0020SMTP\u0020DATA\u0020command\u0020\u0028RFC\u00205321\n\u005B4.1.1.4\u005D\u0029.",
            "url": "classes/Horde-Smtp-Filter-Data.html"
        },                {
            "fqsen": "\\Horde_Smtp_Filter_Data\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "",
            "url": "classes/Horde-Smtp-Filter-Data.html#method_filter"
        },                {
            "fqsen": "\\Horde_Smtp_Filter_Data\u003A\u003A\u0024_last",
            "name": "_last",
            "summary": "Last\u0020character.",
            "url": "classes/Horde-Smtp-Filter-Data.html#property__last"
        },                {
            "fqsen": "\\Horde_Smtp_Lmtp",
            "name": "Horde_Smtp_Lmtp",
            "summary": "An\u0020interface\u0020to\u0020an\u0020LMTP\u0020server\u0020\u0028RFC\u00202033\u0029.",
            "url": "classes/Horde-Smtp-Lmtp.html"
        },                {
            "fqsen": "\\Horde_Smtp_Lmtp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Smtp-Lmtp.html#method___construct"
        },                {
            "fqsen": "\\Horde_Smtp_Lmtp\u003A\u003A_processData\u0028\u0029",
            "name": "_processData",
            "summary": "Process\u0020the\u0020return\u0020from\u0020the\u0020DATA\u0020command.",
            "url": "classes/Horde-Smtp-Lmtp.html#method__processData"
        },                {
            "fqsen": "\\Horde_Smtp_Lmtp\u003A\u003A\u0024_ehlo",
            "name": "_ehlo",
            "summary": "LMTP\u0020only\u0020supports\u0020LHLO\u0020hello\u0020command\u0020\u0028RFC\u00202033\u0020\u005B4.1\u005D\u0029,\u0020not\u0020EHLO.",
            "url": "classes/Horde-Smtp-Lmtp.html#property__ehlo"
        },                {
            "fqsen": "\\Horde_Smtp_Lmtp\u003A\u003A\u0024_requiredExts",
            "name": "_requiredExts",
            "summary": "These\u0020extensions\u0020are\u0020required\u0020for\u0020LMTP\u0020\u0028RFC\u00202033\u0020\u005B5\u005D\u0029.",
            "url": "classes/Horde-Smtp-Lmtp.html#property__requiredExts"
        },                {
            "fqsen": "\\Horde_Smtp_Password_Xoauth2",
            "name": "Horde_Smtp_Password_Xoauth2",
            "summary": "Generates\u0020an\u0020OAuth\u00202.0\u0020authentication\u0020token\u0020as\u0020used\u0020in\u0020the\u0020Gmail\u0020XOAUTH2\nauthentication\u0020mechanism.",
            "url": "classes/Horde-Smtp-Password-Xoauth2.html"
        },                {
            "fqsen": "\\Horde_Smtp_Password_Xoauth2\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Smtp-Password-Xoauth2.html#method___construct"
        },                {
            "fqsen": "\\Horde_Smtp_Password_Xoauth2\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Return\u0020the\u0020password\u0020to\u0020use\u0020for\u0020the\u0020server\u0020connection.",
            "url": "classes/Horde-Smtp-Password-Xoauth2.html#method_getPassword"
        },                {
            "fqsen": "\\Horde_Smtp_Password_Xoauth2\u003A\u003A\u0024access_token",
            "name": "access_token",
            "summary": "Access\u0020token.",
            "url": "classes/Horde-Smtp-Password-Xoauth2.html#property_access_token"
        },                {
            "fqsen": "\\Horde_Smtp_Password_Xoauth2\u003A\u003A\u0024username",
            "name": "username",
            "summary": "Username.",
            "url": "classes/Horde-Smtp-Password-Xoauth2.html#property_username"
        },                {
            "fqsen": "\\Horde_Smtp_Password",
            "name": "Horde_Smtp_Password",
            "summary": "Interface\u0020to\u0020allow\u0020dynamic\u0020generation\u0020of\u0020SMTP\u0020password.",
            "url": "classes/Horde-Smtp-Password.html"
        },                {
            "fqsen": "\\Horde_Smtp_Password\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Return\u0020the\u0020password\u0020to\u0020use\u0020for\u0020the\u0020SMTP\u0020connection.",
            "url": "classes/Horde-Smtp-Password.html#method_getPassword"
        },                {
            "fqsen": "\\Horde_Smtp_Translation",
            "name": "Horde_Smtp_Translation",
            "summary": "Translation\u0020wrapper\u0020class\u0020for\u0020Horde_Smtp.",
            "url": "classes/Horde-Smtp-Translation.html"
        },                {
            "fqsen": "\\Horde_Smtp_Translation\u003A\u003A\u0024_domain",
            "name": "_domain",
            "summary": "The\u0020translation\u0020domain",
            "url": "classes/Horde-Smtp-Translation.html#property__domain"
        },                {
            "fqsen": "\\Horde_Smtp_Translation\u003A\u003A\u0024_pearDirectory",
            "name": "_pearDirectory",
            "summary": "The\u0020absolute\u0020PEAR\u0020path\u0020to\u0020the\u0020translations\u0020for\u0020the\u0020default\u0020gettext\u0020handler.",
            "url": "classes/Horde-Smtp-Translation.html#property__pearDirectory"
        },                {
            "fqsen": "\\Horde_Smtp",
            "name": "Horde_Smtp",
            "summary": "An\u0020interface\u0020to\u0020an\u0020SMTP\u0020server\u0020\u0028RFC\u00205321\u0029.",
            "url": "classes/Horde-Smtp.html"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Smtp.html#method___construct"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A_getEncryptKey\u0028\u0029",
            "name": "_getEncryptKey",
            "summary": "Get\u0020encryption\u0020key.",
            "url": "classes/Horde-Smtp.html#method__getEncryptKey"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A_initOb\u0028\u0029",
            "name": "_initOb",
            "summary": "Do\u0020initialization\u0020tasks.",
            "url": "classes/Horde-Smtp.html#method__initOb"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003Ashutdown\u0028\u0029",
            "name": "shutdown",
            "summary": "Shutdown\u0020actions.",
            "url": "classes/Horde-Smtp.html#method_shutdown"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "This\u0020object\u0020can\u0020not\u0020be\u0020cloned.",
            "url": "classes/Horde-Smtp.html#method___clone"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/Horde-Smtp.html#method_serialize"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "",
            "url": "classes/Horde-Smtp.html#method_unserialize"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-Smtp.html#method___get"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003AgetParam\u0028\u0029",
            "name": "getParam",
            "summary": "Returns\u0020a\u0020value\u0020from\u0020the\u0020internal\u0020params\u0020array.",
            "url": "classes/Horde-Smtp.html#method_getParam"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003AsetParam\u0028\u0029",
            "name": "setParam",
            "summary": "Sets\u0020a\u0020configuration\u0020parameter\u0020value.",
            "url": "classes/Horde-Smtp.html#method_setParam"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003AqueryExtension\u0028\u0029",
            "name": "queryExtension",
            "summary": "Returns\u0020whether\u0020the\u0020SMTP\u0020server\u0020supports\u0020the\u0020given\u0020extension.",
            "url": "classes/Horde-Smtp.html#method_queryExtension"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003AisSecureConnection\u0028\u0029",
            "name": "isSecureConnection",
            "summary": "Display\u0020if\u0020connection\u0020to\u0020the\u0020server\u0020has\u0020been\u0020secured\u0020via\u0020TLS\u0020or\u0020SSL.",
            "url": "classes/Horde-Smtp.html#method_isSecureConnection"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Connect\/login\u0020to\u0020the\u0020SMTP\u0020server.",
            "url": "classes/Horde-Smtp.html#method_login"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Logout\u0020from\u0020the\u0020SMTP\u0020server.",
            "url": "classes/Horde-Smtp.html#method_logout"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020a\u0020message.",
            "url": "classes/Horde-Smtp.html#method_send"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003AresetCmd\u0028\u0029",
            "name": "resetCmd",
            "summary": "Send\u0020a\u0020reset\u0020command.",
            "url": "classes/Horde-Smtp.html#method_resetCmd"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003Anoop\u0028\u0029",
            "name": "noop",
            "summary": "Send\u0020a\u0020NOOP\u0020command.",
            "url": "classes/Horde-Smtp.html#method_noop"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003AprocessQueue\u0028\u0029",
            "name": "processQueue",
            "summary": "Send\u0020request\u0020to\u0020process\u0020the\u0020remote\u0020queue.",
            "url": "classes/Horde-Smtp.html#method_processQueue"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A_hello\u0028\u0029",
            "name": "_hello",
            "summary": "Send\u0020\u0022Hello\u0022\u0020command\u0020to\u0020the\u0020server.",
            "url": "classes/Horde-Smtp.html#method__hello"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A_startTls\u0028\u0029",
            "name": "_startTls",
            "summary": "Starts\u0020the\u0020TLS\u0020connection\u0020to\u0020the\u0020server,\u0020if\u0020necessary.\u0020\u0020See\u0020RFC\u00203207.",
            "url": "classes/Horde-Smtp.html#method__startTls"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A_auth\u0028\u0029",
            "name": "_auth",
            "summary": "Authenticate\u0020user\u0020to\u0020server\u0020for\u0020a\u0020given\u0020method.",
            "url": "classes/Horde-Smtp.html#method__auth"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A_getResponse\u0028\u0029",
            "name": "_getResponse",
            "summary": "Gets\u0020a\u0020line\u0020from\u0020the\u0020incoming\u0020stream\u0020and\u0020parses\u0020it.",
            "url": "classes/Horde-Smtp.html#method__getResponse"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A_processData\u0028\u0029",
            "name": "_processData",
            "summary": "Process\u0020the\u0020return\u0020from\u0020the\u0020DATA\u0020command.",
            "url": "classes/Horde-Smtp.html#method__processData"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A_getHostname\u0028\u0029",
            "name": "_getHostname",
            "summary": "Return\u0020the\u0020local\u0020hostname.",
            "url": "classes/Horde-Smtp.html#method__getHostname"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003ACHUNK_DEFAULT",
            "name": "CHUNK_DEFAULT",
            "summary": "",
            "url": "classes/Horde-Smtp.html#constant_CHUNK_DEFAULT"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A\u0024_connection",
            "name": "_connection",
            "summary": "Connection\u0020to\u0020the\u0020SMTP\u0020server.",
            "url": "classes/Horde-Smtp.html#property__connection"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A\u0024_debug",
            "name": "_debug",
            "summary": "The\u0020debug\u0020object.",
            "url": "classes/Horde-Smtp.html#property__debug"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A\u0024_ehlo",
            "name": "_ehlo",
            "summary": "The\u0020hello\u0020command\u0020to\u0020use\u0020for\u0020extended\u0020SMTP\u0020support.",
            "url": "classes/Horde-Smtp.html#property__ehlo"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A\u0024_extensions",
            "name": "_extensions",
            "summary": "The\u0020list\u0020of\u0020ESMTP\u0020extensions.",
            "url": "classes/Horde-Smtp.html#property__extensions"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "Hash\u0020containing\u0020connection\u0020parameters.",
            "url": "classes/Horde-Smtp.html#property__params"
        },                {
            "fqsen": "\\Horde_Smtp\u003A\u003A\u0024_requiredExts",
            "name": "_requiredExts",
            "summary": "List\u0020of\u0020required\u0020ESMTP\u0020extensions.",
            "url": "classes/Horde-Smtp.html#property__requiredExts"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
