Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_CssMinify_CssParser",
            "name": "Horde_CssMinify_CssParser",
            "summary": "CSS\u0020minification\u0020driver\u0020implemented\u0020by\u0020using\u0020the\u0020Horde\/Css_Parse\u0020library.",
            "url": "classes/Horde-CssMinify-CssParser.html"
        },                {
            "fqsen": "\\Horde_CssMinify_CssParser\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "Set\u0020minification\u0020options.",
            "url": "classes/Horde-CssMinify-CssParser.html#method_setOptions"
        },                {
            "fqsen": "\\Horde_CssMinify_CssParser\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "Return\u0020the\u0020minified\u0020CSS.",
            "url": "classes/Horde-CssMinify-CssParser.html#method_minify"
        },                {
            "fqsen": "\\Horde_CssMinify_CssParser\u003A\u003A_minify\u0028\u0029",
            "name": "_minify",
            "summary": "",
            "url": "classes/Horde-CssMinify-CssParser.html#method__minify"
        },                {
            "fqsen": "\\Horde_CssMinify_Exception",
            "name": "Horde_CssMinify_Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020Horde_CssMinify\u0020package.",
            "url": "classes/Horde-CssMinify-Exception.html"
        },                {
            "fqsen": "\\Horde_CssMinify",
            "name": "Horde_CssMinify",
            "summary": "Abstract\u0020base\u0020class\u0020for\u0020implementing\u0020a\u0020CSS\u0020minification\u0020driver.",
            "url": "classes/Horde-CssMinify.html"
        },                {
            "fqsen": "\\Horde_CssMinify\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-CssMinify.html#method___construct"
        },                {
            "fqsen": "\\Horde_CssMinify\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-CssMinify.html#method___toString"
        },                {
            "fqsen": "\\Horde_CssMinify\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "Set\u0020minification\u0020options.",
            "url": "classes/Horde-CssMinify.html#method_setOptions"
        },                {
            "fqsen": "\\Horde_CssMinify\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "Return\u0020the\u0020minified\u0020CSS.",
            "url": "classes/Horde-CssMinify.html#method_minify"
        },                {
            "fqsen": "\\Horde_CssMinify\u003A\u003A\u0024_data",
            "name": "_data",
            "summary": "Original\u0020CSS\u0020data.",
            "url": "classes/Horde-CssMinify.html#property__data"
        },                {
            "fqsen": "\\Horde_CssMinify\u003A\u003A\u0024_opts",
            "name": "_opts",
            "summary": "Minification\u0020options.",
            "url": "classes/Horde-CssMinify.html#property__opts"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
