Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Push_Cli",
            "name": "Horde_Push_Cli",
            "summary": "Command\u0020line\u0020tool\u0020for\u0020pushing\u0020content\u0020to\u0020social\u0020networks.",
            "url": "classes/Horde-Push-Cli.html"
        },                {
            "fqsen": "\\Horde_Push_Cli\u003A\u003Amain\u0028\u0029",
            "name": "main",
            "summary": "The\u0020main\u0020entry\u0020point\u0020for\u0020the\u0020application.",
            "url": "classes/Horde-Push-Cli.html#method_main"
        },                {
            "fqsen": "\\Horde_Push_Exception",
            "name": "Horde_Push_Exception",
            "summary": "The\u0020exception\u0020specific\u0020to\u0020Horde_Push.",
            "url": "classes/Horde-Push-Exception.html"
        },                {
            "fqsen": "\\Horde_Push_Factory_Push",
            "name": "Horde_Push_Factory_Push",
            "summary": "Creates\u0020the\u0020Horde_Push\u0020content\u0020object.",
            "url": "classes/Horde-Push-Factory-Push.html"
        },                {
            "fqsen": "\\Horde_Push_Factory_Push\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020the\u0020Horde_Push\u0020content\u0020element.",
            "url": "classes/Horde-Push-Factory-Push.html#method_create"
        },                {
            "fqsen": "\\Horde_Push_Factory_Push\u003A\u003A_parseArgument\u0028\u0029",
            "name": "_parseArgument",
            "summary": "Parse\u0020an\u0020argument\u0020into\u0020a\u0020Horde_Push\u0020element.",
            "url": "classes/Horde-Push-Factory-Push.html#method__parseArgument"
        },                {
            "fqsen": "\\Horde_Push_Factory_Push\u003A\u003A_parseKolab\u0028\u0029",
            "name": "_parseKolab",
            "summary": "Parse\u0020the\u0020content\u0020of\u0020a\u0020Kolab\u0020object\u0020into\u0020a\u0020Horde_Push\u0020element.",
            "url": "classes/Horde-Push-Factory-Push.html#method__parseKolab"
        },                {
            "fqsen": "\\Horde_Push_Factory_Push\u003A\u003A_parsePhp\u0028\u0029",
            "name": "_parsePhp",
            "summary": "Parse\u0020the\u0020content\u0020of\u0020a\u0020PHP\u0020file\u0020into\u0020a\u0020Horde_Push\u0020element.",
            "url": "classes/Horde-Push-Factory-Push.html#method__parsePhp"
        },                {
            "fqsen": "\\Horde_Push_Factory_Push\u003A\u003A_parseYaml\u0028\u0029",
            "name": "_parseYaml",
            "summary": "Parse\u0020the\u0020content\u0020of\u0020a\u0020YAML\u0020file\u0020into\u0020a\u0020Horde_Push\u0020element.",
            "url": "classes/Horde-Push-Factory-Push.html#method__parseYaml"
        },                {
            "fqsen": "\\Horde_Push_Factory_Push\u003A\u003A_createFromData\u0028\u0029",
            "name": "_createFromData",
            "summary": "Generate\u0020a\u0020Horde_Push\u0020element\u0020based\u0020on\u0020the\u0020provided\u0020data.",
            "url": "classes/Horde-Push-Factory-Push.html#method__createFromData"
        },                {
            "fqsen": "\\Horde_Push_Factory_Recipients",
            "name": "Horde_Push_Factory_Recipients",
            "summary": "Creates\u0020the\u0020Horde_Push\u0020recipients.",
            "url": "classes/Horde-Push-Factory-Recipients.html"
        },                {
            "fqsen": "\\Horde_Push_Factory_Recipients\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020the\u0020recipient\u0020list.",
            "url": "classes/Horde-Push-Factory-Recipients.html#method_create"
        },                {
            "fqsen": "\\Horde_Push_Factory_Recipients\u003A\u003A_createTwitter\u0028\u0029",
            "name": "_createTwitter",
            "summary": "Create\u0020the\u0020twitter\u0020recipient.",
            "url": "classes/Horde-Push-Factory-Recipients.html#method__createTwitter"
        },                {
            "fqsen": "\\Horde_Push_Factory_Recipients\u003A\u003A_createFacebook\u0028\u0029",
            "name": "_createFacebook",
            "summary": "Create\u0020the\u0020facebook\u0020recipient.",
            "url": "classes/Horde-Push-Factory-Recipients.html#method__createFacebook"
        },                {
            "fqsen": "\\Horde_Push_Factory_Recipients\u003A\u003A_createBlogger\u0028\u0029",
            "name": "_createBlogger",
            "summary": "Create\u0020the\u0020blogger\u0020recipient.",
            "url": "classes/Horde-Push-Factory-Recipients.html#method__createBlogger"
        },                {
            "fqsen": "\\Horde_Push_Factory_Recipients\u003A\u003A_createMail\u0028\u0029",
            "name": "_createMail",
            "summary": "Create\u0020the\u0020mail\u0020recipient\u0028s\u0029.",
            "url": "classes/Horde-Push-Factory-Recipients.html#method__createMail"
        },                {
            "fqsen": "\\Horde_Push_Factory_Recipients\u003A\u003A_createHttpClient\u0028\u0029",
            "name": "_createHttpClient",
            "summary": "Create\u0020a\u0020HTTP\u0020client.",
            "url": "classes/Horde-Push-Factory-Recipients.html#method__createHttpClient"
        },                {
            "fqsen": "\\Horde_Push_Factory_Recipients\u003A\u003A_createControllerRequest\u0028\u0029",
            "name": "_createControllerRequest",
            "summary": "Create\u0020a\u0020controller\u0020request.",
            "url": "classes/Horde-Push-Factory-Recipients.html#method__createControllerRequest"
        },                {
            "fqsen": "\\Horde_Push_Factory_Recipients\u003A\u003A_createMailTransport\u0028\u0029",
            "name": "_createMailTransport",
            "summary": "Create\u0020a\u0020mail\u0020transport.",
            "url": "classes/Horde-Push-Factory-Recipients.html#method__createMailTransport"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Base",
            "name": "Horde_Push_Recipient_Base",
            "summary": "The\u0020base\u0020recipient\u0020implementation.",
            "url": "classes/Horde-Push-Recipient-Base.html"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Base\u003A\u003AsetAcl\u0028\u0029",
            "name": "setAcl",
            "summary": "Set\u0020the\u0020ACL\u0020for\u0020this\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Base.html#method_setAcl"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Base\u003A\u003AgetAcl\u0028\u0029",
            "name": "getAcl",
            "summary": "Retrieve\u0020the\u0020ACL\u0020setting\u0020for\u0020this\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Base.html#method_getAcl"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Base\u003A\u003A\u0024_acl",
            "name": "_acl",
            "summary": "The\u0020ACL\u0020for\u0020this\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Base.html#property__acl"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Blogger",
            "name": "Horde_Push_Recipient_Blogger",
            "summary": "Blogger.com\u0020as\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Blogger.html"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Blogger\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Push-Recipient-Blogger.html#method___construct"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Blogger\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "Push\u0020content\u0020to\u0020the\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Blogger.html#method_push"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Blogger\u003A\u003A\u0024_client",
            "name": "_client",
            "summary": "The\u0020HTTP\u0020client.",
            "url": "classes/Horde-Push-Recipient-Blogger.html#property__client"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Blogger\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "The\u0020connection\u0020details\u0020for\u0020blogger.com",
            "url": "classes/Horde-Push-Recipient-Blogger.html#property__params"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Facebook",
            "name": "Horde_Push_Recipient_Facebook",
            "summary": "Facebook\u0020as\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Facebook.html"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Facebook\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Push-Recipient-Facebook.html#method___construct"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Facebook\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "Push\u0020content\u0020to\u0020the\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Facebook.html#method_push"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Facebook\u003A\u003AgetAcl\u0028\u0029",
            "name": "getAcl",
            "summary": "Retrieve\u0020the\u0020ACL\u0020setting\u0020for\u0020this\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Facebook.html#method_getAcl"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Facebook\u003A\u003A\u0024_facebook",
            "name": "_facebook",
            "summary": "The\u0020facebook\u0020client.",
            "url": "classes/Horde-Push-Recipient-Facebook.html#property__facebook"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Facebook\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "The\u0020configuration\u0020for\u0020this\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Facebook.html#property__params"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Mail",
            "name": "Horde_Push_Recipient_Mail",
            "summary": "E\u002Dmail\u0020recipients.",
            "url": "classes/Horde-Push-Recipient-Mail.html"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Mail\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Push-Recipient-Mail.html#method___construct"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Mail\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "Push\u0020content\u0020to\u0020the\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Mail.html#method_push"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Mail\u003A\u003A\u0024_mail",
            "name": "_mail",
            "summary": "The\u0020mail\u0020transport.",
            "url": "classes/Horde-Push-Recipient-Mail.html#property__mail"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Mail\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "Mail\u0020parameters.",
            "url": "classes/Horde-Push-Recipient-Mail.html#property__params"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Mock",
            "name": "Horde_Push_Recipient_Mock",
            "summary": "A\u0020mock\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Mock.html"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Mock\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "Push\u0020content\u0020to\u0020the\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Mock.html#method_push"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Mock\u003A\u003A\u0024pushed",
            "name": "pushed",
            "summary": "Pushed\u0020content\u0020elements.",
            "url": "classes/Horde-Push-Recipient-Mock.html#property_pushed"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Twitter",
            "name": "Horde_Push_Recipient_Twitter",
            "summary": "Twitter\u0020as\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Twitter.html"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Twitter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Push-Recipient-Twitter.html#method___construct"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Twitter\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "Push\u0020content\u0020to\u0020the\u0020recipient.",
            "url": "classes/Horde-Push-Recipient-Twitter.html#method_push"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Twitter\u003A\u003A\u0024_twitter",
            "name": "_twitter",
            "summary": "The\u0020twitter\u0020client.",
            "url": "classes/Horde-Push-Recipient-Twitter.html#property__twitter"
        },                {
            "fqsen": "\\Horde_Push_Recipient_Twitter\u003A\u003A\u0024_client",
            "name": "_client",
            "summary": "A\u0020HTTP\u0020client.",
            "url": "classes/Horde-Push-Recipient-Twitter.html#property__client"
        },                {
            "fqsen": "\\Horde_Push_Recipient",
            "name": "Horde_Push_Recipient",
            "summary": "This\u0020interface\u0020describes\u0020content\u0020recipients.",
            "url": "classes/Horde-Push-Recipient.html"
        },                {
            "fqsen": "\\Horde_Push_Recipient\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "Push\u0020content\u0020to\u0020the\u0020recipient.",
            "url": "classes/Horde-Push-Recipient.html#method_push"
        },                {
            "fqsen": "\\Horde_Push_Translation",
            "name": "Horde_Push_Translation",
            "summary": "Horde_Push_Translation\u0020is\u0020the\u0020translation\u0020wrapper\u0020class\u0020for\u0020Horde_Push.",
            "url": "classes/Horde-Push-Translation.html"
        },                {
            "fqsen": "\\Horde_Push_Translation\u003A\u003A\u0024_domain",
            "name": "_domain",
            "summary": "The\u0020translation\u0020domain",
            "url": "classes/Horde-Push-Translation.html#property__domain"
        },                {
            "fqsen": "\\Horde_Push_Translation\u003A\u003A\u0024_pearDirectory",
            "name": "_pearDirectory",
            "summary": "The\u0020absolute\u0020PEAR\u0020path\u0020to\u0020the\u0020translations\u0020for\u0020the\u0020default\u0020gettext\u0020handler.",
            "url": "classes/Horde-Push-Translation.html#property__pearDirectory"
        },                {
            "fqsen": "\\Horde_Push",
            "name": "Horde_Push",
            "summary": "A\u0020content\u0020element\u0020that\u0020will\u0020be\u0020pushed\u0020to\u0020various\u0020recipients.",
            "url": "classes/Horde-Push.html"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AgetSummary\u0028\u0029",
            "name": "getSummary",
            "summary": "Return\u0020the\u0020summary\u0020for\u0020this\u0020content\u0020element.",
            "url": "classes/Horde-Push.html#method_getSummary"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AsetSummary\u0028\u0029",
            "name": "setSummary",
            "summary": "Set\u0020the\u0020summary\u0020for\u0020this\u0020content\u0020element.",
            "url": "classes/Horde-Push.html#method_setSummary"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "Return\u0020the\u0020contents\u0020for\u0020this\u0020element.",
            "url": "classes/Horde-Push.html#method_getContent"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AgetStringContent\u0028\u0029",
            "name": "getStringContent",
            "summary": "Return\u0020the\u0020content\u0020at\u0020the\u0020given\u0020index\u0020as\u0020a\u0020string.",
            "url": "classes/Horde-Push.html#method_getStringContent"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AgetMimeTypes\u0028\u0029",
            "name": "getMimeTypes",
            "summary": "Return\u0020the\u0020contents\u0020by\u0020MIME\u0020type\u0020for\u0020this\u0020element.",
            "url": "classes/Horde-Push.html#method_getMimeTypes"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AaddContent\u0028\u0029",
            "name": "addContent",
            "summary": "Add\u0020content\u0020to\u0020this\u0020element.",
            "url": "classes/Horde-Push.html#method_addContent"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AaddRecipient\u0028\u0029",
            "name": "addRecipient",
            "summary": "Add\u0020a\u0020recipient\u0020for\u0020this\u0020element.",
            "url": "classes/Horde-Push.html#method_addRecipient"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AaddReference\u0028\u0029",
            "name": "addReference",
            "summary": "Add\u0020a\u0020URL\u0020reference\u0020for\u0020this\u0020element.",
            "url": "classes/Horde-Push.html#method_addReference"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AgetReferences\u0028\u0029",
            "name": "getReferences",
            "summary": "Retrieve\u0020the\u0020URL\u0020references\u0020for\u0020this\u0020element.",
            "url": "classes/Horde-Push.html#method_getReferences"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AhasReferences\u0028\u0029",
            "name": "hasReferences",
            "summary": "Indicate\u0020if\u0020this\u0020element\u0020has\u0020URL\u0020references.",
            "url": "classes/Horde-Push.html#method_hasReferences"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AaddTag\u0028\u0029",
            "name": "addTag",
            "summary": "Add\u0020a\u0020tag\u0020for\u0020this\u0020element.",
            "url": "classes/Horde-Push.html#method_addTag"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AgetTags\u0028\u0029",
            "name": "getTags",
            "summary": "Retrieve\u0020the\u0020tags\u0020for\u0020this\u0020element.",
            "url": "classes/Horde-Push.html#method_getTags"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003AhasTags\u0028\u0029",
            "name": "hasTags",
            "summary": "Indicate\u0020if\u0020this\u0020element\u0020has\u0020tags.",
            "url": "classes/Horde-Push.html#method_hasTags"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "Push\u0020the\u0020content\u0020to\u0020the\u0020recipients.",
            "url": "classes/Horde-Push.html#method_push"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003A\u0024_summary",
            "name": "_summary",
            "summary": "Content\u0020summary.",
            "url": "classes/Horde-Push.html#property__summary"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003A\u0024_content",
            "name": "_content",
            "summary": "Content.",
            "url": "classes/Horde-Push.html#property__content"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003A\u0024_types",
            "name": "_types",
            "summary": "Content\u0020types.",
            "url": "classes/Horde-Push.html#property__types"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003A\u0024_recipients",
            "name": "_recipients",
            "summary": "The\u0020recipients\u0020that\u0020will\u0020receive\u0020the\u0020content.",
            "url": "classes/Horde-Push.html#property__recipients"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003A\u0024_references",
            "name": "_references",
            "summary": "Reference\u0020links.",
            "url": "classes/Horde-Push.html#property__references"
        },                {
            "fqsen": "\\Horde_Push\u003A\u003A\u0024_tags",
            "name": "_tags",
            "summary": "Tags\u0020for\u0020the\u0020push.",
            "url": "classes/Horde-Push.html#property__tags"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
