Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Serialize_Exception",
            "name": "Horde_Serialize_Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020Horde_Serialize\u0020package.",
            "url": "classes/Horde-Serialize-Exception.html"
        },                {
            "fqsen": "\\Horde_Serialize",
            "name": "Horde_Serialize",
            "summary": "The\u0020Serialize\u003A\u003A\u0020class\u0020provides\u0020various\u0020methods\u0020of\u0020encapsulating\u0020data.",
            "url": "classes/Horde-Serialize.html"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Serialize\u0020a\u0020value.",
            "url": "classes/Horde-Serialize.html#method_serialize"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "Unserialize\u0020a\u0020value.",
            "url": "classes/Horde-Serialize.html#method_unserialize"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AhasCapability\u0028\u0029",
            "name": "hasCapability",
            "summary": "Check\u0020whether\u0020or\u0020not\u0020a\u0020serialization\u0020method\u0020is\u0020supported.",
            "url": "classes/Horde-Serialize.html#method_hasCapability"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003A_serialize\u0028\u0029",
            "name": "_serialize",
            "summary": "Serialize\u0020data.",
            "url": "classes/Horde-Serialize.html#method__serialize"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003A_unserialize\u0028\u0029",
            "name": "_unserialize",
            "summary": "Unserialize\u0020data.",
            "url": "classes/Horde-Serialize.html#method__unserialize"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AUNKNOWN",
            "name": "UNKNOWN",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_UNKNOWN"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003ANONE",
            "name": "NONE",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_NONE"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AWDDX",
            "name": "WDDX",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_WDDX"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003ABZIP",
            "name": "BZIP",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_BZIP"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AIMAP8",
            "name": "IMAP8",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_IMAP8"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AIMAPUTF7",
            "name": "IMAPUTF7",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_IMAPUTF7"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AIMAPUTF8",
            "name": "IMAPUTF8",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_IMAPUTF8"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003ABASIC",
            "name": "BASIC",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_BASIC"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AGZ_DEFLATE",
            "name": "GZ_DEFLATE",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_GZ_DEFLATE"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AGZ_COMPRESS",
            "name": "GZ_COMPRESS",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_GZ_COMPRESS"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AGZ_ENCODE",
            "name": "GZ_ENCODE",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_GZ_ENCODE"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003ABASE64",
            "name": "BASE64",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_BASE64"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003ARAW",
            "name": "RAW",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_RAW"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AURL",
            "name": "URL",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_URL"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AUTF7",
            "name": "UTF7",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_UTF7"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AUTF7_BASIC",
            "name": "UTF7_BASIC",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_UTF7_BASIC"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003AJSON",
            "name": "JSON",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_JSON"
        },                {
            "fqsen": "\\Horde_Serialize\u003A\u003ALZF",
            "name": "LZF",
            "summary": "",
            "url": "classes/Horde-Serialize.html#constant_LZF"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
