Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_SpellChecker_Aspell",
            "name": "Horde_SpellChecker_Aspell",
            "summary": "A\u0020spellcheck\u0020driver\u0020for\u0020the\u0020aspell\/ispell\u0020binary.",
            "url": "classes/Horde-SpellChecker-Aspell.html"
        },                {
            "fqsen": "\\Horde_SpellChecker_Aspell\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SpellChecker-Aspell.html#method___construct"
        },                {
            "fqsen": "\\Horde_SpellChecker_Aspell\u003A\u003AspellCheck\u0028\u0029",
            "name": "spellCheck",
            "summary": "Perform\u0020spellcheck.",
            "url": "classes/Horde-SpellChecker-Aspell.html#method_spellCheck"
        },                {
            "fqsen": "\\Horde_SpellChecker_Aspell\u003A\u003A_cmd\u0028\u0029",
            "name": "_cmd",
            "summary": "Create\u0020the\u0020command\u0020line\u0020string.",
            "url": "classes/Horde-SpellChecker-Aspell.html#method__cmd"
        },                {
            "fqsen": "\\Horde_SpellChecker_Exception",
            "name": "Horde_SpellChecker_Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020Horde_SpellChecker\u0020package.",
            "url": "classes/Horde-SpellChecker-Exception.html"
        },                {
            "fqsen": "\\Horde_SpellChecker",
            "name": "Horde_SpellChecker",
            "summary": "Provides\u0020a\u0020unified\u0020spellchecker\u0020API.",
            "url": "classes/Horde-SpellChecker.html"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003Afactory\u0028\u0029",
            "name": "factory",
            "summary": "Attempts\u0020to\u0020return\u0020a\u0020concrete\u0020Horde_SpellChecker\u0020instance\u0020based\u0020on\n\u0024driver.",
            "url": "classes/Horde-SpellChecker.html#method_factory"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-SpellChecker.html#method___construct"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003AsetParams\u0028\u0029",
            "name": "setParams",
            "summary": "Set\u0020configuration\u0020parmeters.",
            "url": "classes/Horde-SpellChecker.html#method_setParams"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003AspellCheck\u0028\u0029",
            "name": "spellCheck",
            "summary": "Perform\u0020spellcheck.",
            "url": "classes/Horde-SpellChecker.html#method_spellCheck"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003A_getWords\u0028\u0029",
            "name": "_getWords",
            "summary": "TODO",
            "url": "classes/Horde-SpellChecker.html#method__getWords"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003A_inLocalDictionary\u0028\u0029",
            "name": "_inLocalDictionary",
            "summary": "Determine\u0020if\u0020a\u0020word\u0020exists\u0020in\u0020the\u0020local\u0020dictionary.",
            "url": "classes/Horde-SpellChecker.html#method__inLocalDictionary"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003ASUGGEST_FAST",
            "name": "SUGGEST_FAST",
            "summary": "",
            "url": "classes/Horde-SpellChecker.html#constant_SUGGEST_FAST"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003ASUGGEST_NORMAL",
            "name": "SUGGEST_NORMAL",
            "summary": "",
            "url": "classes/Horde-SpellChecker.html#constant_SUGGEST_NORMAL"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003ASUGGEST_SLOW",
            "name": "SUGGEST_SLOW",
            "summary": "",
            "url": "classes/Horde-SpellChecker.html#constant_SUGGEST_SLOW"
        },                {
            "fqsen": "\\Horde_SpellChecker\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "Configuration\u0020parameters.",
            "url": "classes/Horde-SpellChecker.html#property__params"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
