Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Pack_Autodetermine",
            "name": "Horde_Pack_Autodetermine",
            "summary": "Auto\u002Ddetermine\u0020whether\u0020data\u0020contains\u0020PHP\u0020objects\u0020\u0028an\u0020object\u0020that\u0020must\u0020be\nserialized\u0020to\u0020be\u0020preserved\u0029.",
            "url": "classes/Horde-Pack-Autodetermine.html"
        },                {
            "fqsen": "\\Horde_Pack_Autodetermine\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Pack-Autodetermine.html#method___construct"
        },                {
            "fqsen": "\\Horde_Pack_Autodetermine\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-Pack-Autodetermine.html#method___get"
        },                {
            "fqsen": "\\Horde_Pack_Autodetermine\u003A\u003A_scanData\u0028\u0029",
            "name": "_scanData",
            "summary": "",
            "url": "classes/Horde-Pack-Autodetermine.html#method__scanData"
        },                {
            "fqsen": "\\Horde_Pack_Autodetermine\u003A\u003A\u0024_result",
            "name": "_result",
            "summary": "Cached\u0020results.",
            "url": "classes/Horde-Pack-Autodetermine.html#property__result"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Igbinary",
            "name": "Horde_Pack_Driver_Igbinary",
            "summary": "PHP\u0020igbinary\u0020extension\u0020handler.",
            "url": "classes/Horde-Pack-Driver-Igbinary.html"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Igbinary\u003A\u003Asupported\u0028\u0029",
            "name": "supported",
            "summary": "Is\u0020this\u0020driver\u0020supported\u0020on\u0020this\u0020system\u003F",
            "url": "classes/Horde-Pack-Driver-Igbinary.html#method_supported"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Igbinary\u003A\u003Apack\u0028\u0029",
            "name": "pack",
            "summary": "Pack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Igbinary.html#method_pack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Igbinary\u003A\u003Aunpack\u0028\u0029",
            "name": "unpack",
            "summary": "Unpack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Igbinary.html#method_unpack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Igbinary\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Identifer\u0020for\u0020this\u0020driver.\u0020Each\u0020driver\u0020needs\u0020a\u0020unique\u0020priority.",
            "url": "classes/Horde-Pack-Driver-Igbinary.html#property__id"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Igbinary\u003A\u003A\u0024_phpob",
            "name": "_phpob",
            "summary": "Does\u0020this\u0020driver\u0020support\u0020packing\u0020PHP\u0020objects\u003F",
            "url": "classes/Horde-Pack-Driver-Igbinary.html#property__phpob"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Json",
            "name": "Horde_Pack_Driver_Json",
            "summary": "PHP\u0020built\u002Din\u0020json_encode\u0028\u0029\/json_decode\u0028\u0029\u0020handler.",
            "url": "classes/Horde-Pack-Driver-Json.html"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Json\u003A\u003Asupported\u0028\u0029",
            "name": "supported",
            "summary": "Is\u0020this\u0020driver\u0020supported\u0020on\u0020this\u0020system\u003F",
            "url": "classes/Horde-Pack-Driver-Json.html#method_supported"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Json\u003A\u003Apack\u0028\u0029",
            "name": "pack",
            "summary": "Pack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Json.html#method_pack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Json\u003A\u003Aunpack\u0028\u0029",
            "name": "unpack",
            "summary": "Unpack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Json.html#method_unpack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Json\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Identifer\u0020for\u0020this\u0020driver.\u0020Each\u0020driver\u0020needs\u0020a\u0020unique\u0020priority.",
            "url": "classes/Horde-Pack-Driver-Json.html#property__id"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpack",
            "name": "Horde_Pack_Driver_Msgpack",
            "summary": "PHP\u0020msgpack\u0020extension\u0020handler\u0020\u0028non\u002Dserialized\u0020methods\u0029.",
            "url": "classes/Horde-Pack-Driver-Msgpack.html"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpack\u003A\u003Asupported\u0028\u0029",
            "name": "supported",
            "summary": "Is\u0020this\u0020driver\u0020supported\u0020on\u0020this\u0020system\u003F",
            "url": "classes/Horde-Pack-Driver-Msgpack.html#method_supported"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpack\u003A\u003Apack\u0028\u0029",
            "name": "pack",
            "summary": "Pack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Msgpack.html#method_pack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpack\u003A\u003Aunpack\u0028\u0029",
            "name": "unpack",
            "summary": "Unpack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Msgpack.html#method_unpack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpack\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Identifer\u0020for\u0020this\u0020driver.\u0020Each\u0020driver\u0020needs\u0020a\u0020unique\u0020priority.",
            "url": "classes/Horde-Pack-Driver-Msgpack.html#property__id"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpackserialize",
            "name": "Horde_Pack_Driver_Msgpackserialize",
            "summary": "PHP\u0020msgpack\u0020extension\u0020handler\u0020\u0028serialized\u0020methods\u0029.",
            "url": "classes/Horde-Pack-Driver-Msgpackserialize.html"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpackserialize\u003A\u003Asupported\u0028\u0029",
            "name": "supported",
            "summary": "Is\u0020this\u0020driver\u0020supported\u0020on\u0020this\u0020system\u003F",
            "url": "classes/Horde-Pack-Driver-Msgpackserialize.html#method_supported"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpackserialize\u003A\u003Apack\u0028\u0029",
            "name": "pack",
            "summary": "Pack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Msgpackserialize.html#method_pack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpackserialize\u003A\u003Aunpack\u0028\u0029",
            "name": "unpack",
            "summary": "Unpack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Msgpackserialize.html#method_unpack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpackserialize\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Identifer\u0020for\u0020this\u0020driver.\u0020Each\u0020driver\u0020needs\u0020a\u0020unique\u0020priority.",
            "url": "classes/Horde-Pack-Driver-Msgpackserialize.html#property__id"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Msgpackserialize\u003A\u003A\u0024_phpob",
            "name": "_phpob",
            "summary": "Does\u0020this\u0020driver\u0020support\u0020packing\u0020PHP\u0020objects\u003F",
            "url": "classes/Horde-Pack-Driver-Msgpackserialize.html#property__phpob"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Serialize",
            "name": "Horde_Pack_Driver_Serialize",
            "summary": "PHP\u0020built\u002Din\u0020serialize\u0028\u0029\/unserialize\u0028\u0029\u0020handler.",
            "url": "classes/Horde-Pack-Driver-Serialize.html"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Serialize\u003A\u003Apack\u0028\u0029",
            "name": "pack",
            "summary": "Pack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Serialize.html#method_pack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Serialize\u003A\u003Aunpack\u0028\u0029",
            "name": "unpack",
            "summary": "Unpack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver-Serialize.html#method_unpack"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Serialize\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Identifer\u0020for\u0020this\u0020driver.\u0020Each\u0020driver\u0020needs\u0020a\u0020unique\u0020priority.",
            "url": "classes/Horde-Pack-Driver-Serialize.html#property__id"
        },                {
            "fqsen": "\\Horde_Pack_Driver_Serialize\u003A\u003A\u0024_phpob",
            "name": "_phpob",
            "summary": "Does\u0020this\u0020driver\u0020support\u0020packing\u0020PHP\u0020objects\u003F",
            "url": "classes/Horde-Pack-Driver-Serialize.html#property__phpob"
        },                {
            "fqsen": "\\Horde_Pack_Driver",
            "name": "Horde_Pack_Driver",
            "summary": "Abstract\u0020driver\u0020class\u0020for\u0020implementing\u0020a\u0020pack\u0020driver.",
            "url": "classes/Horde-Pack-Driver.html"
        },                {
            "fqsen": "\\Horde_Pack_Driver\u003A\u003Asupported\u0028\u0029",
            "name": "supported",
            "summary": "Is\u0020this\u0020driver\u0020supported\u0020on\u0020this\u0020system\u003F",
            "url": "classes/Horde-Pack-Driver.html#method_supported"
        },                {
            "fqsen": "\\Horde_Pack_Driver\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-Pack-Driver.html#method___get"
        },                {
            "fqsen": "\\Horde_Pack_Driver\u003A\u003Apack\u0028\u0029",
            "name": "pack",
            "summary": "Pack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver.html#method_pack"
        },                {
            "fqsen": "\\Horde_Pack_Driver\u003A\u003Aunpack\u0028\u0029",
            "name": "unpack",
            "summary": "Unpack\u0020a\u0020string.",
            "url": "classes/Horde-Pack-Driver.html#method_unpack"
        },                {
            "fqsen": "\\Horde_Pack_Driver\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "Identifer\u0020for\u0020this\u0020driver.\u0020Each\u0020driver\u0020needs\u0020a\u0020unique\u0020priority.",
            "url": "classes/Horde-Pack-Driver.html#property__id"
        },                {
            "fqsen": "\\Horde_Pack_Driver\u003A\u003A\u0024_phpob",
            "name": "_phpob",
            "summary": "Does\u0020this\u0020driver\u0020support\u0020packing\u0020PHP\u0020objects\u003F",
            "url": "classes/Horde-Pack-Driver.html#property__phpob"
        },                {
            "fqsen": "\\Horde_Pack_Exception",
            "name": "Horde_Pack_Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020horde\/Pack\u0020package.",
            "url": "classes/Horde-Pack-Exception.html"
        },                {
            "fqsen": "\\Horde_Pack",
            "name": "Horde_Pack",
            "summary": "A\u0020replacement\u0020for\u0020serialize\u0028\u0029\/json_encode\u0028\u0029\u0020that\u0020will\u0020automatically\nuse\u0020the\u0020most\u0020efficient\u0020serialization\u0020available\u0020based\u0020on\u0020the\u0020input.",
            "url": "classes/Horde-Pack.html"
        },                {
            "fqsen": "\\Horde_Pack\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Pack.html#method___construct"
        },                {
            "fqsen": "\\Horde_Pack\u003A\u003A__sleep\u0028\u0029",
            "name": "__sleep",
            "summary": "",
            "url": "classes/Horde-Pack.html#method___sleep"
        },                {
            "fqsen": "\\Horde_Pack\u003A\u003Apack\u0028\u0029",
            "name": "pack",
            "summary": "Pack\u0020a\u0020string.",
            "url": "classes/Horde-Pack.html#method_pack"
        },                {
            "fqsen": "\\Horde_Pack\u003A\u003Aunpack\u0028\u0029",
            "name": "unpack",
            "summary": "Unpack\u0020a\u0020string.",
            "url": "classes/Horde-Pack.html#method_unpack"
        },                {
            "fqsen": "\\Horde_Pack\u003A\u003ADEFAULT_COMPRESS",
            "name": "DEFAULT_COMPRESS",
            "summary": "",
            "url": "classes/Horde-Pack.html#constant_DEFAULT_COMPRESS"
        },                {
            "fqsen": "\\Horde_Pack\u003A\u003ACOMPRESS_MASK",
            "name": "COMPRESS_MASK",
            "summary": "",
            "url": "classes/Horde-Pack.html#constant_COMPRESS_MASK"
        },                {
            "fqsen": "\\Horde_Pack\u003A\u003A\u0024_compress",
            "name": "_compress",
            "summary": "Instance\u0020of\u0020Horde_Compress_Fast\u0020shared\u0020between\u0020all\u0020instances.",
            "url": "classes/Horde-Pack.html#property__compress"
        },                {
            "fqsen": "\\Horde_Pack\u003A\u003A\u0024_drivers",
            "name": "_drivers",
            "summary": "Drivers.\u0020Shared\u0020between\u0020all\u0020instances.",
            "url": "classes/Horde-Pack.html#property__drivers"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
