Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Date_Parser_Exception",
            "name": "Horde_Date_Parser_Exception",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Exception.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Handler",
            "name": "Horde_Date_Parser_Handler",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Handler.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Handler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Handler.html#method___construct"
        },                {
            "fqsen": "\\Horde_Date_Parser_Handler\u003A\u003Amatch\u0028\u0029",
            "name": "match",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Handler.html#method_match"
        },                {
            "fqsen": "\\Horde_Date_Parser_Handler\u003A\u003A\u0024pattern",
            "name": "pattern",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Handler.html#property_pattern"
        },                {
            "fqsen": "\\Horde_Date_Parser_Handler\u003A\u003A\u0024handlerMethod",
            "name": "handlerMethod",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Handler.html#property_handlerMethod"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Grabber",
            "name": "Horde_Date_Parser_Locale_Base_Grabber",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Grabber.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Grabber\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Grabber.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Grabber\u003A\u003AscanForAll\u0028\u0029",
            "name": "scanForAll",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Grabber.html#method_scanForAll"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Grabber\u003A\u003A\u0024scanner",
            "name": "scanner",
            "summary": "Regex\u0020tokens",
            "url": "classes/Horde-Date-Parser-Locale-Base-Grabber.html#property_scanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Ordinal",
            "name": "Horde_Date_Parser_Locale_Base_Ordinal",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Ordinal.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Ordinal\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Ordinal.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Ordinal\u003A\u003AscanForOrdinals\u0028\u0029",
            "name": "scanForOrdinals",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Ordinal.html#method_scanForOrdinals"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Ordinal\u003A\u003AscanForDays\u0028\u0029",
            "name": "scanForDays",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Ordinal.html#method_scanForDays"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Ordinal\u003A\u003A\u0024ordinalRegex",
            "name": "ordinalRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Ordinal.html#property_ordinalRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Ordinal\u003A\u003A\u0024ordinalDayRegex",
            "name": "ordinalDayRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Ordinal.html#property_ordinalDayRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Pointer",
            "name": "Horde_Date_Parser_Locale_Base_Pointer",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Pointer.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Pointer\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Pointer.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Pointer\u003A\u003AscanForAll\u0028\u0029",
            "name": "scanForAll",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Pointer.html#method_scanForAll"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Pointer\u003A\u003A\u0024scanner",
            "name": "scanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Pointer.html#property_scanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater",
            "name": "Horde_Date_Parser_Locale_Base_Repeater",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003AscanForMonthNames\u0028\u0029",
            "name": "scanForMonthNames",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#method_scanForMonthNames"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003AscanForDayNames\u0028\u0029",
            "name": "scanForDayNames",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#method_scanForDayNames"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003AscanForDayPortions\u0028\u0029",
            "name": "scanForDayPortions",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#method_scanForDayPortions"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003AscanForTimes\u0028\u0029",
            "name": "scanForTimes",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#method_scanForTimes"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003AscanForUnits\u0028\u0029",
            "name": "scanForUnits",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#method_scanForUnits"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003A\u0024monthNameScanner",
            "name": "monthNameScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#property_monthNameScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003A\u0024dayNameScanner",
            "name": "dayNameScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#property_dayNameScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003A\u0024dayPortionScanner",
            "name": "dayPortionScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#property_dayPortionScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003A\u0024unitScanner",
            "name": "unitScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#property_unitScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Repeater\u003A\u003A\u0024timeRegex",
            "name": "timeRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Repeater.html#property_timeRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar",
            "name": "Horde_Date_Parser_Locale_Base_Scalar",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003AscanForScalars\u0028\u0029",
            "name": "scanForScalars",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#method_scanForScalars"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003AscanForDays\u0028\u0029",
            "name": "scanForDays",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#method_scanForDays"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003AscanForMonths\u0028\u0029",
            "name": "scanForMonths",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#method_scanForMonths"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003AscanForYears\u0028\u0029",
            "name": "scanForYears",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#method_scanForYears"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003A\u0024scalarRegex",
            "name": "scalarRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#property_scalarRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003A\u0024dayRegex",
            "name": "dayRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#property_dayRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003A\u0024monthRegex",
            "name": "monthRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#property_monthRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003A\u0024yearRegex",
            "name": "yearRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#property_yearRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Scalar\u003A\u003A\u0024timeSignifiers",
            "name": "timeSignifiers",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Scalar.html#property_timeSignifiers"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator",
            "name": "Horde_Date_Parser_Locale_Base_Separator",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator\u003A\u003AscanForCommas\u0028\u0029",
            "name": "scanForCommas",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html#method_scanForCommas"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator\u003A\u003AscanForSlashOrDash\u0028\u0029",
            "name": "scanForSlashOrDash",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html#method_scanForSlashOrDash"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator\u003A\u003AscanForAt\u0028\u0029",
            "name": "scanForAt",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html#method_scanForAt"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator\u003A\u003AscanForIn\u0028\u0029",
            "name": "scanForIn",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html#method_scanForIn"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator\u003A\u003A\u0024commaScanner",
            "name": "commaScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html#property_commaScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator\u003A\u003A\u0024slashOrDashScanner",
            "name": "slashOrDashScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html#property_slashOrDashScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator\u003A\u003A\u0024atScanner",
            "name": "atScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html#property_atScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Separator\u003A\u003A\u0024inScanner",
            "name": "inScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Separator.html#property_inScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Timezone",
            "name": "Horde_Date_Parser_Locale_Base_Timezone",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Timezone.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Timezone\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Timezone.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Timezone\u003A\u003AscanForAll\u0028\u0029",
            "name": "scanForAll",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Timezone.html#method_scanForAll"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base_Timezone\u003A\u003A\u0024scanner",
            "name": "scanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base-Timezone.html#property_scanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base",
            "name": "Horde_Date_Parser_Locale_Base",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method___construct"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "\u0023\u0020Parses\u0020a\u0020string\u0020containing\u0020a\u0020natural\u0020language\u0020date\u0020or\u0020time.\u0020If\u0020the\u0020parser\n\u0023\u0020can\u0020find\u0020a\u0020date\u0020or\u0020time,\u0020either\u0020a\u0020Horde_Date\u0020or\u0020Horde_Date_Span\u0020will\u0020be\u0020returned\n\u0023\u0020\u0028depending\u0020on\u0020the\u0020value\u0020of\u0020\u003Ctt\u003E\u003Areturn\u003C\/tt\u003E\u0029.\u0020If\u0020no\u0020date\u0020or\u0020time\u0020can\u0020be\u0020found,\n\u0023\u0020\u002Bnil\u002B\u0020will\u0020be\u0020returned.",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_parse"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AcomponentFactory\u0028\u0029",
            "name": "componentFactory",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_componentFactory"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003ApreNormalize\u0028\u0029",
            "name": "preNormalize",
            "summary": "\u0023\u0020Clean\u0020up\u0020the\u0020specified\u0020input\u0020text\u0020by\u0020stripping\u0020unwanted\u0020characters,\n\u0023\u0020converting\u0020idioms\u0020to\u0020their\u0020canonical\u0020form,\u0020converting\u0020number\u0020words\n\u0023\u0020to\u0020numbers\u0020\u0028three\u0020\u003D\u003E\u00203\u0029,\u0020and\u0020converting\u0020ordinal\u0020words\u0020to\u0020numeric\n\u0023\u0020ordinals\u0020\u0028third\u0020\u003D\u003E\u00203rd\u0029",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_preNormalize"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AnumericizeNumbers\u0028\u0029",
            "name": "numericizeNumbers",
            "summary": "Convert\u0020number\u0020words\u0020to\u0020numbers\u0020\u0028three\u0020\u003D\u003E\u00203\u0029",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_numericizeNumbers"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AnumericizeOrdinals\u0028\u0029",
            "name": "numericizeOrdinals",
            "summary": "Convert\u0020ordinal\u0020words\u0020to\u0020numeric\u0020ordinals\u0020\u0028third\u0020\u003D\u003E\u00203rd\u0029",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_numericizeOrdinals"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003ApreTokenize\u0028\u0029",
            "name": "preTokenize",
            "summary": "Split\u0020the\u0020text\u0020on\u0020spaces\u0020and\u0020convert\u0020each\u0020word\u0020into\u0020a\u0020Token.",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_preTokenize"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003ApostTokenize\u0028\u0029",
            "name": "postTokenize",
            "summary": "Remove\u0020tokens\u0020that\u0020don\u0027t\u0020fit\u0020our\u0020definitions.",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_postTokenize"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AinitDefinitions\u0028\u0029",
            "name": "initDefinitions",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_initDefinitions"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AtokensToSpan\u0028\u0029",
            "name": "tokensToSpan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_tokensToSpan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AdayOrTime\u0028\u0029",
            "name": "dayOrTime",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_dayOrTime"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_m_d\u0028\u0029",
            "name": "handle_m_d",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_m_d"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_rmn_sd\u0028\u0029",
            "name": "handle_rmn_sd",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_rmn_sd"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_rmn_od\u0028\u0029",
            "name": "handle_rmn_od",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_rmn_od"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_rmn_sy\u0028\u0029",
            "name": "handle_rmn_sy",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_rmn_sy"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_rdn_rmn_sd_t_tz_sy\u0028\u0029",
            "name": "handle_rdn_rmn_sd_t_tz_sy",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_rdn_rmn_sd_t_tz_sy"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_rmn_sd_sy\u0028\u0029",
            "name": "handle_rmn_sd_sy",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_rmn_sd_sy"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_sd_rmn_sy\u0028\u0029",
            "name": "handle_sd_rmn_sy",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_sd_rmn_sy"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_sm_sd_sy\u0028\u0029",
            "name": "handle_sm_sd_sy",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_sm_sd_sy"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_sd_sm_sy\u0028\u0029",
            "name": "handle_sd_sm_sy",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_sd_sm_sy"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_sy_sm_sd\u0028\u0029",
            "name": "handle_sy_sm_sd",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_sy_sm_sd"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_sm_sy\u0028\u0029",
            "name": "handle_sm_sy",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_sm_sy"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_r\u0028\u0029",
            "name": "handle_r",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_r"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_r_g_r\u0028\u0029",
            "name": "handle_r_g_r",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_r_g_r"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_srp\u0028\u0029",
            "name": "handle_srp",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_srp"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_s_r_p\u0028\u0029",
            "name": "handle_s_r_p",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_s_r_p"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_p_s_r\u0028\u0029",
            "name": "handle_p_s_r",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_p_s_r"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_s_r_p_a\u0028\u0029",
            "name": "handle_s_r_p_a",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_s_r_p_a"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_orr\u0028\u0029",
            "name": "handle_orr",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_orr"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_o_r_s_r\u0028\u0029",
            "name": "handle_o_r_s_r",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_o_r_s_r"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Ahandle_o_r_g_r\u0028\u0029",
            "name": "handle_o_r_g_r",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_handle_o_r_g_r"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003Adebug\u0028\u0029",
            "name": "debug",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_debug"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AgetAnchor\u0028\u0029",
            "name": "getAnchor",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_getAnchor"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AgetRepeaters\u0028\u0029",
            "name": "getRepeaters",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_getRepeaters"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AfindWithin\u0028\u0029",
            "name": "findWithin",
            "summary": "Recursively\u0020finds\u0020repeaters\u0020within\u0020other\u0020repeaters.\u0020\u0020Returns\u0020a\u0020Span\nrepresenting\u0020the\u0020innermost\u0020time\u0020span\u0020or\u0020null\u0020if\u0020no\u0020repeater\u0020union\u0020could\nbe\u0020found",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_findWithin"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003AdealiasAndDisambiguateTimes\u0028\u0029",
            "name": "dealiasAndDisambiguateTimes",
            "summary": "handle\u0020aliases\u0020of\u0020am\/pm\n5\u003A00\u0020in\u0020the\u0020morning\u0020\u002D\u003E\u00205\u003A00\u0020am\n7\u003A00\u0020in\u0020the\u0020evening\u0020\u002D\u003E\u00207\u003A00\u0020pm",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#method_dealiasAndDisambiguateTimes"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003A\u0024definitions",
            "name": "definitions",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#property_definitions"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003A\u0024args",
            "name": "args",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#property_args"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Base\u003A\u003A\u0024now",
            "name": "now",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Base.html#property_now"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Grabber",
            "name": "Horde_Date_Parser_Locale_De_Grabber",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Grabber.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Grabber\u003A\u003A\u0024scanner",
            "name": "scanner",
            "summary": "Regex\u0020tokens",
            "url": "classes/Horde-Date-Parser-Locale-De-Grabber.html#property_scanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Ordinal",
            "name": "Horde_Date_Parser_Locale_De_Ordinal",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Ordinal.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Ordinal\u003A\u003A\u0024ordinalRegex",
            "name": "ordinalRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Ordinal.html#property_ordinalRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Ordinal\u003A\u003A\u0024ordinalDayRegex",
            "name": "ordinalDayRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Ordinal.html#property_ordinalDayRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Pointer",
            "name": "Horde_Date_Parser_Locale_De_Pointer",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Pointer.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Pointer\u003A\u003A\u0024scanner",
            "name": "scanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Pointer.html#property_scanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Repeater",
            "name": "Horde_Date_Parser_Locale_De_Repeater",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Repeater.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Repeater\u003A\u003A\u0024monthNameScanner",
            "name": "monthNameScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Repeater.html#property_monthNameScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Repeater\u003A\u003A\u0024dayNameScanner",
            "name": "dayNameScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Repeater.html#property_dayNameScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Repeater\u003A\u003A\u0024dayPortionScanner",
            "name": "dayPortionScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Repeater.html#property_dayPortionScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Repeater\u003A\u003A\u0024unitScanner",
            "name": "unitScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Repeater.html#property_unitScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Scalar",
            "name": "Horde_Date_Parser_Locale_De_Scalar",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Scalar.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Separator",
            "name": "Horde_Date_Parser_Locale_De_Separator",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Separator.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Separator\u003A\u003A\u0024atScanner",
            "name": "atScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Separator.html#property_atScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Timezone",
            "name": "Horde_Date_Parser_Locale_De_Timezone",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Timezone.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De_Timezone\u003A\u003A\u0024scanner",
            "name": "scanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De-Timezone.html#property_scanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De",
            "name": "Horde_Date_Parser_Locale_De",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-De.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De\u003A\u003ApreNormalize\u0028\u0029",
            "name": "preNormalize",
            "summary": "Clean\u0020up\u0020the\u0020specified\u0020input\u0020text\u0020by\u0020stripping\u0020unwanted\u0020characters,\nconverting\u0020idioms\u0020to\u0020their\u0020canonical\u0020form,\u0020converting\u0020number\u0020words\nto\u0020numbers\u0020\u0028three\u0020\u003D\u003E\u00203\u0029,\u0020and\u0020converting\u0020ordinal\u0020words\u0020to\u0020numeric\nordinals\u0020\u0028third\u0020\u003D\u003E\u00203rd\u0029",
            "url": "classes/Horde-Date-Parser-Locale-De.html#method_preNormalize"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_De\u003A\u003ApostTokenize\u0028\u0029",
            "name": "postTokenize",
            "summary": "Remove\u0020tokens\u0020that\u0020don\u0027t\u0020fit\u0020our\u0020definitions\u0020and\u0020re\u002Dorders\u0020tokens\u0020when\nnecessary.",
            "url": "classes/Horde-Date-Parser-Locale-De.html#method_postTokenize"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Grabber",
            "name": "Horde_Date_Parser_Locale_Pt_Grabber",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Grabber.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Grabber\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Grabber.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Grabber\u003A\u003AscanForAll\u0028\u0029",
            "name": "scanForAll",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Grabber.html#method_scanForAll"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Grabber\u003A\u003A\u0024scanner",
            "name": "scanner",
            "summary": "Regex\u0020tokens",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Grabber.html#property_scanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Ordinal",
            "name": "Horde_Date_Parser_Locale_Pt_Ordinal",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Ordinal.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Ordinal\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Ordinal.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Ordinal\u003A\u003AscanForOrdinals\u0028\u0029",
            "name": "scanForOrdinals",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Ordinal.html#method_scanForOrdinals"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Ordinal\u003A\u003AscanForDays\u0028\u0029",
            "name": "scanForDays",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Ordinal.html#method_scanForDays"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Ordinal\u003A\u003AscanForMonths\u0028\u0029",
            "name": "scanForMonths",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Ordinal.html#method_scanForMonths"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Ordinal\u003A\u003A\u0024ordinalRegex",
            "name": "ordinalRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Ordinal.html#property_ordinalRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Ordinal\u003A\u003A\u0024ordinalDayRegex",
            "name": "ordinalDayRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Ordinal.html#property_ordinalDayRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Ordinal\u003A\u003A\u0024ordinalMonthsRegex",
            "name": "ordinalMonthsRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Ordinal.html#property_ordinalMonthsRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Pointer",
            "name": "Horde_Date_Parser_Locale_Pt_Pointer",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Pointer.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Pointer\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Pointer.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Pointer\u003A\u003AscanForAll\u0028\u0029",
            "name": "scanForAll",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Pointer.html#method_scanForAll"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Pointer\u003A\u003A\u0024scanner",
            "name": "scanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Pointer.html#property_scanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater",
            "name": "Horde_Date_Parser_Locale_Pt_Repeater",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003AscanForMonthNames\u0028\u0029",
            "name": "scanForMonthNames",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#method_scanForMonthNames"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003AscanForDayNames\u0028\u0029",
            "name": "scanForDayNames",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#method_scanForDayNames"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003AscanForDayPortions\u0028\u0029",
            "name": "scanForDayPortions",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#method_scanForDayPortions"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003AscanForTimes\u0028\u0029",
            "name": "scanForTimes",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#method_scanForTimes"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003AscanForUnits\u0028\u0029",
            "name": "scanForUnits",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#method_scanForUnits"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003A\u0024monthNameScanner",
            "name": "monthNameScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#property_monthNameScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003A\u0024dayNameScanner",
            "name": "dayNameScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#property_dayNameScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003A\u0024dayPortionScanner",
            "name": "dayPortionScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#property_dayPortionScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003A\u0024unitScanner",
            "name": "unitScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#property_unitScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Repeater\u003A\u003A\u0024timeRegex",
            "name": "timeRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Repeater.html#property_timeRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar",
            "name": "Horde_Date_Parser_Locale_Pt_Scalar",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003AscanForScalars\u0028\u0029",
            "name": "scanForScalars",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#method_scanForScalars"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003AscanForDays\u0028\u0029",
            "name": "scanForDays",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#method_scanForDays"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003AscanForMonths\u0028\u0029",
            "name": "scanForMonths",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#method_scanForMonths"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003AscanForYears\u0028\u0029",
            "name": "scanForYears",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#method_scanForYears"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003A\u0024scalarRegex",
            "name": "scalarRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#property_scalarRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003A\u0024dayRegex",
            "name": "dayRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#property_dayRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003A\u0024monthRegex",
            "name": "monthRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#property_monthRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003A\u0024yearRegex",
            "name": "yearRegex",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#property_yearRegex"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Scalar\u003A\u003A\u0024timeSignifiers",
            "name": "timeSignifiers",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Scalar.html#property_timeSignifiers"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator",
            "name": "Horde_Date_Parser_Locale_Pt_Separator",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html#method_scan"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator\u003A\u003AscanForCommas\u0028\u0029",
            "name": "scanForCommas",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html#method_scanForCommas"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator\u003A\u003AscanForSlashOrDash\u0028\u0029",
            "name": "scanForSlashOrDash",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html#method_scanForSlashOrDash"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator\u003A\u003AscanForAt\u0028\u0029",
            "name": "scanForAt",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html#method_scanForAt"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator\u003A\u003AscanForIn\u0028\u0029",
            "name": "scanForIn",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html#method_scanForIn"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator\u003A\u003A\u0024commaScanner",
            "name": "commaScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html#property_commaScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator\u003A\u003A\u0024slashOrDashScanner",
            "name": "slashOrDashScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html#property_slashOrDashScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator\u003A\u003A\u0024atScanner",
            "name": "atScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html#property_atScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Separator\u003A\u003A\u0024inScanner",
            "name": "inScanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Separator.html#property_inScanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Timezone",
            "name": "Horde_Date_Parser_Locale_Pt_Timezone",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Timezone.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt_Timezone\u003A\u003A\u0024scanner",
            "name": "scanner",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt-Timezone.html#property_scanner"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt",
            "name": "Horde_Date_Parser_Locale_Pt",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#method___construct"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "Parses\u0020a\u0020string\u0020containing\u0020a\u0020natural\u0020language\u0020date\u0020or\u0020time.\u0020If\u0020the\nparser\u0020can\u0020find\u0020a\u0020date\u0020or\u0020time,\u0020either\u0020a\u0020Horde_Date\u0020or\u0020Horde_Date_Span\nwill\u0020be\u0020returned\u0020\u0028depending\u0020on\u0020the\u0020value\u0020of\u0020\u003Ctt\u003E\u003Areturn\u003C\/tt\u003E\u0029.\u0020If\u0020no\ndate\u0020or\u0020time\u0020can\u0020be\u0020found,\u0020\u002Bnil\u002B\u0020will\u0020be\u0020returned.",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#method_parse"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003Anormalize_special_characters\u0028\u0029",
            "name": "normalize_special_characters",
            "summary": "Replaces\u0020special\u0020characters\u0020with\u0020non\u002Dspecial\u0020equivalents.",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#method_normalize_special_characters"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003ApreNormalize\u0028\u0029",
            "name": "preNormalize",
            "summary": "Clean\u0020up\u0020the\u0020specified\u0020input\u0020text\u0020by\u0020stripping\u0020unwanted\u0020characters,\nconverting\u0020idioms\u0020to\u0020their\u0020canonical\u0020form,\u0020converting\u0020number\u0020words\u0020to\nnumbers\u0020\u0028three\u0020\u003D\u003E\u00203\u0029,\u0020and\u0020converting\u0020ordinal\u0020words\u0020to\u0020numeric\u0020ordinals\n\u0028third\u0020\u003D\u003E\u00203rd\u0029",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#method_preNormalize"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003AnumericizeOrdinals\u0028\u0029",
            "name": "numericizeOrdinals",
            "summary": "Convert\u0020ordinal\u0020words\u0020to\u0020numeric\u0020ordinals\u0020\u0028third\u0020\u003D\u003E\u00203rd\u0029",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#method_numericizeOrdinals"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003AinitDefinitions\u0028\u0029",
            "name": "initDefinitions",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#method_initDefinitions"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003Ahandle_rdn\u0028\u0029",
            "name": "handle_rdn",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#method_handle_rdn"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003Ahandle_sd_rmn\u0028\u0029",
            "name": "handle_sd_rmn",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#method_handle_sd_rmn"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003Ahandle_od_rmn\u0028\u0029",
            "name": "handle_od_rmn",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#method_handle_od_rmn"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003A\u0024definitions",
            "name": "definitions",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#property_definitions"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003A\u0024args",
            "name": "args",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#property_args"
        },                {
            "fqsen": "\\Horde_Date_Parser_Locale_Pt\u003A\u003A\u0024now",
            "name": "now",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Locale-Pt.html#property_now"
        },                {
            "fqsen": "\\Horde_Date_Parser_Result",
            "name": "Horde_Date_Parser_Result",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Result.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Result\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Result.html#method___construct"
        },                {
            "fqsen": "\\Horde_Date_Parser_Result\u003A\u003Aguess\u0028\u0029",
            "name": "guess",
            "summary": "Guess\u0020a\u0020specific\u0020time\u0020within\u0020the\u0020given\u0020span",
            "url": "classes/Horde-Date-Parser-Result.html#method_guess"
        },                {
            "fqsen": "\\Horde_Date_Parser_Result\u003A\u003AtaggedText\u0028\u0029",
            "name": "taggedText",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Result.html#method_taggedText"
        },                {
            "fqsen": "\\Horde_Date_Parser_Result\u003A\u003AuntaggedText\u0028\u0029",
            "name": "untaggedText",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Result.html#method_untaggedText"
        },                {
            "fqsen": "\\Horde_Date_Parser_Result\u003A\u003A\u0024span",
            "name": "span",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Result.html#property_span"
        },                {
            "fqsen": "\\Horde_Date_Parser_Result\u003A\u003A\u0024tokens",
            "name": "tokens",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Result.html#property_tokens"
        },                {
            "fqsen": "\\Horde_Date_Parser_Token",
            "name": "Horde_Date_Parser_Token",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Token.html"
        },                {
            "fqsen": "\\Horde_Date_Parser_Token\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Token.html#method___construct"
        },                {
            "fqsen": "\\Horde_Date_Parser_Token\u003A\u003Atag\u0028\u0029",
            "name": "tag",
            "summary": "Tag\u0020this\u0020token\u0020with\u0020the\u0020specified\u0020tag",
            "url": "classes/Horde-Date-Parser-Token.html#method_tag"
        },                {
            "fqsen": "\\Horde_Date_Parser_Token\u003A\u003Auntag\u0028\u0029",
            "name": "untag",
            "summary": "Remove\u0020all\u0020tags\u0020of\u0020the\u0020given\u0020class",
            "url": "classes/Horde-Date-Parser-Token.html#method_untag"
        },                {
            "fqsen": "\\Horde_Date_Parser_Token\u003A\u003Atagged\u0028\u0029",
            "name": "tagged",
            "summary": "Return\u0020true\u0020if\u0020this\u0020token\u0020has\u0020any\u0020tags",
            "url": "classes/Horde-Date-Parser-Token.html#method_tagged"
        },                {
            "fqsen": "\\Horde_Date_Parser_Token\u003A\u003AgetTag\u0028\u0029",
            "name": "getTag",
            "summary": "Return\u0020the\u0020Tag\u0020that\u0020matches\u0020the\u0020given\u0020class",
            "url": "classes/Horde-Date-Parser-Token.html#method_getTag"
        },                {
            "fqsen": "\\Horde_Date_Parser_Token\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Print\u0020this\u0020Token\u0020in\u0020a\u0020pretty\u0020way",
            "url": "classes/Horde-Date-Parser-Token.html#method___toString"
        },                {
            "fqsen": "\\Horde_Date_Parser_Token\u003A\u003A\u0024word",
            "name": "word",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Token.html#property_word"
        },                {
            "fqsen": "\\Horde_Date_Parser_Token\u003A\u003A\u0024tags",
            "name": "tags",
            "summary": "",
            "url": "classes/Horde-Date-Parser-Token.html#property_tags"
        },                {
            "fqsen": "\\Horde_Date_Parser",
            "name": "Horde_Date_Parser",
            "summary": "",
            "url": "classes/Horde-Date-Parser.html"
        },                {
            "fqsen": "\\Horde_Date_Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Horde-Date-Parser.html#method_parse"
        },                {
            "fqsen": "\\Horde_Date_Parser\u003A\u003Afactory\u0028\u0029",
            "name": "factory",
            "summary": "",
            "url": "classes/Horde-Date-Parser.html#method_factory"
        },                {
            "fqsen": "\\Horde_Date_Parser\u003A\u003AgetLocales\u0028\u0029",
            "name": "getLocales",
            "summary": "Return\u0020a\u0020list\u0020of\u0020available\u0020locales",
            "url": "classes/Horde-Date-Parser.html#method_getLocales"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
