Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Scribd_Block_Scribd",
            "name": "Horde_Scribd_Block_Scribd",
            "summary": "",
            "url": "classes/Horde-Scribd-Block-Scribd.html"
        },                {
            "fqsen": "\\Horde_Scribd_Block_Scribd\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Scribd-Block-Scribd.html#method___construct"
        },                {
            "fqsen": "\\Horde_Scribd_Block_Scribd\u003A\u003A_content\u0028\u0029",
            "name": "_content",
            "summary": "",
            "url": "classes/Horde-Scribd-Block-Scribd.html#method__content"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Exception",
            "name": "Horde_Service_Scribd_Exception",
            "summary": "Scribd\u0020exception\u0020class",
            "url": "classes/Horde-Service-Scribd-Exception.html"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Request",
            "name": "Horde_Service_Scribd_Request",
            "summary": "Scribd\u0020request\u0020class",
            "url": "classes/Horde-Service-Scribd-Request.html"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Request\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Service-Scribd-Request.html#method___construct"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Request\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Horde-Service-Scribd-Request.html#method_run"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Request\u003A\u003AsetConfig\u0028\u0029",
            "name": "setConfig",
            "summary": "",
            "url": "classes/Horde-Service-Scribd-Request.html#method_setConfig"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Request\u003A\u003A_sign\u0028\u0029",
            "name": "_sign",
            "summary": "",
            "url": "classes/Horde-Service-Scribd-Request.html#method__sign"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Request\u003A\u003A\u0024_args",
            "name": "_args",
            "summary": "",
            "url": "classes/Horde-Service-Scribd-Request.html#property__args"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Request\u003A\u003A\u0024_config",
            "name": "_config",
            "summary": "",
            "url": "classes/Horde-Service-Scribd-Request.html#property__config"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Request\u003A\u003A\u0024_method",
            "name": "_method",
            "summary": "",
            "url": "classes/Horde-Service-Scribd-Request.html#property__method"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Response",
            "name": "Horde_Service_Scribd_Response",
            "summary": "Scribd\u0020response\u0020class",
            "url": "classes/Horde-Service-Scribd-Response.html"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Response\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.\u0020Do\u0020basic\u0020error\u0020checking\u0020on\u0020the\u0020resposne.",
            "url": "classes/Horde-Service-Scribd-Response.html#method___construct"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Response\u003A\u003AgetResultSet\u0028\u0029",
            "name": "getResultSet",
            "summary": "",
            "url": "classes/Horde-Service-Scribd-Response.html#method_getResultSet"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Result",
            "name": "Horde_Service_Scribd_Result",
            "summary": "Scribd\u0020result\u0020class",
            "url": "classes/Horde-Service-Scribd-Result.html"
        },                {
            "fqsen": "\\Horde_Service_Scribd_ResultSet",
            "name": "Horde_Service_Scribd_ResultSet",
            "summary": "Scribd\u0020result\u0020set\u0020class",
            "url": "classes/Horde-Service-Scribd-ResultSet.html"
        },                {
            "fqsen": "\\Horde_Service_Scribd_ResultSet\u003A\u003A_buildListItemCache\u0028\u0029",
            "name": "_buildListItemCache",
            "summary": "Cache\u0020the\u0020individual\u0020list\u0020items\u0020so\u0020they\u0020don\u0027t\u0020need\u0020to\u0020be\nsearched\u0020for\u0020on\u0020every\u0020operation.",
            "url": "classes/Horde-Service-Scribd-ResultSet.html#method__buildListItemCache"
        },                {
            "fqsen": "\\Horde_Service_Scribd_ResultSet\u003A\u003A\u0024_listItemClassName",
            "name": "_listItemClassName",
            "summary": "The\u0020classname\u0020for\u0020individual\u0020feed\u0020elements.",
            "url": "classes/Horde-Service-Scribd-ResultSet.html#property__listItemClassName"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Translation",
            "name": "Horde_Service_Scribd_Translation",
            "summary": "Horde_Date_Translation\u0020is\u0020the\u0020translation\u0020wrapper\u0020class\u0020for\u0020Horde_Date.",
            "url": "classes/Horde-Service-Scribd-Translation.html"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Translation\u003A\u003A\u0024_domain",
            "name": "_domain",
            "summary": "The\u0020translation\u0020domain",
            "url": "classes/Horde-Service-Scribd-Translation.html#property__domain"
        },                {
            "fqsen": "\\Horde_Service_Scribd_Translation\u003A\u003A\u0024_pearDirectory",
            "name": "_pearDirectory",
            "summary": "The\u0020absolute\u0020PEAR\u0020path\u0020to\u0020the\u0020translations\u0020for\u0020the\u0020default\u0020gettext\u0020handler.",
            "url": "classes/Horde-Service-Scribd-Translation.html#property__pearDirectory"
        },                {
            "fqsen": "\\Horde_Service_Scribd",
            "name": "Horde_Service_Scribd",
            "summary": "Scribd\u0020client\u0020class",
            "url": "classes/Horde-Service-Scribd.html"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003AsetHttpClient\u0028\u0029",
            "name": "setHttpClient",
            "summary": "Set\u0020the\u0020HTTP\u0020client\u0020instance",
            "url": "classes/Horde-Service-Scribd.html#method_setHttpClient"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003AgetHttpClient\u0028\u0029",
            "name": "getHttpClient",
            "summary": "Gets\u0020the\u0020HTTP\u0020client\u0020object.",
            "url": "classes/Horde-Service-Scribd.html#method_getHttpClient"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Service-Scribd.html#method___construct"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Upload\u0020a\u0020local\u0020file.",
            "url": "classes/Horde-Service-Scribd.html#method_upload"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003AuploadFromUrl\u0028\u0029",
            "name": "uploadFromUrl",
            "summary": "Upload\u0020a\u0020document\u0020from\u0020a\u0020publicly\u0020accessible\u0020URL.",
            "url": "classes/Horde-Service-Scribd.html#method_uploadFromUrl"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003AgetList\u0028\u0029",
            "name": "getList",
            "summary": "Return\u0020an\u0020iterator\u0020over\u0020the\u0020authorized\u0020user\u0027s\u0020documents.",
            "url": "classes/Horde-Service-Scribd.html#method_getList"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003AgetConversionStatus\u0028\u0029",
            "name": "getConversionStatus",
            "summary": "Get\u0020the\u0020current\u0020conversion\u0020status\u0020of\u0020a\u0020document.",
            "url": "classes/Horde-Service-Scribd.html#method_getConversionStatus"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003AgetSettings\u0028\u0029",
            "name": "getSettings",
            "summary": "Get\u0020a\u0020document\u0027s\u0020settings",
            "url": "classes/Horde-Service-Scribd.html#method_getSettings"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003AchangeSettings\u0028\u0029",
            "name": "changeSettings",
            "summary": "Change\u0020a\u0020document\u0027s\u0020settings.",
            "url": "classes/Horde-Service-Scribd.html#method_changeSettings"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020a\u0020document.",
            "url": "classes/Horde-Service-Scribd.html#method_delete"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020the\u0020Scribd\u0020database",
            "url": "classes/Horde-Service-Scribd.html#method_search"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Log\u0020in\u0020as\u0020a\u0020user",
            "url": "classes/Horde-Service-Scribd.html#method_login"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003Asignup\u0028\u0029",
            "name": "signup",
            "summary": "Sign\u0020up\u0020a\u0020new\u0020user",
            "url": "classes/Horde-Service-Scribd.html#method_signup"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003AnewRequest\u0028\u0029",
            "name": "newRequest",
            "summary": "Create\u0020an\u0020API\u0020request\u0020for\u0020\u0024method\u0020with\u0020\u0024args",
            "url": "classes/Horde-Service-Scribd.html#method_newRequest"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003AENDPOINT",
            "name": "ENDPOINT",
            "summary": "",
            "url": "classes/Horde-Service-Scribd.html#constant_ENDPOINT"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003A\u0024_httpClient",
            "name": "_httpClient",
            "summary": "HTTP\u0020client\u0020object\u0020to\u0020use\u0020for\u0020accessing\u0020the\u0020Scribd\u0020API.",
            "url": "classes/Horde-Service-Scribd.html#property__httpClient"
        },                {
            "fqsen": "\\Horde_Service_Scribd\u003A\u003A\u0024_config",
            "name": "_config",
            "summary": "",
            "url": "classes/Horde-Service-Scribd.html#property__config"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
