Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Argv_AmbiguousOptionException",
            "name": "Horde_Argv_AmbiguousOptionException",
            "summary": "Raised\u0020if\u0020an\u0020ambiguous\u0020option\u0020is\u0020seen\u0020on\u0020the\u0020command\u0020line.",
            "url": "classes/Horde-Argv-AmbiguousOptionException.html"
        },                {
            "fqsen": "\\Horde_Argv_AmbiguousOptionException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-AmbiguousOptionException.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_BadOptionException",
            "name": "Horde_Argv_BadOptionException",
            "summary": "Raised\u0020if\u0020an\u0020invalid\u0020option\u0020is\u0020seen\u0020on\u0020the\u0020command\u0020line.",
            "url": "classes/Horde-Argv-BadOptionException.html"
        },                {
            "fqsen": "\\Horde_Argv_BadOptionException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-BadOptionException.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_Exception",
            "name": "Horde_Argv_Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020Horde_Argv\u0020library.",
            "url": "classes/Horde-Argv-Exception.html"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter",
            "name": "Horde_Argv_HelpFormatter",
            "summary": "Provides\u0020HelpFormatter,\u0020used\u0020by\u0020Horde_Argv_Parser\u0020to\u0020generate\u0020formatted\nhelp\u0020text.",
            "url": "classes/Horde-Argv-HelpFormatter.html"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AsetParser\u0028\u0029",
            "name": "setParser",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_setParser"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AsetShortOptDelimiter\u0028\u0029",
            "name": "setShortOptDelimiter",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_setShortOptDelimiter"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AsetLongOptDelimiter\u0028\u0029",
            "name": "setLongOptDelimiter",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_setLongOptDelimiter"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003Aindent\u0028\u0029",
            "name": "indent",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_indent"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003Adedent\u0028\u0029",
            "name": "dedent",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_dedent"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AformatUsage\u0028\u0029",
            "name": "formatUsage",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatUsage"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AformatHeading\u0028\u0029",
            "name": "formatHeading",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatHeading"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AhighlightHeading\u0028\u0029",
            "name": "highlightHeading",
            "summary": "Highlights\u0020with\u0020the\u0020heading\u0020color.",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_highlightHeading"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003A_formatText\u0028\u0029",
            "name": "_formatText",
            "summary": "Format\u0020a\u0020paragraph\u0020of\u0020free\u002Dform\u0020text\u0020for\u0020inclusion\u0020in\u0020the\nhelp\u0020output\u0020at\u0020the\u0020current\u0020indentation\u0020level.",
            "url": "classes/Horde-Argv-HelpFormatter.html#method__formatText"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AformatDescription\u0028\u0029",
            "name": "formatDescription",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatDescription"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AformatEpilog\u0028\u0029",
            "name": "formatEpilog",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatEpilog"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AexpandDefault\u0028\u0029",
            "name": "expandDefault",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_expandDefault"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AformatOption\u0028\u0029",
            "name": "formatOption",
            "summary": "The\u0020help\u0020for\u0020each\u0020option\u0020consists\u0020of\u0020two\u0020parts\u003A\n\u0020\u0020\u002A\u0020the\u0020opt\u0020strings\u0020and\u0020metavars\n\u0020\u0020\u0020\u0020eg.\u0020\u0028\u0022\u002Dx\u0022,\u0020or\u0020\u0022\u002DfFILENAME,\u0020\u002D\u002Dfile\u003DFILENAME\u0022\u0029\n\u0020\u0020\u002A\u0020the\u0020user\u002Dsupplied\u0020help\u0020string\n\u0020\u0020\u0020\u0020eg.\u0020\u0028\u0022turn\u0020on\u0020expert\u0020mode\u0022,\u0020\u0022read\u0020data\u0020from\u0020FILENAME\u0022\u0029",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatOption"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AhighlightOption\u0028\u0029",
            "name": "highlightOption",
            "summary": "Highlights\u0020with\u0020the\u0020option\u0020color.",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_highlightOption"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AstoreOptionStrings\u0028\u0029",
            "name": "storeOptionStrings",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_storeOptionStrings"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003AformatOptionStrings\u0028\u0029",
            "name": "formatOptionStrings",
            "summary": "Return\u0020a\u0020comma\u002Dseparated\u0020list\u0020of\u0020option\u0020strings\u0020\u0026\u0020metavariables.",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatOptionStrings"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003ANO_DEFAULT_VALUE",
            "name": "NO_DEFAULT_VALUE",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#constant_NO_DEFAULT_VALUE"
        },                {
            "fqsen": "\\Horde_Argv_HelpFormatter\u003A\u003A\u0024parser",
            "name": "parser",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#property_parser"
        },                {
            "fqsen": "\\Horde_Argv_IndentedHelpFormatter",
            "name": "Horde_Argv_IndentedHelpFormatter",
            "summary": "Format\u0020help\u0020with\u0020indented\u0020section\u0020bodies.",
            "url": "classes/Horde-Argv-IndentedHelpFormatter.html"
        },                {
            "fqsen": "\\Horde_Argv_IndentedHelpFormatter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-IndentedHelpFormatter.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_IndentedHelpFormatter\u003A\u003AformatUsage\u0028\u0029",
            "name": "formatUsage",
            "summary": "",
            "url": "classes/Horde-Argv-IndentedHelpFormatter.html#method_formatUsage"
        },                {
            "fqsen": "\\Horde_Argv_IndentedHelpFormatter\u003A\u003AformatHeading\u0028\u0029",
            "name": "formatHeading",
            "summary": "",
            "url": "classes/Horde-Argv-IndentedHelpFormatter.html#method_formatHeading"
        },                {
            "fqsen": "\\Horde_Argv_Option",
            "name": "Horde_Argv_Option",
            "summary": "Defines\u0020the\u0020Option\u0020class\u0020and\u0020some\u0020standard\u0020value\u002Dchecking\u0020functions.",
            "url": "classes/Horde-Argv-Option.html"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003AparseNumber\u0028\u0029",
            "name": "parseNumber",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_parseNumber"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003AcheckBuiltin\u0028\u0029",
            "name": "checkBuiltin",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_checkBuiltin"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003AcheckChoice\u0028\u0029",
            "name": "checkChoice",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_checkChoice"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Argv-Option.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_checkOptStrings\u0028\u0029",
            "name": "_checkOptStrings",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkOptStrings"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_setOptStrings\u0028\u0029",
            "name": "_setOptStrings",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__setOptStrings"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_setAttrs\u0028\u0029",
            "name": "_setAttrs",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__setAttrs"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_checkAction\u0028\u0029",
            "name": "_checkAction",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkAction"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_checkType\u0028\u0029",
            "name": "_checkType",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkType"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_checkChoice\u0028\u0029",
            "name": "_checkChoice",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkChoice"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_checkDest\u0028\u0029",
            "name": "_checkDest",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkDest"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_checkConst\u0028\u0029",
            "name": "_checkConst",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkConst"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_checkNargs\u0028\u0029",
            "name": "_checkNargs",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkNargs"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A_checkCallback\u0028\u0029",
            "name": "_checkCallback",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkCallback"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method___toString"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003AtakesValue\u0028\u0029",
            "name": "takesValue",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_takesValue"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003AhasDefault\u0028\u0029",
            "name": "hasDefault",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_hasDefault"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003AgetOptString\u0028\u0029",
            "name": "getOptString",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_getOptString"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003AcheckValue\u0028\u0029",
            "name": "checkValue",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_checkValue"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003AconvertValue\u0028\u0029",
            "name": "convertValue",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_convertValue"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_process"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003AtakeAction\u0028\u0029",
            "name": "takeAction",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_takeAction"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003ASUPPRESS_HELP",
            "name": "SUPPRESS_HELP",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#constant_SUPPRESS_HELP"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003ASUPPRESS_USAGE",
            "name": "SUPPRESS_USAGE",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#constant_SUPPRESS_USAGE"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024NO_DEFAULT",
            "name": "NO_DEFAULT",
            "summary": "Not\u0020supplying\u0020a\u0020default\u0020is\u0020different\u0020from\u0020a\u0020default\u0020of\u0020None,\nso\u0020we\u0020need\u0020an\u0020explicit\u0020\u0027not\u0020supplied\u0027\u0020value.",
            "url": "classes/Horde-Argv-Option.html#property_NO_DEFAULT"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024ATTRS",
            "name": "ATTRS",
            "summary": "The\u0020list\u0020of\u0020instance\u0020attributes\u0020that\u0020may\u0020be\u0020set\u0020through\u0020keyword\u0020args\u0020to\nthe\u0020constructor.",
            "url": "classes/Horde-Argv-Option.html#property_ATTRS"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024ACTIONS",
            "name": "ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020allowed\u0020by\u0020option\u0020parsers.\u0020\u0020Explicitly\u0020listed\u0020here\u0020so\nthe\u0020constructor\u0020can\u0020validate\u0020its\u0020arguments.",
            "url": "classes/Horde-Argv-Option.html#property_ACTIONS"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024STORE_ACTIONS",
            "name": "STORE_ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020that\u0020involve\u0020storing\u0020a\u0020value\u0020somewhere\u003B\nalso\u0020listed\u0020just\u0020for\u0020constructor\u0020argument\u0020validation.\u0020\u0020\u0028If\nthe\u0020action\u0020is\u0020one\u0020of\u0020these,\u0020there\u0020must\u0020be\u0020a\u0020destination.\u0029",
            "url": "classes/Horde-Argv-Option.html#property_STORE_ACTIONS"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024TYPED_ACTIONS",
            "name": "TYPED_ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020for\u0020which\u0020it\u0020makes\u0020sense\u0020to\u0020supply\u0020a\u0020value\u0020type,\nie.\u0020which\u0020may\u0020consume\u0020an\u0020argument\u0020from\u0020the\u0020command\u0020line.",
            "url": "classes/Horde-Argv-Option.html#property_TYPED_ACTIONS"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024ALWAYS_TYPED_ACTIONS",
            "name": "ALWAYS_TYPED_ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020which\u0020\u002Arequire\u002A\u0020a\u0020value\u0020type,\u0020ie.\u0020that\u0020always\u0020consume\nan\u0020argument\u0020from\u0020the\u0020command\u0020line.",
            "url": "classes/Horde-Argv-Option.html#property_ALWAYS_TYPED_ACTIONS"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024CONST_ACTIONS",
            "name": "CONST_ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020which\u0020take\u0020a\u0020\u0027const\u0027\u0020attribute.",
            "url": "classes/Horde-Argv-Option.html#property_CONST_ACTIONS"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024TYPES",
            "name": "TYPES",
            "summary": "The\u0020set\u0020of\u0020known\u0020types\u0020for\u0020option\u0020parsers.",
            "url": "classes/Horde-Argv-Option.html#property_TYPES"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024TYPE_CHECKER",
            "name": "TYPE_CHECKER",
            "summary": "Dictionary\u0020of\u0020argument\u0020checking\u0020functions,\u0020which\u0020convert\u0020and\u0020validate\noption\u0020arguments\u0020according\u0020to\u0020the\u0020option\u0020type.",
            "url": "classes/Horde-Argv-Option.html#property_TYPE_CHECKER"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024CHECK_METHODS",
            "name": "CHECK_METHODS",
            "summary": "A\u0020list\u0020of\u0020unbound\u0020method\u0020objects.",
            "url": "classes/Horde-Argv-Option.html#property_CHECK_METHODS"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024shortOpts",
            "name": "shortOpts",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#property_shortOpts"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024longOpts",
            "name": "longOpts",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#property_longOpts"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024dest",
            "name": "dest",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#property_dest"
        },                {
            "fqsen": "\\Horde_Argv_Option\u003A\u003A\u0024default",
            "name": "default",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#property_default"
        },                {
            "fqsen": "\\Horde_Argv_OptionConflictException",
            "name": "Horde_Argv_OptionConflictException",
            "summary": "Raised\u0020if\u0020conflicting\u0020options\u0020are\u0020added\u0020to\u0020a\u0020Horde_Argv_Parser.",
            "url": "classes/Horde-Argv-OptionConflictException.html"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer",
            "name": "Horde_Argv_OptionContainer",
            "summary": "Abstract\u0020base\u0020class.",
            "url": "classes/Horde-Argv-OptionContainer.html"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020option\u0020list\u0020and\u0020related\u0020data\u0020structures.",
            "url": "classes/Horde-Argv-OptionContainer.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A_createOptionMappings\u0028\u0029",
            "name": "_createOptionMappings",
            "summary": "For\u0020use\u0020by\u0020Horde_Argv_Parser\u0020constructor\u0020\u002D\u002D\u0020create\u0020the\u0020master\noption\u0020mappings\u0020used\u0020by\u0020this\u0020Horde_Argv_Parser\u0020and\u0020all\nOptionGroups\u0020that\u0020it\u0020owns.",
            "url": "classes/Horde-Argv-OptionContainer.html#method__createOptionMappings"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A_shareOptionMappings\u0028\u0029",
            "name": "_shareOptionMappings",
            "summary": "For\u0020use\u0020by\u0020OptionGroup\u0020constructor\u0020\u002D\u002D\u0020use\u0020shared\u0020option\nmappings\u0020from\u0020the\u0020Horde_Argv_Parser\u0020that\u0020owns\u0020this\u0020OptionGroup.",
            "url": "classes/Horde-Argv-OptionContainer.html#method__shareOptionMappings"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AsetConflictHandler\u0028\u0029",
            "name": "setConflictHandler",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_setConflictHandler"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_setDescription"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_getDescription"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A_checkConflict\u0028\u0029",
            "name": "_checkConflict",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method__checkConflict"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AaddOption\u0028\u0029",
            "name": "addOption",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_addOption"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AaddOptions\u0028\u0029",
            "name": "addOptions",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_addOptions"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AgetOption\u0028\u0029",
            "name": "getOption",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_getOption"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AhasOption\u0028\u0029",
            "name": "hasOption",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_hasOption"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AremoveOption\u0028\u0029",
            "name": "removeOption",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_removeOption"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AformatOptionHelp\u0028\u0029",
            "name": "formatOptionHelp",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_formatOptionHelp"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AformatDescription\u0028\u0029",
            "name": "formatDescription",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_formatDescription"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003AformatHelp\u0028\u0029",
            "name": "formatHelp",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_formatHelp"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_description"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A\u0024optionList",
            "name": "optionList",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_optionList"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A\u0024optionClass",
            "name": "optionClass",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_optionClass"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A\u0024defaults",
            "name": "defaults",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_defaults"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A\u0024shortOpt",
            "name": "shortOpt",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_shortOpt"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A\u0024longOpt",
            "name": "longOpt",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_longOpt"
        },                {
            "fqsen": "\\Horde_Argv_OptionContainer\u003A\u003A\u0024conflictHandler",
            "name": "conflictHandler",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_conflictHandler"
        },                {
            "fqsen": "\\Horde_Argv_OptionException",
            "name": "Horde_Argv_OptionException",
            "summary": "Raised\u0020if\u0020an\u0020Option\u0020instance\u0020is\u0020created\u0020with\u0020invalid\u0020or\ninconsistent\u0020arguments.",
            "url": "classes/Horde-Argv-OptionException.html"
        },                {
            "fqsen": "\\Horde_Argv_OptionException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-OptionException.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_OptionGroup",
            "name": "Horde_Argv_OptionGroup",
            "summary": "An\u0020option\u0020group\u0020allows\u0020to\u0020group\u0020a\u0020number\u0020of\u0020options\u0020under\u0020a\u0020common\u0020header\nand\u0020description.",
            "url": "classes/Horde-Argv-OptionGroup.html"
        },                {
            "fqsen": "\\Horde_Argv_OptionGroup\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020option\u0020list\u0020and\u0020related\u0020data\u0020structures.",
            "url": "classes/Horde-Argv-OptionGroup.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_OptionGroup\u003A\u003A_createOptionList\u0028\u0029",
            "name": "_createOptionList",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#method__createOptionList"
        },                {
            "fqsen": "\\Horde_Argv_OptionGroup\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#method_setTitle"
        },                {
            "fqsen": "\\Horde_Argv_OptionGroup\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#method___destruct"
        },                {
            "fqsen": "\\Horde_Argv_OptionGroup\u003A\u003AformatHelp\u0028\u0029",
            "name": "formatHelp",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#method_formatHelp"
        },                {
            "fqsen": "\\Horde_Argv_OptionGroup\u003A\u003A\u0024_title",
            "name": "_title",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#property__title"
        },                {
            "fqsen": "\\Horde_Argv_OptionValueException",
            "name": "Horde_Argv_OptionValueException",
            "summary": "Raised\u0020if\u0020an\u0020invalid\u0020option\u0020value\u0020is\u0020encountered\u0020on\u0020the\u0020command",
            "url": "classes/Horde-Argv-OptionValueException.html"
        },                {
            "fqsen": "\\Horde_Argv_Parser",
            "name": "Horde_Argv_Parser",
            "summary": "Horde\u0020command\u002Dline\u0020argument\u0020parsing\u0020package.",
            "url": "classes/Horde-Argv-Parser.html"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020option\u0020list\u0020and\u0020related\u0020data\u0020structures.",
            "url": "classes/Horde-Argv-Parser.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_createOptionList\u0028\u0029",
            "name": "_createOptionList",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__createOptionList"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_addHelpOption\u0028\u0029",
            "name": "_addHelpOption",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__addHelpOption"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_addVersionOption\u0028\u0029",
            "name": "_addVersionOption",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__addVersionOption"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_populateOptionList\u0028\u0029",
            "name": "_populateOptionList",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__populateOptionList"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_initParsingState\u0028\u0029",
            "name": "_initParsingState",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__initParsingState"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AsetUsage\u0028\u0029",
            "name": "setUsage",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_setUsage"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AenableInterspersedArgs\u0028\u0029",
            "name": "enableInterspersedArgs",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_enableInterspersedArgs"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AdisableInterspersedArgs\u0028\u0029",
            "name": "disableInterspersedArgs",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_disableInterspersedArgs"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AsetDefault\u0028\u0029",
            "name": "setDefault",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_setDefault"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AsetDefaults\u0028\u0029",
            "name": "setDefaults",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_setDefaults"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_getAllOptions\u0028\u0029",
            "name": "_getAllOptions",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__getAllOptions"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AgetDefaultValues\u0028\u0029",
            "name": "getDefaultValues",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getDefaultValues"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AaddOptionGroup\u0028\u0029",
            "name": "addOptionGroup",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_addOptionGroup"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AgetOptionGroup\u0028\u0029",
            "name": "getOptionGroup",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getOptionGroup"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_getArgs\u0028\u0029",
            "name": "_getArgs",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__getArgs"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AparseArgs\u0028\u0029",
            "name": "parseArgs",
            "summary": "Parse\u0020the\u0020command\u002Dline\u0020options\u0020found\u0020in\u0020\u0027args\u0027\u0020\u0028default\u003A\n\u0020sys.argv\u005B1\u003A\u005D\u0029.\u0020\u0020Any\u0020errors\u0020result\u0020in\u0020a\u0020call\u0020to\u0020\u0027parserError\u0028\u0029\u0027,\u0020which\n\u0020by\u0020default\u0020prints\u0020the\u0020usage\u0020message\u0020to\u0020stderr\u0020and\u0020calls\n\u0020exit\u0028\u0029\u0020with\u0020an\u0020error\u0020message.\u0020\u0020On\u0020success\u0020returns\u0020a\u0020pair\n\u0020\u0028values,\u0020args\u0029\u0020where\u0020\u0027values\u0027\u0020is\u0020an\u0020Values\u0020instance\u0020\u0028with\u0020all\n\u0020your\u0020option\u0020values\u0029\u0020and\u0020\u0027args\u0027\u0020is\u0020the\u0020list\u0020of\u0020arguments\u0020left\n\u0020over\u0020after\u0020parsing\u0020options.",
            "url": "classes/Horde-Argv-Parser.html#method_parseArgs"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AcheckValues\u0028\u0029",
            "name": "checkValues",
            "summary": "Check\u0020that\u0020the\u0020supplied\u0020option\u0020values\u0020and\u0020leftover\u0020arguments\u0020are\n\u0020valid.\u0020\u0020Returns\u0020the\u0020option\u0020values\u0020and\u0020leftover\u0020arguments\n\u0020\u0028possibly\u0020adjusted,\u0020possibly\u0020completely\u0020new\u0020\u002D\u002D\u0020whatever\u0020you\n\u0020like\u0029.\u0020\u0020Default\u0020implementation\u0020just\u0020returns\u0020the\u0020passed\u002Din\n\u0020values\u003B\u0020subclasses\u0020may\u0020override\u0020as\u0020desired.",
            "url": "classes/Horde-Argv-Parser.html#method_checkValues"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_processArgs\u0028\u0029",
            "name": "_processArgs",
            "summary": "_process_args\u0028largs\u0020\u003A\u0020\u005Bstring\u005D,\n\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020rargs\u0020\u003A\u0020\u005Bstring\u005D,\n\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020values\u0020\u003A\u0020Values\u0029",
            "url": "classes/Horde-Argv-Parser.html#method__processArgs"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_matchLongOpt\u0028\u0029",
            "name": "_matchLongOpt",
            "summary": "opt\u0020\u003A\u0020string\u0029\u0020\u002D\u003E\u0020string",
            "url": "classes/Horde-Argv-Parser.html#method__matchLongOpt"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AmatchAbbrev\u0028\u0029",
            "name": "matchAbbrev",
            "summary": "\u0028s\u0020\u003A\u0020string,\u0020wordmap\u0020\u003A\u0020\u007Bstring\u0020\u003A\u0020Option\u007D\u0029\u0020\u002D\u003E\u0020string",
            "url": "classes/Horde-Argv-Parser.html#method_matchAbbrev"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_processLongOpt\u0028\u0029",
            "name": "_processLongOpt",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__processLongOpt"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A_processShortOpts\u0028\u0029",
            "name": "_processShortOpts",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__processShortOpts"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AgetProgName\u0028\u0029",
            "name": "getProgName",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getProgName"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AexpandProgName\u0028\u0029",
            "name": "expandProgName",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_expandProgName"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getDescription"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AparserExit\u0028\u0029",
            "name": "parserExit",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_parserExit"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AparserError\u0028\u0029",
            "name": "parserError",
            "summary": "Print\u0020a\u0020usage\u0020message\u0020incorporating\u0020\u0024msg\u0020to\u0020stderr\u0020and\u0020exit.",
            "url": "classes/Horde-Argv-Parser.html#method_parserError"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AgetUsage\u0028\u0029",
            "name": "getUsage",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getUsage"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AprintUsage\u0028\u0029",
            "name": "printUsage",
            "summary": "\u0028file\u0020\u003A\u0020file\u0020\u003D\u0020stdout\u0029",
            "url": "classes/Horde-Argv-Parser.html#method_printUsage"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getVersion"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AprintVersion\u0028\u0029",
            "name": "printVersion",
            "summary": "file\u0020\u003A\u0020file\u0020\u003D\u0020stdout",
            "url": "classes/Horde-Argv-Parser.html#method_printVersion"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AformatOptionHelp\u0028\u0029",
            "name": "formatOptionHelp",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_formatOptionHelp"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AformatEpilog\u0028\u0029",
            "name": "formatEpilog",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_formatEpilog"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AformatHelp\u0028\u0029",
            "name": "formatHelp",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_formatHelp"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003AprintHelp\u0028\u0029",
            "name": "printHelp",
            "summary": "file\u0020\u003A\u0020file\u0020\u003D\u0020stdout",
            "url": "classes/Horde-Argv-Parser.html#method_printHelp"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A\u0024standardOptionList",
            "name": "standardOptionList",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#property_standardOptionList"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A\u0024_usage",
            "name": "_usage",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#property__usage"
        },                {
            "fqsen": "\\Horde_Argv_Parser\u003A\u003A\u0024optionGroups",
            "name": "optionGroups",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#property_optionGroups"
        },                {
            "fqsen": "\\Horde_Argv_TitledHelpFormatter",
            "name": "Horde_Argv_TitledHelpFormatter",
            "summary": "Format\u0020help\u0020with\u0020underlined\u0020section\u0020headers.",
            "url": "classes/Horde-Argv-TitledHelpFormatter.html"
        },                {
            "fqsen": "\\Horde_Argv_TitledHelpFormatter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-TitledHelpFormatter.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_TitledHelpFormatter\u003A\u003AformatUsage\u0028\u0029",
            "name": "formatUsage",
            "summary": "",
            "url": "classes/Horde-Argv-TitledHelpFormatter.html#method_formatUsage"
        },                {
            "fqsen": "\\Horde_Argv_TitledHelpFormatter\u003A\u003AformatHeading\u0028\u0029",
            "name": "formatHeading",
            "summary": "",
            "url": "classes/Horde-Argv-TitledHelpFormatter.html#method_formatHeading"
        },                {
            "fqsen": "\\Horde_Argv_Translation",
            "name": "Horde_Argv_Translation",
            "summary": "Horde_Argv_Translation\u0020is\u0020the\u0020translation\u0020wrapper\u0020class\u0020for\u0020Horde_Argv.",
            "url": "classes/Horde-Argv-Translation.html"
        },                {
            "fqsen": "\\Horde_Argv_Translation\u003A\u003A\u0024_domain",
            "name": "_domain",
            "summary": "The\u0020translation\u0020domain",
            "url": "classes/Horde-Argv-Translation.html#property__domain"
        },                {
            "fqsen": "\\Horde_Argv_Translation\u003A\u003A\u0024_pearDirectory",
            "name": "_pearDirectory",
            "summary": "The\u0020absolute\u0020PEAR\u0020path\u0020to\u0020the\u0020translations\u0020for\u0020the\u0020default\u0020gettext\u0020handler.",
            "url": "classes/Horde-Argv-Translation.html#property__pearDirectory"
        },                {
            "fqsen": "\\Horde_Argv_Values",
            "name": "Horde_Argv_Values",
            "summary": "Result\u0020hash\u0020for\u0020Horde_Argv_Parser",
            "url": "classes/Horde-Argv-Values.html"
        },                {
            "fqsen": "\\Horde_Argv_Values\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method___construct"
        },                {
            "fqsen": "\\Horde_Argv_Values\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method___toString"
        },                {
            "fqsen": "\\Horde_Argv_Values\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_offsetExists"
        },                {
            "fqsen": "\\Horde_Argv_Values\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_offsetGet"
        },                {
            "fqsen": "\\Horde_Argv_Values\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_offsetSet"
        },                {
            "fqsen": "\\Horde_Argv_Values\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_offsetUnset"
        },                {
            "fqsen": "\\Horde_Argv_Values\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_getIterator"
        },                {
            "fqsen": "\\Horde_Argv_Values\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_count"
        },                {
            "fqsen": "\\Horde_Argv_Values\u003A\u003AensureValue\u0028\u0029",
            "name": "ensureValue",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_ensureValue"
        },                {
            "fqsen": "\\Horde\\Argv\\AmbiguousOptionException",
            "name": "AmbiguousOptionException",
            "summary": "Raised\u0020if\u0020an\u0020ambiguous\u0020option\u0020is\u0020seen\u0020on\u0020the\u0020command\u0020line.",
            "url": "classes/Horde-Argv-AmbiguousOptionException.html"
        },                {
            "fqsen": "\\Horde\\Argv\\AmbiguousOptionException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-AmbiguousOptionException.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\HBadOptionException",
            "name": "HBadOptionException",
            "summary": "Raised\u0020if\u0020an\u0020invalid\u0020option\u0020is\u0020seen\u0020on\u0020the\u0020command\u0020line.",
            "url": "classes/Horde-Argv-HBadOptionException.html"
        },                {
            "fqsen": "\\Horde\\Argv\\HBadOptionException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-HBadOptionException.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\Exception",
            "name": "Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020Horde_Argv\u0020library.",
            "url": "classes/Horde-Argv-Exception.html"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter",
            "name": "HelpFormatter",
            "summary": "Provides\u0020HelpFormatter,\u0020used\u0020by\u0020Horde_Argv_Parser\u0020to\u0020generate\u0020formatted\nhelp\u0020text.",
            "url": "classes/Horde-Argv-HelpFormatter.html"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AsetParser\u0028\u0029",
            "name": "setParser",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_setParser"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AsetShortOptDelimiter\u0028\u0029",
            "name": "setShortOptDelimiter",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_setShortOptDelimiter"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AsetLongOptDelimiter\u0028\u0029",
            "name": "setLongOptDelimiter",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_setLongOptDelimiter"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003Aindent\u0028\u0029",
            "name": "indent",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_indent"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003Adedent\u0028\u0029",
            "name": "dedent",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_dedent"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AformatUsage\u0028\u0029",
            "name": "formatUsage",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatUsage"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AformatHeading\u0028\u0029",
            "name": "formatHeading",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatHeading"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AhighlightHeading\u0028\u0029",
            "name": "highlightHeading",
            "summary": "Highlights\u0020with\u0020the\u0020heading\u0020color.",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_highlightHeading"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003A_formatText\u0028\u0029",
            "name": "_formatText",
            "summary": "Format\u0020a\u0020paragraph\u0020of\u0020free\u002Dform\u0020text\u0020for\u0020inclusion\u0020in\u0020the\nhelp\u0020output\u0020at\u0020the\u0020current\u0020indentation\u0020level.",
            "url": "classes/Horde-Argv-HelpFormatter.html#method__formatText"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AformatDescription\u0028\u0029",
            "name": "formatDescription",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatDescription"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AformatEpilog\u0028\u0029",
            "name": "formatEpilog",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatEpilog"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AexpandDefault\u0028\u0029",
            "name": "expandDefault",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_expandDefault"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AformatOption\u0028\u0029",
            "name": "formatOption",
            "summary": "The\u0020help\u0020for\u0020each\u0020option\u0020consists\u0020of\u0020two\u0020parts\u003A\n\u0020\u0020\u002A\u0020the\u0020opt\u0020strings\u0020and\u0020metavars\n\u0020\u0020\u0020\u0020eg.\u0020\u0028\u0022\u002Dx\u0022,\u0020or\u0020\u0022\u002DfFILENAME,\u0020\u002D\u002Dfile\u003DFILENAME\u0022\u0029\n\u0020\u0020\u002A\u0020the\u0020user\u002Dsupplied\u0020help\u0020string\n\u0020\u0020\u0020\u0020eg.\u0020\u0028\u0022turn\u0020on\u0020expert\u0020mode\u0022,\u0020\u0022read\u0020data\u0020from\u0020FILENAME\u0022\u0029",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatOption"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AhighlightOption\u0028\u0029",
            "name": "highlightOption",
            "summary": "Highlights\u0020with\u0020the\u0020option\u0020color.",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_highlightOption"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AstoreOptionStrings\u0028\u0029",
            "name": "storeOptionStrings",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_storeOptionStrings"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003AformatOptionStrings\u0028\u0029",
            "name": "formatOptionStrings",
            "summary": "Return\u0020a\u0020comma\u002Dseparated\u0020list\u0020of\u0020option\u0020strings\u0020\u0026\u0020metavariables.",
            "url": "classes/Horde-Argv-HelpFormatter.html#method_formatOptionStrings"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003ANO_DEFAULT_VALUE",
            "name": "NO_DEFAULT_VALUE",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#constant_NO_DEFAULT_VALUE"
        },                {
            "fqsen": "\\Horde\\Argv\\HelpFormatter\u003A\u003A\u0024parser",
            "name": "parser",
            "summary": "",
            "url": "classes/Horde-Argv-HelpFormatter.html#property_parser"
        },                {
            "fqsen": "\\Horde\\Argv\\Horde_Argv_IndentedHelpFormatter",
            "name": "Horde_Argv_IndentedHelpFormatter",
            "summary": "Format\u0020help\u0020with\u0020indented\u0020section\u0020bodies.",
            "url": "classes/Horde-Argv-Horde-Argv-IndentedHelpFormatter.html"
        },                {
            "fqsen": "\\Horde\\Argv\\Horde_Argv_IndentedHelpFormatter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-Horde-Argv-IndentedHelpFormatter.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\Horde_Argv_IndentedHelpFormatter\u003A\u003AformatUsage\u0028\u0029",
            "name": "formatUsage",
            "summary": "",
            "url": "classes/Horde-Argv-Horde-Argv-IndentedHelpFormatter.html#method_formatUsage"
        },                {
            "fqsen": "\\Horde\\Argv\\Horde_Argv_IndentedHelpFormatter\u003A\u003AformatHeading\u0028\u0029",
            "name": "formatHeading",
            "summary": "",
            "url": "classes/Horde-Argv-Horde-Argv-IndentedHelpFormatter.html#method_formatHeading"
        },                {
            "fqsen": "\\Horde\\Argv\\Option",
            "name": "Option",
            "summary": "Defines\u0020the\u0020Option\u0020class\u0020and\u0020some\u0020standard\u0020value\u002Dchecking\u0020functions.",
            "url": "classes/Horde-Argv-Option.html"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003AparseNumber\u0028\u0029",
            "name": "parseNumber",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_parseNumber"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003AcheckBuiltin\u0028\u0029",
            "name": "checkBuiltin",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_checkBuiltin"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003AcheckChoice\u0028\u0029",
            "name": "checkChoice",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_checkChoice"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Argv-Option.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_checkOptStrings\u0028\u0029",
            "name": "_checkOptStrings",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkOptStrings"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_setOptStrings\u0028\u0029",
            "name": "_setOptStrings",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__setOptStrings"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_setAttrs\u0028\u0029",
            "name": "_setAttrs",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__setAttrs"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_checkAction\u0028\u0029",
            "name": "_checkAction",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkAction"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_checkType\u0028\u0029",
            "name": "_checkType",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkType"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_checkChoice\u0028\u0029",
            "name": "_checkChoice",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkChoice"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_checkDest\u0028\u0029",
            "name": "_checkDest",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkDest"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_checkConst\u0028\u0029",
            "name": "_checkConst",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkConst"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_checkNargs\u0028\u0029",
            "name": "_checkNargs",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkNargs"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A_checkCallback\u0028\u0029",
            "name": "_checkCallback",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method__checkCallback"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003AtakesValue\u0028\u0029",
            "name": "takesValue",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_takesValue"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003AhasDefault\u0028\u0029",
            "name": "hasDefault",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_hasDefault"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003AgetOptString\u0028\u0029",
            "name": "getOptString",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_getOptString"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003AcheckValue\u0028\u0029",
            "name": "checkValue",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_checkValue"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003AconvertValue\u0028\u0029",
            "name": "convertValue",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_convertValue"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_process"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003AtakeAction\u0028\u0029",
            "name": "takeAction",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#method_takeAction"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003ASUPPRESS_HELP",
            "name": "SUPPRESS_HELP",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#constant_SUPPRESS_HELP"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003ASUPPRESS_USAGE",
            "name": "SUPPRESS_USAGE",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#constant_SUPPRESS_USAGE"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024NO_DEFAULT",
            "name": "NO_DEFAULT",
            "summary": "Not\u0020supplying\u0020a\u0020default\u0020is\u0020different\u0020from\u0020a\u0020default\u0020of\u0020None,\nso\u0020we\u0020need\u0020an\u0020explicit\u0020\u0027not\u0020supplied\u0027\u0020value.",
            "url": "classes/Horde-Argv-Option.html#property_NO_DEFAULT"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024ATTRS",
            "name": "ATTRS",
            "summary": "The\u0020list\u0020of\u0020instance\u0020attributes\u0020that\u0020may\u0020be\u0020set\u0020through\u0020keyword\u0020args\u0020to\nthe\u0020constructor.",
            "url": "classes/Horde-Argv-Option.html#property_ATTRS"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024ACTIONS",
            "name": "ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020allowed\u0020by\u0020option\u0020parsers.\u0020\u0020Explicitly\u0020listed\u0020here\u0020so\nthe\u0020constructor\u0020can\u0020validate\u0020its\u0020arguments.",
            "url": "classes/Horde-Argv-Option.html#property_ACTIONS"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024STORE_ACTIONS",
            "name": "STORE_ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020that\u0020involve\u0020storing\u0020a\u0020value\u0020somewhere\u003B\nalso\u0020listed\u0020just\u0020for\u0020constructor\u0020argument\u0020validation.\u0020\u0020\u0028If\nthe\u0020action\u0020is\u0020one\u0020of\u0020these,\u0020there\u0020must\u0020be\u0020a\u0020destination.\u0029",
            "url": "classes/Horde-Argv-Option.html#property_STORE_ACTIONS"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024TYPED_ACTIONS",
            "name": "TYPED_ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020for\u0020which\u0020it\u0020makes\u0020sense\u0020to\u0020supply\u0020a\u0020value\u0020type,\nie.\u0020which\u0020may\u0020consume\u0020an\u0020argument\u0020from\u0020the\u0020command\u0020line.",
            "url": "classes/Horde-Argv-Option.html#property_TYPED_ACTIONS"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024ALWAYS_TYPED_ACTIONS",
            "name": "ALWAYS_TYPED_ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020which\u0020\u002Arequire\u002A\u0020a\u0020value\u0020type,\u0020ie.\u0020that\u0020always\u0020consume\nan\u0020argument\u0020from\u0020the\u0020command\u0020line.",
            "url": "classes/Horde-Argv-Option.html#property_ALWAYS_TYPED_ACTIONS"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024CONST_ACTIONS",
            "name": "CONST_ACTIONS",
            "summary": "The\u0020set\u0020of\u0020actions\u0020which\u0020take\u0020a\u0020\u0027const\u0027\u0020attribute.",
            "url": "classes/Horde-Argv-Option.html#property_CONST_ACTIONS"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024TYPES",
            "name": "TYPES",
            "summary": "The\u0020set\u0020of\u0020known\u0020types\u0020for\u0020option\u0020parsers.",
            "url": "classes/Horde-Argv-Option.html#property_TYPES"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024TYPE_CHECKER",
            "name": "TYPE_CHECKER",
            "summary": "Dictionary\u0020of\u0020argument\u0020checking\u0020functions,\u0020which\u0020convert\u0020and\u0020validate\noption\u0020arguments\u0020according\u0020to\u0020the\u0020option\u0020type.",
            "url": "classes/Horde-Argv-Option.html#property_TYPE_CHECKER"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024CHECK_METHODS",
            "name": "CHECK_METHODS",
            "summary": "A\u0020list\u0020of\u0020unbound\u0020method\u0020objects.",
            "url": "classes/Horde-Argv-Option.html#property_CHECK_METHODS"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024shortOpts",
            "name": "shortOpts",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#property_shortOpts"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024longOpts",
            "name": "longOpts",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#property_longOpts"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024dest",
            "name": "dest",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#property_dest"
        },                {
            "fqsen": "\\Horde\\Argv\\Option\u003A\u003A\u0024default",
            "name": "default",
            "summary": "",
            "url": "classes/Horde-Argv-Option.html#property_default"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionConflictException",
            "name": "OptionConflictException",
            "summary": "Raised\u0020if\u0020conflicting\u0020options\u0020are\u0020added\u0020to\u0020a\u0020Horde_Argv_Parser.",
            "url": "classes/Horde-Argv-OptionConflictException.html"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer",
            "name": "OptionContainer",
            "summary": "Abstract\u0020base\u0020class.",
            "url": "classes/Horde-Argv-OptionContainer.html"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020option\u0020list\u0020and\u0020related\u0020data\u0020structures.",
            "url": "classes/Horde-Argv-OptionContainer.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A_createOptionMappings\u0028\u0029",
            "name": "_createOptionMappings",
            "summary": "For\u0020use\u0020by\u0020Horde_Argv_Parser\u0020constructor\u0020\u002D\u002D\u0020create\u0020the\u0020master\noption\u0020mappings\u0020used\u0020by\u0020this\u0020Horde_Argv_Parser\u0020and\u0020all\nOptionGroups\u0020that\u0020it\u0020owns.",
            "url": "classes/Horde-Argv-OptionContainer.html#method__createOptionMappings"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A_shareOptionMappings\u0028\u0029",
            "name": "_shareOptionMappings",
            "summary": "For\u0020use\u0020by\u0020OptionGroup\u0020constructor\u0020\u002D\u002D\u0020use\u0020shared\u0020option\nmappings\u0020from\u0020the\u0020Horde_Argv_Parser\u0020that\u0020owns\u0020this\u0020OptionGroup.",
            "url": "classes/Horde-Argv-OptionContainer.html#method__shareOptionMappings"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AsetConflictHandler\u0028\u0029",
            "name": "setConflictHandler",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_setConflictHandler"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_setDescription"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_getDescription"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A_checkConflict\u0028\u0029",
            "name": "_checkConflict",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method__checkConflict"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AaddOption\u0028\u0029",
            "name": "addOption",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_addOption"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AaddOptions\u0028\u0029",
            "name": "addOptions",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_addOptions"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AgetOption\u0028\u0029",
            "name": "getOption",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_getOption"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AhasOption\u0028\u0029",
            "name": "hasOption",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_hasOption"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AremoveOption\u0028\u0029",
            "name": "removeOption",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_removeOption"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AformatOptionHelp\u0028\u0029",
            "name": "formatOptionHelp",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_formatOptionHelp"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AformatDescription\u0028\u0029",
            "name": "formatDescription",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_formatDescription"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003AformatHelp\u0028\u0029",
            "name": "formatHelp",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#method_formatHelp"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_description"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A\u0024optionList",
            "name": "optionList",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_optionList"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A\u0024optionClass",
            "name": "optionClass",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_optionClass"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A\u0024defaults",
            "name": "defaults",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_defaults"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A\u0024shortOpt",
            "name": "shortOpt",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_shortOpt"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A\u0024longOpt",
            "name": "longOpt",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_longOpt"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionContainer\u003A\u003A\u0024conflictHandler",
            "name": "conflictHandler",
            "summary": "",
            "url": "classes/Horde-Argv-OptionContainer.html#property_conflictHandler"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionException",
            "name": "OptionException",
            "summary": "Raised\u0020if\u0020an\u0020Option\u0020instance\u0020is\u0020created\u0020with\u0020invalid\u0020or\ninconsistent\u0020arguments.",
            "url": "classes/Horde-Argv-OptionException.html"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-OptionException.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionGroup",
            "name": "OptionGroup",
            "summary": "An\u0020option\u0020group\u0020allows\u0020to\u0020group\u0020a\u0020number\u0020of\u0020options\u0020under\u0020a\u0020common\u0020header\nand\u0020description.",
            "url": "classes/Horde-Argv-OptionGroup.html"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionGroup\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020option\u0020list\u0020and\u0020related\u0020data\u0020structures.",
            "url": "classes/Horde-Argv-OptionGroup.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionGroup\u003A\u003A_createOptionList\u0028\u0029",
            "name": "_createOptionList",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#method__createOptionList"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionGroup\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#method_setTitle"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionGroup\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#method___destruct"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionGroup\u003A\u003AformatHelp\u0028\u0029",
            "name": "formatHelp",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#method_formatHelp"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionGroup\u003A\u003A\u0024_title",
            "name": "_title",
            "summary": "",
            "url": "classes/Horde-Argv-OptionGroup.html#property__title"
        },                {
            "fqsen": "\\Horde\\Argv\\OptionValueException",
            "name": "OptionValueException",
            "summary": "Raised\u0020if\u0020an\u0020invalid\u0020option\u0020value\u0020is\u0020encountered\u0020on\u0020the\u0020command",
            "url": "classes/Horde-Argv-OptionValueException.html"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser",
            "name": "Parser",
            "summary": "Horde\u0020command\u002Dline\u0020argument\u0020parsing\u0020package.",
            "url": "classes/Horde-Argv-Parser.html"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Initialize\u0020the\u0020option\u0020list\u0020and\u0020related\u0020data\u0020structures.",
            "url": "classes/Horde-Argv-Parser.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_createOptionList\u0028\u0029",
            "name": "_createOptionList",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__createOptionList"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_addHelpOption\u0028\u0029",
            "name": "_addHelpOption",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__addHelpOption"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_addVersionOption\u0028\u0029",
            "name": "_addVersionOption",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__addVersionOption"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_populateOptionList\u0028\u0029",
            "name": "_populateOptionList",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__populateOptionList"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_initParsingState\u0028\u0029",
            "name": "_initParsingState",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__initParsingState"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AsetUsage\u0028\u0029",
            "name": "setUsage",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_setUsage"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AenableInterspersedArgs\u0028\u0029",
            "name": "enableInterspersedArgs",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_enableInterspersedArgs"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AdisableInterspersedArgs\u0028\u0029",
            "name": "disableInterspersedArgs",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_disableInterspersedArgs"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AsetDefault\u0028\u0029",
            "name": "setDefault",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_setDefault"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AsetDefaults\u0028\u0029",
            "name": "setDefaults",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_setDefaults"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_getAllOptions\u0028\u0029",
            "name": "_getAllOptions",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__getAllOptions"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AgetDefaultValues\u0028\u0029",
            "name": "getDefaultValues",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getDefaultValues"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AaddOptionGroup\u0028\u0029",
            "name": "addOptionGroup",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_addOptionGroup"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AgetOptionGroup\u0028\u0029",
            "name": "getOptionGroup",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getOptionGroup"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_getArgs\u0028\u0029",
            "name": "_getArgs",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__getArgs"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AparseArgs\u0028\u0029",
            "name": "parseArgs",
            "summary": "Parse\u0020the\u0020command\u002Dline\u0020options\u0020found\u0020in\u0020\u0027args\u0027\u0020\u0028default\u003A\n\u0020sys.argv\u005B1\u003A\u005D\u0029.\u0020\u0020Any\u0020errors\u0020result\u0020in\u0020a\u0020call\u0020to\u0020\u0027parserError\u0028\u0029\u0027,\u0020which\n\u0020by\u0020default\u0020prints\u0020the\u0020usage\u0020message\u0020to\u0020stderr\u0020and\u0020calls\n\u0020exit\u0028\u0029\u0020with\u0020an\u0020error\u0020message.\u0020\u0020On\u0020success\u0020returns\u0020a\u0020pair\n\u0020\u0028values,\u0020args\u0029\u0020where\u0020\u0027values\u0027\u0020is\u0020an\u0020Values\u0020instance\u0020\u0028with\u0020all\n\u0020your\u0020option\u0020values\u0029\u0020and\u0020\u0027args\u0027\u0020is\u0020the\u0020list\u0020of\u0020arguments\u0020left\n\u0020over\u0020after\u0020parsing\u0020options.",
            "url": "classes/Horde-Argv-Parser.html#method_parseArgs"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AcheckValues\u0028\u0029",
            "name": "checkValues",
            "summary": "Check\u0020that\u0020the\u0020supplied\u0020option\u0020values\u0020and\u0020leftover\u0020arguments\u0020are\n\u0020valid.\u0020\u0020Returns\u0020the\u0020option\u0020values\u0020and\u0020leftover\u0020arguments\n\u0020\u0028possibly\u0020adjusted,\u0020possibly\u0020completely\u0020new\u0020\u002D\u002D\u0020whatever\u0020you\n\u0020like\u0029.\u0020\u0020Default\u0020implementation\u0020just\u0020returns\u0020the\u0020passed\u002Din\n\u0020values\u003B\u0020subclasses\u0020may\u0020override\u0020as\u0020desired.",
            "url": "classes/Horde-Argv-Parser.html#method_checkValues"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_processArgs\u0028\u0029",
            "name": "_processArgs",
            "summary": "_process_args\u0028largs\u0020\u003A\u0020\u005Bstring\u005D,\n\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020rargs\u0020\u003A\u0020\u005Bstring\u005D,\n\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020values\u0020\u003A\u0020Values\u0029",
            "url": "classes/Horde-Argv-Parser.html#method__processArgs"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_matchLongOpt\u0028\u0029",
            "name": "_matchLongOpt",
            "summary": "opt\u0020\u003A\u0020string\u0029\u0020\u002D\u003E\u0020string",
            "url": "classes/Horde-Argv-Parser.html#method__matchLongOpt"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AmatchAbbrev\u0028\u0029",
            "name": "matchAbbrev",
            "summary": "\u0028s\u0020\u003A\u0020string,\u0020wordmap\u0020\u003A\u0020\u007Bstring\u0020\u003A\u0020Option\u007D\u0029\u0020\u002D\u003E\u0020string",
            "url": "classes/Horde-Argv-Parser.html#method_matchAbbrev"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_processLongOpt\u0028\u0029",
            "name": "_processLongOpt",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__processLongOpt"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A_processShortOpts\u0028\u0029",
            "name": "_processShortOpts",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method__processShortOpts"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AgetProgName\u0028\u0029",
            "name": "getProgName",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getProgName"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AexpandProgName\u0028\u0029",
            "name": "expandProgName",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_expandProgName"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getDescription"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AparserExit\u0028\u0029",
            "name": "parserExit",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_parserExit"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AparserError\u0028\u0029",
            "name": "parserError",
            "summary": "Print\u0020a\u0020usage\u0020message\u0020incorporating\u0020\u0024msg\u0020to\u0020stderr\u0020and\u0020exit.",
            "url": "classes/Horde-Argv-Parser.html#method_parserError"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AgetUsage\u0028\u0029",
            "name": "getUsage",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getUsage"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AprintUsage\u0028\u0029",
            "name": "printUsage",
            "summary": "\u0028file\u0020\u003A\u0020file\u0020\u003D\u0020stdout\u0029",
            "url": "classes/Horde-Argv-Parser.html#method_printUsage"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_getVersion"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AprintVersion\u0028\u0029",
            "name": "printVersion",
            "summary": "file\u0020\u003A\u0020file\u0020\u003D\u0020stdout",
            "url": "classes/Horde-Argv-Parser.html#method_printVersion"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AformatOptionHelp\u0028\u0029",
            "name": "formatOptionHelp",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_formatOptionHelp"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AformatEpilog\u0028\u0029",
            "name": "formatEpilog",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_formatEpilog"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AformatHelp\u0028\u0029",
            "name": "formatHelp",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#method_formatHelp"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003AprintHelp\u0028\u0029",
            "name": "printHelp",
            "summary": "file\u0020\u003A\u0020file\u0020\u003D\u0020stdout",
            "url": "classes/Horde-Argv-Parser.html#method_printHelp"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A\u0024standardOptionList",
            "name": "standardOptionList",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#property_standardOptionList"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A\u0024_usage",
            "name": "_usage",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#property__usage"
        },                {
            "fqsen": "\\Horde\\Argv\\Parser\u003A\u003A\u0024optionGroups",
            "name": "optionGroups",
            "summary": "",
            "url": "classes/Horde-Argv-Parser.html#property_optionGroups"
        },                {
            "fqsen": "\\Horde\\Argv\\TitledHelpFormatter",
            "name": "TitledHelpFormatter",
            "summary": "Format\u0020help\u0020with\u0020underlined\u0020section\u0020headers.",
            "url": "classes/Horde-Argv-TitledHelpFormatter.html"
        },                {
            "fqsen": "\\Horde\\Argv\\TitledHelpFormatter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-TitledHelpFormatter.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\TitledHelpFormatter\u003A\u003AformatUsage\u0028\u0029",
            "name": "formatUsage",
            "summary": "",
            "url": "classes/Horde-Argv-TitledHelpFormatter.html#method_formatUsage"
        },                {
            "fqsen": "\\Horde\\Argv\\TitledHelpFormatter\u003A\u003AformatHeading\u0028\u0029",
            "name": "formatHeading",
            "summary": "",
            "url": "classes/Horde-Argv-TitledHelpFormatter.html#method_formatHeading"
        },                {
            "fqsen": "\\Horde\\Argv\\Translation",
            "name": "Translation",
            "summary": "Horde_Argv_Translation\u0020is\u0020the\u0020translation\u0020wrapper\u0020class\u0020for\u0020Horde_Argv.",
            "url": "classes/Horde-Argv-Translation.html"
        },                {
            "fqsen": "\\Horde\\Argv\\Translation\u003A\u003A\u0024_domain",
            "name": "_domain",
            "summary": "The\u0020translation\u0020domain",
            "url": "classes/Horde-Argv-Translation.html#property__domain"
        },                {
            "fqsen": "\\Horde\\Argv\\Translation\u003A\u003A\u0024_pearDirectory",
            "name": "_pearDirectory",
            "summary": "The\u0020absolute\u0020PEAR\u0020path\u0020to\u0020the\u0020translations\u0020for\u0020the\u0020default\u0020gettext\u0020handler.",
            "url": "classes/Horde-Argv-Translation.html#property__pearDirectory"
        },                {
            "fqsen": "\\Horde\\Argv\\Values",
            "name": "Values",
            "summary": "Result\u0020hash\u0020for\u0020Horde_Argv_Parser",
            "url": "classes/Horde-Argv-Values.html"
        },                {
            "fqsen": "\\Horde\\Argv\\Values\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Argv\\Values\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Argv\\Values\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_offsetExists"
        },                {
            "fqsen": "\\Horde\\Argv\\Values\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_offsetGet"
        },                {
            "fqsen": "\\Horde\\Argv\\Values\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_offsetSet"
        },                {
            "fqsen": "\\Horde\\Argv\\Values\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_offsetUnset"
        },                {
            "fqsen": "\\Horde\\Argv\\Values\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_getIterator"
        },                {
            "fqsen": "\\Horde\\Argv\\Values\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_count"
        },                {
            "fqsen": "\\Horde\\Argv\\Values\u003A\u003AensureValue\u0028\u0029",
            "name": "ensureValue",
            "summary": "",
            "url": "classes/Horde-Argv-Values.html#method_ensureValue"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Argv",
            "name": "Argv",
            "summary": "",
            "url": "namespaces/horde-argv.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
