Search.appendIndex(
    [
                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath",
            "name": "AbsolutePath",
            "summary": "Represent\u0020and\u0020manipulate\u0020unixoid\u0020paths\u0020as\u0020immutables.",
            "url": "classes/Horde-Filesystem-AbsolutePath.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "Normalize\u0020a\u0020path",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003AaddTrailingSlash\u0028\u0029",
            "name": "addTrailingSlash",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method_addTrailingSlash"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003AremoveTrailingSlash\u0028\u0029",
            "name": "removeTrailingSlash",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method_removeTrailingSlash"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003AlevelUp\u0028\u0029",
            "name": "levelUp",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method_levelUp"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003A\u0024path",
            "name": "path",
            "summary": "TODO\u0020PHP\u00208.1\u0020make\u0020readonly",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#property_path"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathFromCurrentDirTrait",
            "name": "AbsolutePathFromCurrentDirTrait",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePathFromCurrentDirTrait.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathFromCurrentDirTrait\u003A\u003AfromCurrentDir\u0028\u0029",
            "name": "fromCurrentDir",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePathFromCurrentDirTrait.html#method_fromCurrentDir"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathInterface",
            "name": "AbsolutePathInterface",
            "summary": "Represents\u0020either\u0020an\u0020absolute\u0020or\u0020a\u0020relative\u0020Path",
            "url": "classes/Horde-Filesystem-AbsolutePathInterface.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathInterface\u003A\u003AfromCurrentDir\u0028\u0029",
            "name": "fromCurrentDir",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePathInterface.html#method_fromCurrentDir"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathInterface\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePathInterface.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Directory",
            "name": "Directory",
            "summary": "Directories,\u0020Files,\u0020Device\u0020entries\u0020etc\u0020are\u0020nodes",
            "url": "classes/Horde-Filesystem-Directory.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Directory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Filesystem-Directory.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Directory\u003A\u003Atouch\u0028\u0029",
            "name": "touch",
            "summary": "",
            "url": "classes/Horde-Filesystem-Directory.html#method_touch"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryCreateIfMissingTrait",
            "name": "DirectoryCreateIfMissingTrait",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryCreateIfMissingTrait.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryCreateIfMissingTrait\u003A\u003AcreateIfMissing\u0028\u0029",
            "name": "createIfMissing",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryCreateIfMissingTrait.html#method_createIfMissing"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryCreateIfMissingTrait\u003A\u003AcreateSubDir\u0028\u0029",
            "name": "createSubDir",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryCreateIfMissingTrait.html#method_createSubDir"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryDeleteTrait",
            "name": "DirectoryDeleteTrait",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryDeleteTrait.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryDeleteTrait\u003A\u003AdeleteIfEmpty\u0028\u0029",
            "name": "deleteIfEmpty",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryDeleteTrait.html#method_deleteIfEmpty"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryDeleteTrait\u003A\u003AdeleteRecursively\u0028\u0029",
            "name": "deleteRecursively",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryDeleteTrait.html#method_deleteRecursively"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryInterface",
            "name": "DirectoryInterface",
            "summary": "A\u0020unixoid\u0020filesystem\u0020directory",
            "url": "classes/Horde-Filesystem-DirectoryInterface.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryInterface\u003A\u003AcreateIfMissing\u0028\u0029",
            "name": "createIfMissing",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryInterface.html#method_createIfMissing"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryInterface\u003A\u003AdeleteIfEmpty\u0028\u0029",
            "name": "deleteIfEmpty",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryInterface.html#method_deleteIfEmpty"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryInterface\u003A\u003AdeleteRecursively\u0028\u0029",
            "name": "deleteRecursively",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryInterface.html#method_deleteRecursively"
        },                {
            "fqsen": "\\Horde\\Filesystem\\DirectoryInterface\u003A\u003AcreateSubDir\u0028\u0029",
            "name": "createSubDir",
            "summary": "",
            "url": "classes/Horde-Filesystem-DirectoryInterface.html#method_createSubDir"
        },                {
            "fqsen": "\\Horde\\Filesystem\\File",
            "name": "File",
            "summary": "An\u0020OO\u0020interface\u0020to\u0020a\u0020file",
            "url": "classes/Horde-Filesystem-File.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\File\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Filesystem-File.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Filesystem\\File\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Horde-Filesystem-File.html#method_delete"
        },                {
            "fqsen": "\\Horde\\Filesystem\\File\u003A\u003Atouch\u0028\u0029",
            "name": "touch",
            "summary": "",
            "url": "classes/Horde-Filesystem-File.html#method_touch"
        },                {
            "fqsen": "\\Horde\\Filesystem\\File\u003A\u003AensureFileExist\u0028\u0029",
            "name": "ensureFileExist",
            "summary": "",
            "url": "classes/Horde-Filesystem-File.html#method_ensureFileExist"
        },                {
            "fqsen": "\\Horde\\Filesystem\\File\u003A\u003A\u0024file",
            "name": "file",
            "summary": "",
            "url": "classes/Horde-Filesystem-File.html#property_file"
        },                {
            "fqsen": "\\Horde\\Filesystem\\FileInterface",
            "name": "FileInterface",
            "summary": "Directories,\u0020Files,\u0020Device\u0020entries\u0020etc\u0020are\u0020nodes",
            "url": "classes/Horde-Filesystem-FileInterface.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\FileInterface\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Horde-Filesystem-FileInterface.html#method_delete"
        },                {
            "fqsen": "\\Horde\\Filesystem\\FileInterface\u003A\u003AensureFileExist\u0028\u0029",
            "name": "ensureFileExist",
            "summary": "",
            "url": "classes/Horde-Filesystem-FileInterface.html#method_ensureFileExist"
        },                {
            "fqsen": "\\Horde\\Filesystem\\FileInterface\u003A\u003Atouch\u0028\u0029",
            "name": "touch",
            "summary": "",
            "url": "classes/Horde-Filesystem-FileInterface.html#method_touch"
        },                {
            "fqsen": "\\Horde\\Filesystem\\GetRelativePathTrait",
            "name": "GetRelativePathTrait",
            "summary": "",
            "url": "classes/Horde-Filesystem-GetRelativePathTrait.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\GetRelativePathTrait\u003A\u003AgetPathRelativeTo\u0028\u0029",
            "name": "getPathRelativeTo",
            "summary": "",
            "url": "classes/Horde-Filesystem-GetRelativePathTrait.html#method_getPathRelativeTo"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface",
            "name": "NodeInterface",
            "summary": "Directories,\u0020Files,\u0020Device\u0020entries\u0020etc\u0020are\u0020nodes",
            "url": "classes/Horde-Filesystem-NodeInterface.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface\u003A\u003AgetAbsolutePath\u0028\u0029",
            "name": "getAbsolutePath",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeInterface.html#method_getAbsolutePath"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface\u003A\u003AgetPathRelativeTo\u0028\u0029",
            "name": "getPathRelativeTo",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeInterface.html#method_getPathRelativeTo"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface\u003A\u003Aexists\u0028\u0029",
            "name": "exists",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeInterface.html#method_exists"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface\u003A\u003AisReadable\u0028\u0029",
            "name": "isReadable",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeInterface.html#method_isReadable"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface\u003A\u003AisWriteable\u0028\u0029",
            "name": "isWriteable",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeInterface.html#method_isWriteable"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface\u003A\u003AisExecutable\u0028\u0029",
            "name": "isExecutable",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeInterface.html#method_isExecutable"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface\u003A\u003AisLink\u0028\u0029",
            "name": "isLink",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeInterface.html#method_isLink"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface\u003A\u003Atouch\u0028\u0029",
            "name": "touch",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeInterface.html#method_touch"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeInterface\u003A\u003AcreateSymlinkAs\u0028\u0029",
            "name": "createSymlinkAs",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeInterface.html#method_createSymlinkAs"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeTrait",
            "name": "NodeTrait",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeTrait.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeTrait\u003A\u003AisExecutable\u0028\u0029",
            "name": "isExecutable",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeTrait.html#method_isExecutable"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeTrait\u003A\u003AisReadable\u0028\u0029",
            "name": "isReadable",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeTrait.html#method_isReadable"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeTrait\u003A\u003AisWriteable\u0028\u0029",
            "name": "isWriteable",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeTrait.html#method_isWriteable"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeTrait\u003A\u003AisLink\u0028\u0029",
            "name": "isLink",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeTrait.html#method_isLink"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeTrait\u003A\u003Aexists\u0028\u0029",
            "name": "exists",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeTrait.html#method_exists"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeTrait\u003A\u003AgetAbsolutePath\u0028\u0029",
            "name": "getAbsolutePath",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeTrait.html#method_getAbsolutePath"
        },                {
            "fqsen": "\\Horde\\Filesystem\\NodeTrait\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Horde-Filesystem-NodeTrait.html#property_path"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path",
            "name": "Path",
            "summary": "The\u0020inevitable\u0020reusable\u0020static\u0020helper",
            "url": "classes/Horde-Filesystem-Path.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AfromString\u0028\u0029",
            "name": "fromString",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_fromString"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AremoveTrailingSlash\u0028\u0029",
            "name": "removeTrailingSlash",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_removeTrailingSlash"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AaddTrailingSlash\u0028\u0029",
            "name": "addTrailingSlash",
            "summary": "Idempotent\u003A\u0020Ensure\u0020there\u0020is\u0020exactly\u0020one\u0020trailing\u0020slash",
            "url": "classes/Horde-Filesystem-Path.html#method_addTrailingSlash"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AlevelUp\u0028\u0029",
            "name": "levelUp",
            "summary": "Move\u0020up\u0020by\u0020X\u0020levels",
            "url": "classes/Horde-Filesystem-Path.html#method_levelUp"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AisAbsolutePath\u0028\u0029",
            "name": "isAbsolutePath",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_isAbsolutePath"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AhasLeadingAnchorDot\u0028\u0029",
            "name": "hasLeadingAnchorDot",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_hasLeadingAnchorDot"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003A\u0024factory",
            "name": "factory",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#property_factory"
        },                {
            "fqsen": "\\Horde\\Filesystem\\PathFactory",
            "name": "PathFactory",
            "summary": "A\u0020factory\u0020for\u0020relative\u0020and\u0020absolute\u0020unixoid\u0020paths",
            "url": "classes/Horde-Filesystem-PathFactory.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\PathFactory\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/Horde-Filesystem-PathFactory.html#method___invoke"
        },                {
            "fqsen": "\\Horde\\Filesystem\\PathInterface",
            "name": "PathInterface",
            "summary": "Represents\u0020either\u0020an\u0020absolute\u0020or\u0020a\u0020relative\u0020Path",
            "url": "classes/Horde-Filesystem-PathInterface.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\PathInterface\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Horde-Filesystem-PathInterface.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath",
            "name": "RelativePath",
            "summary": "Represent\u0020and\u0020manipulate\u0020unixoid\u0020paths\u0020as\u0020immutables.",
            "url": "classes/Horde-Filesystem-RelativePath.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Filesystem-RelativePath.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "Normalize\u0020a\u0020path",
            "url": "classes/Horde-Filesystem-RelativePath.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-Filesystem-RelativePath.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath\u003A\u003A\u0024path",
            "name": "path",
            "summary": "TODO\u0020PHP\u00208.1\u0020make\u0020readonly",
            "url": "classes/Horde-Filesystem-RelativePath.html#property_path"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePathInterface",
            "name": "RelativePathInterface",
            "summary": "Represents\u0020either\u0020an\u0020absolute\u0020or\u0020a\u0020relative\u0020Path",
            "url": "classes/Horde-Filesystem-RelativePathInterface.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePathInterface\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Horde-Filesystem-RelativePathInterface.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\SymlinkTrait",
            "name": "SymlinkTrait",
            "summary": "",
            "url": "classes/Horde-Filesystem-SymlinkTrait.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\SymlinkTrait\u003A\u003AcreateSymlinkAs\u0028\u0029",
            "name": "createSymlinkAs",
            "summary": "",
            "url": "classes/Horde-Filesystem-SymlinkTrait.html#method_createSymlinkAs"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Filesystem",
            "name": "Filesystem",
            "summary": "",
            "url": "namespaces/horde-filesystem.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
