Search.appendIndex(
    [
                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath",
            "name": "AbsolutePath",
            "summary": "Represent\u0020and\u0020manipulate\u0020unixoid\u0020paths\u0020as\u0020immutables.",
            "url": "classes/Horde-Filesystem-AbsolutePath.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "Normalize\u0020a\u0020path",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003AaddTrailingSlash\u0028\u0029",
            "name": "addTrailingSlash",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method_addTrailingSlash"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003AremoveTrailingSlash\u0028\u0029",
            "name": "removeTrailingSlash",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method_removeTrailingSlash"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003AlevelUp\u0028\u0029",
            "name": "levelUp",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method_levelUp"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePath\u003A\u003A\u0024path",
            "name": "path",
            "summary": "TODO\u0020PHP\u00208.1\u0020make\u0020readonly",
            "url": "classes/Horde-Filesystem-AbsolutePath.html#property_path"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathFromCurrentDirTrait",
            "name": "AbsolutePathFromCurrentDirTrait",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePathFromCurrentDirTrait.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathFromCurrentDirTrait\u003A\u003AfromCurrentDir\u0028\u0029",
            "name": "fromCurrentDir",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePathFromCurrentDirTrait.html#method_fromCurrentDir"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathInterface",
            "name": "AbsolutePathInterface",
            "summary": "Represents\u0020either\u0020an\u0020absolute\u0020or\u0020a\u0020relative\u0020Path",
            "url": "classes/Horde-Filesystem-AbsolutePathInterface.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathInterface\u003A\u003AfromCurrentDir\u0028\u0029",
            "name": "fromCurrentDir",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePathInterface.html#method_fromCurrentDir"
        },                {
            "fqsen": "\\Horde\\Filesystem\\AbsolutePathInterface\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Horde-Filesystem-AbsolutePathInterface.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path",
            "name": "Path",
            "summary": "The\u0020inevitable\u0020reusable\u0020static\u0020helper",
            "url": "classes/Horde-Filesystem-Path.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AfromString\u0028\u0029",
            "name": "fromString",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_fromString"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AremoveTrailingSlash\u0028\u0029",
            "name": "removeTrailingSlash",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_removeTrailingSlash"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AaddTrailingSlash\u0028\u0029",
            "name": "addTrailingSlash",
            "summary": "Idempotent\u003A\u0020Ensure\u0020there\u0020is\u0020exactly\u0020one\u0020trailing\u0020slash",
            "url": "classes/Horde-Filesystem-Path.html#method_addTrailingSlash"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AlevelUp\u0028\u0029",
            "name": "levelUp",
            "summary": "Move\u0020up\u0020by\u0020X\u0020levels",
            "url": "classes/Horde-Filesystem-Path.html#method_levelUp"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AisAbsolutePath\u0028\u0029",
            "name": "isAbsolutePath",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_isAbsolutePath"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003AhasLeadingAnchorDot\u0028\u0029",
            "name": "hasLeadingAnchorDot",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_hasLeadingAnchorDot"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\Path\u003A\u003A\u0024factory",
            "name": "factory",
            "summary": "",
            "url": "classes/Horde-Filesystem-Path.html#property_factory"
        },                {
            "fqsen": "\\Horde\\Filesystem\\PathFactory",
            "name": "PathFactory",
            "summary": "A\u0020factory\u0020for\u0020relative\u0020and\u0020absolute\u0020unixoid\u0020paths",
            "url": "classes/Horde-Filesystem-PathFactory.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\PathFactory\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/Horde-Filesystem-PathFactory.html#method___invoke"
        },                {
            "fqsen": "\\Horde\\Filesystem\\PathInterface",
            "name": "PathInterface",
            "summary": "Represents\u0020either\u0020an\u0020absolute\u0020or\u0020a\u0020relative\u0020Path",
            "url": "classes/Horde-Filesystem-PathInterface.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\PathInterface\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Horde-Filesystem-PathInterface.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath",
            "name": "RelativePath",
            "summary": "Represent\u0020and\u0020manipulate\u0020unixoid\u0020paths\u0020as\u0020immutables.",
            "url": "classes/Horde-Filesystem-RelativePath.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Filesystem-RelativePath.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "Normalize\u0020a\u0020path",
            "url": "classes/Horde-Filesystem-RelativePath.html#method_normalize"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Horde-Filesystem-RelativePath.html#method___toString"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePath\u003A\u003A\u0024path",
            "name": "path",
            "summary": "TODO\u0020PHP\u00208.1\u0020make\u0020readonly",
            "url": "classes/Horde-Filesystem-RelativePath.html#property_path"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePathInterface",
            "name": "RelativePathInterface",
            "summary": "Represents\u0020either\u0020an\u0020absolute\u0020or\u0020a\u0020relative\u0020Path",
            "url": "classes/Horde-Filesystem-RelativePathInterface.html"
        },                {
            "fqsen": "\\Horde\\Filesystem\\RelativePathInterface\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Horde-Filesystem-RelativePathInterface.html#method_normalize"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Filesystem",
            "name": "Filesystem",
            "summary": "",
            "url": "namespaces/horde-filesystem.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
