Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler",
            "name": "Horde_Xml_Wbxml_ContentHandler",
            "summary": "From\u0020Binary\u0020XML\u0020Content\u0020Format\u0020Specification\u0020Version\u00201.3,\u002025\u0020July\u00202001\nfound\u0020at\u0020http\u003A\/\/www.wapforum.org",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method___construct"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AgetCharsetStr\u0028\u0029",
            "name": "getCharsetStr",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_getCharsetStr"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AsetCharset\u0028\u0029",
            "name": "setCharset",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_setCharset"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_getVersion"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AsetVersion\u0028\u0029",
            "name": "setVersion",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_setVersion"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_getOutput"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AgetOutputSize\u0028\u0029",
            "name": "getOutputSize",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_getOutputSize"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AstartElement\u0028\u0029",
            "name": "startElement",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_startElement"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AendElement\u0028\u0029",
            "name": "endElement",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_endElement"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003Acharacters\u0028\u0029",
            "name": "characters",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_characters"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003Aopaque\u0028\u0029",
            "name": "opaque",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_opaque"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AsetOpaqueHandler\u0028\u0029",
            "name": "setOpaqueHandler",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_setOpaqueHandler"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AremoveOpaqueHandler\u0028\u0029",
            "name": "removeOpaqueHandler",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_removeOpaqueHandler"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003AcreateSubHandler\u0028\u0029",
            "name": "createSubHandler",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#method_createSubHandler"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003A\u0024_currentUri",
            "name": "_currentUri",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#property__currentUri"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003A\u0024_output",
            "name": "_output",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#property__output"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003A\u0024_opaqueHandler",
            "name": "_opaqueHandler",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#property__opaqueHandler"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003A\u0024_charset",
            "name": "_charset",
            "summary": "Charset.",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#property__charset"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_ContentHandler\u003A\u003A\u0024_wbxmlVersion",
            "name": "_wbxmlVersion",
            "summary": "WBXML\u0020Version.",
            "url": "classes/Horde-Xml-Wbxml-ContentHandler.html#property__wbxmlVersion"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder",
            "name": "Horde_Xml_Wbxml_Decoder",
            "summary": "From\u0020Binary\u0020XML\u0020Content\u0020Format\u0020Specification\u0020Version\u00201.3,\u002025\u0020July\u00202001\nfound\u0020at\u0020http\u003A\/\/www.wapforum.org",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method___construct"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AsetContentHandler\u0028\u0029",
            "name": "setContentHandler",
            "summary": "Sets\u0020the\u0020contentHandler\u0020that\u0020will\u0020receive\u0020the\u0020output\u0020of\u0020the\ndecoding.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_setContentHandler"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetByte\u0028\u0029",
            "name": "getByte",
            "summary": "Return\u0020one\u0020byte\u0020from\u0020the\u0020input\u0020stream.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getByte"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AdecodeToString\u0028\u0029",
            "name": "decodeToString",
            "summary": "Takes\u0020a\u0020WBXML\u0020input\u0020document\u0020and\u0020returns\u0020decoded\u0020XML.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_decodeToString"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "Takes\u0020a\u0020WBXML\u0020input\u0020document\u0020and\u0020decodes\u0020it.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_decode"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetVersionNumber\u0028\u0029",
            "name": "getVersionNumber",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getVersionNumber"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetDocumentPublicIdentifier\u0028\u0029",
            "name": "getDocumentPublicIdentifier",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getDocumentPublicIdentifier"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetDocumentPublicIdentifierImpl\u0028\u0029",
            "name": "getDocumentPublicIdentifierImpl",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getDocumentPublicIdentifierImpl"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetCharset\u0028\u0029",
            "name": "getCharset",
            "summary": "Returns\u0020the\u0020character\u0020encoding.\u0020Only\u0020default\u0020character\nencodings\u0020from\u0020J2SE\u0020are\u0020supported.\u0020\u0020From\nhttp\u003A\/\/www.iana.org\/assignments\/character\u002Dsets\u0020and\nhttp\u003A\/\/java.sun.com\/j2se\/1.4.2\/docs\/api\/java\/nio\/charset\/Charset.html",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getCharset"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AretrieveStringTable\u0028\u0029",
            "name": "retrieveStringTable",
            "summary": "Retrieves\u0020the\u0020string\u0020table.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_retrieveStringTable"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetStringTableEntry\u0028\u0029",
            "name": "getStringTableEntry",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getStringTableEntry"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A_decode\u0028\u0029",
            "name": "_decode",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method__decode"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AparseTag\u0028\u0029",
            "name": "parseTag",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_parseTag"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AendTag\u0028\u0029",
            "name": "endTag",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_endTag"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetAttributes\u0028\u0029",
            "name": "getAttributes",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getAttributes"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AstartGetAttributes\u0028\u0029",
            "name": "startGetAttributes",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_startGetAttributes"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AstopGetAttributes\u0028\u0029",
            "name": "stopGetAttributes",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_stopGetAttributes"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetCurrentURI\u0028\u0029",
            "name": "getCurrentURI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getCurrentURI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AwriteString\u0028\u0029",
            "name": "writeString",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_writeString"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetTag\u0028\u0029",
            "name": "getTag",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getTag"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AgetAttribute\u0028\u0029",
            "name": "getAttribute",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_getAttribute"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AswitchElementCodePage\u0028\u0029",
            "name": "switchElementCodePage",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_switchElementCodePage"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003AswitchAttributeCodePage\u0028\u0029",
            "name": "switchAttributeCodePage",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_switchAttributeCodePage"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003Aentity\u0028\u0029",
            "name": "entity",
            "summary": "Return\u0020the\u0020hex\u0020version\u0020of\u0020the\u0020base\u002010\u0020\u0024entity.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_entity"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003Atermstr\u0028\u0029",
            "name": "termstr",
            "summary": "Reads\u0020a\u0020null\u0020terminated\u0020string.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#method_termstr"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_dpi",
            "name": "_dpi",
            "summary": "Document\u0020Public\u0020Identifier\u0020type\n1\u0020mb_u_int32\u0020well\u0020known\u0020type\n2\u0020string\u0020table\nfrom\u0020spec\u0020but\u0020converted\u0020into\u0020a\u0020string.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__dpi"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_stringTable",
            "name": "_stringTable",
            "summary": "String\u0020table\u0020as\u0020defined\u0020in\u00205.7",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__stringTable"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_ch",
            "name": "_ch",
            "summary": "Content\u0020handler.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__ch"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_tagDTD",
            "name": "_tagDTD",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__tagDTD"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_prevAttributeDTD",
            "name": "_prevAttributeDTD",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__prevAttributeDTD"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_attributeDTD",
            "name": "_attributeDTD",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__attributeDTD"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_tagStack",
            "name": "_tagStack",
            "summary": "State\u0020variables.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__tagStack"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_isAttribute",
            "name": "_isAttribute",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__isAttribute"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_isData",
            "name": "_isData",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__isData"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_error",
            "name": "_error",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__error"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_dtdManager",
            "name": "_dtdManager",
            "summary": "The\u0020DTD\u0020Manager.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__dtdManager"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Decoder\u003A\u003A\u0024_strpos",
            "name": "_strpos",
            "summary": "The\u0020string\u0020position.",
            "url": "classes/Horde-Xml-Wbxml-Decoder.html#property__strpos"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd_SyncMl",
            "name": "Horde_Xml_Wbxml_Dtd_SyncMl",
            "summary": "From\u0020Binary\u0020XML\u0020Content\u0020Format\u0020Specification\u0020Version\u00201.3,\u002025\u0020July\u00202001\nfound\u0020at\u0020http\u003A\/\/www.wapforum.org",
            "url": "classes/Horde-Xml-Wbxml-Dtd-SyncMl.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd_SyncMl\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd-SyncMl.html#method_init"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd_SyncMlDevInf",
            "name": "Horde_Xml_Wbxml_Dtd_SyncMlDevInf",
            "summary": "From\u0020Binary\u0020XML\u0020Content\u0020Format\u0020Specification\u0020Version\u00201.3,\u002025\u0020July\u00202001\nfound\u0020at\u0020http\u003A\/\/www.wapforum.org",
            "url": "classes/Horde-Xml-Wbxml-Dtd-SyncMlDevInf.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd_SyncMlDevInf\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd-SyncMlDevInf.html#method_init"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd_SyncMlMetInf",
            "name": "Horde_Xml_Wbxml_Dtd_SyncMlMetInf",
            "summary": "From\u0020Binary\u0020XML\u0020Content\u0020Format\u0020Specification\u0020Version\u00201.3,\u002025\u0020July\u00202001\nfound\u0020at\u0020http\u003A\/\/www.wapforum.org",
            "url": "classes/Horde-Xml-Wbxml-Dtd-SyncMlMetInf.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd_SyncMlMetInf\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd-SyncMlMetInf.html#method_init"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd",
            "name": "Horde_Xml_Wbxml_Dtd",
            "summary": "From\u0020Binary\u0020XML\u0020Content\u0020Format\u0020Specification\u0020Version\u00201.3,\u002025\u0020July\u00202001\nfound\u0020at\u0020http\u003A\/\/www.wapforum.org",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method___construct"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_init"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AsetAttribute\u0028\u0029",
            "name": "setAttribute",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_setAttribute"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AsetTag\u0028\u0029",
            "name": "setTag",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_setTag"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AsetCodePage\u0028\u0029",
            "name": "setCodePage",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_setCodePage"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AtoTagStr\u0028\u0029",
            "name": "toTagStr",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_toTagStr"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AtoAttributeStr\u0028\u0029",
            "name": "toAttributeStr",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_toAttributeStr"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AtoCodePageStr\u0028\u0029",
            "name": "toCodePageStr",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_toCodePageStr"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AtoTagInt\u0028\u0029",
            "name": "toTagInt",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_toTagInt"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AtoAttributeInt\u0028\u0029",
            "name": "toAttributeInt",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_toAttributeInt"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AtoCodePageInt\u0028\u0029",
            "name": "toCodePageInt",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_toCodePageInt"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AtoCodePageURI\u0028\u0029",
            "name": "toCodePageURI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_toCodePageURI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "Getter\u0020for\u0020property\u0020version.",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_getVersion"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AsetVersion\u0028\u0029",
            "name": "setVersion",
            "summary": "Setter\u0020for\u0020property\u0020version.",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_setVersion"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AgetURI\u0028\u0029",
            "name": "getURI",
            "summary": "Getter\u0020for\u0020property\u0020URI.",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_getURI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AsetURI\u0028\u0029",
            "name": "setURI",
            "summary": "Setter\u0020for\u0020property\u0020URI.",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_setURI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AgetDPI\u0028\u0029",
            "name": "getDPI",
            "summary": "Getter\u0020for\u0020property\u0020DPI.",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_getDPI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AsetDPI\u0028\u0029",
            "name": "setDPI",
            "summary": "Setter\u0020for\u0020property\u0020DPI.",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#method_setDPI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AWML_1_0",
            "name": "WML_1_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_WML_1_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AWTA_1_0",
            "name": "WTA_1_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_WTA_1_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AWML_1_1",
            "name": "WML_1_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_WML_1_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ASI_1_1",
            "name": "SI_1_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_SI_1_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ASL_1_0",
            "name": "SL_1_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_SL_1_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ACO_1_0",
            "name": "CO_1_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_CO_1_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ACHANNEL_1_1",
            "name": "CHANNEL_1_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_CHANNEL_1_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AWML_1_2",
            "name": "WML_1_2",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_WML_1_2"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AWML_1_3",
            "name": "WML_1_3",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_WML_1_3"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003APROV_1_0",
            "name": "PROV_1_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_PROV_1_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AWTA_WML_1_2",
            "name": "WTA_WML_1_2",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_WTA_WML_1_2"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ACHANNEL_1_2",
            "name": "CHANNEL_1_2",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_CHANNEL_1_2"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ASYNCML_1_0",
            "name": "SYNCML_1_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_SYNCML_1_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ADEVINF_1_0",
            "name": "DEVINF_1_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_DEVINF_1_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AMETINF_1_0",
            "name": "METINF_1_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_METINF_1_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ASYNCML_1_1",
            "name": "SYNCML_1_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_SYNCML_1_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ADEVINF_1_1",
            "name": "DEVINF_1_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_DEVINF_1_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AMETINF_1_1",
            "name": "METINF_1_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_METINF_1_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ASYNCML_1_2",
            "name": "SYNCML_1_2",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_SYNCML_1_2"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003ADEVINF_1_2",
            "name": "DEVINF_1_2",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_DEVINF_1_2"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003AMETINF_1_2",
            "name": "METINF_1_2",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#constant_METINF_1_2"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_version"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024intTags",
            "name": "intTags",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_intTags"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024intAttributes",
            "name": "intAttributes",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_intAttributes"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024strTags",
            "name": "strTags",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_strTags"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024strAttributes",
            "name": "strAttributes",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_strAttributes"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024intCodePages",
            "name": "intCodePages",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_intCodePages"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024strCodePages",
            "name": "strCodePages",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_strCodePages"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024strCodePagesURI",
            "name": "strCodePagesURI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_strCodePagesURI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024URI",
            "name": "URI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_URI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024XMLNS",
            "name": "XMLNS",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_XMLNS"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Dtd\u003A\u003A\u0024DPI",
            "name": "DPI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Dtd.html#property_DPI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_DtdManager",
            "name": "Horde_Xml_Wbxml_DtdManager",
            "summary": "From\u0020Binary\u0020XML\u0020Content\u0020Format\u0020Specification\u0020Version\u00201.3,\u002025\u0020July\u00202001\nfound\u0020at\u0020http\u003A\/\/www.wapforum.org",
            "url": "classes/Horde-Xml-Wbxml-DtdManager.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_DtdManager\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-DtdManager.html#method___construct"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_DtdManager\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-DtdManager.html#method_getInstance"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_DtdManager\u003A\u003AgetInstanceURI\u0028\u0029",
            "name": "getInstanceURI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-DtdManager.html#method_getInstanceURI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_DtdManager\u003A\u003AregisterDTD\u0028\u0029",
            "name": "registerDTD",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-DtdManager.html#method_registerDTD"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_DtdManager\u003A\u003A\u0024_strDTD",
            "name": "_strDTD",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-DtdManager.html#property__strDTD"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_DtdManager\u003A\u003A\u0024_strDTDURI",
            "name": "_strDTDURI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-DtdManager.html#property__strDTDURI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder",
            "name": "Horde_Xml_Wbxml_Encoder",
            "summary": "From\u0020Binary\u0020XML\u0020Content\u0020Format\u0020Specification\u0020Version\u00201.3,\u002025\u0020July\u00202001\nfound\u0020at\u0020http\u003A\/\/www.wapforum.org",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method___construct"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "Take\u0020the\u0020input\u0020\u0024xml\u0020and\u0020turn\u0020it\u0020into\u0020WBXML.\u0020This\u0020is\u0020_not_\u0020the\nintended\u0020way\u0020of\u0020using\u0020this\u0020class.\u0020It\u0020is\u0020derived\u0020from\nContenthandler\u0020and\u0020one\u0020should\u0020use\u0020it\u0020as\u0020a\u0020ContentHandler\u0020and\nproduce\u0020the\u0020XML\u002Dstructure\u0020with\u0020startElement\u0028\u0029,\u0020endElement\u0028\u0029,\nand\u0020characters\u0028\u0029.",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_encode"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteHeader\u0028\u0029",
            "name": "writeHeader",
            "summary": "This\u0020will\u0020write\u0020the\u0020correct\u0020headers.",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeHeader"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteVersionNumber\u0028\u0029",
            "name": "writeVersionNumber",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeVersionNumber"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteDocumentPublicIdentifier\u0028\u0029",
            "name": "writeDocumentPublicIdentifier",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeDocumentPublicIdentifier"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteCharset\u0028\u0029",
            "name": "writeCharset",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeCharset"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteStringTable\u0028\u0029",
            "name": "writeStringTable",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeStringTable"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteString\u0028\u0029",
            "name": "writeString",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeString"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteNull\u0028\u0029",
            "name": "writeNull",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeNull"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A_addNullByte\u0028\u0029",
            "name": "_addNullByte",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method__addNullByte"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A_getBytes\u0028\u0029",
            "name": "_getBytes",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method__getBytes"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A_splitURI\u0028\u0029",
            "name": "_splitURI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method__splitURI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AstartElement\u0028\u0029",
            "name": "startElement",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_startElement"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A_startElement\u0028\u0029",
            "name": "_startElement",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method__startElement"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003Aopaque\u0028\u0029",
            "name": "opaque",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_opaque"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003Acharacters\u0028\u0029",
            "name": "characters",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_characters"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A_characters\u0028\u0029",
            "name": "_characters",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method__characters"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteTag\u0028\u0029",
            "name": "writeTag",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeTag"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteAttributes\u0028\u0029",
            "name": "writeAttributes",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeAttributes"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AwriteAttribute\u0028\u0029",
            "name": "writeAttribute",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_writeAttribute"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AendElement\u0028\u0029",
            "name": "endElement",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_endElement"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A_endElement\u0028\u0029",
            "name": "_endElement",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method__endElement"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003Achangecodepage\u0028\u0029",
            "name": "changecodepage",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_changecodepage"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "Getter\u0020for\u0020property\u0020output.",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_getOutput"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003AgetOutputSize\u0028\u0029",
            "name": "getOutputSize",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#method_getOutputSize"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_strings",
            "name": "_strings",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__strings"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_stringTable",
            "name": "_stringTable",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__stringTable"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_hasWrittenHeader",
            "name": "_hasWrittenHeader",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__hasWrittenHeader"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_dtd",
            "name": "_dtd",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__dtd"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_output",
            "name": "_output",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__output"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_uris",
            "name": "_uris",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__uris"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_uriNums",
            "name": "_uriNums",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__uriNums"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_currentURI",
            "name": "_currentURI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__currentURI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_subParser",
            "name": "_subParser",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__subParser"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_subParserStack",
            "name": "_subParserStack",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__subParserStack"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_parser",
            "name": "_parser",
            "summary": "The\u0020XML\u0020parser.",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__parser"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Encoder\u003A\u003A\u0024_dtdManager",
            "name": "_dtdManager",
            "summary": "The\u0020DTD\u0020Manager.",
            "url": "classes/Horde-Xml-Wbxml-Encoder.html#property__dtdManager"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_Exception",
            "name": "Horde_Xml_Wbxml_Exception",
            "summary": "Base\u0020exception\u0020class\u0020for\u0020Horde_Xml_Wbxml.",
            "url": "classes/Horde-Xml-Wbxml-Exception.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_HashTable",
            "name": "Horde_Xml_Wbxml_HashTable",
            "summary": "Copyright\u00202003\u002D2017\u0020Horde\u0020LLC\u0020\u0028http\u003A\/\/www.horde.org\/\u0029",
            "url": "classes/Horde-Xml-Wbxml-HashTable.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_HashTable\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-HashTable.html#method_set"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_HashTable\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-HashTable.html#method_get"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_HashTable\u003A\u003A\u0024_h",
            "name": "_h",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-HashTable.html#property__h"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_LifoQueue",
            "name": "Horde_Xml_Wbxml_LifoQueue",
            "summary": "From\u0020Binary\u0020XML\u0020Content\u0020Format\u0020Specification\u0020Version\u00201.3,\u002025\u0020July\u00202001\nfound\u0020at\u0020http\u003A\/\/www.wapforum.org",
            "url": "classes/Horde-Xml-Wbxml-LifoQueue.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_LifoQueue\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-LifoQueue.html#method_push"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_LifoQueue\u003A\u003Apop\u0028\u0029",
            "name": "pop",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-LifoQueue.html#method_pop"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_LifoQueue\u003A\u003Atop\u0028\u0029",
            "name": "top",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-LifoQueue.html#method_top"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml_LifoQueue\u003A\u003A\u0024_queue",
            "name": "_queue",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml-LifoQueue.html#property__queue"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml",
            "name": "Horde_Xml_Wbxml",
            "summary": "Copyright\u00202003\u002D2017\u0020Horde\u0020LLC\u0020\u0028http\u003A\/\/www.horde.org\/\u0029",
            "url": "classes/Horde-Xml-Wbxml.html"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AMBUInt32ToInt\u0028\u0029",
            "name": "MBUInt32ToInt",
            "summary": "Decoding\u0020Multi\u002Dbyte\u0020Integers\u0020from\u0020Section\u00205.1",
            "url": "classes/Horde-Xml-Wbxml.html#method_MBUInt32ToInt"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AintToMBUInt32\u0028\u0029",
            "name": "intToMBUInt32",
            "summary": "Encoding\u0020Multi\u002Dbyte\u0020Integers\u0020from\u0020Section\u00205.1",
            "url": "classes/Horde-Xml-Wbxml.html#method_intToMBUInt32"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AgetBits\u0028\u0029",
            "name": "getBits",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#method_getBits"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AgetDPIString\u0028\u0029",
            "name": "getDPIString",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#method_getDPIString"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AgetDPIInt\u0028\u0029",
            "name": "getDPIInt",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#method_getDPIInt"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AgetCharsetString\u0028\u0029",
            "name": "getCharsetString",
            "summary": "Returns\u0020the\u0020character\u0020encoding.",
            "url": "classes/Horde-Xml-Wbxml.html#method_getCharsetString"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AgetCharsetInt\u0028\u0029",
            "name": "getCharsetInt",
            "summary": "Returns\u0020the\u0020character\u0020encoding.",
            "url": "classes/Horde-Xml-Wbxml.html#method_getCharsetInt"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_SWITCH_PAGE",
            "name": "GLOBAL_TOKEN_SWITCH_PAGE",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_SWITCH_PAGE"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_END",
            "name": "GLOBAL_TOKEN_END",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_END"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_ENTITY",
            "name": "GLOBAL_TOKEN_ENTITY",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_ENTITY"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_STR_I",
            "name": "GLOBAL_TOKEN_STR_I",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_STR_I"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_LITERAL",
            "name": "GLOBAL_TOKEN_LITERAL",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_LITERAL"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_EXT_I_0",
            "name": "GLOBAL_TOKEN_EXT_I_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_EXT_I_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_EXT_I_1",
            "name": "GLOBAL_TOKEN_EXT_I_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_EXT_I_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_EXT_I_2",
            "name": "GLOBAL_TOKEN_EXT_I_2",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_EXT_I_2"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_PI",
            "name": "GLOBAL_TOKEN_PI",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_PI"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_LITERAL_C",
            "name": "GLOBAL_TOKEN_LITERAL_C",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_LITERAL_C"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_EXT_T_0",
            "name": "GLOBAL_TOKEN_EXT_T_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_EXT_T_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_EXT_T_1",
            "name": "GLOBAL_TOKEN_EXT_T_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_EXT_T_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_EXT_T_2",
            "name": "GLOBAL_TOKEN_EXT_T_2",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_EXT_T_2"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_STR_T",
            "name": "GLOBAL_TOKEN_STR_T",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_STR_T"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_LITERAL_A",
            "name": "GLOBAL_TOKEN_LITERAL_A",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_LITERAL_A"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_EXT_0",
            "name": "GLOBAL_TOKEN_EXT_0",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_EXT_0"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_EXT_1",
            "name": "GLOBAL_TOKEN_EXT_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_EXT_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_EXT_2",
            "name": "GLOBAL_TOKEN_EXT_2",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_EXT_2"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_OPAQUE",
            "name": "GLOBAL_TOKEN_OPAQUE",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_OPAQUE"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003AGLOBAL_TOKEN_LITERAL_AC",
            "name": "GLOBAL_TOKEN_LITERAL_AC",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_GLOBAL_TOKEN_LITERAL_AC"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003ACHARSET_US_ASCII",
            "name": "CHARSET_US_ASCII",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_CHARSET_US_ASCII"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003ACHARSET_ISO_8859_1",
            "name": "CHARSET_ISO_8859_1",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_CHARSET_ISO_8859_1"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003ACHARSET_UTF_8",
            "name": "CHARSET_UTF_8",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_CHARSET_UTF_8"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003ACHARSET_UTF_16BE",
            "name": "CHARSET_UTF_16BE",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_CHARSET_UTF_16BE"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003ACHARSET_UTF_16LE",
            "name": "CHARSET_UTF_16LE",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_CHARSET_UTF_16LE"
        },                {
            "fqsen": "\\Horde_Xml_Wbxml\u003A\u003ACHARSET_UTF_16",
            "name": "CHARSET_UTF_16",
            "summary": "",
            "url": "classes/Horde-Xml-Wbxml.html#constant_CHARSET_UTF_16"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
