Search.appendIndex(
    [
                {
            "fqsen": "\\Chora_Application",
            "name": "Chora_Application",
            "summary": "",
            "url": "classes/Chora-Application.html"
        },                {
            "fqsen": "\\Chora_Application\u003A\u003A_init\u0028\u0029",
            "name": "_init",
            "summary": "Global\u0020variables\u0020defined\u003A\n\u0020\u0020\u0024chora_conf\n\u0020\u0020\u0024sourceroots",
            "url": "classes/Chora-Application.html#method__init"
        },                {
            "fqsen": "\\Chora_Application\u003A\u003Aperms\u0028\u0029",
            "name": "perms",
            "summary": "",
            "url": "classes/Chora-Application.html#method_perms"
        },                {
            "fqsen": "\\Chora_Application\u003A\u003Asidebar\u0028\u0029",
            "name": "sidebar",
            "summary": "Add\u0020additional\u0020items\u0020to\u0020the\u0020sidebar.",
            "url": "classes/Chora-Application.html#method_sidebar"
        },                {
            "fqsen": "\\Chora_Application\u003A\u003AtopbarCreate\u0028\u0029",
            "name": "topbarCreate",
            "summary": "",
            "url": "classes/Chora-Application.html#method_topbarCreate"
        },                {
            "fqsen": "\\Chora_Application\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/Chora-Application.html#property_version"
        },                {
            "fqsen": "\\Chora",
            "name": "Chora",
            "summary": "Chora\u0020Base\u0020Class.",
            "url": "classes/Chora.html"
        },                {
            "fqsen": "\\Chora\u003A\u003Aheader\u0028\u0029",
            "name": "header",
            "summary": "Generates\u0020and\u0020prints\u0020the\u0020page\u0020header.",
            "url": "classes/Chora.html#method_header"
        },                {
            "fqsen": "\\Chora\u003A\u003AwhereMenu\u0028\u0029",
            "name": "whereMenu",
            "summary": "Create\u0020the\u0020breadcrumb\u0020directory\u0020listing.",
            "url": "classes/Chora.html#method_whereMenu"
        },                {
            "fqsen": "\\Chora\u003A\u003Afatal\u0028\u0029",
            "name": "fatal",
            "summary": "Output\u0020an\u0020error\u0020page.",
            "url": "classes/Chora.html#method_fatal"
        },                {
            "fqsen": "\\Chora\u003A\u003Aurl\u0028\u0029",
            "name": "url",
            "summary": "Generate\u0020a\u0020URL\u0020that\u0020links\u0020into\u0020Chora.",
            "url": "classes/Chora.html#method_url"
        },                {
            "fqsen": "\\Chora\u003A\u003AformInputs\u0028\u0029",
            "name": "formInputs",
            "summary": "Generates\u0020hidden\u0020form\u0020fields\u0020with\u0020all\u0020required\u0020parameters.",
            "url": "classes/Chora.html#method_formInputs"
        },                {
            "fqsen": "\\Chora\u003A\u003A_getArgList\u0028\u0029",
            "name": "_getArgList",
            "summary": "TODO",
            "url": "classes/Chora.html#method__getArgList"
        },                {
            "fqsen": "\\Chora\u003A\u003AcheckPerms\u0028\u0029",
            "name": "checkPerms",
            "summary": "TODO",
            "url": "classes/Chora.html#method_checkPerms"
        },                {
            "fqsen": "\\Chora\u003A\u003Asourceroots\u0028\u0029",
            "name": "sourceroots",
            "summary": "Returns\u0020the\u0020entries\u0020of\u0020\u0024sourceroots\u0020that\u0020the\u0020current\u0020user\u0020has\u0020access\nto.",
            "url": "classes/Chora.html#method_sourceroots"
        },                {
            "fqsen": "\\Chora\u003A\u003Apretty\u0028\u0029",
            "name": "pretty",
            "summary": "Pretty\u002Dprint\u0020the\u0020checked\u0020out\u0020copy,\u0020using\u0020Horde_Mime_Viewer.",
            "url": "classes/Chora.html#method_pretty"
        },                {
            "fqsen": "\\Chora\u003A\u003AisRestricted\u0028\u0029",
            "name": "isRestricted",
            "summary": "Check\u0020if\u0020the\u0020given\u0020item\u0020is\u0020restricted\u0020from\u0020being\u0020shown.",
            "url": "classes/Chora.html#method_isRestricted"
        },                {
            "fqsen": "\\Chora\u003A\u003AgetHistoryViews\u0028\u0029",
            "name": "getHistoryViews",
            "summary": "Generate\u0020the\u0020link\u0020used\u0020for\u0020various\u0020history\u0020views.",
            "url": "classes/Chora.html#method_getHistoryViews"
        },                {
            "fqsen": "\\Chora\u003A\u003AgetFileViews\u0028\u0029",
            "name": "getFileViews",
            "summary": "Generate\u0020the\u0020link\u0020used\u0020for\u0020various\u0020file\u0020views.",
            "url": "classes/Chora.html#method_getFileViews"
        },                {
            "fqsen": "\\Chora\u003A\u003AgetTags\u0028\u0029",
            "name": "getTags",
            "summary": "Return\u0020a\u0020list\u0020of\u0020tags\u0020for\u0020a\u0020given\u0020log\u0020entry.",
            "url": "classes/Chora.html#method_getTags"
        },                {
            "fqsen": "\\Chora\u003A\u003AreadableTime\u0028\u0029",
            "name": "readableTime",
            "summary": "Return\u0020a\u0020text\u0020description\u0020of\u0020how\u0020long\u0020its\u0020been\u0020since\u0020the\u0020file\nhas\u0020been\u0020last\u0020modified.",
            "url": "classes/Chora.html#method_readableTime"
        },                {
            "fqsen": "\\Chora\u003A\u003AshowAuthorName\u0028\u0029",
            "name": "showAuthorName",
            "summary": "Convert\u0020a\u0020commit\u002Dname\u0020into\u0020whatever\u0020the\u0020user\u0020wants.",
            "url": "classes/Chora.html#method_showAuthorName"
        },                {
            "fqsen": "\\Chora\u003A\u003AgetAuthorEmail\u0028\u0029",
            "name": "getAuthorEmail",
            "summary": "",
            "url": "classes/Chora.html#method_getAuthorEmail"
        },                {
            "fqsen": "\\Chora\u003A\u003AformatDate\u0028\u0029",
            "name": "formatDate",
            "summary": "Return\u0020formatted\u0020date\u0020information.",
            "url": "classes/Chora.html#method_formatDate"
        },                {
            "fqsen": "\\Chora\u003A\u003AformatLogMessage\u0028\u0029",
            "name": "formatLogMessage",
            "summary": "Formats\u0020a\u0020log\u0020message.",
            "url": "classes/Chora.html#method_formatLogMessage"
        },                {
            "fqsen": "\\Chora\u003A\u003A\u0024restricted",
            "name": "restricted",
            "summary": "Cached\u0020data\u0020for\u0020isRestricted\u0028\u0029.",
            "url": "classes/Chora.html#property_restricted"
        },                {
            "fqsen": "\\Chora\u003A\u003A\u0024rtcache",
            "name": "rtcache",
            "summary": "Cached\u0020data\u0020for\u0020readableTime\u0028\u0029.",
            "url": "classes/Chora.html#property_rtcache"
        },                {
            "fqsen": "\\Chora\u003A\u003A\u0024fdcache",
            "name": "fdcache",
            "summary": "Cached\u0020data\u0020for\u0020formatDate\u0028\u0029.",
            "url": "classes/Chora.html#property_fdcache"
        },                {
            "fqsen": "\\Chora_Exception",
            "name": "Chora_Exception",
            "summary": "Copyright\u00202000\u002D2017\u0020Horde\u0020LLC\u0020\u0028http\u003A\/\/www.horde.org\/\u0029",
            "url": "classes/Chora-Exception.html"
        },                {
            "fqsen": "\\Chora_Readme_Collection",
            "name": "Chora_Readme_Collection",
            "summary": "Copyright\u00202000\u002D2017\u0020Horde\u0020LLC\u0020\u0028http\u003A\/\/www.horde.org\/\u0029",
            "url": "classes/Chora-Readme-Collection.html"
        },                {
            "fqsen": "\\Chora_Readme_Collection\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chora-Readme-Collection.html#method___construct"
        },                {
            "fqsen": "\\Chora_Readme_Collection\u003A\u003AchooseReadme\u0028\u0029",
            "name": "chooseReadme",
            "summary": "",
            "url": "classes/Chora-Readme-Collection.html#method_chooseReadme"
        },                {
            "fqsen": "\\Chora_Readme_Collection\u003A\u003AcompareReadmes\u0028\u0029",
            "name": "compareReadmes",
            "summary": "",
            "url": "classes/Chora-Readme-Collection.html#method_compareReadmes"
        },                {
            "fqsen": "\\Chora_Readme_Collection\u003A\u003A_isHtmlReadme\u0028\u0029",
            "name": "_isHtmlReadme",
            "summary": "",
            "url": "classes/Chora-Readme-Collection.html#method__isHtmlReadme"
        },                {
            "fqsen": "\\Chora_Readme_Collection\u003A\u003ACHOOSE_A",
            "name": "CHOOSE_A",
            "summary": "",
            "url": "classes/Chora-Readme-Collection.html#constant_CHOOSE_A"
        },                {
            "fqsen": "\\Chora_Readme_Collection\u003A\u003ACHOOSE_B",
            "name": "CHOOSE_B",
            "summary": "",
            "url": "classes/Chora-Readme-Collection.html#constant_CHOOSE_B"
        },                {
            "fqsen": "\\Chora_Readme_Collection\u003A\u003AEQUAL",
            "name": "EQUAL",
            "summary": "",
            "url": "classes/Chora-Readme-Collection.html#constant_EQUAL"
        },                {
            "fqsen": "\\Chora_Readme_Collection\u003A\u003A\u0024_readmes",
            "name": "_readmes",
            "summary": "",
            "url": "classes/Chora-Readme-Collection.html#property__readmes"
        },                {
            "fqsen": "\\Chora_Renderer_File_Html",
            "name": "Chora_Renderer_File_Html",
            "summary": "Copyright\u00202000\u002D2017\u0020Horde\u0020LLC\u0020\u0028http\u003A\/\/www.horde.org\/\u0029",
            "url": "classes/Chora-Renderer-File-Html.html"
        },                {
            "fqsen": "\\Chora_Renderer_File_Html\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "classes/Chora-Renderer-File-Html.html#method_render"
        },                {
            "fqsen": "\\Chora_Renderer_File_Plain",
            "name": "Chora_Renderer_File_Plain",
            "summary": "Copyright\u00202000\u002D2017\u0020Horde\u0020LLC\u0020\u0028http\u003A\/\/www.horde.org\/\u0029",
            "url": "classes/Chora-Renderer-File-Plain.html"
        },                {
            "fqsen": "\\Chora_Renderer_File_Plain\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "classes/Chora-Renderer-File-Plain.html#method_render"
        },                {
            "fqsen": "\\Chora_Renderer_File",
            "name": "Chora_Renderer_File",
            "summary": "Copyright\u00202000\u002D2017\u0020Horde\u0020LLC\u0020\u0028http\u003A\/\/www.horde.org\/\u0029",
            "url": "classes/Chora-Renderer-File.html"
        },                {
            "fqsen": "\\Chora_Renderer_File\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Chora-Renderer-File.html#method___construct"
        },                {
            "fqsen": "\\Chora_Renderer_File\u003A\u003A\u0024_view",
            "name": "_view",
            "summary": "",
            "url": "classes/Chora-Renderer-File.html#property__view"
        },                {
            "fqsen": "\\Chora_Renderer_File\u003A\u003A\u0024_file",
            "name": "_file",
            "summary": "",
            "url": "classes/Chora-Renderer-File.html#property__file"
        },                {
            "fqsen": "\\Chora_Renderer_File\u003A\u003A\u0024_revision",
            "name": "_revision",
            "summary": "",
            "url": "classes/Chora-Renderer-File.html#property__revision"
        },                {
            "fqsen": "\\Chora_Test",
            "name": "Chora_Test",
            "summary": "This\u0020class\u0020provides\u0020the\u0020Chora\u0020configuration\u0020for\u0020the\u0020test\u0020script.",
            "url": "classes/Chora-Test.html"
        },                {
            "fqsen": "\\Chora_Test\u003A\u003AappTests\u0028\u0029",
            "name": "appTests",
            "summary": "Any\u0020application\u0020specific\u0020tests\u0020that\u0020need\u0020to\u0020be\u0020done.",
            "url": "classes/Chora-Test.html#method_appTests"
        },                {
            "fqsen": "\\Chora_Test\u003A\u003A\u0024_moduleList",
            "name": "_moduleList",
            "summary": "The\u0020module\u0020list",
            "url": "classes/Chora-Test.html#property__moduleList"
        },                {
            "fqsen": "\\Chora_Test\u003A\u003A\u0024_settingsList",
            "name": "_settingsList",
            "summary": "PHP\u0020settings\u0020list.",
            "url": "classes/Chora-Test.html#property__settingsList"
        },                {
            "fqsen": "\\Chora_Test\u003A\u003A\u0024_pearList",
            "name": "_pearList",
            "summary": "PEAR\u0020modules\u0020list.",
            "url": "classes/Chora-Test.html#property__pearList"
        },                {
            "fqsen": "\\Chora_Test\u003A\u003A\u0024_fileList",
            "name": "_fileList",
            "summary": "Required\u0020configuration\u0020files.",
            "url": "classes/Chora-Test.html#property__fileList"
        },                {
            "fqsen": "\\Chora_Test\u003A\u003A\u0024_appList",
            "name": "_appList",
            "summary": "Inter\u002DHorde\u0020application\u0020dependencies.",
            "url": "classes/Chora-Test.html#property__appList"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
