Search.appendIndex(
    [
                {
            "fqsen": "\\Horde\\Hordectl\\Cli",
            "name": "Cli",
            "summary": "Hordectl\u0020CLI\u0020Root\u0020Module",
            "url": "classes/Horde-Hordectl-Cli.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Cli\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Cli.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Cli\u003A\u003Amain\u0028\u0029",
            "name": "main",
            "summary": "",
            "url": "classes/Horde-Hordectl-Cli.html#method_main"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Cli\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Horde-Hordectl-Cli.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Cli\u003A\u003A_prepareModular\u0028\u0029",
            "name": "_prepareModular",
            "summary": "Prepare\u0020the\u0020modular\u0020CLI\u0020instance.",
            "url": "classes/Horde-Hordectl-Cli.html#method__prepareModular"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Help",
            "name": "Help",
            "summary": "Help\u0020command\u0020module\u0020implements\u0020CLI\u0020help\/usage",
            "url": "classes/Horde-Hordectl-Command-Help.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Help\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Help.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Help\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Decide\u0020if\u0020this\u0020module\u0020handles\u0020the\u0020commandline",
            "url": "classes/Horde-Hordectl-Command-Help.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\App",
            "name": "App",
            "summary": "Import\u0020command\u0020module\u0020for\u0020Horde\u0020App\u0020provided\u0020resources",
            "url": "classes/Horde-Hordectl-Command-Import-App.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\App\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import-App.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\App\u003A\u003Aimport\u0028\u0029",
            "name": "import",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import-App.html#method_import"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\Group",
            "name": "Group",
            "summary": "Import\u0020command\u0020module\u0020for\u0020Horde\u0020groups",
            "url": "classes/Horde-Hordectl-Command-Import-Group.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\Group\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import-Group.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\Group\u003A\u003Aimport\u0028\u0029",
            "name": "import",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import-Group.html#method_import"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\Permission",
            "name": "Permission",
            "summary": "Import\u0020command\u0020module\u0020for\u0020Horde\u0020permissions",
            "url": "classes/Horde-Hordectl-Command-Import-Permission.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\Permission\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import-Permission.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\Permission\u003A\u003Aimport\u0028\u0029",
            "name": "import",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import-Permission.html#method_import"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\User",
            "name": "User",
            "summary": "Import\u0020command\u0020module\u0020for\u0020Horde\u0020users",
            "url": "classes/Horde-Hordectl-Command-Import-User.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import-User.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\\User\u003A\u003Aimport\u0028\u0029",
            "name": "import",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import-User.html#method_import"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import",
            "name": "Import",
            "summary": "Import\u0020command\u0020module\u0020implements\u0020CLI\u0020Query\u0020Yaml\u0020import",
            "url": "classes/Horde-Hordectl-Command-Import.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\u003A\u003AgetBaseOptions\u0028\u0029",
            "name": "getBaseOptions",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Import.html#method_getBaseOptions"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Decide\u0020if\u0020this\u0020module\u0020handles\u0020the\u0020commandline",
            "url": "classes/Horde-Hordectl-Command-Import.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Patch",
            "name": "Patch",
            "summary": "Command\u0020module\u0020to\u0020manipulate\u0020single\u0020resource\u0020entities",
            "url": "classes/Horde-Hordectl-Command-Patch.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Patch\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Patch.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Patch\u003A\u003AgetBaseOptions\u0028\u0029",
            "name": "getBaseOptions",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Patch.html#method_getBaseOptions"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Patch\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Decide\u0020if\u0020this\u0020module\u0020handles\u0020the\u0020commandline",
            "url": "classes/Horde-Hordectl-Command-Patch.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\App",
            "name": "App",
            "summary": "Query\u0020command\u0020module\u0020for\u0020resources\u0020implemented\u0020by\u0020Horde\u0020Registry\u0020Apps",
            "url": "classes/Horde-Hordectl-Command-Query-App.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\App\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Query-App.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\App\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Decide\u0020if\u0020this\u0020module\u0020handles\u0020the\u0020commandline",
            "url": "classes/Horde-Hordectl-Command-Query-App.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\Group",
            "name": "Group",
            "summary": "Query\u0020command\u0020module\u0020for\u0020Horde\u0020Group",
            "url": "classes/Horde-Hordectl-Command-Query-Group.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\Group\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Query-Group.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\Group\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Decide\u0020if\u0020this\u0020module\u0020handles\u0020the\u0020commandline",
            "url": "classes/Horde-Hordectl-Command-Query-Group.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\Permission",
            "name": "Permission",
            "summary": "Query\u0020command\u0020module\u0020for\u0020Horde\u0020permissions",
            "url": "classes/Horde-Hordectl-Command-Query-Permission.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\Permission\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Query-Permission.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\Permission\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Decide\u0020if\u0020this\u0020module\u0020handles\u0020the\u0020commandline",
            "url": "classes/Horde-Hordectl-Command-Query-Permission.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\User",
            "name": "User",
            "summary": "Query\u0020command\u0020module\u0020for\u0020Horde\u0020users",
            "url": "classes/Horde-Hordectl-Command-Query-User.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Query-User.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\\User\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Decide\u0020if\u0020this\u0020module\u0020handles\u0020the\u0020commandline",
            "url": "classes/Horde-Hordectl-Command-Query-User.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query",
            "name": "Query",
            "summary": "Query\u0020command\u0020module\u0020implements\u0020CLI\u0020Query\u0020Yaml\u0020output",
            "url": "classes/Horde-Hordectl-Command-Query.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Command-Query.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Decide\u0020if\u0020this\u0020module\u0020handles\u0020the\u0020commandline",
            "url": "classes/Horde-Hordectl-Command-Query.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Identity",
            "name": "Horde_Core_Factory_Identity",
            "summary": "A\u0020Horde_Injector\u0020based\u0020Horde_Identity\u0020factory.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Identity.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Identity\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Returns\u0020the\u0020Horde_Identity\u0020instance.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Identity.html#method_create"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Identity\u003A\u003A\u0024_instances",
            "name": "_instances",
            "summary": "Instances.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Identity.html#property__instances"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Prefs",
            "name": "Horde_Core_Factory_Prefs",
            "summary": "A\u0020Horde_Injector\u003A\u003A\u0020based\u0020Horde_Prefs\u003A\u003A\u0020factory.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Prefs.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Prefs\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Return\u0020the\u0020Horde_Prefs\u003A\u003A\u0020instance.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Prefs.html#method_create"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Prefs\u003A\u003A_notifyError\u0028\u0029",
            "name": "_notifyError",
            "summary": "Notifies\u0020\u0028once\u0029\u0020if\u0020one\u0020of\u0020the\u0020preference\u0020backends\u0020is\u0020not\u0020available\u0020and\nlogs\u0020details\u0020for\u0020the\u0020administrator.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Prefs.html#method__notifyError"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Prefs\u003A\u003A_getCache\u0028\u0029",
            "name": "_getCache",
            "summary": "Return\u0020the\u0020cache\u0020object\u0020to\u0020use\u0020for\u0020the\u0020prefs\u0020driver.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Prefs.html#method__getCache"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Prefs\u003A\u003AclearCache\u0028\u0029",
            "name": "clearCache",
            "summary": "Clears\u0020the\u0020instances\u0020cache.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Prefs.html#method_clearCache"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Prefs\u003A\u003AsizeCallback\u0028\u0029",
            "name": "sizeCallback",
            "summary": "Max\u0020size\u0020callback.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Prefs.html#method_sizeCallback"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Prefs\u003A\u003A\u0024storage",
            "name": "storage",
            "summary": "Storage\u0020driver.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Prefs.html#property_storage"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat\\Horde_Core_Factory_Prefs\u003A\u003A\u0024_instances",
            "name": "_instances",
            "summary": "Instances.",
            "url": "classes/Horde-Hordectl-Compat-Horde-Core-Factory-Prefs.html#property__instances"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Configuration\\AppConfigReader",
            "name": "AppConfigReader",
            "summary": "Handles\u0020reading\u0020a\u0020stack\u0020of\u0020configuration\u0020files",
            "url": "classes/Horde-Hordectl-Configuration-AppConfigReader.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Configuration\\AppConfigReader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Configuration-AppConfigReader.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Configuration\\AppConfigReader\u003A\u003AgetAppConfig\u0028\u0029",
            "name": "getAppConfig",
            "summary": "Read\u0020a\u0020stack\u0020of\u0020application\u0020\u0024conf\u0020files",
            "url": "classes/Horde-Hordectl-Configuration-AppConfigReader.html#method_getAppConfig"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Configuration\\AppConfigReader\u003A\u003A\u0024registry",
            "name": "registry",
            "summary": "",
            "url": "classes/Horde-Hordectl-Configuration-AppConfigReader.html#property_registry"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies",
            "name": "Dependencies",
            "summary": "",
            "url": "classes/Horde-Hordectl-Dependencies.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Dependencies.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003AfindHordePath\u0028\u0029",
            "name": "findHordePath",
            "summary": "Return\u0020the\u0020path\u0020to\u0020horde",
            "url": "classes/Horde-Hordectl-Dependencies.html#method_findHordePath"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003AbootstrapHorde\u0028\u0029",
            "name": "bootstrapHorde",
            "summary": "Perform\u0020bootstrap\u0020of\u0020the\u0020horde\u0020base\u0020app",
            "url": "classes/Horde-Hordectl-Dependencies.html#method_bootstrapHorde"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003AsetupCommonDependencies\u0028\u0029",
            "name": "setupCommonDependencies",
            "summary": "Setup\u0020some\u0020dependencies\u0020which\u0020are\u0020too\u0020simple\/common\u0020for\u0020a\u0020full\u0020factory",
            "url": "classes/Horde-Hordectl-Dependencies.html#method_setupCommonDependencies"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003AglobalizeHordeConfig\u0028\u0029",
            "name": "globalizeHordeConfig",
            "summary": "Expose\u0020Horde\u0020Config\u0020in\u0020global\u0020namespace",
            "url": "classes/Horde-Hordectl-Dependencies.html#method_globalizeHordeConfig"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003AglobalizeApp\u0028\u0029",
            "name": "globalizeApp",
            "summary": "Push\/initialize\u0020all\u0020globals\u0020which\u0020may\u0020be\u0020used\u0020by\u0020application\u0020code",
            "url": "classes/Horde-Hordectl-Dependencies.html#method_globalizeApp"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003AunglobalizeHordeConfig\u0028\u0029",
            "name": "unglobalizeHordeConfig",
            "summary": "Hide\u0020Horde\u0020Config\u0020from\u0020global\u0020namespace",
            "url": "classes/Horde-Hordectl-Dependencies.html#method_unglobalizeHordeConfig"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003AgetRegistryApplications\u0028\u0029",
            "name": "getRegistryApplications",
            "summary": "Return\u0020a\u0020list\u0020of\u0020applications\u0020from\u0020the\u0020Horde\u0020Registry",
            "url": "classes/Horde-Hordectl-Dependencies.html#method_getRegistryApplications"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003AgetApplicationResources\u0028\u0029",
            "name": "getApplicationResources",
            "summary": "Return\u0020the\u0020application\u0020resource\u0020provider",
            "url": "classes/Horde-Hordectl-Dependencies.html#method_getApplicationResources"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Dependencies\u003A\u003A\u0024hordeBootstrapped",
            "name": "hordeBootstrapped",
            "summary": "",
            "url": "classes/Horde-Hordectl-Dependencies.html#property_hordeBootstrapped"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HasModulesTrait",
            "name": "HasModulesTrait",
            "summary": "",
            "url": "classes/Horde-Hordectl-HasModulesTrait.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HasModulesTrait\u003A\u003A_initModules\u0028\u0029",
            "name": "_initModules",
            "summary": "Initialize\u0020the\u0020list\u0020of\u0020direct\u0020submodules\u0020to\u0020the\u0020current\u0020module",
            "url": "classes/Horde-Hordectl-HasModulesTrait.html#method__initModules"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HasModulesTrait\u003A\u003AlistModules\u0028\u0029",
            "name": "listModules",
            "summary": "List\u0020the\u0020available\u0020modules.",
            "url": "classes/Horde-Hordectl-HasModulesTrait.html#method_listModules"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HasModulesTrait\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/Horde-Hordectl-HasModulesTrait.html#method_getIterator"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HasModulesTrait\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "Implementation\u0020of\u0020Countable\u0020count\u0028\u0029\u0020method.\u0020Returns\u0020the\u0020number\u0020of\u0020modules.",
            "url": "classes/Horde-Hordectl-HasModulesTrait.html#method_count"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HasModulesTrait\u003A\u003A\u0024_modules",
            "name": "_modules",
            "summary": "",
            "url": "classes/Horde-Hordectl-HasModulesTrait.html#property__modules"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait",
            "name": "HordectlModuleTrait",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AisRootModule\u0028\u0029",
            "name": "isRootModule",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_isRootModule"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AgetParentModule\u0028\u0029",
            "name": "getParentModule",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_getParentModule"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AsetParentModule\u0028\u0029",
            "name": "setParentModule",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_setParentModule"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AgetUsage\u0028\u0029",
            "name": "getUsage",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_getUsage"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AgetBaseOptions\u0028\u0029",
            "name": "getBaseOptions",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_getBaseOptions"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AhasOptionGroup\u0028\u0029",
            "name": "hasOptionGroup",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_hasOptionGroup"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AgetOptionGroupDescription\u0028\u0029",
            "name": "getOptionGroupDescription",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_getOptionGroupDescription"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AgetOptionGroupOptions\u0028\u0029",
            "name": "getOptionGroupOptions",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_getOptionGroupOptions"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AgetOptionGroupTitle\u0028\u0029",
            "name": "getOptionGroupTitle",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_getOptionGroupTitle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Default\u0020implementation\u0020of\u0020getTitle",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_getTitle"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AgetPositionalArgs\u0028\u0029",
            "name": "getPositionalArgs",
            "summary": "Get\u0020the\u0020list\u0020of\u0020possible\u0020arguments\u0020for\u0020this\u0020module\u0027s\u0020position",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_getPositionalArgs"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003AhandleCommandline\u0028\u0029",
            "name": "handleCommandline",
            "summary": "Handle\u0020commandline\u0020given\u0020to\u0020this\u0020module",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#method_handleCommandline"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003A\u0024_parentModule",
            "name": "_parentModule",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#property__parentModule"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003A\u0024_parsed",
            "name": "_parsed",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#property__parsed"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003A\u0024_positional",
            "name": "_positional",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#property__positional"
        },                {
            "fqsen": "\\Horde\\Hordectl\\HordectlModuleTrait\u003A\u003A\u0024_parser",
            "name": "_parser",
            "summary": "",
            "url": "classes/Horde-Hordectl-HordectlModuleTrait.html#property__parser"
        },                {
            "fqsen": "\\Horde\\HordeCtl\\HordeInstallationFinder",
            "name": "HordeInstallationFinder",
            "summary": "Horde\u0020Installation\u0020finder",
            "url": "classes/Horde-HordeCtl-HordeInstallationFinder.html"
        },                {
            "fqsen": "\\Horde\\HordeCtl\\HordeInstallationFinder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-HordeCtl-HordeInstallationFinder.html#method___construct"
        },                {
            "fqsen": "\\Horde\\HordeCtl\\HordeInstallationFinder\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Find\u0020a\u0020horde\u0020installation",
            "url": "classes/Horde-HordeCtl-HordeInstallationFinder.html#method_find"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Group",
            "name": "Group",
            "summary": "Resource\u0020Group\u0020handles\u0020querying\u0020and\u0020formatting\ngroup\u0020representations",
            "url": "classes/Horde-Hordectl-Repository-Group.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Group\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Group.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Group\u003A\u003Aexport\u0028\u0029",
            "name": "export",
            "summary": "Export\u0020Group\u0020names\u0020and\u0020members",
            "url": "classes/Horde-Hordectl-Repository-Group.html#method_export"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Group\u003A\u003Aimport\u0028\u0029",
            "name": "import",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Group.html#method_import"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Group\u003A\u003AgetGroupIdByName\u0028\u0029",
            "name": "getGroupIdByName",
            "summary": "Resolve\u0020group\u0020names\u0020to\u0020Ids",
            "url": "classes/Horde-Hordectl-Repository-Group.html#method_getGroupIdByName"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Group\u003A\u003Aexists\u0028\u0029",
            "name": "exists",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Group.html#method_exists"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Group\u003A\u003AgetGroupNameById\u0028\u0029",
            "name": "getGroupNameById",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Group.html#method_getGroupNameById"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Group\u003A\u003A\u0024_driver",
            "name": "_driver",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Group.html#property__driver"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Permission",
            "name": "Permission",
            "summary": "Resource\u0020Group\u0020handles\u0020querying\u0020and\u0020formatting\ngroup\u0020representations",
            "url": "classes/Horde-Hordectl-Repository-Permission.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Permission\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Permission.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Permission\u003A\u003Aexport\u0028\u0029",
            "name": "export",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Permission.html#method_export"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Permission\u003A\u003A_exportGroupPermissions\u0028\u0029",
            "name": "_exportGroupPermissions",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Permission.html#method__exportGroupPermissions"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Permission\u003A\u003Aimport\u0028\u0029",
            "name": "import",
            "summary": "Import\u0020a\u0020single\u0020permission",
            "url": "classes/Horde-Hordectl-Repository-Permission.html#method_import"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Permission\u003A\u003A_importGroupPermissions\u0028\u0029",
            "name": "_importGroupPermissions",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Permission.html#method__importGroupPermissions"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Permission\u003A\u003A\u0024_perms",
            "name": "_perms",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Permission.html#property__perms"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Permission\u003A\u003A\u0024_corePerms",
            "name": "_corePerms",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Permission.html#property__corePerms"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\Permission\u003A\u003A\u0024_groupRepo",
            "name": "_groupRepo",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-Permission.html#property__groupRepo"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\User",
            "name": "User",
            "summary": "Resource\u0020User\u0020handles\u0020querying\u0020and\u0020formatting\nuser\u0020representations",
            "url": "classes/Horde-Hordectl-Repository-User.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-User.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\User\u003A\u003Aexport\u0028\u0029",
            "name": "export",
            "summary": "Export\u0020user\u0020uid\u0027s",
            "url": "classes/Horde-Hordectl-Repository-User.html#method_export"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\User\u003A\u003Aimport\u0028\u0029",
            "name": "import",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-User.html#method_import"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\User\u003A\u003A_saveIdentities\u0028\u0029",
            "name": "_saveIdentities",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-User.html#method__saveIdentities"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\User\u003A\u003Aexists\u0028\u0029",
            "name": "exists",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-User.html#method_exists"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\User\u003A\u003A\u0024_driver",
            "name": "_driver",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-User.html#property__driver"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository\\User\u003A\u003A\u0024_identity",
            "name": "_identity",
            "summary": "",
            "url": "classes/Horde-Hordectl-Repository-User.html#property__identity"
        },                {
            "fqsen": "\\Horde\\Hordectl\\YamlWriter",
            "name": "YamlWriter",
            "summary": "",
            "url": "classes/Horde-Hordectl-YamlWriter.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\YamlWriter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Hordectl-YamlWriter.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Hordectl\\YamlWriter\u003A\u003AaddResource\u0028\u0029",
            "name": "addResource",
            "summary": "",
            "url": "classes/Horde-Hordectl-YamlWriter.html#method_addResource"
        },                {
            "fqsen": "\\Horde\\Hordectl\\YamlWriter\u003A\u003Adump\u0028\u0029",
            "name": "dump",
            "summary": "",
            "url": "classes/Horde-Hordectl-YamlWriter.html#method_dump"
        },                {
            "fqsen": "\\Horde\\Hordectl\\YamlWriter\u003A\u003A\u0024_dumper",
            "name": "_dumper",
            "summary": "",
            "url": "classes/Horde-Hordectl-YamlWriter.html#property__dumper"
        },                {
            "fqsen": "\\Horde\\Hordectl\\YamlWriter\u003A\u003A\u0024_resources",
            "name": "_resources",
            "summary": "",
            "url": "classes/Horde-Hordectl-YamlWriter.html#property__resources"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Hordectl",
            "name": "Hordectl",
            "summary": "",
            "url": "namespaces/horde-hordectl.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command",
            "name": "Command",
            "summary": "",
            "url": "namespaces/horde-hordectl-command.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Import",
            "name": "Import",
            "summary": "",
            "url": "namespaces/horde-hordectl-command-import.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Command\\Query",
            "name": "Query",
            "summary": "",
            "url": "namespaces/horde-hordectl-command-query.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Compat",
            "name": "Compat",
            "summary": "",
            "url": "namespaces/horde-hordectl-compat.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Configuration",
            "name": "Configuration",
            "summary": "",
            "url": "namespaces/horde-hordectl-configuration.html"
        },                {
            "fqsen": "\\Horde\\HordeCtl",
            "name": "HordeCtl",
            "summary": "",
            "url": "namespaces/horde-hordectl.html"
        },                {
            "fqsen": "\\Horde\\Hordectl\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/horde-hordectl-repository.html"
        }            ]
);
