Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_Constraint_AlwaysFalse",
            "name": "Horde_Constraint_AlwaysFalse",
            "summary": "Always\u0020returns\u0020false",
            "url": "classes/Horde-Constraint-AlwaysFalse.html"
        },                {
            "fqsen": "\\Horde_Constraint_AlwaysFalse\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-AlwaysFalse.html#method_evaluate"
        },                {
            "fqsen": "\\Horde_Constraint_AlwaysTrue",
            "name": "Horde_Constraint_AlwaysTrue",
            "summary": "Always\u0020returns\u0020true",
            "url": "classes/Horde-Constraint-AlwaysTrue.html"
        },                {
            "fqsen": "\\Horde_Constraint_AlwaysTrue\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-AlwaysTrue.html#method_evaluate"
        },                {
            "fqsen": "\\Horde_Constraint_And",
            "name": "Horde_Constraint_And",
            "summary": "Represents\u0020a\u0020collection\u0020of\u0020constraints,\u0020if\u0020one\u0020is\u0020false,\u0020this\u0020collection\u0020will\nevaluate\u0020to\u0020false",
            "url": "classes/Horde-Constraint-And.html"
        },                {
            "fqsen": "\\Horde_Constraint_And\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-And.html#method_evaluate"
        },                {
            "fqsen": "\\Horde_Constraint_Coupler",
            "name": "Horde_Constraint_Coupler",
            "summary": "Interface\u0020for\u0020grouped\u0020\u0028compound,\u0020coupled\u0029\u0020constraints.",
            "url": "classes/Horde-Constraint-Coupler.html"
        },                {
            "fqsen": "\\Horde_Constraint_Coupler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-Coupler.html#method___construct"
        },                {
            "fqsen": "\\Horde_Constraint_Coupler\u003A\u003AaddConstraint\u0028\u0029",
            "name": "addConstraint",
            "summary": "",
            "url": "classes/Horde-Constraint-Coupler.html#method_addConstraint"
        },                {
            "fqsen": "\\Horde_Constraint_Coupler\u003A\u003AgetConstraints\u0028\u0029",
            "name": "getConstraints",
            "summary": "",
            "url": "classes/Horde-Constraint-Coupler.html#method_getConstraints"
        },                {
            "fqsen": "\\Horde_Constraint_Coupler\u003A\u003A\u0024_constraints",
            "name": "_constraints",
            "summary": "",
            "url": "classes/Horde-Constraint-Coupler.html#property__constraints"
        },                {
            "fqsen": "\\Horde_Constraint_IsEqual",
            "name": "Horde_Constraint_IsEqual",
            "summary": "Checks\u0020for\u0020equality",
            "url": "classes/Horde-Constraint-IsEqual.html"
        },                {
            "fqsen": "\\Horde_Constraint_IsEqual\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-IsEqual.html#method___construct"
        },                {
            "fqsen": "\\Horde_Constraint_IsEqual\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-IsEqual.html#method_evaluate"
        },                {
            "fqsen": "\\Horde_Constraint_IsEqual\u003A\u003A\u0024_value",
            "name": "_value",
            "summary": "",
            "url": "classes/Horde-Constraint-IsEqual.html#property__value"
        },                {
            "fqsen": "\\Horde_Constraint_IsInstanceOf",
            "name": "Horde_Constraint_IsInstanceOf",
            "summary": "Checks\u0020for\u0020an\u0020instance\u0020of\u0020a\u0020class",
            "url": "classes/Horde-Constraint-IsInstanceOf.html"
        },                {
            "fqsen": "\\Horde_Constraint_IsInstanceOf\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-IsInstanceOf.html#method___construct"
        },                {
            "fqsen": "\\Horde_Constraint_IsInstanceOf\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-IsInstanceOf.html#method_evaluate"
        },                {
            "fqsen": "\\Horde_Constraint_IsInstanceOf\u003A\u003A\u0024_type",
            "name": "_type",
            "summary": "",
            "url": "classes/Horde-Constraint-IsInstanceOf.html#property__type"
        },                {
            "fqsen": "\\Horde_Constraint_Not",
            "name": "Horde_Constraint_Not",
            "summary": "Negates\u0020another\u0020constraint",
            "url": "classes/Horde-Constraint-Not.html"
        },                {
            "fqsen": "\\Horde_Constraint_Not\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-Not.html#method___construct"
        },                {
            "fqsen": "\\Horde_Constraint_Not\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-Not.html#method_evaluate"
        },                {
            "fqsen": "\\Horde_Constraint_Not\u003A\u003A\u0024_constraint",
            "name": "_constraint",
            "summary": "",
            "url": "classes/Horde-Constraint-Not.html#property__constraint"
        },                {
            "fqsen": "\\Horde_Constraint_Null",
            "name": "Horde_Constraint_Null",
            "summary": "Checks\u0020if\u0020the\u0020value\u0020is\u0020null",
            "url": "classes/Horde-Constraint-Null.html"
        },                {
            "fqsen": "\\Horde_Constraint_Null\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-Null.html#method_evaluate"
        },                {
            "fqsen": "\\Horde_Constraint_Or",
            "name": "Horde_Constraint_Or",
            "summary": "Represents\u0020a\u0020collection\u0020of\u0020constraints,\u0020if\u0020any\u0020are\u0020true,\u0020the\u0020collection\u0020will\u0020evaluate\u0020to\u0020true.",
            "url": "classes/Horde-Constraint-Or.html"
        },                {
            "fqsen": "\\Horde_Constraint_Or\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-Or.html#method_evaluate"
        },                {
            "fqsen": "\\Horde_Constraint_PregMatch",
            "name": "Horde_Constraint_PregMatch",
            "summary": "Matches\u0020against\u0020a\u0020PCRE\u0020regex",
            "url": "classes/Horde-Constraint-PregMatch.html"
        },                {
            "fqsen": "\\Horde_Constraint_PregMatch\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-PregMatch.html#method___construct"
        },                {
            "fqsen": "\\Horde_Constraint_PregMatch\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-PregMatch.html#method_evaluate"
        },                {
            "fqsen": "\\Horde_Constraint_PregMatch\u003A\u003A\u0024_regex",
            "name": "_regex",
            "summary": "",
            "url": "classes/Horde-Constraint-PregMatch.html#property__regex"
        },                {
            "fqsen": "\\Horde_Constraint",
            "name": "Horde_Constraint",
            "summary": "Interface\u0020for\u0020constraints.",
            "url": "classes/Horde-Constraint.html"
        },                {
            "fqsen": "\\Horde_Constraint\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\AlwaysFalse",
            "name": "AlwaysFalse",
            "summary": "Always\u0020returns\u0020false",
            "url": "classes/Horde-Constraint-AlwaysFalse.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\AlwaysFalse\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-AlwaysFalse.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\AlwaysTrue",
            "name": "AlwaysTrue",
            "summary": "Always\u0020returns\u0020true",
            "url": "classes/Horde-Constraint-AlwaysTrue.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\AlwaysTrue\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-AlwaysTrue.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\AndCoupler",
            "name": "AndCoupler",
            "summary": "Represents\u0020a\u0020collection\u0020of\u0020constraints,\u0020if\u0020one\u0020is\u0020false,\u0020this\u0020collection\u0020will\nevaluate\u0020to\u0020false",
            "url": "classes/Horde-Constraint-AndCoupler.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\AndCoupler\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-AndCoupler.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\Constraint",
            "name": "Constraint",
            "summary": "Interface\u0020for\u0020constraints.",
            "url": "classes/Horde-Constraint-Constraint.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\Constraint\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-Constraint.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\Coupler",
            "name": "Coupler",
            "summary": "Interface\u0020for\u0020grouped\u0020\u0028compound,\u0020coupled\u0029\u0020constraints.",
            "url": "classes/Horde-Constraint-Coupler.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\Coupler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-Coupler.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Constraint\\Coupler\u003A\u003AaddConstraint\u0028\u0029",
            "name": "addConstraint",
            "summary": "",
            "url": "classes/Horde-Constraint-Coupler.html#method_addConstraint"
        },                {
            "fqsen": "\\Horde\\Constraint\\Coupler\u003A\u003AgetConstraints\u0028\u0029",
            "name": "getConstraints",
            "summary": "",
            "url": "classes/Horde-Constraint-Coupler.html#method_getConstraints"
        },                {
            "fqsen": "\\Horde\\Constraint\\Coupler\u003A\u003A\u0024constraints",
            "name": "constraints",
            "summary": "",
            "url": "classes/Horde-Constraint-Coupler.html#property_constraints"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsEqual",
            "name": "IsEqual",
            "summary": "Checks\u0020for\u0020equality",
            "url": "classes/Horde-Constraint-IsEqual.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsEqual\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-IsEqual.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsEqual\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-IsEqual.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsEqual\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Horde-Constraint-IsEqual.html#property_value"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsInstanceOf",
            "name": "IsInstanceOf",
            "summary": "Checks\u0020for\u0020an\u0020instance\u0020of\u0020a\u0020class",
            "url": "classes/Horde-Constraint-IsInstanceOf.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsInstanceOf\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-IsInstanceOf.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsInstanceOf\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-IsInstanceOf.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsInstanceOf\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Horde-Constraint-IsInstanceOf.html#property_type"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsNull",
            "name": "IsNull",
            "summary": "Checks\u0020if\u0020the\u0020value\u0020is\u0020null",
            "url": "classes/Horde-Constraint-IsNull.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\IsNull\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-IsNull.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\Not",
            "name": "Not",
            "summary": "Negates\u0020another\u0020constraint",
            "url": "classes/Horde-Constraint-Not.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\Not\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-Not.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Constraint\\Not\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-Not.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\Not\u003A\u003A\u0024constraint",
            "name": "constraint",
            "summary": "",
            "url": "classes/Horde-Constraint-Not.html#property_constraint"
        },                {
            "fqsen": "\\Horde\\Constraint\\OrCoupler",
            "name": "OrCoupler",
            "summary": "Represents\u0020a\u0020collection\u0020of\u0020constraints,\u0020if\u0020any\u0020are\u0020true,\u0020the\u0020collection\u0020will\u0020evaluate\u0020to\u0020true.",
            "url": "classes/Horde-Constraint-OrCoupler.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\OrCoupler\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-OrCoupler.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\PregMatch",
            "name": "PregMatch",
            "summary": "Matches\u0020against\u0020a\u0020PCRE\u0020regex",
            "url": "classes/Horde-Constraint-PregMatch.html"
        },                {
            "fqsen": "\\Horde\\Constraint\\PregMatch\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Constraint-PregMatch.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Constraint\\PregMatch\u003A\u003Aevaluate\u0028\u0029",
            "name": "evaluate",
            "summary": "",
            "url": "classes/Horde-Constraint-PregMatch.html#method_evaluate"
        },                {
            "fqsen": "\\Horde\\Constraint\\PregMatch\u003A\u003A\u0024regex",
            "name": "regex",
            "summary": "",
            "url": "classes/Horde-Constraint-PregMatch.html#property_regex"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Constraint",
            "name": "Constraint",
            "summary": "",
            "url": "namespaces/horde-constraint.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
