Search.appendIndex(
    [
                {
            "fqsen": "\\Horde\\Otp\\Facade",
            "name": "Facade",
            "summary": "Facade\u0020for\u0020interacting\u0020with\u0020the\u0020OTP\u0020system",
            "url": "classes/Horde-Otp-Facade.html"
        },                {
            "fqsen": "\\Horde\\Otp\\Facade\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Otp-Facade.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Otp\\Facade\u003A\u003AcheckHasOtpSetup\u0028\u0029",
            "name": "checkHasOtpSetup",
            "summary": "Check\u0020if\u0020a\u0020subject\u0020has\u0020opted\u0020in\u0020to\u0020OTP\u0020usage",
            "url": "classes/Horde-Otp-Facade.html#method_checkHasOtpSetup"
        },                {
            "fqsen": "\\Horde\\Otp\\Facade\u003A\u003AcheckMustUseOtp\u0028\u0029",
            "name": "checkMustUseOtp",
            "summary": "",
            "url": "classes/Horde-Otp-Facade.html#method_checkMustUseOtp"
        },                {
            "fqsen": "\\Horde\\Otp\\Facade\u003A\u003AresetOtpSetup\u0028\u0029",
            "name": "resetOtpSetup",
            "summary": "",
            "url": "classes/Horde-Otp-Facade.html#method_resetOtpSetup"
        },                {
            "fqsen": "\\Horde\\Otp\\Facade\u003A\u003AvalidatePasscode\u0028\u0029",
            "name": "validatePasscode",
            "summary": "Validate\u0020a\u0020user\u0020input",
            "url": "classes/Horde-Otp-Facade.html#method_validatePasscode"
        },                {
            "fqsen": "\\Horde\\Otp\\FileStorage",
            "name": "FileStorage",
            "summary": "",
            "url": "classes/Horde-Otp-FileStorage.html"
        },                {
            "fqsen": "\\Horde\\Otp\\FileStorage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Otp-FileStorage.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Otp\\FileStorage\u003A\u003AgetSetup\u0028\u0029",
            "name": "getSetup",
            "summary": "",
            "url": "classes/Horde-Otp-FileStorage.html#method_getSetup"
        },                {
            "fqsen": "\\Horde\\Otp\\FileStorage\u003A\u003AsaveSetup\u0028\u0029",
            "name": "saveSetup",
            "summary": "",
            "url": "classes/Horde-Otp-FileStorage.html#method_saveSetup"
        },                {
            "fqsen": "\\Horde\\Otp\\FileStorage\u003A\u003Afilename\u0028\u0029",
            "name": "filename",
            "summary": "Generate\u0020a\u0020filename\u0020in\u0020storageDir",
            "url": "classes/Horde-Otp-FileStorage.html#method_filename"
        },                {
            "fqsen": "\\Horde\\Otp\\FileStorage\u003A\u003A\u0024storageDir",
            "name": "storageDir",
            "summary": "",
            "url": "classes/Horde-Otp-FileStorage.html#property_storageDir"
        },                {
            "fqsen": "\\Horde\\Otp\\Hotp",
            "name": "Hotp",
            "summary": "HOTP\u0020\u0028RFC\u00206238\u0029",
            "url": "classes/Horde-Otp-Hotp.html"
        },                {
            "fqsen": "\\Horde\\Otp\\Hotp\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "A\u0020human\u0020readable\u0020name",
            "url": "classes/Horde-Otp-Hotp.html#method_name"
        },                {
            "fqsen": "\\Horde\\Otp\\Hotp\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Horde-Otp-Hotp.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Horde\\Otp\\Hotp\u003A\u003AfromJson\u0028\u0029",
            "name": "fromJson",
            "summary": "Construct\u0020from\u0020a\u0020JSON\u0020string\u0020with\u0020parameters",
            "url": "classes/Horde-Otp-Hotp.html#method_fromJson"
        },                {
            "fqsen": "\\Horde\\Otp\\Hotp\u003A\u003AfromParams\u0028\u0029",
            "name": "fromParams",
            "summary": "Construct\u0020from\u0020a\u0020plain\u0020object\u0020with\u0020parameters",
            "url": "classes/Horde-Otp-Hotp.html#method_fromParams"
        },                {
            "fqsen": "\\Horde\\Otp\\Hotp\u003A\u003ASUPPORTED_ALGORITHMS",
            "name": "SUPPORTED_ALGORITHMS",
            "summary": "",
            "url": "classes/Horde-Otp-Hotp.html#constant_SUPPORTED_ALGORITHMS"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpCalculationTrait",
            "name": "OtpCalculationTrait",
            "summary": "A\u0020trait\u0020with\u0020shared\u0020implementation\u0020code\u0020for\u0020TOTP\u0020and\u0020HOTP",
            "url": "classes/Horde-Otp-OtpCalculationTrait.html"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpCalculationTrait\u003A\u003AcalculateSerial\u0028\u0029",
            "name": "calculateSerial",
            "summary": "",
            "url": "classes/Horde-Otp-OtpCalculationTrait.html#method_calculateSerial"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpCalculationTrait\u003A\u003ApadSecret\u0028\u0029",
            "name": "padSecret",
            "summary": "",
            "url": "classes/Horde-Otp-OtpCalculationTrait.html#method_padSecret"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpCalculationTrait\u003A\u003AgenerateHotp\u0028\u0029",
            "name": "generateHotp",
            "summary": "",
            "url": "classes/Horde-Otp-OtpCalculationTrait.html#method_generateHotp"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpCalculationTrait\u003A\u003AbuildHotpValue\u0028\u0029",
            "name": "buildHotpValue",
            "summary": "",
            "url": "classes/Horde-Otp-OtpCalculationTrait.html#method_buildHotpValue"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpCalculationTrait\u003A\u003ApackCounter\u0028\u0029",
            "name": "packCounter",
            "summary": "Pack\u0020the\u0020counter\u0020to\u0020a\u0020binary\u0020string\u0020of\u00208\u0020chars",
            "url": "classes/Horde-Otp-OtpCalculationTrait.html#method_packCounter"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpCalculationTrait\u003A\u003A\u0024startTime",
            "name": "startTime",
            "summary": "",
            "url": "classes/Horde-Otp-OtpCalculationTrait.html#property_startTime"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpCalculationTrait\u003A\u003A\u0024algorithm",
            "name": "algorithm",
            "summary": "",
            "url": "classes/Horde-Otp-OtpCalculationTrait.html#property_algorithm"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpCalculationTrait\u003A\u003A\u0024window",
            "name": "window",
            "summary": "",
            "url": "classes/Horde-Otp-OtpCalculationTrait.html#property_window"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpType",
            "name": "OtpType",
            "summary": "Interface\u0020of\u0020an\u0020OTP\u0020Type\u0020Definition",
            "url": "classes/Horde-Otp-OtpType.html"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpType\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "A\u0020human\u0020readable\u0020name",
            "url": "classes/Horde-Otp-OtpType.html#method_name"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpType\u003A\u003AfromJson\u0028\u0029",
            "name": "fromJson",
            "summary": "Construct\u0020from\u0020a\u0020JSON\u0020string\u0020with\u0020parameters",
            "url": "classes/Horde-Otp-OtpType.html#method_fromJson"
        },                {
            "fqsen": "\\Horde\\Otp\\OtpType\u003A\u003AfromParams\u0028\u0029",
            "name": "fromParams",
            "summary": "Construct\u0020from\u0020a\u0020plain\u0020object\u0020with\u0020parameters",
            "url": "classes/Horde-Otp-OtpType.html#method_fromParams"
        },                {
            "fqsen": "\\Horde\\Otp\\SecretGenerator",
            "name": "SecretGenerator",
            "summary": "",
            "url": "classes/Horde-Otp-SecretGenerator.html"
        },                {
            "fqsen": "\\Horde\\Otp\\SecretGenerator\u003A\u003AgenerateRandomSecret\u0028\u0029",
            "name": "generateRandomSecret",
            "summary": "",
            "url": "classes/Horde-Otp-SecretGenerator.html#method_generateRandomSecret"
        },                {
            "fqsen": "\\Horde\\Otp\\StaticSecret",
            "name": "StaticSecret",
            "summary": "An\u0020OtpType\u0020implementing\u0020a\u0020static\u0020secret",
            "url": "classes/Horde-Otp-StaticSecret.html"
        },                {
            "fqsen": "\\Horde\\Otp\\StaticSecret\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "A\u0020human\u0020readable\u0020name",
            "url": "classes/Horde-Otp-StaticSecret.html#method_name"
        },                {
            "fqsen": "\\Horde\\Otp\\StaticSecret\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Horde-Otp-StaticSecret.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Horde\\Otp\\StaticSecret\u003A\u003AfromJson\u0028\u0029",
            "name": "fromJson",
            "summary": "Construct\u0020from\u0020a\u0020JSON\u0020string\u0020with\u0020parameters",
            "url": "classes/Horde-Otp-StaticSecret.html#method_fromJson"
        },                {
            "fqsen": "\\Horde\\Otp\\StaticSecret\u003A\u003AfromParams\u0028\u0029",
            "name": "fromParams",
            "summary": "Construct\u0020from\u0020a\u0020plain\u0020object\u0020with\u0020parameters",
            "url": "classes/Horde-Otp-StaticSecret.html#method_fromParams"
        },                {
            "fqsen": "\\Horde\\Otp\\Storage",
            "name": "Storage",
            "summary": "",
            "url": "classes/Horde-Otp-Storage.html"
        },                {
            "fqsen": "\\Horde\\Otp\\Storage\u003A\u003AgetSetup\u0028\u0029",
            "name": "getSetup",
            "summary": "",
            "url": "classes/Horde-Otp-Storage.html#method_getSetup"
        },                {
            "fqsen": "\\Horde\\Otp\\Storage\u003A\u003AsaveSetup\u0028\u0029",
            "name": "saveSetup",
            "summary": "",
            "url": "classes/Horde-Otp-Storage.html#method_saveSetup"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp",
            "name": "Totp",
            "summary": "TOTP\u0020\u0028RFC\u00206238\u0029",
            "url": "classes/Horde-Otp-Totp.html"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Otp-Totp.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "A\u0020human\u0020readable\u0020name",
            "url": "classes/Horde-Otp-Totp.html#method_name"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Horde-Otp-Totp.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp\u003A\u003AfromJson\u0028\u0029",
            "name": "fromJson",
            "summary": "Construct\u0020from\u0020a\u0020JSON\u0020string\u0020with\u0020parameters",
            "url": "classes/Horde-Otp-Totp.html#method_fromJson"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp\u003A\u003AfromParams\u0028\u0029",
            "name": "fromParams",
            "summary": "Construct\u0020from\u0020a\u0020plain\u0020object\u0020with\u0020parameters",
            "url": "classes/Horde-Otp-Totp.html#method_fromParams"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp\u003A\u003ASUPPORTED_ALGORITHMS",
            "name": "SUPPORTED_ALGORITHMS",
            "summary": "",
            "url": "classes/Horde-Otp-Totp.html#constant_SUPPORTED_ALGORITHMS"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp\u003A\u003A\u0024secret",
            "name": "secret",
            "summary": "",
            "url": "classes/Horde-Otp-Totp.html#property_secret"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp\u003A\u003A\u0024grace",
            "name": "grace",
            "summary": "",
            "url": "classes/Horde-Otp-Totp.html#property_grace"
        },                {
            "fqsen": "\\Horde\\Otp\\Totp\u003A\u003A\u0024digits",
            "name": "digits",
            "summary": "",
            "url": "classes/Horde-Otp-Totp.html#property_digits"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Otp",
            "name": "Otp",
            "summary": "",
            "url": "namespaces/horde-otp.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
