Search.appendIndex(
    [
                {
            "fqsen": "\\Timeobjects_Api",
            "name": "Timeobjects_Api",
            "summary": "API\u0020methods\u0020for\u0020exposing\u0020various\u0020bits\u0020of\u0020data\u0020via\u0020the\u0020listTimeObjects\u0020API.",
            "url": "classes/Timeobjects-Api.html"
        },                {
            "fqsen": "\\Timeobjects_Api\u003A\u003AlistTimeObjectCategories\u0028\u0029",
            "name": "listTimeObjectCategories",
            "summary": "Returns\u0020the\u0020available\u0020categories.",
            "url": "classes/Timeobjects-Api.html#method_listTimeObjectCategories"
        },                {
            "fqsen": "\\Timeobjects_Api\u003A\u003AlistTimeObjects\u0028\u0029",
            "name": "listTimeObjects",
            "summary": "Returns\u0020time\u0020objects\u0020for\u0020the\u0020requested\u0020category.",
            "url": "classes/Timeobjects-Api.html#method_listTimeObjects"
        },                {
            "fqsen": "\\Timeobjects_Api\u003A\u003A\u0024_links",
            "name": "_links",
            "summary": "Links.",
            "url": "classes/Timeobjects-Api.html#property__links"
        },                {
            "fqsen": "\\TIMEOBJECTS_BASE",
            "name": "TIMEOBJECTS_BASE",
            "summary": "",
            "url": "namespaces/default.html#constant_TIMEOBJECTS_BASE"
        },                {
            "fqsen": "\\HORDE_BASE",
            "name": "HORDE_BASE",
            "summary": "",
            "url": "namespaces/default.html#constant_HORDE_BASE"
        },                {
            "fqsen": "\\Timeobjects_Application",
            "name": "Timeobjects_Application",
            "summary": "",
            "url": "classes/Timeobjects-Application.html"
        },                {
            "fqsen": "\\Timeobjects_Application\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/Timeobjects-Application.html#property_version"
        },                {
            "fqsen": "\\TimeObjects_Driver_Base",
            "name": "TimeObjects_Driver_Base",
            "summary": "Base\u0020TimeObjects_Driver.",
            "url": "classes/TimeObjects-Driver-Base.html"
        },                {
            "fqsen": "\\TimeObjects_Driver_Base\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/TimeObjects-Driver-Base.html#method___construct"
        },                {
            "fqsen": "\\TimeObjects_Driver_Base\u003A\u003AlistTimeObjects\u0028\u0029",
            "name": "listTimeObjects",
            "summary": "Get\u0020a\u0020list\u0020of\u0020TimeObjects.",
            "url": "classes/TimeObjects-Driver-Base.html#method_listTimeObjects"
        },                {
            "fqsen": "\\TimeObjects_Driver_Base\u003A\u003Aensure\u0028\u0029",
            "name": "ensure",
            "summary": "Ensure\u0020we\u0020have\u0020minimum\u0020requirements\u0020for\u0020concrete\u0020driver\u0020to\u0020run.",
            "url": "classes/TimeObjects-Driver-Base.html#method_ensure"
        },                {
            "fqsen": "\\TimeObjects_Driver_Base\u003A\u003Afactory\u0028\u0029",
            "name": "factory",
            "summary": "Factory\u0020method",
            "url": "classes/TimeObjects-Driver-Base.html#method_factory"
        },                {
            "fqsen": "\\TimeObjects_Driver_Base\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "",
            "url": "classes/TimeObjects-Driver-Base.html#property__params"
        },                {
            "fqsen": "\\TimeObjects_Driver_FacebookEvents",
            "name": "TimeObjects_Driver_FacebookEvents",
            "summary": "TimeObjects\u0020driver\u0020for\u0020exposing\u0020a\u0020user\u0027s\u0020Facebook\u0020Events\u0020via\u0020the\nlistTimeObjects\u0020API.",
            "url": "classes/TimeObjects-Driver-FacebookEvents.html"
        },                {
            "fqsen": "\\TimeObjects_Driver_FacebookEvents\u003A\u003Aensure\u0028\u0029",
            "name": "ensure",
            "summary": "Ensure\u0020we\u0020have\u0020minimum\u0020requirements\u0020for\u0020concrete\u0020driver\u0020to\u0020run.",
            "url": "classes/TimeObjects-Driver-FacebookEvents.html#method_ensure"
        },                {
            "fqsen": "\\TimeObjects_Driver_FacebookEvents\u003A\u003AlistTimeObjects\u0028\u0029",
            "name": "listTimeObjects",
            "summary": "Get\u0020a\u0020list\u0020of\u0020TimeObjects.",
            "url": "classes/TimeObjects-Driver-FacebookEvents.html#method_listTimeObjects"
        },                {
            "fqsen": "\\TimeObjects_Driver_FacebookEvents\u003A\u003A_getFacebook\u0028\u0029",
            "name": "_getFacebook",
            "summary": "",
            "url": "classes/TimeObjects-Driver-FacebookEvents.html#method__getFacebook"
        },                {
            "fqsen": "\\TimeObjects_Driver_FacebookEvents\u003A\u003A\u0024_fb_session",
            "name": "_fb_session",
            "summary": "",
            "url": "classes/TimeObjects-Driver-FacebookEvents.html#property__fb_session"
        },                {
            "fqsen": "\\TimeObjects_Driver_Weather",
            "name": "TimeObjects_Driver_Weather",
            "summary": "TimeObjects\u0020driver\u0020for\u0020exposing\u0020weatherunderground\u0020information\u0020via\u0020the\nlistTimeObjects\u0020API.",
            "url": "classes/TimeObjects-Driver-Weather.html"
        },                {
            "fqsen": "\\TimeObjects_Driver_Weather\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/TimeObjects-Driver-Weather.html#method___construct"
        },                {
            "fqsen": "\\TimeObjects_Driver_Weather\u003A\u003Aensure\u0028\u0029",
            "name": "ensure",
            "summary": "Ensures\u0020that\u0020we\u0020meet\u0020all\u0020requirements\u0020to\u0020use\u0020this\u0020time\u0020object",
            "url": "classes/TimeObjects-Driver-Weather.html#method_ensure"
        },                {
            "fqsen": "\\TimeObjects_Driver_Weather\u003A\u003AlistTimeObjects\u0028\u0029",
            "name": "listTimeObjects",
            "summary": "Get\u0020a\u0020list\u0020of\u0020TimeObjects.",
            "url": "classes/TimeObjects-Driver-Weather.html#method_listTimeObjects"
        },                {
            "fqsen": "\\TimeObjects_Driver_Weather\u003A\u003A_findLocation\u0028\u0029",
            "name": "_findLocation",
            "summary": "",
            "url": "classes/TimeObjects-Driver-Weather.html#method__findLocation"
        },                {
            "fqsen": "\\TimeObjects_Driver_Weather\u003A\u003A_create\u0028\u0029",
            "name": "_create",
            "summary": "Private\u0020factory\u0020for\u0020weather\u0020driver.",
            "url": "classes/TimeObjects-Driver-Weather.html#method__create"
        },                {
            "fqsen": "\\TimeObjects_Driver_Weather\u003A\u003A\u0024_forecastDays",
            "name": "_forecastDays",
            "summary": "",
            "url": "classes/TimeObjects-Driver-Weather.html#property__forecastDays"
        },                {
            "fqsen": "\\TimeObjects_Driver_Weather\u003A\u003A\u0024_location",
            "name": "_location",
            "summary": "",
            "url": "classes/TimeObjects-Driver-Weather.html#property__location"
        },                {
            "fqsen": "\\TimeObjects_Driver",
            "name": "TimeObjects_Driver",
            "summary": "Base\u0020TimeObjects_Driver.",
            "url": "classes/TimeObjects-Driver.html"
        },                {
            "fqsen": "\\TimeObjects_Driver\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/TimeObjects-Driver.html#method___construct"
        },                {
            "fqsen": "\\TimeObjects_Driver\u003A\u003AlistTimeObjects\u0028\u0029",
            "name": "listTimeObjects",
            "summary": "Get\u0020a\u0020list\u0020of\u0020TimeObjects.",
            "url": "classes/TimeObjects-Driver.html#method_listTimeObjects"
        },                {
            "fqsen": "\\TimeObjects_Driver\u003A\u003Aensure\u0028\u0029",
            "name": "ensure",
            "summary": "Ensure\u0020we\u0020have\u0020minimum\u0020requirements\u0020for\u0020concrete\u0020driver\u0020to\u0020run.",
            "url": "classes/TimeObjects-Driver.html#method_ensure"
        },                {
            "fqsen": "\\TimeObjects_Driver\u003A\u003Afactory\u0028\u0029",
            "name": "factory",
            "summary": "Factory\u0020method",
            "url": "classes/TimeObjects-Driver.html#method_factory"
        },                {
            "fqsen": "\\TimeObjects_Driver\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "",
            "url": "classes/TimeObjects-Driver.html#property__params"
        },                {
            "fqsen": "\\TimeObjects_Exception",
            "name": "TimeObjects_Exception",
            "summary": "Copyright\u00202009\u002D2017\u0020Horde\u0020LLC\u0020\u0028http\u003A\/\/www.horde.org\/\u0029",
            "url": "classes/TimeObjects-Exception.html"
        },                {
            "fqsen": "\\TimeObjects_Factory_Driver",
            "name": "TimeObjects_Factory_Driver",
            "summary": "Factory\u0020for\u0020TimeObjects_Driver",
            "url": "classes/TimeObjects-Factory-Driver.html"
        },                {
            "fqsen": "\\TimeObjects_Factory_Driver\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Creates\u0020a\u0020concrete\u0020TimeObjects_Driver\u0020object.",
            "url": "classes/TimeObjects-Factory-Driver.html#method_create"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
