Search.appendIndex(
    [
                {
            "fqsen": "\\Horde\\Http\\Server\\DefaultHandlerTrait",
            "name": "DefaultHandlerTrait",
            "summary": "Default\u0020Handler\u0020Trait.",
            "url": "classes/Horde-Http-Server-DefaultHandlerTrait.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\DefaultHandlerTrait\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Server-DefaultHandlerTrait.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\DefaultHandlerTrait\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020a\u0020request",
            "url": "classes/Horde-Http-Server-DefaultHandlerTrait.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\DefaultHandlerTrait\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-DefaultHandlerTrait.html#property_responseFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\DefaultHandlerTrait\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-DefaultHandlerTrait.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Horde-Http-Server-Exception.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Gzip",
            "name": "Gzip",
            "summary": "Filter\u0020to\u0020gzip\u0020content\u0020before\u0020being\u0020served",
            "url": "classes/Horde-Http-Server-Gzip.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Gzip\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Server-Gzip.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Gzip\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "Compress\u0020output\u0020stream\u0020and\u0020set\u0020header",
            "url": "classes/Horde-Http-Server-Gzip.html#method_process"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Gzip\u003A\u003A_byteCount\u0028\u0029",
            "name": "_byteCount",
            "summary": "If\u0020mbstring\u0020is\u0020set\u0020to\u0020overload\u0020str\u002A\u0020function\u0020then\u0020we\u0020could\u0020be\u0020counting\nmulti\u002Dbyte\u0020chars\u0020as\u0020single\u0020bytes\u0020so\u0020we\u0020need\u0020to\u0020treat\u0020the\u0020string\u0020like\u0020its\n8\u002Dbit\u0020encoded\u0020to\u0020get\u0020an\u0020accurate\u0020byte\u0020count.",
            "url": "classes/Horde-Http-Server-Gzip.html#method__byteCount"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Gzip\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-Gzip.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Mock",
            "name": "Mock",
            "summary": "A\u0020Mock\u0020Middleware",
            "url": "classes/Horde-Http-Server-Middleware-Mock.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Mock\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Server-Middleware-Mock.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Mock\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "Process\u0020the\u0020incoming\u0020request",
            "url": "classes/Horde-Http-Server-Middleware-Mock.html#method_process"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Mock\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Horde-Http-Server-Middleware-Mock.html#property_response"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Base",
            "name": "Base",
            "summary": "A\u0020Null\u0020Middleware",
            "url": "classes/Horde-Http-Server-Middleware-Base.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Base\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "",
            "url": "classes/Horde-Http-Server-Middleware-Base.html#method_process"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Responder",
            "name": "Responder",
            "summary": "A\u0020Responder\u0020Middleware",
            "url": "classes/Horde-Http-Server-Middleware-Responder.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Responder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Server-Middleware-Responder.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Responder\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "Process\u0020the\u0020incoming\u0020request",
            "url": "classes/Horde-Http-Server-Middleware-Responder.html#method_process"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Responder\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-Middleware-Responder.html#property_responseFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware\\Responder\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-Middleware-Responder.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\PayloadHandler",
            "name": "PayloadHandler",
            "summary": "A\u0020very\u0020simple\u0020payload\u0020handler.",
            "url": "classes/Horde-Http-Server-PayloadHandler.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\PayloadHandler\u003A\u003AbodyContent\u0028\u0029",
            "name": "bodyContent",
            "summary": "Overload\u0020this\u0020function\u0020to\u0020return\u0020different\u0020body\u0020content.",
            "url": "classes/Horde-Http-Server-PayloadHandler.html#method_bodyContent"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\PayloadHandler\u003A\u003AreturnCode\u0028\u0029",
            "name": "returnCode",
            "summary": "Overload\u0020this\u0020function\u0020to\u0020change\u0020the\u0020return\u0020code",
            "url": "classes/Horde-Http-Server-PayloadHandler.html#method_returnCode"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler",
            "name": "RampageRequestHandler",
            "summary": "The\u0020Rampage\u0020request\u0020handler.",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler\u003A\u003AaddMiddleware\u0028\u0029",
            "name": "addMiddleware",
            "summary": "Add\u0020another\u0020middleware\u0020to\u0020the\u0020queue\u0020just\u0020before\u0020the\u0020payload\u0020handler",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html#method_addMiddleware"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler\u003A\u003AsetPayloadHandler\u0028\u0029",
            "name": "setPayloadHandler",
            "summary": "Configure\u0020the\u0020payload\u0020handler",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html#method_setPayloadHandler"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler\u003A\u003AnextMiddleware\u0028\u0029",
            "name": "nextMiddleware",
            "summary": "",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html#method_nextMiddleware"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020a\u0020request",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html#method_handle"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html#property_responseFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler\u003A\u003A\u0024middlewares",
            "name": "middlewares",
            "summary": "",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html#property_middlewares"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RampageRequestHandler\u003A\u003A\u0024payloadHandler",
            "name": "payloadHandler",
            "summary": "",
            "url": "classes/Horde-Http-Server-RampageRequestHandler.html#property_payloadHandler"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RequestBuilder",
            "name": "RequestBuilder",
            "summary": "RequestBuilder\u0020applies\u0020global\u0020state\u0020or\u0020other\u0020resources\u0020to\u0020a\u0020ServerRequest",
            "url": "classes/Horde-Http-Server-RequestBuilder.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RequestBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Server-RequestBuilder.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RequestBuilder\u003A\u003AwithGlobalVariables\u0028\u0029",
            "name": "withGlobalVariables",
            "summary": "Create\u0020a\u0020new\u0020server\u0020request\u0020populated\u0020with\u0020global\u0020state",
            "url": "classes/Horde-Http-Server-RequestBuilder.html#method_withGlobalVariables"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RequestBuilder\u003A\u003AwithHeaders\u0028\u0029",
            "name": "withHeaders",
            "summary": "Add\u0020headers\u0020from\u0020list",
            "url": "classes/Horde-Http-Server-RequestBuilder.html#method_withHeaders"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RequestBuilder\u003A\u003Abuild\u0028\u0029",
            "name": "build",
            "summary": "",
            "url": "classes/Horde-Http-Server-RequestBuilder.html#method_build"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RequestBuilder\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/Horde-Http-Server-RequestBuilder.html#property_request"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RequestBuilder\u003A\u003A\u0024requestFactory",
            "name": "requestFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-RequestBuilder.html#property_requestFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RequestBuilder\u003A\u003A\u0024streamFactory",
            "name": "streamFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-RequestBuilder.html#property_streamFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\RequestBuilder\u003A\u003A\u0024uriFactory",
            "name": "uriFactory",
            "summary": "",
            "url": "classes/Horde-Http-Server-RequestBuilder.html#property_uriFactory"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\ResponseWriterInterface",
            "name": "ResponseWriterInterface",
            "summary": "",
            "url": "classes/Horde-Http-Server-ResponseWriterInterface.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\ResponseWriterInterface\u003A\u003AwriteResponse\u0028\u0029",
            "name": "writeResponse",
            "summary": "Output\u0020the\u0020HTTP\u0020Response\u0020to\u0020STDOUT",
            "url": "classes/Horde-Http-Server-ResponseWriterInterface.html#method_writeResponse"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\ResponseWriterWeb",
            "name": "ResponseWriterWeb",
            "summary": "Transform\u0020a\u0020Response\u0020object\u0020to\u0020HTTP\u0020output",
            "url": "classes/Horde-Http-Server-ResponseWriterWeb.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\ResponseWriterWeb\u003A\u003AwriteResponse\u0028\u0029",
            "name": "writeResponse",
            "summary": "Output\u0020the\u0020HTTP\u0020Response\u0020to\u0020STDOUT",
            "url": "classes/Horde-Http-Server-ResponseWriterWeb.html#method_writeResponse"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Runner",
            "name": "Runner",
            "summary": "HTTP\u0020Server\u0020Runner",
            "url": "classes/Horde-Http-Server-Runner.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Runner\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-Http-Server-Runner.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Runner\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Horde-Http-Server-Runner.html#method_run"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Runner\u003A\u003A\u0024handler",
            "name": "handler",
            "summary": "",
            "url": "classes/Horde-Http-Server-Runner.html#property_handler"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Runner\u003A\u003A\u0024responseWriter",
            "name": "responseWriter",
            "summary": "",
            "url": "classes/Horde-Http-Server-Runner.html#property_responseWriter"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server",
            "name": "Server",
            "summary": "",
            "url": "namespaces/horde-http-server.html"
        },                {
            "fqsen": "\\Horde\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/horde-http.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        },                {
            "fqsen": "\\Horde\\Http\\Server\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/horde-http-server-middleware.html"
        }            ]
);
