Search.appendIndex(
    [
                {
            "fqsen": "\\Horde\\Socket\\Client\\Exception",
            "name": "Exception",
            "summary": "Exception\u0020handler\u0020for\u0020the\u0020Horde_Socket_Client\u0020package.",
            "url": "classes/Horde-Socket-Client-Exception.html"
        },                {
            "fqsen": "\\Horde\\Socket\\Client",
            "name": "Client",
            "summary": "Utility\u0020interface\u0020for\u0020establishing\u0020a\u0020stream\u0020socket\u0020client.",
            "url": "classes/Horde-Socket-Client.html"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Horde-Socket-Client.html#method___construct"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Horde-Socket-Client.html#method___get"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "This\u0020object\u0020can\u0020not\u0020be\u0020cloned.",
            "url": "classes/Horde-Socket-Client.html#method___clone"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A__sleep\u0028\u0029",
            "name": "__sleep",
            "summary": "This\u0020object\u0020can\u0020not\u0020be\u0020serialized.",
            "url": "classes/Horde-Socket-Client.html#method___sleep"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003AstartTls\u0028\u0029",
            "name": "startTls",
            "summary": "Start\u0020a\u0020TLS\u0020connection.",
            "url": "classes/Horde-Socket-Client.html#method_startTls"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020the\u0020connection.",
            "url": "classes/Horde-Socket-Client.html#method_close"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003AgetStatus\u0028\u0029",
            "name": "getStatus",
            "summary": "Returns\u0020information\u0020about\u0020the\u0020connection.",
            "url": "classes/Horde-Socket-Client.html#method_getStatus"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003Agets\u0028\u0029",
            "name": "gets",
            "summary": "Returns\u0020a\u0020line\u0020of\u0020data.",
            "url": "classes/Horde-Socket-Client.html#method_gets"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Returns\u0020a\u0020specified\u0020amount\u0020of\u0020data.",
            "url": "classes/Horde-Socket-Client.html#method_read"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Writes\u0020data\u0020to\u0020the\u0020stream.",
            "url": "classes/Horde-Socket-Client.html#method_write"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A_connect\u0028\u0029",
            "name": "_connect",
            "summary": "Connect\u0020to\u0020the\u0020remote\u0020server.",
            "url": "classes/Horde-Socket-Client.html#method__connect"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A_checkStream\u0028\u0029",
            "name": "_checkStream",
            "summary": "Throws\u0020an\u0020exception\u0020is\u0020the\u0020stream\u0020is\u0020not\u0020a\u0020resource.",
            "url": "classes/Horde-Socket-Client.html#method__checkStream"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A\u0024_connected",
            "name": "_connected",
            "summary": "Is\u0020there\u0020an\u0020active\u0020connection\u003F",
            "url": "classes/Horde-Socket-Client.html#property__connected"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A\u0024_params",
            "name": "_params",
            "summary": "Configuration\u0020parameters.",
            "url": "classes/Horde-Socket-Client.html#property__params"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A\u0024_secure",
            "name": "_secure",
            "summary": "Is\u0020the\u0020connection\u0020secure\u003F",
            "url": "classes/Horde-Socket-Client.html#property__secure"
        },                {
            "fqsen": "\\Horde\\Socket\\Client\u003A\u003A\u0024_stream",
            "name": "_stream",
            "summary": "The\u0020actual\u0020socket.",
            "url": "classes/Horde-Socket-Client.html#property__stream"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Horde\\Socket\\Client",
            "name": "Client",
            "summary": "",
            "url": "namespaces/horde-socket-client.html"
        },                {
            "fqsen": "\\Horde\\Socket",
            "name": "Socket",
            "summary": "",
            "url": "namespaces/horde-socket.html"
        },                {
            "fqsen": "\\Horde",
            "name": "Horde",
            "summary": "",
            "url": "namespaces/horde.html"
        }            ]
);
