Search.appendIndex(
    [
                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier",
            "name": "Horde_JavascriptMinify_Jsmin_Minifier",
            "summary": "PHP\u0020implementation\u0020of\u0020Douglas\u0020Crockford\u0027s\u0020JSMin.",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#method___construct"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#method_minify"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A_action\u0028\u0029",
            "name": "_action",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#method__action"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A_get\u0028\u0029",
            "name": "_get",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#method__get"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A_isAlphaNum\u0028\u0029",
            "name": "_isAlphaNum",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#method__isAlphaNum"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A_isRegexLiteral\u0028\u0029",
            "name": "_isRegexLiteral",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#method__isRegexLiteral"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A_next\u0028\u0029",
            "name": "_next",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#method__next"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A_peek\u0028\u0029",
            "name": "_peek",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#method__peek"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003AORD_LF",
            "name": "ORD_LF",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#constant_ORD_LF"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003AORD_SPACE",
            "name": "ORD_SPACE",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#constant_ORD_SPACE"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003AACTION_KEEP_A",
            "name": "ACTION_KEEP_A",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#constant_ACTION_KEEP_A"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003AACTION_DELETE_A",
            "name": "ACTION_DELETE_A",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#constant_ACTION_DELETE_A"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003AACTION_DELETE_A_B",
            "name": "ACTION_DELETE_A_B",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#constant_ACTION_DELETE_A_B"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_a",
            "name": "_a",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__a"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_b",
            "name": "_b",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__b"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_input",
            "name": "_input",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__input"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_inputIndex",
            "name": "_inputIndex",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__inputIndex"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_inputLength",
            "name": "_inputLength",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__inputLength"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_keywords",
            "name": "_keywords",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__keywords"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_lookAhead",
            "name": "_lookAhead",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__lookAhead"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_output",
            "name": "_output",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__output"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_x",
            "name": "_x",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__x"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin_Minifier\u003A\u003A\u0024_y",
            "name": "_y",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin-Minifier.html#property__y"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin",
            "name": "Horde_JavascriptMinify_Jsmin",
            "summary": "Native\u0020PHP\u0020javascript\u0020minification\u0020driver.",
            "url": "classes/Horde-JavascriptMinify-Jsmin.html"
        },                {
            "fqsen": "\\Horde_JavascriptMinify_Jsmin\u003A\u003Aminify\u0028\u0029",
            "name": "minify",
            "summary": "",
            "url": "classes/Horde-JavascriptMinify-Jsmin.html#method_minify"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
